### ISSUE TITLE
Cannot compile in subdirectory for Android

### ISSUE THREAD

**Issue by star-tek-mb** [kcat/openal-soft#100]
I have a simple CMakeLists.txt:
~~~
add_subdirectory(openal-soft)
~~~
And CMakeToolchain for Android - [here](https://github.com/taka-no-me/android-cmake).
I can compile with this toolchain with no subdirectory. But cannot compile in subdirectory project.

Anyway to fix this?

Thank you in advance

**Comment by kcat** [comment]
It should work to build in a sub-directory. What cmake/make commands do you use? What errors do you get?

**Comment by star-tek-mb** [comment]
Thank you for reply.
I used this command for both types (subdir and not):
~~~
cmake -DCMAKE_TOOLCHAIN_FILE=android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=24
~~~

This is error logs (CMakeOutput.log and CMakeError.log) for subdir:
[CMakeFiles.zip](https://github.com/kcat/openal-soft/files/870776/CMakeFiles.zip)

This is error logs (CMakeOutput.log and CMakeError.log) with no subdir:
[CMakeFiles.zip](https://github.com/kcat/openal-soft/files/870782/CMakeFiles.zip)

**Comment by kcat** [comment]
The actual terminal output would be more helpful (from a clean build dir, so it will check everything). CMakeOutput and CMakeError very verbosely tell what individual checks succeeded and failed, but don't clearly say what caused configuration to stop prematurely.

**Comment by star-tek-mb** [comment]
Sorry, i am a beginner with cmake. Thats is:
[errors.zip](https://github.com/kcat/openal-soft/files/872266/errors.zip)

I found only one visible error in terminal output (file with-warnings.txt):
~~~
-- Looking for include files SLES/OpenSLES.h, SLES/OpenSLES_Android.h - found
-- Looking for slCreateEngine in OpenSLES
CMake Error at /home/startek/test/subdir/android.toolchain.cmake:800 (message):
  Specified Android native API level 'android-8' is not supported by your
  NDK/toolchain.
Call Stack (most recent call first):
  /home/startek/test/subdir/build/CMakeFiles/3.7.2/CMakeSystem.cmake:6 (include)
  /home/startek/test/subdir/build/openal-soft/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)


CMake Deprecation Warning at /home/startek/cmake/share/cmake-3.7/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/startek/test/subdir/android.toolchain.cmake:1128 (CMAKE_FORCE_C_COMPILER)
  /home/startek/test/subdir/build/CMakeFiles/3.7.2/CMakeSystem.cmake:6 (include)
  /home/startek/test/subdir/build/openal-soft/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)
~~~

I think, there is some command that overwrites API level.

**Comment by kcat** [comment]
Looks like it might be a problem with that CMake toolchain. All those deprecation warnings are a red flag that something's not right, something causing "internal errors" with TryCompile commands, and it getting confused with the NDK version on some checks (which is causing it to fail detecting OpenSL, so even if it did build, you wouldn't get any output).

**Comment by star-tek-mb** [comment]
Thank you for response. I will try to adaptate my code to google's ndk toolchain.
