### ISSUE TITLE
compile error ubuntu 14.04 and solved way

### ISSUE THREAD

**Issue by fatalfeel** [kcat/openal-soft#101]
/root/openal-soft-master/examples/alstream.c: In function ‘OpenPlayerFile’:
/root/openal-soft-master/examples/alstream.c:160:18: warning: implicit declaration of function ‘SDL_AUDIO_BITSIZE’ [-Wimplicit-function-declaration]
                  SDL_AUDIO_BITSIZE(player->sample->actual.format) / 8;
                  ^
Linking C executable alstream
CMakeFiles/alstream.dir/examples/alstream.c.o: In function `OpenPlayerFile':
/root/openal-soft-master/examples/alstream.c:160: undefined reference to「SDL_AUDIO_BITSIZE」
collect2: error: ld returned 1 exit status
make[2]: *** [alstream] Error 1
make[1]: *** [CMakeFiles/alstream.dir/all] Error 2
make: *** [all] Error 2

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
solved way
refer to https://fossies.org/linux/SDL2/include/SDL_audio.h
add 2 lines into alloopback.c and alstream.c

#define SDL_AUDIO_MASK_BITSIZE	(0xFF)
#define SDL_AUDIO_BITSIZE(x)         (x & SDL_AUDIO_MASK_BITSIZE)

**Comment by kcat** [comment]
Thanks, fixed in commit 710bbde09c45cf32e94e815f43ce48fd80c9d77b.
