### ISSUE TITLE
[bug] atomic doesn't exist on mac, ios but is added

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#1019]
Problem line: https://github.com/kcat/openal-soft/blob/master/CMakeLists.txt#L206

Reference: https://github.com/nodejs/node/pull/28232#issuecomment-502415178

Is causing linker errors ex.
```
ld: library 'atomic' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kcat** [comment]
Sounds like a configuration issue. The code section you link to runs a check to see if `-latomic` can be linked when using atomic functions. If libatomic doesn't exist, that check should fail and not include it with the link. If it tries to link with libatomic later, that check must have succeeded.

This seems to have come up before with issue #760, with an iOS toolchain file having `ENABLE_STRICT_TRY_COMPILE` disabled that prevented the check from running and assuming success (the point of such checks is to see if they work; assuming something works when it may not is just asking for problems like that).

**Comment by hsdk123** [comment]
it was the exact same toolchain! Thank you!
