### ISSUE TITLE
New stable release?

### ISSUE THREAD

**Issue by dustContributor** [kcat/openal-soft#1030]
Hi! I've been wondering, is it time for a new stable release? It's been a year and half since the previous one and there have been a looot of changes since then (~800 commits according to github,  "Showing with 35,430 additions and 27,137 deletions"). In particular I'm very interested in the debug extension that brings ARB_debug_output-like functionality to OpenAL.

In particular I'm asking because LWJGL doesn't picks up non-stable releases for their bindings so I'm "stuck" with the version from april 2023.

**Comment by dustContributor** [comment]
Sorry I meant april 2023.

**Comment by kcat** [comment]
Yes, I've been meaning to start getting a release together. But feature creep keeps creeping in, like the recent work with supporting ASIO drivers. I should probably put a hold on that to do afterward, though.

**Comment by dustContributor** [comment]
Sweet, I hope you can make it.

**Comment by kcat** [comment]
OpenAL Soft 1.24.0 has been released now., available on [the release page](https://github.com/kcat/openal-soft/releases/tag/1.24.0).
