### ISSUE TITLE
openal-soft.org is down

### ISSUE THREAD

**Issue by thewierdnut** [kcat/openal-soft#1039]
As of september 2, I can't access it :(

**Comment by kcat** [comment]
I've poked the sysadmin about it, so they should be able to look into it soon when they get the message.

**Comment by ThreeDeeJay** [comment]
In the meantime, there's always plan B: http://web.archive.org/web/20240824141628/https://openal-soft.org/

**Comment by thewierdnut** [comment]
Its back up now. Thank you!
