### ISSUE TITLE
AL_EFFECTSLOT_AUXILIARY_SEND_AUTO no effect

### ISSUE THREAD

**Issue by fatalfeel** [kcat/openal-soft#104]
in Main.c
alAuxiliaryEffectSloti(slot00, AL_EFFECTSLOT_AUXILIARY_SEND_AUTO, AL_FALSE);

alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, AL_EFFECTSLOT_NULL, 0, AL_FILTER_NULL);

after fixed, match with alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, AL_EFFECTSLOT_NULL, 0, AL_FILTER_NULL);

sound is correct but it still goto ALequalizerState_process to calculate

fixed in
/openal-soft-172/Alc/ALu.c
 while(slot)
            {
                const ALeffectslot *cslot = slot;
                ALeffectState *state = cslot->Params.EffectState;
                if( slot->AuxSendAuto ) //add this
                	V(state,process)(SamplesToDo, cslot->WetBuffer, state->OutBuffer, state->OutChannels);
                slot = ATOMIC_LOAD(&slot->next, almemory_order_relaxed);
            }

**Comment by fatalfeel** [comment]
after fixed,  better than use alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, AL_EFFECTSLOT_NULL, 0, AL_FILTER_NULL);

**Comment by kcat** [comment]
That's not what ```AL_EFFECTSLOT_AUXILIARY_SEND_AUTO``` does. That setting determines if room attenuation and absorption (and initial decay for reverb) is applied for the source sends the effect slot is connected to, or if it uses the direct path's attenuation and absorption. It doesn't affect the effect slot processing.
