### ISSUE TITLE
WASAPI Notify when microphone was disconnected

### ISSUE THREAD

**Issue by Switch0621** [kcat/openal-soft#1050]
Hello!
How can i detect this change? List of capture devices contains disconnected device name after repeat calling.

**Comment by kcat** [comment]
Hi.

That's up to the system. On some systems with a microphone jack, the device itself is always considered connected and simply produces silence when nothing is plugged in. Some (particularly older) hardware isn't able to tell the system that nothing is plugged in, so the system and apps will assume the device is always there, even if nothing is connected to generate sound.

If you're talking about a USB microphone, or some other external audio hardware that's physically removed, it should be able to tell when that's disconnected. What's your hardware?

**Comment by Switch0621** [comment]
> Hi.
> 
> That's up to the system. On some systems with a microphone jack, the device itself is always considered connected and simply produces silence when nothing is plugged in. Some (particularly older) hardware isn't able to tell the system that nothing is plugged in, so the system and apps will assume the device is always there, even if nothing is connected to generate sound.
> 
> If you're talking about a USB microphone, or some other external audio hardware that's physically removed, it should be able to tell when that's disconnected. What's your hardware?

Thanks for your answer! One some interesting moment, i connect microphone and run program - device is looking good and working. In running program i disconnect microphone (3.5 jack), program in cycle request current device name but it's not changing. After sop program and run again - the field with microphone name is empty.  
I'm planned to use all available devices: handset, speaker, usb, hid usb.

**Comment by kcat** [comment]
> In running program i disconnect microphone (3.5 jack), program in cycle request current device name but it's not changing. After sop program and run again - the field with microphone name is empty.

The device name of an open `ALCdevice` won't change without calling `alcReopenDeviceSOFT` (which doesn't work with capture devices). If the device it's referencing becomes disconnected, it will still refer to that device and just become unusable.

With OpenAL Soft, the default capture device name returned by `alcGetString(NULL, ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER)` also won't change until the capture device names are re-enumerated with `alcGetString(NULL, ALC_CAPTURE_DEVICE_SPECIFIER)` (OpenAL Soft updates its internal device name list and the default device name at the same time when enumerating them, to ensure the returned default name will always be found in the enumerated names even if devices are added to or removed from the system between enumerating the names and querying the default).

More generally, if you want to just get a notification when devices are added to or removed from the system, recent Git versions have the [`ALC_SOFT_system_events`](https://openal-soft.org/openal-extensions/SOFT_system_events.txt) extension. It won't say if a particular `ALCdevice` was disconnected, but it can say that devices were added to or removed from the system.

**Comment by Switch0621** [comment]
> > In running program i disconnect microphone (3.5 jack), program in cycle request current device name but it's not changing. After sop program and run again - the field with microphone name is empty.
> 
> The device name of an open `ALCdevice` won't change without calling `alcReopenDeviceSOFT` (which doesn't work with capture devices). If the device it's referencing becomes disconnected, it will still refer to that device and just become unusable.
> 
> With OpenAL Soft, the default capture device name returned by `alcGetString(NULL, ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER)` also won't change until the capture device names are re-enumerated with `alcGetString(NULL, ALC_CAPTURE_DEVICE_SPECIFIER)` (OpenAL Soft updates its internal device name list and the default device name at the same time when enumerating them, to ensure the returned default name will always be found in the enumerated names even if devices are added to or removed from the system between enumerating the names and querying the default).
> 
> More generally, if you want to just get a notification when devices are added to or removed from the system, recent Git versions have the [`ALC_SOFT_system_events`](https://openal-soft.org/openal-extensions/SOFT_system_events.txt) extension. It won't say if a particular `ALCdevice` was disconnected, but it can say that devices were added to or removed from the system.

Thank you for taking the time to answer! I think the extension must to solve my issue!

**Comment by Switch0621** [comment]
Sorry for re-open, but can you to check project [](https://github.com/Switch0621/TestOpenAL)? I can't understand why alcGetString(NULL, ALC_CAPTURE_DEVICE_SPECIFIER) return the same list when capture device exist and after remove it?
In example repository:
run with attached capture device, print "show", detach capture device (no exit for program), anf print "show" again.
I apologize again for my lack of clarity.

**Comment by kcat** [comment]
What does the system say about the device when you disconnect it? Does the system still show the device in its list of audio devices? If Windows thinks the device is still there, neither WASAPI or OpenAL Soft can know it's been disconnected.

**Comment by Switch0621** [comment]
1) show devices list
![image](https://github.com/user-attachments/assets/917773e9-80aa-4019-9243-ff32564ed8eb)
2) remove microphone
![image](https://github.com/user-attachments/assets/b12147c5-efcc-4257-9800-31534d5d700c)
3) show devices list again
![image](https://github.com/user-attachments/assets/add3424a-5c9e-453e-933b-c9caa83708fd)

**Comment by kcat** [comment]
That's Creative's wrapper driver, not OpenAL Soft. If you're using Creative's wrapper driver, that would suggest you're using Creative's router also, and unfortunately it appears that Creative's router only enumerates devices once and returns that same list forever, never reenumerating the available devices. It might work if you use OpenAL Soft's router instead, or if you use OpenAL Soft itself directly without a router.
