### ISSUE TITLE
Soft OpenAL 1.24 in STALKER games (32 bit)

### ISSUE THREAD

**Issue by donizettilorenzo** [kcat/openal-soft#1062]
It just makes the game crash at start with old alsoft.ini
So we must update alsoft.ini too?

**Comment by donizettilorenzo** [comment]
It's something about the dither and the gain limiter. If I delete those 2 entries in the OLD alsoft.ini then games run.

**Comment by kcat** [comment]
Can you create a trace log? If you can run it with a debugger and a debugging version of OpenAL Soft, a backtrace could be helpful too. There's no reason dithering or the gain limiter should crash that I can think of. Does it work with other 32-bit games?

**Comment by kcat** [comment]
Check to see if it's fixed now with commit b27ef50c5d8b32321527d453145fcaeaa1803755. I notice the `distance-comp=false` option value that had a bug for boolean options.

**Comment by donizettilorenzo** [comment]
Problem seems solved! Thanks!
