### ISSUE TITLE
fmt issues

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#1072]
Hi, I currently build openal as a static library and also add fmt as well.
I've started getting the below error:
```
CMake Error at D:/a/Light.vn-core/Light.vn-core/_deps/fmt/2333d29341f1038845b9a41d3ceeb716c6ac7d94/CMakeLists.txt:306 (add_library):
  add_library cannot create ALIAS target "fmt::fmt" because another target
  with the same name already exists.
  
CMake Error at D:/a/Light.vn-core/Light.vn-core/_deps/fmt/2333d29341f1038845b9a41d3ceeb716c6ac7d94/CMakeLists.txt:361 (add_library):
  add_library cannot create target "fmt-header-only" because another target
  with the same name already exists.  The existing target is an interface
  library created in source directory
  "D:/a/Light.vn-core/Light.vn-core/_deps/openal-soft/3be63b3f39a174450de1f24ffd50073c72bb031a/fmt-11.0.2".
  See documentation for policy CMP0002 for more details.
```

**Comment by kcat** [comment]
That's not good. OpenAL Soft is using fmt as an internal thing/private detail to provide more sensible text i/o and formatting functions (currently only some examples and utilities, but eventually the main library would use it too). It doesn't need to be exposed as a public target, just an extra thing as if it was another part of OpenAL Soft. But if OpenAL Soft is being used as a sub-project, and either the parent project or another of its sub-projects also includes its own copy of fmt, its going to create duplicate targets if there isn't a way to encapsulate them.

I can try to include a globally-installed fmt first, and check that fmt isn't already included, and have OpenAL Soft only include it's own copy if it doesn't detect one already available, but that does feel touchy (if OpenAL Soft is included first and there is no globally-installed fmt, OpenAL Soft will include its own copy and it will be up to other projects to have a check to avoid including their local copy), and it could hit compatibility problems if a different fmt version is included than what OpenAL Soft is expecting.

**Comment by kcat** [comment]
This should work now. I had to rename the targets used in fmt's CMakeLists.txt (and cleaned it out of unused options), so they shouldn't clash with parent or sibling projects also using fmt.

**Comment by hsdk123** [comment]
Thank you, I'll check in the morning.

**Comment by hsdk123** [comment]
Works! Thank you!
