### ISSUE TITLE
fmt: alsoft.fmt built but not get installed

### ISSUE THREAD

**Issue by fundawang** [kcat/openal-soft#1075]
alsoft.fmt produces libalsoft.fmt.so.11 when building shared libraries. But this library does not get installed along with utils, which will cause utils could not be used due to missing libraries.

May alsoft.fmt should be built as a static library always?

**Comment by kcat** [comment]
Yes, it should always be built as a static library. Not sure what would cause it to be built as a dynamic library, but it's fixed now with commit 5d2c405c4aea0b6dbcfbcfe147b6a17855627acf.
