### ISSUE TITLE
Static library + embedded HRTF data

### ISSUE THREAD

**Issue by alexey-lysiuk** [kcat/openal-soft#111]
I tried to build static library of macOS with embedded HRTF data for 10.7 as target OS version, i.e. CMake variables were set as following:
* `LIBTYPE = STATIC`
* `ALSOFT_EMBED_HRTF_DATA = YES`
* `CMAKE_OSX_DEPLOYMENT_TARGET = 10.7`

Tools like `openal-info` and `altonegen` were failed to link with this error:
```
Undefined symbols for architecture x86_64:
  "__mh_dylib_header", referenced from:
      _GetResource in libopenal.a(hrtf.o)
```
Apparently there is no such symbol in executable files.
It seems that embedding of HRTF data require dynamic library (and .dylib or framework on macOS).

At the same time, is it possible to use `_mh_execute_header` symbol when static library is being built?
It will user's responsibility to link executable with `default-44100.mhr.o` and
`default-48000.mhr.o` files in order to load HRTF data.

I'm not sure about other platforms but for macOS this works for me.

One more question related to this issue: why don't you store HRTF data as byte arrays in code?
This looks simpler to me: no platforms specific loaders, custom build steps, only arrays in own in header files generated by a tool like `xxd`.

I'm not suggesting to change this. I'm just asking because I might be unaware of something.

**Comment by kcat** [comment]
> At the same time, is it possible to use ```_mh_execute_header``` symbol when static library is being built?

Technically, yes. The issue is that, when built as static, the resulting lib can be linked into an executable or another dynamic lib. There's no telling which ```_mh_*_header``` to use in that case. It would probably make more sense to assume an executable when building statically, though that won't be true 100% of the time.

Does macOS have a symbol to use for compiling that will be treated as ```_mh_dylib_header``` or ```_mh_executable_header``` depending if the object code is linked into a dylib or executable?

> One more question related to this issue: why don't you store HRTF data as byte arrays in code?
This looks simpler to me: no platforms specific loaders, custom build steps, only arrays in own in header files generated by a tool like ```xxd```.

Mainly due to the lack of standard tools to convert a binary file into a C source file containing a byte data array. Particularly for Windows. ```xxd``` unfortunately doesn't seem to be very flexible, either... I can't tell it to make the array ```static const```, for example, or to omit the _len variable (unneeded since I can do ```sizeof``` on the array).

**Comment by alexey-lysiuk** [comment]
I mean that HRTF data in byte array form should be committed to the repository but not created during build.
Or if you think that it's mandatory to generate these arrays at compile time, a custom tool can be coded for this purpose.
I'm pretty sure that both cases (especially the first one) are simpler than platform dependent loaders and custom build steps.
As a bonus any of them eliminates the mentioned issue with static library.

Is there any other concern with this approach? If not, I can try to implement it.

**Comment by kcat** [comment]
I don't generally like having to store the same data twice. So if I update the default mhr files some time in the future, I'd rather not have to be concerned about remembering to update the source files also, or else letting them fall out of sync. That's why I'd prefer for for the source files to be automatically generated during build time, so they're guaranteed to be the same.

I'd definitely like to have a platform-independent way of compiling the built-in data sets into the lib. I'm just not sure of the most reliable way to.

**Comment by alexey-lysiuk** [comment]
I pushed a rough implementation to [this branch](https://github.com/alexey-lysiuk/openal-soft/tree/embed_hrtf).
Like I promised it's much simpler than existing platform-dependent HRTF embedding logic.

Please let know your thoughts about this approach in general.

**Comment by kcat** [comment]
The general idea looks okay. The main issue is when cross-compiling, the created program can't be run since it's for a different host. I don't know how to make cmake build the bin2h program for the native system while the lib and other things are cross-compiled.

**Comment by alexey-lysiuk** [comment]
I updated [my branch](https://github.com/alexey-lysiuk/openal-soft/tree/embed_hrtf) with cross-compilation support. Implementation is based on [this guide](https://cmake.org/Wiki/CMake_Cross_Compiling).
I tested these changes using a separate [branch](https://github.com/alexey-lysiuk/openal-soft/tree/embed_hrtf_ci).
Both branches have continuous integration systems enabled, so you can verify that everything is fine.

**Comment by kcat** [comment]
Interesting. So cmake notices when cross-compiling that it needs native programs that are built when not cross-compiling, and will automatically do a native build for those programs before doing the cross-compile build. That looks like it should be acceptable. Kind of unfortunate that it has to do a full configure just to build the native app, but I guess ultimately it's not a big deal.

**Comment by alexey-lysiuk** [comment]
The native build of tools during compilation isn't automatic.
I explicitly configured native target to own directory but did `make bin2h` only.

`ALSOFT_EMBED_HRTF_DATA` is disabled by default so the changes won't increase CI build times.
These builds are quite fast anyway.

Actually, I enabled it in a separate branch only, just to verify cross-compilation.

**Comment by kcat** [comment]
> The native build of tools during compilation isn't automatic.

I'm less happy about that, if you need to make a separate build first to do a cross-compile.

Hmm, though I think I have an idea. Kind of like how the Git version is handled, it should be possible to invoke a separate cmake instance during the build, where a short and simple configuration script can use the native compiler to generate the bin2h program. So something like
```
SET(BIN2H_COMMAND "${OpenAL_BINARY_DIR}/native/bin2h")
ADD_CUSTOM_COMAND(OUTPUT "${BIN2H_COMMAND}"
    COMMAND ${CMAKE_COMMAND} "${OpenAL_SOURCE_DIR}/build_bin2h.cmake"
                             -DSRC_PATH="${OpenAL_SOURCE_DIR}" 
    COMMAND ${CMAKE_COMMAND} --build
    WORKING_DIRECTORY "${OpenAL_BINARY_DIR}/native"
    MAIN_DEPENDENCY "${OpenAL_SOURCE_DIR}/build_bin2h.cmake"
    DEPENDS "${OpenAL_SOURCE_DIR}/utils/bin2h.c"
    VERBATIM
)

# then to build the headers...
add_custom_command(OUTPUT "${outfile}"
    COMMAND "${BIN2H_COMMAND}" "${infile}" "${outfile}" ${VARNAME}
    DEPENDS "${BIN2H_COMMAND}" "${infile}"
    COMMENT "Generating ${FILENAME}.h"
    VERBATIM
)
```
And build_bin2h.cmake can simply be:
```
project(bin2h)
add_executable(bin2h "${SRC_PATH}/utils/bin2h.c")
# Enforce no dressing for executable names, so the main script can find it
set_target_properties(bin2h PROPERTIES OUTPUT_NAME bin2h)
```

**Comment by alexey-lysiuk** [comment]
I updated both branches ([feature](https://github.com/alexey-lysiuk/openal-soft/tree/embed_hrtf) and [CI test](https://github.com/alexey-lysiuk/openal-soft/tree/embed_hrtf_ci)) with implementation of proposed approach for `bin2h` tool.

**Comment by kcat** [comment]
That seems to do the trick nicely. To keep things clean, I'd probably put bin2h.c and its CMakeLists.txt into a native-tools directory, in case any more need to be made they can be added there. But otherwise, that seems to be good.

**Comment by alexey-lysiuk** [comment]
Squashed everything to the single commit to pushed to [this branch](https://github.com/alexey-lysiuk/openal-soft/tree/embed_hrtf_clean).
Updated CI configurations files are in their own commit, just in case you don't want embedding to be enabled there.
I can make a PR with (the first or both commits, please tell me what's better) if you are OK with the implementation.

**Comment by kcat** [comment]
Looks good to me. Both commits should be fine, I don't see any reason not to check that it's working with CI.

**Comment by kcat** [comment]
Thanks!
