### ISSUE TITLE
Can not setting ALC_OUTPUT_LIMITER_SOFT

### ISSUE THREAD

**Issue by fatalfeel** [kcat/openal-soft#113]
ALCint 	attr[5] = { ALC_HRTF_SOFT, ALC_FALSE, ALC_OUTPUT_LIMITER_SOFT, ALC_FALSE, 0};
.
.
.
if(!alcResetDeviceSOFT(device, attr))
    	printf("Failed to reset device: %s\n", alcGetString(device, alcGetError(device)));

//..
but ALC_OUTPUT_LIMITER_SOFT in /openal-soft-master/OpenAL32/Include/alMain.h

can not define  should move to other .h file

**Comment by kcat** [comment]
The extension's not public yet. It should only be used for testing purposes and not in production code, since details about it can change. I'd rather not put it in ```alext.h``` until I can be sure the public interface won't break.

**Comment by kcat** [comment]
The extension is public now.
