### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by fornwall** [kcat/openal-soft#114]
The latest release is from Jan 25 2016, and there has been a lot of activity since then!

Is it time for a new release or are there blocking issues (would you recommend packaging git master for users)?

**Comment by kcat** [comment]
There should be a new release soon. If all goes well, I'd like to make a release by the start of next month.

Currently, there's an issue with the reverb output volume I'm trying to get settled before release. It seems overall quieter than it's supposed to be to me, but someone else is saying it's too loud when I try to fix it. So I need to find the reason for that discrepancy and try to solve it. If it doesn't matter to you that the reverb may be too quiet, and may become a bit louder in a following update, there shouldn't be an issue using git master if it has things you want.

**Comment by kcat** [comment]
1.18 is now out.
