### ISSUE TITLE
Build Error (GCC 7.1.1)

### ISSUE THREAD

**Issue by shoober420** [kcat/openal-soft#116]
When tyring to compile the 32bit or 64bit version, I get the following error. This is with GCC 7.1.1

/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp: In member function ‘bool {anonymous}::MovieState::prepare()’:
/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp:1185:37: error: ‘mem_fn’ is not a member of ‘std’
     mParseThread = std::thread(std::mem_fn(&MovieState::parse_handler), this);
                                     ^~~~~~
/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp:1185:37: note: suggested alternative: ‘mem_fun’
     mParseThread = std::thread(std::mem_fn(&MovieState::parse_handler), this);
                                     ^~~~~~
                                     mem_fun
/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp: In member function ‘int {anonymous}::MovieState::streamComponentOpen(int)’:
/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp:1252:45: error: ‘mem_fn’ is not a member of ‘std’
             mAudioThread = std::thread(std::mem_fn(&AudioState::handler), &mAudio);
                                             ^~~~~~
/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp:1252:45: note: suggested alternative: ‘mem_fun’
             mAudioThread = std::thread(std::mem_fn(&AudioState::handler), &mAudio);
                                             ^~~~~~
                                             mem_fun
/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp:1264:45: error: ‘mem_fn’ is not a member of ‘std’
             mVideoThread = std::thread(std::mem_fn(&VideoState::handler), &mVideo);
                                             ^~~~~~
/home/abc/Downloads/packages/openal-git/src/openal-soft/examples/alffplay.cpp:1264:45: note: suggested alternative: ‘mem_fun’
             mVideoThread = std::thread(std::mem_fn(&VideoState::handler), &mVideo);
                                             ^~~~~~
                                             mem_fun
make[2]: *** [CMakeFiles/alffplay.dir/build.make:63: CMakeFiles/alffplay.dir/examples/alffplay.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:470: CMakeFiles/alffplay.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by kcat** [comment]
Looks like it's missing an include. Can you check if it's fixed now with commit 07bb5f13?

**Comment by shoober420** [comment]
Awesome, this indeed fixed the error. Thank you so much kcat.
