### ISSUE TITLE
Updating Reflections Delay in Reverb Effect every frame results in 'distortion'

### ISSUE THREAD

**Issue by kunal-vzw** [kcat/openal-soft#118]
I'm using the OpenAL Effects Extension and I have a reverb effect, whose reflections delay value i'm updating every frame. Nothing fancy - I calculate the reflections delay based on the distance from the user to the closest wall in the environment, and then update the effect value and re-attach it like so:

    void updateFrame(float reflectionsDelay)
    {
        // Update Reflections Delay only
        alEffectf(mReverbEffect, AL_REVERB_REFLECTIONS_DELAY, reflectionsDelay);

        // Reattach Effect
        alAuxiliaryEffectSloti(mReverbTrack, AL_EFFECTSLOT_EFFECT, mReverbEffect);
    }

And the reverb effect is simply being set up in the following way on start (updateFrame of course gets called _after_ the below setup is complete):

    EFXEAXREVERBPROPERTIES reverb = EFX_REVERB_PRESET_GENERIC;
	
    // Create Effect
	alGenEffects(1, &mReverbEffect);

	// Set Effect Type to Reverb
	if (alIsEffect(mReverbEffect))
	{
		alEffecti(mReverbEffect, AL_EFFECT_TYPE, AL_EFFECT_REVERB);
	}

	// Load Effect on Aux Track
	alAuxiliaryEffectSloti(mReverbTrack, AL_EFFECTSLOT_EFFECT, mReverbEffect);

	// Load Reverb parameters into our Reverb Effect
	alEffectf(mReverbEffect, AL_REVERB_DENSITY, reverb.flDensity);
	alEffectf(mReverbEffect, AL_REVERB_DIFFUSION, reverb.flDiffusion);
	alEffectf(mReverbEffect, AL_REVERB_GAIN, reverb.flGain);
	alEffectf(mReverbEffect, AL_REVERB_GAINHF, reverb.flGainHF);
	alEffectf(mReverbEffect, AL_REVERB_DECAY_TIME, reverb.flDecayTime);
	alEffectf(mReverbEffect, AL_REVERB_DECAY_HFRATIO, reverb.flDecayHFRatio);
	alEffectf(mReverbEffect, AL_REVERB_REFLECTIONS_GAIN, reverb.flReflectionsGain);
	alEffectf(mReverbEffect, AL_REVERB_REFLECTIONS_DELAY, reverb.flReflectionsDelay);
	alEffectf(mReverbEffect, AL_REVERB_LATE_REVERB_GAIN, reverb.flLateReverbGain);
	alEffectf(mReverbEffect, AL_REVERB_LATE_REVERB_DELAY, reverb.flLateReverbDelay);
	alEffectf(mReverbEffect, AL_REVERB_AIR_ABSORPTION_GAINHF, reverb.flAirAbsorptionGainHF);
	alEffectf(mReverbEffect, AL_REVERB_ROOM_ROLLOFF_FACTOR, reverb.flRoomRolloffFactor);
	alEffecti(mReverbEffect, AL_REVERB_DECAY_HFLIMIT, reverb.iDecayHFLimit);

	// Reattach Effect
	alAuxiliaryEffectSloti(mReverbTrack, AL_EFFECTSLOT_EFFECT, mReverbEffect);

The thing is, the reflections delay values are fine (I have checked and they are in the range of ~0.01 - 0.15) and the audio sounds perfect when the user is not in motion (i.e. I can hear the audible difference in the delay values). It's only when the user is in _motion_ that the audio sounds grainy (static-y and distorted). I'm guessing that there's something about the reverb computation process that perhaps requires re-sampling/interpolation as the new delay values come in every frame, and that results in the graininess? We're running at basically 60 fps.

Thanks

**Comment by kcat** [comment]
> It's only when the user is in motion that the audio sounds grainy (static-y and distorted). I'm guessing that there's something about the reverb computation process that perhaps requires re-sampling/interpolation as the new delay values come in every frame, and that results in the graininess?

Basically, yeah. Assuming you're using a release version, OpenAL Soft's reverb would set the new reflections delay value when it internally updates, but it does so without considering existing sound in the delay line. This can cause clicks from unexpected changes in amplitude.

The current Git version should have this fixed, as it fades between delay times to smooth out the transition. If you're able to build from Git, you can test to see if it still happens. Otherwise, the next release will be in about 4 or 5 days which will include that fix.

**Comment by kunal-vzw** [comment]
The current Git version fixes this! Thanks Chris. Looking forward to the next release that includes the fix :)
