### ISSUE TITLE
VS2015: "No snprintf function found, please report!"

### ISSUE THREAD

**Issue by cmdrf** [kcat/openal-soft#12]
[VS2015 finally implements snprintf](http://blogs.msdn.com/b/vcblog/archive/2014/06/18/crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx), however the OpenAL CMakeLists.txt Fails to find it, giving the message "No snprintf function found, please report!".

Replacing the line
`CHECK_FUNCTION_EXISTS(snprintf HAVE_SNPRINTF)`
with
`CHECK_SYMBOL_EXISTS(snprintf stdio.h HAVE_SNPRINTF)`
fixes the issue. However, I'm not sure which implications exist for other OSes, and if the search for _snprintf is maybe unnecessary.

**Comment by kcat** [comment]
That change should be fine (my man pages also say snprintf is in stdio.h). Searching for _snprintf is still necessary for older MSVC versions, though as long as snprintf is found the script shouldn't bother looking.

Thanks! Fixed in commit 5543000.
