### ISSUE TITLE
Counter-Strike 1.6 crash on de_aztec because of rain sound effect

### ISSUE THREAD

**Issue by shoober420** [kcat/openal-soft#120]
So I made an issue about this in the Steam Linux GitHub, and it didn't get fixed for some time. I remember before when it would crash, an OpenAL overrun error would print in the terminal, but this no longer occurs. Here is the original issue page.

https://github.com/ValveSoftware/steam-for-linux/issues/4742

Is there anyway I can help you debug this? It happens very often.

**Comment by kcat** [comment]
What info do you have about the crash? An OpenAL overrun or underrun by itself doesn't mean too much in this instance, it just means OpenAL had trouble processing the system's audio requests on time. It may happen as a result of a crash, since the crash handler may take up a lot of the CPU time which causes OpenAL to lag and miss updates, but isn't necessarily the cause of the crash.

**Comment by shoober420** [comment]
I think it was an underrun actually. I have to use the "stopsound" command every start of the round to silence the ambient rain sound effect. If I don't, a couple rounds in, I will crash back to desktop.

**Comment by kcat** [comment]
That unfortunately doesn't say much. Like mentioned, an underrun could happen as a result of the crash, rather than be the cause of it. There's any number of issues that could be causing the crash that "stopsound" somehow alleviates.

**Comment by shoober420** [comment]
Is there strace, or something I can use to further investigate?

**Comment by kcat** [comment]
I'm not sure the best way to debug Counter Strike. Perhaps you could try using gdb to get a backtrace from where it crashes.

**Comment by shoober420** [comment]
I ran gdb and only got the overrun error message. I forgot to mention that I don't use Pulseaudio. Maybe some sort of buffer is too small and it crashes because of that rain sound effect that keeps playing. It for sure has something to do with that rain effect since the "stopsound" cvar stops ambient environmental sounds in the game. I googled how to increase buffer size for OpenAL and couldn't find any definitive method. Do you know the preferred method for increasing buffer sizes in OpenAL?

**Comment by kcat** [comment]
It's very unlikely to be because of the overrun/underrun. Can you provide a full trace log? Set the ```ALSOFT_LOGLEVEL``` environment variable to ```3``` when you run the game, and the log will be written to stderr.

**Comment by shoober420** [comment]
I tried some more things, and you're right. It doesn't seem to be an issue with rain sound effects, but with the "cl_weather" command when set to 3. I'm sorry for the confusion.

**Comment by shoober420** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/4742
