### ISSUE TITLE
codeblocks request

### ISSUE THREAD

**Issue by tecan** [kcat/openal-soft#121]
would like a codeblocks project file for compiling on windows 32 / 64. cmake sometimes has issues with missing dll's

**Comment by kcat** [comment]
What do you mean that CMake sometimes has issues with missing DLLs?

**Comment by jhasse** [comment]
Checkout https://cmake.org/cmake/help/v3.10/generator/CodeBlocks.html

**Comment by kcat** [comment]
CMake's CodeBlocks generator is your best option. I don't have any plans to provide IDE-specific project files.
