### ISSUE TITLE
invalid suffix on literal; C++11 requires a space between literal and identifier

### ISSUE THREAD

**Issue by fatalfeel** [kcat/openal-soft#122]
in alMain.h

#define AL_PRINT(T, MSG, ...) fprintf(LogFile, "AL lib: %s %s: "MSG, T, __FUNCTION__ , ## __VA_ARGS__)

#define LOG_ANDROID(T, MSG, ...) __android_log_print(T, "openal", "AL lib: %s: "MSG, __FUNCTION__ , ## __VA_ARGS__)

/////////////

change to
#if defined(__GNUC__) && !defined(_WIN32) && !defined(IN_IDE_PARSER)
#define AL_PRINT(T, MSG, ...) fprintf(LogFile, "AL lib: %s %s: " MSG, T, __FUNCTION__ , ## __VA_ARGS__)
#else
void al_print(const char *type, const char *func, const char *fmt, ...) DECL_FORMAT(printf, 3,4);
#define AL_PRINT(T, ...) al_print((T), __FUNCTION__, __VA_ARGS__)
#endif

#ifdef __ANDROID__
#include <android/log.h>
#define LOG_ANDROID(T, MSG, ...) __android_log_print(T, "openal", "AL lib: %s: " MSG, __FUNCTION__ , ## __VA_ARGS__)
#else
#define LOG_ANDROID(T, MSG, ...) ((void)0)
#endif

**Comment by kcat** [comment]
Can you please provide proper patches? It's not easy to see what's different when you just type out various lines like that.

Also, this isn't C++, so there shouldn't be C++11 related errors.

**Comment by UnknownShadow200** [comment]
Change was just putting after a space before MSG, otherwise compiling with recent G++ versions (G++ 4.8.4 fine, G++ 6.3 fails, GCC 6.3 fine) fails with:

_error: unable to find string literal operator 'operator""MSG' with 'const char [16]', 'long unsigned int' arguments_

test case:
```C
#include <stdio.h>
#define AL_PRINT(T, MSG, ...) fprintf(stdout, "AL lib: %s %s: "MSG, T, __FUNCTION__ , ## __VA_ARGS__)

int main() {
    AL_PRINT("u", "v");
    return 0;
}
```

**Comment by fatalfeel** [comment]
failed
#define AL_PRINT(T, MSG, ...) fprintf(LogFile, "AL lib: %s %s: "MSG, T, FUNCTION , ## VA_ARGS)
correct
#define AL_PRINT(T, MSG, ...) fprintf(LogFile, "AL lib: %s %s: " MSG, T, FUNCTION , ## VA_ARGS)

just need a little space before  MSG

**Comment by fatalfeel** [comment]
failed build
#define AL_PRINT(T, MSG, ...) fprintf(LogFile, "AL lib: %s %s: "MSG, T, FUNCTION , ## VA_ARGS)
correct it
#define AL_PRINT(T, MSG, ...) fprintf(LogFile, "AL lib: %s %s: " MSG, T, FUNCTION , ## VA_ARGS)

just need a space before MSG will build ok

**Comment by fatalfeel** [comment]
for android version and it can put on external directory
http://www.mediafire.com/file/h279wr4x7wrh8cz/libopenal_1.18.2_android.tar.gz

**Comment by kcat** [comment]
This is no longer an issue, now that the code base is C++.
