### ISSUE TITLE
[1.18.0] Regression for pausing streaming sources

### ISSUE THREAD

**Issue by flibitijibibo** [kcat/openal-soft#124]
In the latest OpenAL Soft release there appears to be an issue with pausing/resuming streaming sources. Simply put, if you pause too fast, resuming has no effect but the state claims to be AL_PLAYING, causing a deadlock depending on what the application expects.

Here's some sample code:

```
#include <AL/al.h>
#include <AL/alc.h>
#include "stb_vorbis.c"

#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

#define BUFFER_COUNT 4

int main(int argc, char **argv)
{
	ALCdevice *device;
	ALCcontext *context;
	ALuint buf[BUFFER_COUNT];
	ALuint src;
	int vorbisLen, channels, sampleRate;
	short *vorbis;
	int done, state;
	int i;

	device = alcOpenDevice(NULL);
	context = alcCreateContext(device, NULL);
	alcMakeContextCurrent(context);

	/* Load up some buffers */
	vorbisLen = stb_vorbis_decode_filename(
		"test.ogg",
		&channels,
		&sampleRate,
		&vorbis
	) / BUFFER_COUNT;
	alGenBuffers(BUFFER_COUNT, buf);
	for (i = 0; i < BUFFER_COUNT; i += 1)
	{
		alBufferData(
			buf[i],
			channels == 2 ? AL_FORMAT_STEREO16 : AL_FORMAT_MONO16,
			vorbis + (vorbisLen * i),
			vorbisLen * sizeof(short),
			sampleRate
		);
	}
	free(vorbis);

	/* Queue some buffers */
	alGenSources(1, &src);
	alSourceQueueBuffers(src, BUFFER_COUNT, buf);

	/* Play, then immediately pause */
	alSourcePlay(src);
	alSourcePause(src);

	/* Wait a little bit... */
#ifdef _WIN32
	Sleep(2000);
#else
	usleep(2000000);
#endif

	/* Okay, now play...?  Or not?! */
	alSourcePlay(src);
	do
	{
		alGetSourcei(src, AL_BUFFERS_PROCESSED, &done);
		alGetSourcei(src, AL_SOURCE_STATE, &state);
		printf("%d %X\n", done, state);
	} while (done < BUFFER_COUNT);

	/* Clean up. We out. */
	alDeleteSources(1, &src);
	alDeleteBuffers(BUFFER_COUNT, buf);
	alcMakeContextCurrent(NULL);
	alcDestroyContext(context);
	alcCloseDevice(device);
	return 0;
}
```

A test file can be found [here](http://www.flibitijibibo.com/files/test.ogg), and stb_vorbis can be found [here](https://raw.githubusercontent.com/nothings/stb/master/stb_vorbis.c).

Similarly we were also able to wait slightly to try pausing and it had no effect, the source kept playing - it wasn't reproducible though.

**Comment by kcat** [comment]
Fixed with commit a35b9bbd3eac75771ca90d5755068cf88d5406aa. The issue was resuming the source cleared the internal mixing parameters to have it fade in, but the mixing parameters never got recalculated because there were no property updates, so it never got mixed. As a workaround, if you're not regularly updating the source's or listener properties, you can specify a redundant property update (e.g. set the source AL_GAIN to what it already is) to ensure the mixer recalculates the internal parameters and mixes it correctly.
