### ISSUE TITLE
Various OpenAL issues reported on my project

### ISSUE THREAD

**Issue by zevv** [kcat/openal-soft#127]
Hi,

I've created a trivial OpenAL app for simulating the sound of retro keyboards, see https://github.com/zevv/bucklespring. Basically it does nothing more then loading and playing a few samples.

A lot of the bug reports on this project seem to be related to OpenAL: distortion, no sound since upgrading to 1.18, for example:

- https://github.com/zevv/bucklespring/issues/53
- https://github.com/zevv/bucklespring/issues/50
- https://github.com/zevv/bucklespring/issues/50

Should I point the users reporting these issues to this issues list of the OpenAL-soft repo, or are there other preffered channels for support?

Thanks,

**Comment by kcat** [comment]
If they're using OpenAL Soft, yeah they can be directed to this issue tracker.

In regards to the issues listed, zevv/bucklespring#50 seems to be the same as issues #125 here by the description, which was just recently fixed. zevv/bucklespring#53 seems to be from Alure, just reporting that it couldn't load those libs (so it can't load files that rely on them). zevv/bucklespring#50 seems to be listed twice, I don't know if you meant another one or if you just accidentally pasted it again.

**Comment by zevv** [comment]
Thanks, I'll forward accordingly.

The last was indeed a mispaste, should be https://github.com/zevv/bucklespring/issues/51

**Comment by somini** [comment]
Hey @kcat
Any change of releasing a new (minor?) version to close this issue and  zevv/bucklespring#50 ?

**Comment by kcat** [comment]
Yes, I'll probably be releasing 1.18.1 in about a week assuming no other major issues pops up.

**Comment by kcat** [comment]
The issue surrounding zevv/bucklespring#50 is fixed, zevv/bucklespring#53 isn't related to OpenAL Soft, and zevv/bucklespring#51 is pretty light on the details. There's been quite a few changes since then, so can you check if it's still a problem with the latest release (and/or current git)?

**Comment by zevv** [comment]
Hi,

I'm taking the pragmatic way out here: these bugs are ancient on our
side and did not get any followups. I will just close them and inform
the original poster that they should re-open if they still have any
problems.

Thanks for reaching out,


Quoting kcat (2021-11-22 09:13:22)
> The issue surrounding zevv/bucklespring#50 is fixed, zevv/bucklespring#53 isn't related to OpenAL Soft, and zevv/bucklespring#51 is pretty light on the details. There's been quite a few changes since then, so can you check if it's still a problem with the latest release (and/or current git)?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kcat/openal-soft/issues/127#issuecomment-975235700


--
:wq
^X^Cy^K^X^C^C^C^C
