### ISSUE TITLE
Regression with 1.18.0 and Borderlands 2

### ISSUE THREAD

**Issue by brettowe** [kcat/openal-soft#128]
after recently getting Borderlands and not finding it working I found others also running Arch mentioning on reddit that reverting to 1.17 makes it work and it does indeed do that
here is output from ALSOFT_LOGLEVEL=3 for both versions

[openal-1.17.txt](https://github.com/kcat/openal-soft/files/1082894/openal-1.17.txt)
[openal-1.18.txt](https://github.com/kcat/openal-soft/files/1082895/openal-1.18.txt)

**Comment by kcat** [comment]
What do you mean by not working? Does it crash, or is it just silent? Do some sounds work and not others?

**Comment by brettowe** [comment]
it goes fullscreen showing black then exits, nothing shows on console like a crash happened

**Comment by kcat** [comment]
Can you run the game in a debugger, and get a backtrace to the crash?

**Comment by brettowe** [comment]
I'll try, game wont run unless its loaded from steam so it might not go well

**Comment by brettowe** [comment]
so turns out its been fixed by the time I was ready to try
https://git.archlinux.org/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/lib32-openal&id=ac03a9ecf5c7d1c5fceb6e174d9ca205b1cc382d
https://bugs.archlinux.org/task/54490
