### ISSUE TITLE
1.18.microphone input on mono - 8bit -48000 samples per second broken

### ISSUE THREAD

**Issue by ShadowTeolog** [kcat/openal-soft#130]
in version 1.18 microphone input with settings mono 8bit,48000 samples per sec broken.
mono16 44100 still look normal
previously installed 1.17.2 both work normal.
compiled from source using VS2015 with default settings
voice reverberated on new version
[sample files.zip](https://github.com/kcat/openal-soft/files/1095068/sample.files.zip)

**Comment by kcat** [comment]
Looks like there was a problem with the resampler used for capture. Can you check to see if it still happens with commit d1077795deb8367d8e6fc39ecfc5f51b3c39d9e5?

**Comment by ShadowTeolog** [comment]
look better
[patched.zip](https://github.com/kcat/openal-soft/files/1097572/patched.zip)
Look better then previous but not so good as old version

**Comment by kcat** [comment]
Are you able to provide a trace log? Set the ```ALSOFT_LOGLEVEL``` environment variable to ```3``` when you run the app, and it'll write to stderr (you can set the ```ALSOFT_LOGFILE``` environment variable to a full path+filename to have it write there instead).

**Comment by ShadowTeolog** [comment]
here log
[openal32.zip](https://github.com/kcat/openal-soft/files/1097984/openal32.zip)

**Comment by kcat** [comment]
Are you able to get a log with the more recent Git version? That one seems to be missing some trace statements that were added.

**Comment by ShadowTeolog** [comment]
[lastestgitversion.zip](https://github.com/kcat/openal-soft/files/1098379/lastestgitversion.zip)
ready. 
next two days I will be far from computer, so next time can send you something only on monday.
Also someting strange happen than i test dsound backend, look like it not support 48000 input, so i have "fast speaking voice".
Also 48000 output can't set on both mmdev and dsound backends, i don't no if this normal.

**Comment by kcat** [comment]
Hmm, well I'm a little bit stumped. I modified the traces a bit to hopefully give a bit more info,so it would be helpful if you could try the latest Git again and provide the log file again. The only other thing I can think of currently is perhaps the sample length you pass to ```alcCaptureOpenDevice``` is too small and it keeps underrunning (750 samples at 48khz is about 15 milliseconds, which borders on the time slice resolution). I'd try using a couple thousand for the sample length at the least.

It's normal for the mmdevapi backend to not be able to set 48000 output, depending on the system settings. For whatever reason, mmdevapi itself doesn't offer resampling capabilities, so if the device is configured for 44.1khz, 48khz won't work (similarly, if the device is configured for 48khz, 44.1khz won't work).

It's unexpected to happen with the dsound backend, though. DirectSound should be capable of resampling, so it should be able to set 48khz if that was requested. In fact, the dsound backend can't change the OpenAL device's sample rate, so if that's what you request that's what you get, unless something else is changing the request. The issue with dsound capture you mention also seems odd, like it's setting a different sample rate despite accepting what was asked for.

**Comment by ShadowTeolog** [comment]
Solved.
You was right. microphone input was damaged because overwrite output buffer while my thread copy it.
Extending buffer in ten times solves trouble. dsound "fast voice" has same source.
Thank you very much for your cooperation ;)
