### ISSUE TITLE
[suggestion] Please add the example listing all devices

### ISSUE THREAD

**Issue by yurivict** [kcat/openal-soft#135]
Listing devices is an important function, and there is no read-to-use program.

For example, like this:
https://stackoverflow.com/questions/28960638/listing-all-devices-open-al-does-not-work

**Comment by kcat** [comment]
[openal-info](https://github.com/kcat/openal-soft/blob/master/utils/openal-info.c) shows listing devices (as well as other things, like resamplers, HRTFs, etc).

**Comment by yurivict** [comment]
Thanks!
