### ISSUE TITLE
When no OSS device is available, OSS Default is still returned

### ISSUE THREAD

**Issue by yurivict** [kcat/openal-soft#136]
The program listing devices https://stackoverflow.com/questions/28960638/listing-all-devices-open-al-does-not-work prints this:

```
$ ./openal_list_audio_devices 
AL lib: (EE) ALCossListPopulate: Could not open /dev/mixer
list of all available output devices:
  OSS Default
AL lib: (EE) ALCossListPopulate: Could not open /dev/mixer
list of all available input devices:
  OSS Default
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory

Error: Audio device not available.
```

Other programs show OSS Default as a choice. In the absence of any OSS devices OSS Default should disappear. Instead, interface should have the way of letting users know that none is available. Return 'Null' or something like that. Returning OSS Default is misleading. Also errors should not be printed. 'No device' is a legitimate outcome.

**Comment by kcat** [comment]
Fixed with commits 5ab4e584eec469708a14df9effe1e038df805f8b and 82a990e08e3bb16063485d13491274de55889664.
