### ISSUE TITLE
[question] HRTF interpolation for unsampled auditory angles

### ISSUE THREAD

**Issue by demaddis** [kcat/openal-soft#140]
I'm trying to implement a psychophysics experiment with a sound source that moves continuously on the horizon in front of the listener. Although the default HRTF data set is only sampled in 5° azimuth steps, I've noticed that there is a smooth transition when using smaller step sizes to spatialize the source. I haven't been able to find any documentation on HRTF interpolation in openal and am not literate in C, so I wanted to ask how the interpolation is implemented. Any pointers to relevant documentation are appreciated.

**Comment by kcat** [comment]
It essentially uses bilinear interpolation between the nearest impulse response measurements. It gets four indices for the impulse responses nearest to the desired point (in a square or trapezoid shape, using the two nearest lower and two nearest higher measurements), calculates blending weights given how far the desired point is between the four impulse responses, then adds the impulse responses together each scaled by its blending weight.

**Comment by demaddis** [comment]
Thanks for the info!
