### ISSUE TITLE
INT_MAX not declared

### ISSUE THREAD

**Issue by JFSF** [kcat/openal-soft#141]
In the file /common/uintmap.h, line 22:
``#define` UINTMAP_STATIC_INITIALIZE UINTMAP_STATIC_INITIALIZE_N(INT_MAX)`
INT_MAX is not declared here. 
Should declare:
`#include <limits.h>` in line 6 or `#define INT_MAX +2147483647`

**Comment by kcat** [comment]
Fixed in commit e3d99412a20f5476cbf700855a934bf724b13a07.
