### ISSUE TITLE
Native-tools/bin2h

### ISSUE THREAD

**Issue by JFSF** [kcat/openal-soft#142]
Using latest version, cmake 3.9.1, codeblocks 16.01 and mingw gcc 6.3.0 i've a broken build recipe:

> CMakeFiles\native-tools.dir\build.make|62|recipe for target 'native-tools/bin2h' failed|
`@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=C:\Dev\openal-soft\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Generating native-tools/bin2h, native-tools/bsincgen"`
> CMakeFiles\Makefile2|103|recipe for target 'CMakeFiles/native-tools.dir/all' failed|
`$(MAKE) -f CMakeFiles\native-tools.dir\build.make CMakeFiles/native-tools.dir/depend`
> C:\Dev\openal-soft\build\Makefile|128|recipe for target 'all' failed|
`$(CMAKE_COMMAND) -E cmake_progress_start C:\Dev\openal-soft\build\CMakeFiles C:\Dev\openal-soft\build\CMakeFiles\progress.marks`

**Comment by kcat** [comment]
Is there any output before that? What about if you run make (mingw-make or whatever it's called) for it directly on the command line (```make VERBOSE=1``` to show full output).

**Comment by JFSF** [comment]
This is the log file generated by cmake:
[CMakeError.zip](https://github.com/kcat/openal-soft/files/1264962/CMakeError.zip)

**Comment by kcat** [comment]
I need make's output, not cmake's.

**Comment by JFSF** [comment]
From the build log output:

> -------------- Build: all in OpenAL (compiler: GNU GCC Compiler)---------------

Checking if target is up-to-date: mingw32-make.exe -q -f Makefile all
Running command: C:/MinGW/bin/mingw32-make.exe -f "C:/Dev/openal-soft/build/Makefile"  VERBOSE=1 all
"C:\Program Files\CMake\bin\cmake.exe" -HC:\Dev\openal-soft -BC:\Dev\openal-soft\build --check-build-system CMakeFiles\Makefile.cmake 0
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start C:\Dev\openal-soft\build\CMakeFiles C:\Dev\openal-soft\build\CMakeFiles\progress.marks
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\Makefile2 all
mingw32-make.exe[1]: Entering directory 'C:/Dev/openal-soft/build'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\native-tools.dir\build.make CMakeFiles/native-tools.dir/depend
mingw32-make.exe[2]: Entering directory 'C:/Dev/openal-soft/build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Dev\openal-soft C:\Dev\openal-soft C:\Dev\openal-soft\build C:\Dev\openal-soft\build C:\Dev\openal-soft\build\CMakeFiles\native-tools.dir\DependInfo.cmake --color=
Dependee "C:\Dev\openal-soft\build\CMakeFiles\native-tools.dir\DependInfo.cmake" is newer than depender "C:/Dev/openal-soft/build/CMakeFiles/native-tools.dir/depend.internal".
Dependee "C:/Dev/openal-soft/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "C:/Dev/openal-soft/build/CMakeFiles/native-tools.dir/depend.internal".
Scanning dependencies of target native-tools
mingw32-make.exe[2]: Leaving directory 'C:/Dev/openal-soft/build'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\native-tools.dir\build.make CMakeFiles/native-tools.dir/build
mingw32-make.exe[2]: Entering directory 'C:/Dev/openal-soft/build'
[  1%] Generating native-tools/bin2h, native-tools/bsincgen
cd /d C:\Dev\openal-soft\build\native-tools && "C:\Program Files\CMake\bin\cmake.exe" C:/Dev/openal-soft/native-tools/
Re-run cmake no build system arguments
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:
    cl
  is not a full path and was not found in the PATH.
  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).
  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:
    cl
  is not a full path and was not found in the PATH.
  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).
  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
mingw32-make.exe[2]: *** [native-tools/bin2h] Error 1
mingw32-make.exe[1]: *** [CMakeFiles/native-tools.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
-- The CXX compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "C:/Dev/openal-soft/build/native-tools/CMakeFiles/CMakeOutput.log".
See also "C:/Dev/openal-soft/build/native-tools/CMakeFiles/CMakeError.log".
CMakeFiles\native-tools.dir\build.make:65: recipe for target 'native-tools/bin2h' failed
mingw32-make.exe[2]: Leaving directory 'C:/Dev/openal-soft/build'
CMakeFiles\Makefile2:106: recipe for target 'CMakeFiles/native-tools.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'C:/Dev/openal-soft/build'
C:/Dev/openal-soft/build/Makefile:131: recipe for target 'all' failed
Process terminated with status 2 (0 minute(s), 1 second(s))
3 error(s), 0 warning(s) (0 minute(s), 1 second(s))

**Comment by kcat** [comment]
Seems it needs the current generator "forwarded" to the native-tools sub-build. Does the latest master work now?

**Comment by JFSF** [comment]
This time there's a error in the given parameter to gcc:

> -------------- Build: all in OpenAL (compiler: GNU GCC Compiler)---------------

Checking if target is up-to-date: mingw32-make.exe -q -f Makefile all
Running command: C:/MinGW/bin/mingw32-make.exe -f "C:/Dev/openal-soft/build/Makefile"  VERBOSE=1 all
"C:\Program Files\CMake\bin\cmake.exe" -HC:\Dev\openal-soft -BC:\Dev\openal-soft\build --check-build-system CMakeFiles\Makefile.cmake 0
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start C:\Dev\openal-soft\build\CMakeFiles C:\Dev\openal-soft\build\CMakeFiles\progress.marks
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\Makefile2 all
mingw32-make.exe[1]: Entering directory 'C:/Dev/openal-soft/build'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\native-tools.dir\build.make CMakeFiles/native-tools.dir/depend
mingw32-make.exe[2]: Entering directory 'C:/Dev/openal-soft/build'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Dev\openal-soft C:\Dev\openal-soft C:\Dev\openal-soft\build C:\Dev\openal-soft\build C:\Dev\openal-soft\build\CMakeFiles\native-tools.dir\DependInfo.cmake --color=
Dependee "C:\Dev\openal-soft\build\CMakeFiles\native-tools.dir\DependInfo.cmake" is newer than depender "C:/Dev/openal-soft/build/CMakeFiles/native-tools.dir/depend.internal".
Dependee "C:/Dev/openal-soft/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "C:/Dev/openal-soft/build/CMakeFiles/native-tools.dir/depend.internal".
Scanning dependencies of target native-tools
mingw32-make.exe[2]: Leaving directory 'C:/Dev/openal-soft/build'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\native-tools.dir\build.make CMakeFiles/native-tools.dir/build
mingw32-make.exe[2]: Entering directory 'C:/Dev/openal-soft/build'
[  1%] Generating native-tools/bin2h, native-tools/bsincgen
cd /d C:\Dev\openal-soft\build\native-tools && "C:\Program Files\CMake\bin\cmake.exe" -G "MinGW Makefiles" C:/Dev/openal-soft/native-tools/
Re-run cmake no build system arguments
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pow in m
-- Looking for pow in m - found
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Dev/openal-soft/build/native-tools
cd /d C:\Dev\openal-soft\build\native-tools && "C:\Program Files\CMake\bin\cmake.exe" -E remove C:/Dev/openal-soft/build/native-tools/bin2h C:/Dev/openal-soft/build/native-tools/bsincgen
cd /d C:\Dev\openal-soft\build\native-tools && "C:\Program Files\CMake\bin\cmake.exe" --build . --config Release
mingw32-make.exe[3]: Entering directory 'C:/Dev/openal-soft/build/native-tools'
"C:\Program Files\CMake\bin\cmake.exe" -HC:\Dev\openal-soft\native-tools -BC:\Dev\openal-soft\build\native-tools --check-build-system CMakeFiles\Makefile.cmake 0
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start C:\Dev\openal-soft\build\native-tools\CMakeFiles C:\Dev\openal-soft\build\native-tools\CMakeFiles\progress.marks
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\Makefile2 all
mingw32-make.exe[4]: Entering directory 'C:/Dev/openal-soft/build/native-tools'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\bin2h.dir\build.make CMakeFiles/bin2h.dir/depend
mingw32-make.exe[5]: Entering directory 'C:/Dev/openal-soft/build/native-tools'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Dev\openal-soft\native-tools C:\Dev\openal-soft\native-tools C:\Dev\openal-soft\build\native-tools C:\Dev\openal-soft\build\native-tools C:\Dev\openal-soft\build\native-tools\CMakeFiles\bin2h.dir\DependInfo.cmake --color=
Dependee "C:\Dev\openal-soft\build\native-tools\CMakeFiles\bin2h.dir\DependInfo.cmake" is newer than depender "C:/Dev/openal-soft/build/native-tools/CMakeFiles/bin2h.dir/depend.internal".
Dependee "C:/Dev/openal-soft/build/native-tools/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "C:/Dev/openal-soft/build/native-tools/CMakeFiles/bin2h.dir/depend.internal".
Scanning dependencies of target bin2h
mingw32-make.exe[5]: Leaving directory 'C:/Dev/openal-soft/build/native-tools'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\bin2h.dir\build.make CMakeFiles/bin2h.dir/build
mingw32-make.exe[5]: Entering directory 'C:/Dev/openal-soft/build/native-tools'
[ 25%] Building C object CMakeFiles/bin2h.dir/bin2h.c.obj
C:\MinGW\bin\gcc.exe    -o CMakeFiles\bin2h.dir\bin2h.c.obj   -c C:\Dev\openal-soft\native-tools\bin2h.c
[ 50%] Linking C executable bin2h.exe
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\bin2h.dir\link.txt --verbose=1
"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\bin2h.dir/objects.a
C:\MinGW\bin\ar.exe cr CMakeFiles\bin2h.dir/objects.a @CMakeFiles\bin2h.dir\objects1.rsp
C:\MinGW\bin\gcc.exe    -Wl,--whole-archive CMakeFiles\bin2h.dir/objects.a -Wl,--no-whole-archive  -o bin2h.exe -Wl,--out-implib,libbin2h.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\bin2h.dir\linklibs.rsp
mingw32-make.exe[5]: Leaving directory 'C:/Dev/openal-soft/build/native-tools'
[ 50%] Built target bin2h
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\bsincgen.dir\build.make CMakeFiles/bsincgen.dir/depend
mingw32-make.exe[5]: Entering directory 'C:/Dev/openal-soft/build/native-tools'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Dev\openal-soft\native-tools C:\Dev\openal-soft\native-tools C:\Dev\openal-soft\build\native-tools C:\Dev\openal-soft\build\native-tools C:\Dev\openal-soft\build\native-tools\CMakeFiles\bsincgen.dir\DependInfo.cmake --color=
Dependee "C:\Dev\openal-soft\build\native-tools\CMakeFiles\bsincgen.dir\DependInfo.cmake" is newer than depender "C:/Dev/openal-soft/build/native-tools/CMakeFiles/bsincgen.dir/depend.internal".
Dependee "C:/Dev/openal-soft/build/native-tools/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "C:/Dev/openal-soft/build/native-tools/CMakeFiles/bsincgen.dir/depend.internal".
Scanning dependencies of target bsincgen
mingw32-make.exe[5]: Leaving directory 'C:/Dev/openal-soft/build/native-tools'
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\bsincgen.dir\build.make CMakeFiles/bsincgen.dir/build
mingw32-make.exe[5]: Entering directory 'C:/Dev/openal-soft/build/native-tools'
[ 75%] Building C object CMakeFiles/bsincgen.dir/bsincgen.c.obj
C:\MinGW\bin\gcc.exe    -o CMakeFiles\bsincgen.dir\bsincgen.c.obj   -c C:\Dev\openal-soft\native-tools\bsincgen.c
[100%] Linking C executable bsincgen.exe
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\bsincgen.dir\link.txt --verbose=1
"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\bsincgen.dir/objects.a
C:\MinGW\bin\ar.exe cr CMakeFiles\bsincgen.dir/objects.a @CMakeFiles\bsincgen.dir\objects1.rsp
gcc.exe: error: unrecognized command line option '-municode'
mingw32-make.exe[5]: *** [bsincgen.exe] Error 1
mingw32-make.exe[4]: *** [CMakeFiles/bsincgen.dir/all] Error 2
mingw32-make.exe[3]: *** [all] Error 2
mingw32-make.exe[2]: *** [native-tools/bin2h] Error 2
mingw32-make.exe[1]: *** [CMakeFiles/native-tools.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
C:\MinGW\bin\gcc.exe    -municode -Wl,--whole-archive CMakeFiles\bsincgen.dir/objects.a -Wl,--no-whole-archive  -o bsincgen.exe -Wl,--out-implib,libbsincgen.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\bsincgen.dir\linklibs.rsp
CMakeFiles\bsincgen.dir\build.make:95: recipe for target 'bsincgen.exe' failed
mingw32-make.exe[5]: Leaving directory 'C:/Dev/openal-soft/build/native-tools'
CMakeFiles\Makefile2:103: recipe for target 'CMakeFiles/bsincgen.dir/all' failed
mingw32-make.exe[4]: Leaving directory 'C:/Dev/openal-soft/build/native-tools'
Makefile:82: recipe for target 'all' failed
mingw32-make.exe[3]: Leaving directory 'C:/Dev/openal-soft/build/native-tools'
CMakeFiles\native-tools.dir\build.make:65: recipe for target 'native-tools/bin2h' failed
mingw32-make.exe[2]: Leaving directory 'C:/Dev/openal-soft/build'
CMakeFiles\Makefile2:106: recipe for target 'CMakeFiles/native-tools.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'C:/Dev/openal-soft/build'
C:/Dev/openal-soft/build/Makefile:131: recipe for target 'all' failed
Process terminated with status 2 (0 minute(s), 19 second(s))
7 error(s), 0 warning(s) (0 minute(s), 19 second(s))

**Comment by JFSF** [comment]
According to the GNU GCC Manual : 

> -municode
This option is available for MinGW-w64 targets. It causes the UNICODE preprocessor
macro to be predefined, and chooses Unicode-capable runtime startup
code.

**Comment by kcat** [comment]
Updated to not rely on ```-municode``` (or ```wmain()```). Does it build now?

**Comment by JFSF** [comment]
Yes, it does build correctly (sorry for the english, i'm portuguese...)
