### ISSUE TITLE
Allow the program to set maximum number of sources

### ISSUE THREAD

**Issue by qwertychouskie** [kcat/openal-soft#144]
Some programs, like SuperTuxKart, can get too close for comfort to the current 256 sources limit (https://github.com/supertuxkart/stk-code/issues/2921).  It would be very useful if there was a way for the program to set the max number of sources.

**Comment by kcat** [comment]
It is actually possible, with 1.18 and newer. You can pass attributes to ```alcCreateContext``` to request a specific number of mono sources (```ALC_MONO_SOURCES```) and stereo sources (```ALC_STEREO_SOURCES```). If the combined value of the two is greater than 256, then the number of sources you can allocate is increased to satisfy the request. You can then query those attributes afterward with ```alcGetIntegerv```, and the sum of the two values you get back is the number of sources you can allocate and use.

**Comment by kcat** [comment]
Closing as fixed.
