### ISSUE TITLE
Cross compiling from master with mingw fails, any idea?

### ISSUE THREAD

**Issue by DeadSix27** [kcat/openal-soft#150]
I'm configuring openal (from master) like:
`cmake . -G"Unix Makefiles" -DENABLE_STATIC_RUNTIME=1 -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_RANLIB=x86_64-w64-mingw32-ranlib -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres-DCMAKE_TOOLCHAIN_FILE=XCompile.txt -DHOST=x86_64-w64-mingw32 -DCMAKE_INSTALL_PREFIX=%prefix -DLIBTYPE=STATIC -DALSOFT_UTILS=OFF -DALSOFT_EXAMPLES=OFF`

But I run into this issue when making:

```
[  3%] Generating bsinc_inc.h
CMakeFiles/OpenAL.dir/build.make:61: recipe for target 'bsinc_inc.h' failed
make[2]: *** [bsinc_inc.h] Illegal instruction (core dumped)
make[2]: *** Deleting file 'bsinc_inc.h'
CMakeFiles/Makefile2:132: recipe for target 'CMakeFiles/OpenAL.dir/all' failed
make[1]: *** [CMakeFiles/OpenAL.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Any clue what causes this?

EDIT: Using an older version (e.g https://github.com/kcat/openal-soft/commit/46f18ba114831ff26e8f270c6b5c881b45838439) works fine.

**Comment by kcat** [comment]
The ```-DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres-DCMAKE_TOOLCHAIN_FILE=XCompile.txt``` part looks like it's missing a space. You should also probably drop the ```-DCMAKE_SYSTEM_NAME=Windows -DCMAKE_RANLIB=x86_64-w64-mingw32-ranlib -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres``` switches since the toolchain file handles that already, and it may be confusing CMake during the build process (it essentially executes a second cmake process without the cross-compiler, so it builds native executables which can run to generate some files).

Otherwise, can you post the full output from cmake and make on a clean build directory?

**Comment by DeadSix27** [comment]
Now configured with: `. -DCMAKE_TOOLCHAIN_FILE=XCompile.txt -DHOST=x86_64-w64-mingw32 -DCMAKE_INSTALL_PREFIX=%prefix -DLIBTYPE=STATIC -DALSOFT_UTILS=OFF -DALSOFT_EXAMPLES=OFF`

Full output: https://gist.github.com/DeadSix27/5ba6c75e1fe8e0ccfdf617163549c690

If you need CMakeFiles/CMakeError.log: https://gist.github.com/DeadSix27/396cda51bee545e4bd26265f22466bc5
and if you need CMakeFiles/CMakeOutput.log: https://gist.github.com/DeadSix27/3d17298368bf7e706ee86980f472ee84

**Comment by kcat** [comment]
It almost looks like the default compiler (```cc```) can't build apps the system can run. Can you check the generated ```bin2h``` executable to see if there's anything odd about it? Can you run it manually on the command line (it'll write a bunch of stuff to stdout if it works)?

**Comment by DeadSix27** [comment]
I should add that if you read my edit (especially edit2) that it actually builds it just fine.. but seems to re-run cmake and use the internal gcc (e.g native linux) rather than the cross comiler gcc to compile windows code.

But bin2h works fine:
```
$ ./bin2h --help
Usage: bin2h [input] [output] [variable]
```

**Comment by kcat** [comment]
> Unless thats intentional and it builds some tools.. hence native tools with local gcc first which it needs to cross compile ?

Yeah, like I said:
> it essentially executes a second cmake process without the cross-compiler, so it builds native executables which can run to generate some files

It runs cmake a second time to build some tools natively (i.e. not cross-compiled), which it can run to generate some files used during the build.

> If so, does that require it to have the same gcc version? Because my cross compiler is gcc 7.2.0, and the local one is 6.3.0

It doesn't need to be the same version, no. Doesn't even have to be the same compiler family. But if you're setting the ```CFLAGS```, ```CXXFLAGS```, and/or ```LDFLAGS``` env vars and using flags that make it not runnable on the current system, that would be an issue. Would be better to use ```-DCMAKE_C_FLAGS=...```, ```-DCMAKE_CXX_FLAGS=...```, and ```-DCMAKE_SHARED_LINKER_FLAGS=...``` to specify custom build flags, and the second cmake should then stick with the defaults.

**Comment by DeadSix27** [comment]
@kcat

> it essentially executes a second cmake process without the cross-compiler, so it builds native executables which can run to generate some files

Ah I actually missed that part, sorry.

And yes, setting the flags via cmake flags sounds like a better idea

**Comment by kcat** [comment]
OpenAL Soft now no longer needs to do a secondary build for native tools, so that shouldn't present a problem with cross-compiling anymore. bsincgen is handled (mostly) with constexpr C++, and the bin2h work is handled by CMake itself.
