### ISSUE TITLE
Undefined Behaviour in VECTOR_RESIZE

### ISSUE THREAD

**Issue by Olof-IL** [kcat/openal-soft#152]
Hi!

While compiling OpenAL Soft with clang6, with Undefined Behaviour Sanitizer (UBSan) enabled, I got notified of undefined behaviour in VECTOR_RESIZE

The problem is this line: 
        ptrdiff_t data_offset = (char*)((_x)->Data) - (char*)(_x);            \

When the vector does not already exist, then _x is nullptr, and dereferencing it is undefined behaviour.

It happened on this line in the backend:
 alstr_copy_cstr(&device->DeviceName, name);

I have not experienced any issues from this, just UBSan complaining.
But I thought you would like to know about it!

**Comment by kcat** [comment]
Should be fixed now with commit 6dd1643a701c45fa779ea6da180f120c36c31a97, thanks!
