### ISSUE TITLE
Compile error when compiling to static build

### ISSUE THREAD

**Issue by shinchiro** [kcat/openal-soft#159]
With following error
`CMake Error: install(EXPORT "OpenAL" ...) includes target "OpenAL" which requires target "common" that is not in the export set.`

Commit d229afb8 introduced the error

**Comment by shinchiro** [comment]
well, fixed in git master

**Comment by sharkwouter** [comment]
How was this fixed? I'm seeing this same issue when compiling to a static build in version 1.20.1

**Comment by kcat** [comment]
Can you paste the full cmake output from a fresh build directory? The `OpenAL` target shouldn't link with `common` when static-linking, so that error shouldn't happen.

**Comment by sharkwouter** [comment]
Sorry about that. The build log can be found here: https://gist.github.com/sharkwouter/6832f38c13681108d3c2ca17f43e34ac

I'm trying to build for the PSP, so the build script is a bit odd as well:
```
## replace memory.h with string.h
sed -i -e "s/memory\.h/string.h/" alc/*.cpp alc/backends/*.cpp || { exit 1; }

## Run cmake
psp-cmake -D CMAKE_INSTALL_PREFIX=$(psp-config --psp-prefix) -D ALSOFT_UTILS=OFF -D ALSOFT_EXAMPLES=OFF . || { exit 1; }

## Compile and Install
make -j `num_cpus`
```

This is what the psp-cmake script looks like:
```
#!/bin/sh

psp_prefix=`psp-config --psp-prefix`

export PKG_CONFIG_LIBDIR=${psp_prefix}/lib/pkgconfig

MODULE_PATH=${psp_prefix}/share/cmake

cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=${psp_prefix} \
  -DBUILD_SHARED_LIBS:BOOL=OFF \
  -DCMAKE_MODULE_PATH=$MODULE_PATH \
  -DCMAKE_TOOLCHAIN_FILE=$MODULE_PATH/PSP.cmake \
  "$@"
```
If it helps I could link the whole PSP toolchain file as well.

**Comment by kcat** [comment]
```
CMake Warning (dev) at CMakeLists.txt:1241 (ADD_LIBRARY):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
```
It's trying to build a shared library, but is being forced to be a static library instead, which as it says, may lead to problems. You'll need to pass -DLIBTYPE=STATIC to cmake for OpenAL Soft to properly build as a static lib.

**Comment by sharkwouter** [comment]
Oh, that explains a lot. Thanks! I'll try that
