### ISSUE TITLE
Some compile warnings.

### ISSUE THREAD

**Issue by volcoma** [kcat/openal-soft#162]
Hi,  there are a lot of warnings when compiling 64bit with msvc and some when 32 bit.

**Comment by kcat** [comment]
MSVC 2015 32-bit is now showing no warnings. 64-bit has a a couple false-positives as a result of the way the atomic macros are defined.

How many are you getting now, what are they, and with which MSVC version?

**Comment by volcoma** [comment]
Yep, seems like you have fixed them. Just the ATOMIC stuff remained. Tried both msvc 2015/2017 with both 32/64 bit builds. Mingw is clear too.
