### ISSUE TITLE
Invalid enum alBufferData despite correct format given

### ISSUE THREAD

**Issue by adct-the-experimenter** [kcat/openal-soft#169]
I'm using Qt Multimedia to extract data from a buffer. I have a context created. 
I get an Invalid_enum error after using alBufferData. I have checked that I am setting format to AL_FORMAT_STEREO16 which is what was read. 

I have no idea what could possibly be causing this error.
Any ideas?

My setup is FreeBSD-10.3 and this was compiled with clang.
Code:
    buffer = 0; //initialize temp buffer
    alGenBuffers(1, &buffer);//request 1 buffer
    //set buffer data
    alBufferData(buffer, format, data, slen, frequency);
    /* Check if an error occured, and clean up if so. */
    err = alGetError();
    if(err != AL_NO_ERROR)
    {
        //fprintf(stderr, "OpenAL Error: %s\n", alGetString(err));
        loadSound_Results.append("OpenAL Error in loading sound: ");
		loadSound_Results.append(alGetString(err));
		loadSound_Results.append("\n");
        if(buffer && alIsBuffer(buffer)){alDeleteBuffers(1, &buffer);}
        return;
    }

**Comment by kcat** [comment]
Which version of OpenAL Soft are you using? I'd first double-check that the error didn't occur before ```alBufferData```  and you just forgot to call ```alGetError``` to see it until after.

**Comment by adct-the-experimenter** [comment]
I am using the 1.18.2 release version on Freshports.org . I will check and let you know the results.

**Comment by adct-the-experimenter** [comment]
The invalid_enum error is happening before the alBufferData is called. It was just something as simple as that. Thanks for your help! I'll check where else I have an invalid enum then.
