### ISSUE TITLE
virus total detect a trojan on installer 

### ISSUE THREAD

**Issue by y1111** [kcat/openal-soft#172]
i downloaded the windows zip from this adress https://www.openal.org/downloads/

and after unzip , i send to virustotal and got a trojan warming.

**Comment by kcat** [comment]
Those aren't OpenAL Soft's downloads. You're better off getting in touch with [icculus](https://icculus.org/~icculus/), or [here](https://github.com/TimeDoctor/openal-website) where the site files are stored.

**Comment by y1111** [comment]
so is that a fake site ? i suspected it but do not have sure , i you have sure report it on Wot web of trust ,and those sites.

but im asking here because can be a false positive too , from 68 AVs only 1 found trojan . see on the page https://www.virustotal.com/en/file/b8f39714d41e009f75efb183c37100f2cbabb71784bbd243be881ac5b42d86fd/analysis/1519237119/

**Comment by kcat** [comment]
The site isn't fake, it's just not maintained by me (OpenAL itself isn't me, just the OpenAL Soft implementation is). The SHA256 hash looks correct, BTW, so I'd presume it's just a false positive (especially since only 1 of the 68 checks thinks there's a problem).
