### ISSUE TITLE
SDL2 as a backend

### ISSUE THREAD

**Issue by jhasse** [kcat/openal-soft#173]
I was wondering if it would be easy to use SDL2 as a *backend*? I'm currently using OpenAL for a game and SDL2 is available for some game consoles where none of the other backends have been ported yet.

**Comment by kcat** [comment]
Looks like it should be possible, using the explicit `*Device` family of audio functions to avoid stepping on (or being stepped on by) a global device handle. The main question would be how to handle (sub-)system initialization. Should an SDL2 backend try to initialize its audio subsystem, or only work if it's already initialized? If it initializes it, should it automatically deinitialize it upon shutting down? What would happen if the audio subsystem gets deinitialized by the app while a device is still open and playing?

**Comment by jhasse** [comment]
I would say use [SDL_WasInit](https://wiki.libsdl.org/SDL_WasInit) to check if it was already initilialized. If not: Initialize the subsystem and also deinitialize. If it is already initiliazed assume that the user handles this all by himself.

> What would happen if the audio subsystem gets deinitialized by the app while a device is still open and playing?

I guess that's something the user has to keep in mind when he uses the backend.

**Comment by jgranick** [comment]
Is it possible to know the priority of OpenAL-Soft's backends?

If we enable SDL2 as an audio backend, do we need to disable all others for it to be enabled? Thank you

**Comment by jhasse** [comment]
> Is it possible to know the priority of OpenAL-Soft's backends?

Have a look at the `BackendList`: https://github.com/kcat/openal-soft/blob/86319127e3e377312f815d55693f7b46569cde62/Alc/ALc.c#L63
Backends appearing first have higher priority.

> If we enable SDL2 as an audio backend, do we need to disable all others for it to be enabled?

Basically yes, but it would also be chosen if other backends aren't available at runtime.

**Comment by jgranick** [comment]
I would have guessed it would be in descending order on that list, but while I was looking around, I found a comment about "the new JACK backend" and that it was "quite low on the priority list", so when I saw it up at the thought, I suspected there might be some other mechanism -- but I couldn't find it.

Two other small questions (if you don't mind), does it perform as well as the other backends? For game consoles, is there any way to use OpenAL-Soft without the GPL license preventing its use?

**Comment by jhasse** [comment]
> Two other small questions (if you don't mind), does it perform as well as the other backends?

Yes, it worked perfectly from my testings.

> For game consoles, is there any way to use OpenAL-Soft without the GPL license preventing its use?

OpenAL Soft's license is LGPLv2. This means, that if you do any modifications to it, users of your binary can request the modified source of OpenAL Soft.

LGPLv**3** would NOT be okay, since that would require users to be able to run the modified binary on the game console, which they can't due to DRM. See https://en.wikipedia.org/wiki/Tivoization

Btw: Sony itself uses LGPLv2 software on the PS4: https://doc.dl.playstation.net/doc/ps4-oss/ffmpeg.html

IANAL though, so if you want to be on the safe side, check out [mojoAL](https://hg.icculus.org/icculus/mojoAL) which is an OpenAL implementation using SDL2 under the zlib license.

**Comment by jgranick** [comment]
I guess I understood it like this:

> Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided.

So I thought that unless you 1.) used dynamic linking and 2.) provided a way for users to modify your application package then your source code was "tainted" by the GPL and had to all be released as open-source

**Comment by jhasse** [comment]
Are you able to relink the PS4 web browser?
