### ISSUE TITLE
Unable to build in cygwin

### ISSUE THREAD

**Issue by Sector7CSD** [kcat/openal-soft#176]
When I try to build openal-soft in an cygwin environment the following happens:
```sh
[16:46:25][Secto@worf:~/Development/openal-soft/build]$ make
[  7%] Built target common
[  9%] Built target ex-common
[ 10%] Built target native-tools
[ 10%] Built target build_version
[ 12%] Linking C shared library cygopenal-1.dll
CMakeFiles/OpenAL.dir/Alc/backends/winmm.c.o: In function `ProbePlaybackDevices':
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:76: undefined reference to `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:76:(.text+0x7a6): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:76: undefined reference to `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:76:(.text+0x831): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `alstr_append_wcstr'
CMakeFiles/OpenAL.dir/Alc/backends/winmm.c.o: In function `ProbeCaptureDevices':
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:119: undefined reference to `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:119:(.text+0xf46): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:119: undefined reference to `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/winmm.c:119:(.text+0xfd1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `alstr_append_wcstr'
CMakeFiles/OpenAL.dir/Alc/backends/dsound.c.o: In function `ALCdsoundPlayback_open':
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:366: undefined reference to `__imp_CoInitialize'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:366:(.text+0xdc4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_CoInitialize'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:371: undefined reference to `__imp_CoUninitialize'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:371:(.text+0xdec): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_CoUninitialize'
CMakeFiles/OpenAL.dir/Alc/backends/dsound.c.o: In function `DSoundEnumDevices':
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:150: undefined reference to `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:150:(.text+0xf95): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:150: undefined reference to `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:150:(.text+0x1021): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:166: undefined reference to `__imp_StringFromCLSID'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:166:(.text+0x107d): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_StringFromCLSID'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:170: undefined reference to `__imp_CoTaskMemFree'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:170:(.text+0x109c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_CoTaskMemFree'
CMakeFiles/OpenAL.dir/Alc/backends/dsound.c.o: In function `ALCdsoundCapture_open':
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:729: undefined reference to `__imp_CoInitialize'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:729:(.text+0x1584): additional relocation overflows omitted from the output
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:734: undefined reference to `__imp_CoUninitialize'
CMakeFiles/OpenAL.dir/Alc/backends/dsound.c.o: In function `ALCdsoundBackendFactory_probe':
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:1036: undefined reference to `__imp_CoInitialize'
/home/Secto/Development/openal-soft/Alc/backends/dsound.c:1056: undefined reference to `__imp_CoUninitialize'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiPlayback_mixerProc':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:630: undefined reference to `__imp_CoInitialize'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:689: undefined reference to `__imp_CoUninitialize'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiPlayback_resetProxy':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:913: undefined reference to `__imp_CoTaskMemFree'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `get_device_formfactor':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:229: undefined reference to `__imp_PropVariantClear'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiPlayback_resetProxy':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:910: undefined reference to `__imp_CoTaskMemFree'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `get_device_name_and_guid':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:179: undefined reference to `__imp_PropVariantClear'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:173: undefined reference to `alstr_append_wcstr'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:191: undefined reference to `alstr_copy_wcstr'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiPlayback_openProxy':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:824: undefined reference to `__imp_CoCreateInstance'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiCapture_openProxy':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:1545: undefined reference to `__imp_CoCreateInstance'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiCapture_recordProc':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:1324: undefined reference to `__imp_CoInitialize'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:1432: undefined reference to `__imp_CoUninitialize'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiCapture_resetProxy':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:1716: undefined reference to `__imp_CoTaskMemFree'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:1707: undefined reference to `__imp_CoTaskMemFree'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:1713: undefined reference to `__imp_CoTaskMemFree'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `add_device':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:244: undefined reference to `strdupW'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `probe_devices':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:333: undefined reference to `__imp_CoTaskMemFree'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:339: undefined reference to `__imp_CoTaskMemFree'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiProxy_messageHandler':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:391: undefined reference to `__imp_CoInitialize'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:399: undefined reference to `__imp_CoCreateInstance'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:411: undefined reference to `__imp_CoUninitialize'
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:403: undefined reference to `__imp_CoUninitialize'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiPlayback_open':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:781: undefined reference to `strdupW'
CMakeFiles/OpenAL.dir/Alc/backends/wasapi.c.o: In function `ALCwasapiCapture_open':
/home/Secto/Development/openal-soft/Alc/backends/wasapi.c:1485: undefined reference to `strdupW'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/OpenAL.dir/build.make:1322: cygopenal-1.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:554: CMakeFiles/OpenAL.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
[16:46:29][Secto@worf:~/Development/openal-soft/build]$
```

After a bit digging around I discovered the following things:
- The libraries **ole32** and **shlwapi** are missing in the linkage. When I manually modify the **link.txt** in the **build/CMakeFiles/OpenAL.dir** those errors are gone

- **strdupW** is defined in the windows shell api as **StrDupW**, I modified the 3 lines in **/Alc/backends/wasapi.c** to solve this

- The function **alstr_copy_wcstr** is missing in my compilation of the **/Alc/ helpers.c**. Check it with the **strings** command on the object file. It looks like, that the define for the preprocessor flag **_DWIN32** is some how unset.

After all those dirty steps I was successfully able to compile it, to use it and everything works fine.

What would be a correct fix for those?

Best regards,
Sector7

**Comment by Sector7CSD** [comment]
Hi kcat,

here are the outputs as files from cmake and make.

[make_output.txt](https://github.com/kcat/openal-soft/files/1804573/make_output.txt)
[cmake_output.txt](https://github.com/kcat/openal-soft/files/1804574/cmake_output.txt)

During the execution of cmake I noticed a warning / information:

```sh
CMake Warning at /usr/share/cmake-3.6.2/Modules/Platform/CYGWIN.cmake:15 (message):
  CMake no longer defines WIN32 on Cygwin!
```

In that warning is mentioned that I should set CMAKE_LEGACY_CYGWIN_WIN32=1. When I do this (with export of course), execute cmake again and then execute make I encounter the same problems.

**Comment by kcat** [comment]
It also looks like setting `CMAKE_LEGACY_CYGWIN_WIN32` didn't do anything since cmake defining `WIN32` should make the headers use `__declspec(dllexport)`, but it still complains about `__attribute__((visibility(...)))` being ignored. Did you pass it to cmake, or set it via ccmake or ...?

**Comment by Sector7CSD** [comment]
To be honest, I've never used cmake before. In the warning was mentioned that I should set an environment variable
```sh
export CMAKE_LEGACY_CYGWIN_WIN32=1
```
, run cmake and make again. I've checked the output of cmake and then this warning disappeared.

**Comment by jhasse** [comment]
Did you try to replace the checks for `WIN32` with `_WIN32`? The latter is also defined by MSVC / MSYS2 and is more reliable.

**Comment by Sector7CSD** [comment]
When I try to run
```
cmake .. -DCMAKE_LEGACY_CYGWIN_WIN32=1
```

And adjust/add the following lines:

- compat.h @ line 10:

```cpp
#ifdef _WIN32

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
```

- oss.c @ line 65 (Just before the FreeBSD ifdef lines):
```cpp
#ifdef _WIN32
#include <Winsock2.h>
#endif
```

- CMakesLists.txt @ line 92 (which is inside the if win32 part):
```sh
SET(EXTRA_LIBS ole32 shlwapi ${EXTRA_LIBS})
```

I get the following linker errors, which look so far not so bad:
```sh
[08:28:47][Secto@worf:~/Development/openal-soft/build]$ make
[  7%] Built target common
[  9%] Built target ex-common
[ 10%] Built target native-tools
[ 10%] Built target build_version
[ 11%] Linking C shared library OpenAL32-1.dll
CMakeFiles/OpenAL.dir/Alc/alconfig.c.o: In function `ReadALConfig':
/home/Secto/Development/openal-soft/Alc/alconfig.c:403: undefined reference to `_wgetenv'
/home/Secto/Development/openal-soft/Alc/alconfig.c:403:(.text+0xa2f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_wgetenv'
CMakeFiles/OpenAL.dir/Alc/helpers.c.o: In function `al_fopen':
/home/Secto/Development/openal-soft/Alc/helpers.c:524: undefined reference to `_wfopen'
/home/Secto/Development/openal-soft/Alc/helpers.c:524:(.text+0x7f4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_wfopen'
CMakeFiles/OpenAL.dir/Alc/helpers.c.o: In function `SearchDataFiles':
/home/Secto/Development/openal-soft/Alc/helpers.c:629: undefined reference to `_wgetenv'
/home/Secto/Development/openal-soft/Alc/helpers.c:629:(.text+0x19f6): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_wgetenv'
/home/Secto/Development/openal-soft/Alc/helpers.c:638: undefined reference to `_wgetcwd'
/home/Secto/Development/openal-soft/Alc/helpers.c:638:(.text+0x1a16): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_wgetcwd'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/OpenAL.dir/build.make:1374: OpenAL32-1.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:554: CMakeFiles/OpenAL.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

So far I was unable to find the correct libraries for the missing functions.

**Comment by Sector7CSD** [comment]
I reverted all my changes, updated my local working copy to the latest head revision (commit 414b56edec5441211dc924fef365c54267c04f1c) and started over again.

This time I have not specified the **CMAKE_LEGACY_CYGWIN_WIN32** flag. I worked a bit on cmake during my easter holidays and came up with the following:

- CMakeLists.txt

  - Added a special CYGWIN entry which sets the a **CYGWIN** cpp define and adds the **ole32** & **shlwapi** libraries to the linker for the **EXTRA_LIBS**

- compat.h

  - I added a missing include for **stdio.h**
  - Modified the **#ifdef** check, so that **strdupW** is included in **_WIN32** and in **CYGWIN**
  - **al_fopen** for **CYGWIN** is still defined as **fopen**

- helpers.c

  - Replaced some **#ifdef _WIN32** with **#if defined(_WIN32) || defined(CYGWIN)**
  - Added **#ifndef CYGWIN** around the implementation of the windows version of **al_fopen**
  - Moved both implementations of **DirectorySearch** and **SearchDataFiles** into a seperate **#ifdef** block, so I can use the non windows one for **CYGWIN**. That resolves my previous problems with the linker errors with **_wgetenv**, **_wfopen** and **_wgetcwd**. Those functions seems to be special Mircosoft C++ runtime functions.

Compiles and works in CYGWIN perfectly.

```sh
[ 75%] Linking C shared library cygopenal-1.dll
[ 75%] Built target OpenAL
...
[ 96%] Building C object CMakeFiles/altonegen.dir/examples/common/alhelpers.c.o
[ 97%] Building C object CMakeFiles/alplay.dir/examples/alplay.c.o
[ 98%] Linking C executable altonegen.exe
[100%] Linking C executable alplay.exe
[100%] Built target altonegen
[100%] Built target alplay
[22:31:03][Secto@worf:~/Development/openal-soft/build]$
```

With my modifications inplace it compiles also in Linux (Debian):

```sh
[ 89%] Building C object CMakeFiles/OpenAL.dir/Alc/backends/oss.c.o
[ 91%] Building C object CMakeFiles/OpenAL.dir/Alc/backends/wave.c.o
Linking C shared library libopenal.so
[ 91%] Built target OpenAL
Scanning dependencies of target alrecord
[ 93%] Building C object CMakeFiles/alrecord.dir/examples/alrecord.c.o
Linking C executable alrecord
[ 93%] Built target alrecord
Scanning dependencies of target altonegen
[ 94%] Building C object CMakeFiles/altonegen.dir/examples/altonegen.c.o
[ 96%] Building C object CMakeFiles/altonegen.dir/examples/common/alhelpers.c.o
Linking C executable altonegen
[ 96%] Built target altonegen
Scanning dependencies of target makehrtf
[ 98%] Building C object CMakeFiles/makehrtf.dir/utils/makehrtf.c.o
Linking C executable makehrtf
[ 98%] Built target makehrtf
Scanning dependencies of target openal-info
[100%] Building C object CMakeFiles/openal-info.dir/utils/openal-info.c.o
Linking C executable openal-info
[100%] Built target openal-info
chris@betsy ~/Development/build $
```

Here are my touched soucecode files:
[openal-soft.zip](https://github.com/kcat/openal-soft/files/1873268/openal-soft.zip)

**Comment by kcat** [comment]
> al_fopen for CYGWIN is still defined as fopen

How does Cygwin handle Unicode filenames? Under Windows, filenames specified as `char*` are ANSI, which is unable to deal with characters not in the current code page. The `_w*` functions are necessary to properly handle Unicode filenames on Windows. OpenAL Soft treats `char*` strings as UTF-8, and converts to/from `WCHAR*` to retain Unicode when interacting with the Windows system APIs.

> Replaced some #ifdef _WIN32 with #if defined(_WIN32) || defined(CYGWIN)
> ...
> Moved both implementations of DirectorySearch and SearchDataFiles into a seperate #ifdef block, so I can use the non windows one for CYGWIN.

It concerns me that Cygwin doesn't identify itself as Windows, while still relying on (parts of) the Windows API. The code using the Windows API was tested and designed for a full Windows environment, and it's difficult to say what subtle bugs may be caused by only using some of it.

> That resolves my previous problems with the linker errors with _wgetenv, _wfopen and _wgetcwd. Those functions seems to be special Mircosoft C++ runtime functions.

They're part of the Windows' basic C runtime (`msvcrt.dll`). Even MinGW has them, which doesn't use MSVC's C++ runtimes.

**Comment by okuoku** [comment]
(Cygwin already have openal package https://github.com/cygwinports/openal . What was wrong with it?)

> How does Cygwin handle Unicode filenames? 

It should follow locale settings e.g. `LANG` variable. [The default is "C.UTF-8" thus it should be safe to assume they use utf-8 for functions](https://cygwin.com/cygwin-ug-net/ov-new.html#ov-new1.7-posix).

> The code using the Windows API was tested and designed for a full Windows environment, and it's difficult to say what subtle bugs may be caused by only using some of it.

OSS (`/dev/dsp`) is the only choice on "native" audio output on Cygwin (with POSIX I/F). The Cygwin distribution uses portaudio and pulseaudio; so it doesn't rely on OpenAL-Soft's OS specific output layer.

> They're part of the Windows' basic C runtime

Cygwin itself does not rely on msvcrt because it has their own C runtime with different behaviour. For example, Cygwin's `fopen` would take UTF-8 (or any charset specified with locale) but MSVCRT one would take ASCII(OEM charset) thus they cannot mix into single executable.

**Comment by Sector7CSD** [comment]
Sorry for the long delay. 

During my search for a perfect Linux-like environment to compile Windows programs and libraries I found this:
[https://github.com/dockcross/dockcross](url)

This contains multiple ready-to-use crosscompile toolchains stored into docker containers, including Win64 and Win32.

This works perfectly for me - there is no need for me to be able to compile under Windows with Cygwin.
