### ISSUE TITLE
New stable version

### ISSUE THREAD

**Issue by Krakean** [kcat/openal-soft#186]
@kcat 
Hello. When new stable release of OPenAl-Soft is planned, approximatelly?

**Comment by Krakean** [comment]
@kcat ping?

**Comment by kcat** [comment]
Sorry, meant to respond earlier. No current plans, but I probably should get a release out in the next month or two. I'll need to look over what's been done, what's nearly done, and what needs fixing, then I can consider a release when that's all dealt with.

**Comment by Krakean** [comment]
@kcat any progress on new stable version release date?

**Comment by kcat** [comment]
1.19.0 has now been released.
