### ISSUE TITLE
listener attenuation broken in 1.18.2

### ISSUE THREAD

**Issue by ghost** [kcat/openal-soft#189]
Hi,
i have a serious problem with the open al listener. Everything else works as expected when moving sources around but moving listener position has no effect. I am using mono sound to do my testing. What am I doing wrong??

my project page is here https://sourceforge.net/projects/rhythm-me-this/
the code i am testing with the backend https://sourceforge.net/p/rhythm-me-this/code/ci/master/tree/tests/audio_backend/main.cpp

Regards,
Shomari

**Comment by kcat** [comment]
Hi.

Taking a quick look at your code, it seems you're always setting the source to be relative:
```
void GAudioPlayerStatic_OPENAL::ApplyAttenuationProperties()
{
    alGetError();
    if (!m_attenuation)
    {
        ///2D sound [OK] ..do distance attenuation
        alSourcei(m_source, AL_SOURCE_RELATIVE, AL_TRUE);
        alSourcef(m_source, AL_REFERENCE_DISTANCE, 0);
        alSourcef(m_source, AL_ROLLOFF_FACTOR, 0);
    } else
    {
        alSourcei(m_source, AL_SOURCE_RELATIVE, AL_TRUE);
        alSourcef(m_source, AL_REFERENCE_DISTANCE, m_refdistance);
        alSourcef(m_source, AL_ROLLOFF_FACTOR, m_rolloff);
        alSourcef(m_source, AL_MAX_DISTANCE, m_maxdistance);
    }
} //end function
```
A similar thing occurs for streaming sources. So no matter whether distance attenuation is set or not, `AL_SOURCE_RELATIVE` is set to true which causes the specified position to always be relative to the listener.

**Comment by shomarisharpe** [comment]
Well that must be it i actually tried a simplified version with 3 wave file on windows and it works perfectly. So basically you're saying setting AL_SOURCE_RELATIVE is throwing off everything ...i'll test it and let you know. Here is a snippet i used to verify under windows.


#include <AL/al.h>
#include <AL/alc.h>
#include <AL/alext.h>
#include <AL/efx.h>

#include <windows.h>
#include <stdio.h>


ALuint loadwave(char* filename)
{
    ALuint bufferid = 0;
    FILE* file = fopen(filename, "rb");
    if (file)
    {
        char header[4] = {0};
        int32_t filesize = 0;
        char format = 0, bits = 0;
        short channels = 0;
        int32_t samplerate = 0, datasize = 0;

        fread(header, 1, sizeof(header), file);
        fread(&filesize, 1, sizeof(int32_t), file);
        fread(header, 1, sizeof(header), file);

        fseek(file, 21, SEEK_SET);
        fread(&format, 1, 1, file);
        fread(&channels, 1, 2, file);
        fread(&samplerate, 1, sizeof(int32_t), file);

        fseek(file, 34, SEEK_SET);
        fread(&bits, 1, 1, file);

        fseek(file, 40, SEEK_SET);
        fread(&datasize, 1, sizeof(int32_t), file);

        if (datasize)
        {
            char buffer[datasize];
            fread(buffer, 1, datasize, file);
            alGenBuffers(1, &bufferid);

            ALuint format = 0;
            if (bits == 8)
            {
                if (channels == 1)
                    format = AL_FORMAT_MONO8;
                else
                    format = AL_FORMAT_STEREO8;
            } else if (bits == 16)
            {
                if (channels == 1)
                    format = AL_FORMAT_MONO16;
                else
                    format = AL_FORMAT_STEREO16;
            }

            alBufferData(bufferid, format, buffer, datasize, samplerate);
        }

        fclose(file);
    }
    return bufferid;
}


int main()
{
    ALCdevice* dev = alcOpenDevice(NULL);
    ALCcontext* ctx = alcCreateContext(dev, NULL);
    alcMakeContextCurrent(ctx);

    const char* vendors = alGetString(AL_VENDOR);
    printf("vendor: %s \n", vendors);

    const char* extensions = alGetString(AL_EXTENSIONS);
    printf("extensions: %s \n", extensions);

    ALuint asource = 0, bsource = 0, csource = 0;
    alGenSources(1, &asource);
    alGenSources(1, &bsource);
    alGenSources(1, &csource);


    ALuint abuff = loadwave("a.wav");
    ALuint bbuff = loadwave("b.wav");
    ALuint cbuff = loadwave("c.wav");

    alSourcei(asource, AL_BUFFER, abuff);
    alSourcei(asource, AL_LOOPING, AL_TRUE);
    alSourcePlay(asource);

    alSourcei(bsource, AL_BUFFER, bbuff);
    alSourcei(bsource, AL_LOOPING, AL_TRUE);
    alSource3f(bsource, AL_POSITION, 6, 2, 0);
    alSourcePlay(bsource);

    alSourcei(csource, AL_BUFFER, bbuff);
    alSourcei(csource, AL_LOOPING, AL_TRUE);
    alSource3f(csource, AL_POSITION, 0, -2, -4);
    alSourcePlay(csource);

    int count = 0;
    float pos = 0;
    DWORD lasttime = 0, currtime = 0;
    DWORD delay = 120;
    int left = 1;
    while (count < 5)
    {
        currtime = GetTickCount();
        if (lasttime - currtime >= delay)
        {
            if (left)
                pos -= 0.1;
            else
                pos += 0.1;
            if (pos < -10)
            {
                left = !left;
                count++;
            }
            if (pos > 10)
            {
                left = !left;
                count++;
            }

            alListener3f(AL_POSITION, pos, 0, 0);
            lasttime = currtime;
        }
    }



    getchar();

    ///cleanup
    alcMakeContextCurrent(NULL);
    alcDestroyContext(ctx);
    alcCloseDevice(dev);

    return 0;
}

**Comment by shomarisharpe** [comment]
Could you please explain exactly what alSourcei(source, AL_SOURCE_RELATIVE, AL_TRUE) and alSourcei(source, AL_SOURCE_RELATIVE, AL_FALSE) do exactly? I assumed that it meant that mean sound is adjusted with attenuation whenever the source is repositioned, etc.

**Comment by kcat** [comment]
`alSourcei(source, AL_SOURCE_RELATIVE, AL_TRUE);` means the source is interpreted to be relative to the listener. Essentially, it means the listener's position, velocity, and orientation do not affect it. Setting the source position to `{-1, 0, 0}` will always be to the left, for example, regardless of where the listener is or where it's facing.

`alSourcei(source, AL_SOURCE_RELATIVE, AL_FALSE);` means the source is interpreted to be placed globally. Its location relative to the listener's location and orientation determines where it's heard from.

**Comment by shomarisharpe** [comment]
I figured, just wanted to be clear about it. Ok I have a question suppose i'm writing a game where I want sounds (panning) from the center of the screen 2D (i.e if a character is more to the left of the screen then the sound will be generated more from the left speaker and the same effect applies to the right side of the screen)?

**Comment by kcat** [comment]
For simple panning, you'd typically use relative positioning, like this:
```
// During initial source setup
alSourcei(source, AL_SOURCE_RELATIVE, AL_TRUE);
alSourcef(source, AL_ROLLOFF_FACTOR, 0.0f);
...

// Set panning
ALfloat pan = ...; // -1 = left, 0 = center, +1 = right

pan *= 0.5f;
alSource3f(source, AL_POSIITION, pan, 0.0f, -sqrtf(1.0f - pan*pan));
```
