### ISSUE TITLE
Generic Software sound device problem...

### ISSUE THREAD

**Issue by ForserX** [kcat/openal-soft#190]
Crashes on dsound after a couple of minutes of the game.

https://github.com/xrOxygen/xray-oxygen/issues/117

**Comment by kcat** [comment]
Generic Software is Creative's wrapper driver, not OpenAL Soft. Unfortunately the code for the the wrapper driver isn't available, so there's not much I can do about crashes in it. At best, we could figure out what that engine is doing that causes the crash and try to avoid doing it (which may be difficult if it's not technically doing anything wrong).

**Comment by ForserX** [comment]
When you try to shoot at the NPC speech.

**Comment by ForserX** [comment]
It's invalide issue. Sorry...
