### ISSUE TITLE
sndio support...

### ISSUE THREAD

**Issue by mazocomp** [kcat/openal-soft#198]
Hi!

I don't know do you test sndio backend support or not, but at my machine openal-soft makes programs crash since 1.17.x releases and they keep crashing when using latest 1.18.2 release...

**Comment by kcat** [comment]
Hi, sorry for the late response. Does every OpenAL app crash, or just some of them? Does it happen right away, or does some audio play first? Can you get a backtrace of the crash?

**Comment by mazocomp** [comment]
@kcat sorry, I forgot to tell that happens at every app when trying to use audio input. OpenBSD already has a fix for that, but that patch is made for 1.17.2 release: https://github.com/openbsd/ports/blob/master/audio/openal/patches/patch-Alc_backends_sndio_c

**Comment by kcat** [comment]
Hmm, well the sndio backend doesn't currently support capture, so it audio input won't work. As long as the app is coded properly, it shouldn't crash though.

I'll see what I can do about integrating that patch for capture support into the latest code.

**Comment by kcat** [comment]
Capture support for sndio is now added in commit 212cb8e298ccfd42e8d44cc2a20108513507e29e, and will be part of the future 1.19.1 release.

**Comment by mazocomp** [comment]
@kcat I need to ask you about your versioning policy because I am confused should I raise a minor number or a major number. Look, in OpenBSD ports tree your library version is marked as 3.0, so in case you only added new functions and programs will keep working, I should mark its version as 3.1, if you have removed any function (and broken backwards compatibility) then I should mark its version as 4.0

**Comment by mazocomp** [comment]
Ok, I raised it to 3.1 and nothing is broken yet.
