### ISSUE TITLE
Weird stereo panning in 1.18.x

### ISSUE THREAD

**Issue by dezo2** [kcat/openal-soft#216]
The panning in recent versions is really strange. I did some testing in Doom 3 source port (dhewm3) and it's like Left - Center - Right and nothing in between. Looking at a person talking - just a slight move off center and it jumps to Left or Right. Also some projectiles sounds are comming from far side and not just slight off center (i.e. plasma gun). Have I misconfigured something or is it a bug? My OpenAL soft settings are "Stereo", "Speakers", "DirectSound" (Win7 x64), everything else is on default.

**Comment by dezo2** [comment]
Hi, thanks for the reply. The game FOV was at default 90 degs and my listening position is based on equilateral triangle. I am not sure the +30 / -30 degs explanation is legit in terms of in-game stereo positioning. Why should you shift directional sound to the far side when the camera is rotated only by 30 degs? The character in front of the camera barely moves to the side, so the direction of his sound doesn't match with his position at all. Comparing this to the vanilla Doom 3 (or any other game in that regard) sounds just weird. The OAL version 1.16 sounds right, any newer behave like this.

**Comment by kcat** [comment]
I should clarify that stereo speakers are expected to be placed at +/-30 degrees, so when a sound moves 30 degrees left it gets placed on the left speaker, which would be 30 degrees left. If the speakers are instead placed at +/-45, 60, or 90 degrees, then it obviously won't line up, and unfortunately few audio systems actually report this information to correct the panning spread (DirectSound is the only API I've seen to do so, but it defaults to +/-20 degrees, which it also considers "wide").

Obviously something will need to be done here though, if people are unhappy with the current stereo spread. But it'll be tricky to come up with something that doesn't also mess with stereo sources and the stereo_angles extension.

**Comment by dezo2** [comment]
Just tried it with UHJ stereo encoding and it is a little better, but it also adds some filtering to the original sound by encoding surround info. Anyway I always thought is should be in +/- 90 degs range when positioning mono samples in 3D games for two speakers (plain stereo), but I am just a noob in this area, so what can I know :-) Maybe some parameter could be added to the external config for adjusting it to pan like in 1.16 - just consider it for future versions. Thanks.

**Comment by kcat** [comment]
The main issue is consistency. For surround sound and HRTF, +/-90 degrees is directly left and directly right. Ideally, a stereo response would essentially be like if you took a surround sound mix and remixed that down to just the front channels (doing things to the side and back channels to not lose them completely).

Also, it turns out that horizontal sound accuracy for humans drops off on the sides and back (i.e. it's harder to pinpoint specifically, and tell when it moves). If stereo was treated as +/- 90 while the speakers were actually placed in front, that'd create a smooth perception of panning from -90 to +90 for stereo, while surround sound and HRTF will have a different experience when the sound is around the two ends, only being smooth when its more toward the front.

If +/- 30 degrees is too narrow a range, it could perhaps be expanded to 45 or 60. But I can't imagine larger than that being desirable.

**Comment by skiselkov** [comment]
I'm struggling with a very similar issue on 1.18.2. I'm building the Windows and Linux versions directly from source, plain as plain can be (Windows version is actually cross-compiled from Linux). The stereo panning on Windows extremely pronounced, where any off-angle viewing of the audio source just makes the far stereo channel die off to nothing. See comparison videos:

Windows: https://youtu.be/PzJtfEBHXPg
Linux: https://youtu.be/AfeIa780atY

As you can hear, on Linux the far channel does diminish, but nowhere near as much as on Windows, where it just goes to zero. Audacity waveforms of these two clips:

Windows: 
![windows](https://user-images.githubusercontent.com/3300688/44753590-e8ecc600-ab1e-11e8-9436-61899338c521.png)
Linux: 
![linux](https://user-images.githubusercontent.com/3300688/44753605-f1dd9780-ab1e-11e8-8c9d-3567748ed283.png)

I've tried enabling HRTF when opening the device, I tried messing around with the stereo stage width, I tried just about anything, but I can't get the same panning on Windows as I get on Linux. What am I doing wrong?

**Comment by kcat** [comment]
@skiselkov It looks and sounds like HRTF is being enabled for Linux, but it's using plain stereo for Windows. If you're using the `ALC_SOFT_HRTF` extension to enable it in-game, make sure you don't have an alsoft.ini anywhere that may be forcefully disabling it. Second, make sure the device is properly configured; OpenAL Soft's default HRTF data sets only support 44.1khz and 48khz, so if it's set to something else in the control panel then HRTF won't be available.

**Comment by kcat** [comment]
Current git (commit 827c66f4f6f1b84082e2ce77ab0dc82221e6adc7) now has the stereo width widened, so front panning should be smoother with plain stereo.

**Comment by kcat** [comment]
Good call. Not sure why it wasn't already, actually. The built-in HRTFs are enabled by default now.

**Comment by skiselkov** [comment]
@kcat Great, thanks for the help again!

**Comment by kcat** [comment]
I'm closing this since it seems to be addressed (stereo panning width is wider, so it should have a smoother left<->right transition). HRTF has also been taken care of to have it built-in by default. If there's still an issue, let me know to either reopen this, or you can open a new issue.
