### ISSUE TITLE
Error generating build for Watcom Wmake

### ISSUE THREAD

**Issue by FlyingJester** [kcat/openal-soft#23]
running cmake errors out with:

```
CMake Error at CMakeLists.txt:415 (MESSAGE):
  No case-insensitive compare function found, please report!
```

**Comment by kcat** [comment]
Does it not support ```strcasecmp```? Does it have any function for a case-insensitive string compare?

**Comment by FlyingJester** [comment]
Not that I could find. I removed that section of the cmake file just to see how far it would get otherwise. It also lacks a strncasecmp-like function, and errors on that part.

**Comment by kcat** [comment]
Does it happen to have ```stricmp``` and ```strnicmp```? What ```str*cmp``` functions does it have?

**Comment by FlyingJester** [comment]
Not that I am aware of. It does not have stricmp, strnicmp. I believe it just has the bare basic strcmp and strncmp.

**Comment by kcat** [comment]
The `strcasecmp`/`stricmp` from libc is no longer used, so this is no longer an issue.
