### ISSUE TITLE
[REGRESSION] "CLICK" sound after upgrade to 1.19 release when playing games with Wine.

### ISSUE THREAD

**Issue by Kerrung** [kcat/openal-soft#230]
Hi! Thank you very much for your work!
But now I hear the annoying "CLICK" sound after upgrade to 1.19 release when playing games with Wine.
For example this happens when I playing The Witcher 3 game using Wine. But this does not happen if I did downgrade to the 1.18.2 release. I using Arch Linux. Do you need some any more info, logs etc? Let me know if you need it.

**Comment by kcat** [comment]
Hi. This has already been reported as issue #226, which was fixed with commit 8bacb5dfb8ef910586fcf5b5cd89526ec81061e8. If you can't get or don't want to use the git version, the fix will be available in an upcoming 1.19.1 release.

**Comment by Kerrung** [comment]
Thank you! When will it be released?

**Comment by kcat** [comment]
Probably the next few weeks or a month, depending on various things.

**Comment by Kerrung** [comment]
Thank you.

**Comment by kcat** [comment]
1.19.1 is now available with this fix.

**Comment by Kerrung** [comment]
Thank you very much!
