### ISSUE TITLE
Question: multichannel buffer spatialized

### ISSUE THREAD

**Issue by nkari82** [kcat/openal-soft#232]
We want to make multi-channel buffer spatialized  on each channel. Is there any way?

**Comment by kcat** [comment]
I'm not sure I understand what you mean.

If you mean you want to spatialize each channel of a multi-channel buffer separately (e.g. move the left channel to xl,yl,zl, and the right channel to xr, yr, zr), there's no automatic way to do that. However, you can accomplish the same effect by deinterleaving the samples, using a different buffer for each channel, and using a different source for each buffer. Then you can move the sources individually, each one controlling a particular channel.

If you mean something else, can you clarify?

**Comment by nkari82** [comment]
Does it mean to split multi-channel into mono and output each?

**Comment by kcat** [comment]
Yes.
