### ISSUE TITLE
The server for openal-binaries is down

### ISSUE THREAD

**Issue by kivutar** [kcat/openal-soft#234]
http://kcat.strangesoft.net/openal-soft/openal-binaries/ is down.

These binary packages were useful for continuous integration, they were saving us some build time: https://github.com/libretro/ludo/blob/master/.appveyor.yml#L24

**Comment by kcat** [comment]
Apologies, it looks like there was a bit of a hiccup with the URL service. It should be back up in a few days. However, you can still get the files through http://openal-soft.org/openal-binaries/ (they're linked to the same storage, so all the files are the same).
