### ISSUE TITLE
Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by 5schatten** [kcat/openal-soft#235]
The recent openal-soft release 1.19.0 & 1.19.1 fail for me to build for an arm target stating:

native-tools/bin2h: 2: native-tools/bin2h: Syntax error: word unexpected (expecting ")")
make[2]: *** [CMakeFiles/OpenAL.dir/build.make:66: default-48000.mhr.h] Error 2
make[2]: *** Waiting for unfinished jobs....
native-tools/bsincgen: 1: native-tools/bsincgen: Syntax error: word unexpected (expecting ")")
make[2]: *** [CMakeFiles/OpenAL.dir/build.make:70: bsinc_inc.h] Error 2
[ 18%] Generating default-44100.mhr.h
native-tools/bin2h: 2: native-tools/bin2h: Syntax error: word unexpected (expecting ")")
make[2]: *** [CMakeFiles/OpenAL.dir/build.make:62: default-44100.mhr.h] Error 2
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/OpenAL.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

https://pastebin.com/F2avfmtY

But the latest version still builds fine tor x86-64 & the older release 1.18.2 also works with arm.

**Comment by kcat** [comment]
Hmm, looks like it's failing to run the bin2h executable, which seemed to get built with the same cross-compiler as the main project. You don't have the CC and CXX environment variables overridden, do you? For some reason it's not picking up the native compiler despite no cross-chain file being specified.

**Comment by 5schatten** [comment]
Well I'm building it the same way as LE does and cross-compiling works with 1.18.2 flawless.

LE package:
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/audio/openal-soft/package.mk

My package:
https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.0-rr/packages/audio/openal-soft/package.mk

**Comment by kcat** [comment]
What's handling the .mk files to do the cross-compilation? Is it playing with the `CC` or `CXX` environment variables prior to running cmake and make?

**Comment by 5schatten** [comment]
I guess something like this?
https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/functions
https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/optimize
https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/arch.arm

**Comment by kcat** [comment]
Yes, it's seems to be setting the `CC`, `CXX`, `CFLAGS`, and a bunch of other environment variables. That's unnecessary since the CMake toolchain file specifies what to use for the cross-compile build, and it's confusing the native sub-project build that needs the system's compiler to make apps to run.

**Comment by 5schatten** [comment]
Well the toolchain builds more than just CMake stuff so I guess it's needed to build several packages for a whole distribution. What confuses me is the fact that previous versions build flawless so there must be some changes under the hood that break it now.

**Comment by kcat** [comment]
> What confuses me is the fact that previous versions build flawless so there must be some changes under the hood that break it now.

Previously some data was pre-generated and included with the source, along with the programs that generated it. Now it's generated automatically during the build, to ensure the data doesn't get out of sync with the programs.

**Comment by kcat** [comment]
The native bsincgen and bin2h tools are no longer part of the build process. It doesn't need to compile and run them to build anymore.
