### ISSUE TITLE
Reverb Update

### ISSUE THREAD

**Issue by marauder2k7** [kcat/openal-soft#239]
Having an issue where reverb parameters are not updating based on zone. I am using torque3d which allows a developer to place zones and portals for rendering specific meshes, these zones can have reverb properties attached to them. is there a function that needs to be used to update reverb properties if they are changed?

**Comment by kcat** [comment]
Whenever you change the effect object properties, you need to reapply the effect to the effect slot. Presuming you're calling OpenAL EFX functions yourself, it's like this:
```
// Update effect properties
alEffectf(effect, AL_EAXREVERB_DENSITY, reverb->flDensity);
alEffectf(effect, AL_EAXREVERB_DIFFUSION, reverb->flDiffusion);
alEffectf(effect, AL_EAXREVERB_GAIN, reverb->flGain);
...

// Update effect slot with the changed effect
alAuxiliaryEffectSloti(auxslot, AL_EFFECTSLOT_EFFECT, effect);
```
Without knowing the specifics of the Torque3D engine, I don't know if anything different needs to be done for that.

**Comment by marauder2k7** [comment]
in torque 3d i think i will need a function that checks the parameters already set against updated ones, then  changes accordingling okay i think i got it :D thank you for such a quick reply usually on github u be waiting for a few days lol im trying to change torque3d over to solely use openal-soft :)

**Comment by marauder2k7** [comment]
okay i think i may be doing something wrong, i should upload my code and let u see it but ill explain it as best as i can to see if it will work. 
In torque3d the level designer places zones around the map these zones have reverb properties attached that work with the same arguments as the presets in efx-presets under the class SFXReverbProperties. I can actually apply EFX_PRESETS to this class and it works perfectly. everytime the player enters a new zone it changes mReverb to be the reverb properties in that zone, but no user input reverb settings get applied only the presets work. and only work when the game is first loaded like a global reverb setting. ive tried to do a check and then update reverb settings but it doesnt seem to work.

My function for checking is as follows
ALBoolean SFXALDevice::updateEffect(SFXReverbProperties &reverb, ALuint EffectID) 
{
  ALBoolean bUpdated = AL_FALSE
        if(mReverb != reverb) 
          {
                   mReverb = reverb;

                     ..........update reverb parameters.
                            
                  update effect slot
                ALBoolean bUpdate = AL_TRUE;
          }  
}        

This function is called everytime a sound effect is played in SFXALVoice

**Comment by kcat** [comment]
> everytime the player enters a new zone it changes mReverb to be the reverb properties in that zone, but no user input reverb settings get applied only the presets work. and only work when the game is first loaded like a global reverb setting. ive tried to do a check and then update reverb settings but it doesnt seem to work.

I'm having difficulty understanding what you mean here. And unfortunately the code you pasted doesn't look valid. `ALBoolean` isn't a type, it's `ALboolean`. You're also defining and setting a local variable at the end of a black where it goes out of scope (the compiler would normally warn about that). It also doesn't show any OpenAL code, so I can't say if there's anything wrong there. Are you getting any OpenAL errors from `alGetError`?

**Comment by marauder2k7** [comment]
oh sorry, this was just written as like a pseudocode type deal i didnt want to paste the actual example here i tell u what though i will tonight when i get home

**Comment by marauder2k7** [comment]
okay this is gonna be a long one lol sorry i hope you can see where i am going wrong here
in sfxCommon the structure is defined: 
class SFXReverbProperties
{
public:

	struct Parent;

	float flDensity;
	float flDiffusion;
	float flGain;
	float flGainHF;
	float flGainLF;
	float flDecayTime;
	float flDecayHFRatio;
	float flDecayLFRatio;
	float flReflectionsGain;
	float flReflectionsDelay;
	float flReflectionsPan[3];
	float flLateReverbGain;
	float flLateReverbDelay;
	float flLateReverbPan[3];
	float flEchoTime;
	float flEchoDepth;
	float flModulationTime;
	float flModulationDepth;
	float flAirAbsorptionGainHF;
	float flHFReference;
	float flLFReference;
	float flRoomRolloffFactor;
	int   iDecayHFLimit;

there are other details for validate, this structure is usually passed to mReverb 

In sfxALVoice when each sound is played we have this
	device->createAuxEffectSlots(&device->effectSlot);

	device->createEffect(&device->effect, AL_EFFECT_EAXREVERB);
	if (device->mOpenAL.alIsEffect(device->effect))
	{
		device->bEffectCreated = AL_TRUE;
	}

	if (device->bEffectCreated)
	{
		SFXReverbProperties mReverb;
		const SFXReverbProperties& getReverb(mReverb);
		if (&device->mReverb != &mReverb)
		{
			device->setReverb(mReverb, device->effect);
		}
		else {
			device->setReverb(device->mReverb, device->effect);
		}

		device->mOpenAL.alSource3i(sourceName, AL_AUXILIARY_SEND_FILTER, device->effectSlot, 0, AL_FILTER_NULL);
	}

after this is a fucntion that plays the source mOpenAL.alSourcePlay(mSourceName);

Then in sfxALDevice we have this

ALboolean SFXALDevice::createAuxEffectSlots(ALuint *uEffectSlot)
{
	ALboolean bReturn = AL_FALSE;

	mOpenAL.alGenAuxiliaryEffectSlots(1, uEffectSlot);
	if (mOpenAL.alGetError() == AL_NO_ERROR)
		bReturn = AL_TRUE;
	return bReturn;
}

ALboolean SFXALDevice::createEffect(ALuint *uEffect, ALenum uEffectType)
{
	ALboolean bReturn = AL_FALSE;

	if (uEffect)
	{
		mOpenAL.alGenEffects(1, uEffect);
		if (mOpenAL.alGetError() == AL_NO_ERROR)
		{
			mOpenAL.alEffecti(*uEffect, AL_EFFECT_TYPE, uEffectType);
			if (mOpenAL.alGetError() == AL_NO_ERROR)
				bReturn = AL_TRUE;
			else
				mOpenAL.alDeleteEffects(1, uEffect);
		}
	}
	return bReturn;
}

ALboolean SFXALDevice::setReverb(const SFXReverbProperties& reverb, ALuint iEffect)
{
	mReverb = reverb;
	ALboolean bReturn = AL_FALSE;
	if (mOpenAL.alGetEnumValue("AL_EFFECT_EAXREVERB") != 0)
	{

		/// EAX Reverb is available. Set the EAX effect type

		mOpenAL.alEffecti(iEffect, AL_EFFECT_TYPE, AL_EFFECT_EAXREVERB);

		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_DENSITY, mReverb.flDensity);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_DIFFUSION, mReverb.flDiffusion);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_GAIN, mReverb.flGain);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_GAINHF, mReverb.flGainHF);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_GAINLF, mReverb.flGainLF);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_DECAY_TIME, mReverb.flDecayTime);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_DECAY_HFRATIO, mReverb.flDecayHFRatio);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_DECAY_LFRATIO, mReverb.flDecayLFRatio);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_REFLECTIONS_GAIN, mReverb.flReflectionsGain);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_REFLECTIONS_DELAY, mReverb.flReflectionsDelay);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_LATE_REVERB_GAIN, mReverb.flLateReverbGain);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_LATE_REVERB_DELAY, mReverb.flLateReverbDelay);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_ECHO_TIME, mReverb.flEchoTime);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_ECHO_DEPTH, mReverb.flEchoDepth);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_MODULATION_TIME, mReverb.flModulationTime);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_MODULATION_DEPTH, mReverb.flModulationDepth);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_AIR_ABSORPTION_GAINHF, mReverb.flAirAbsorptionGainHF);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_HFREFERENCE, mReverb.flHFReference);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_LFREFERENCE, mReverb.flLFReference);
		mOpenAL.alEffectf(iEffect, AL_EAXREVERB_ROOM_ROLLOFF_FACTOR, mReverb.flRoomRolloffFactor);
		mOpenAL.alEffecti(iEffect, AL_EAXREVERB_DECAY_HFLIMIT, mReverb.iDecayHFLimit);

		if (mOpenAL.alGetError() == AL_NO_ERROR)
		{
			mOpenAL.alAuxiliaryEffectSloti(effectSlot, AL_EFFECTSLOT_EFFECT, effect);
			bReturn = AL_TRUE;
		}
	}
	else
	{

		/// No EAX Reverb. Set the standard reverb effect
		mOpenAL.alEffecti(iEffect, AL_EFFECT_TYPE, AL_EFFECT_REVERB);

		mOpenAL.alEffectf(iEffect, AL_REVERB_DENSITY, mReverb.flDensity);
		mOpenAL.alEffectf(iEffect, AL_REVERB_DIFFUSION, mReverb.flDiffusion);
		mOpenAL.alEffectf(iEffect, AL_REVERB_GAIN, mReverb.flGain);
		mOpenAL.alEffectf(iEffect, AL_REVERB_GAINHF, mReverb.flGainHF);
		mOpenAL.alEffectf(iEffect, AL_REVERB_DECAY_TIME, mReverb.flDecayTime);
		mOpenAL.alEffectf(iEffect, AL_REVERB_DECAY_HFRATIO, mReverb.flDecayHFRatio);
		mOpenAL.alEffectf(iEffect, AL_REVERB_REFLECTIONS_GAIN, mReverb.flReflectionsGain);
		mOpenAL.alEffectf(iEffect, AL_REVERB_REFLECTIONS_DELAY, mReverb.flReflectionsDelay);
		mOpenAL.alEffectf(iEffect, AL_REVERB_LATE_REVERB_GAIN, mReverb.flLateReverbGain);
		mOpenAL.alEffectf(iEffect, AL_REVERB_LATE_REVERB_DELAY, mReverb.flLateReverbDelay);
		mOpenAL.alEffectf(iEffect, AL_REVERB_AIR_ABSORPTION_GAINHF, mReverb.flAirAbsorptionGainHF);
		mOpenAL.alEffectf(iEffect, AL_REVERB_ROOM_ROLLOFF_FACTOR, mReverb.flRoomRolloffFactor);
		mOpenAL.alEffecti(iEffect, AL_REVERB_DECAY_HFLIMIT, mReverb.iDecayHFLimit);
		if (mOpenAL.alGetError() == AL_NO_ERROR)
		{
			mOpenAL.alAuxiliaryEffectSloti(effectSlot, AL_EFFECTSLOT_EFFECT, effect);
			bReturn = AL_TRUE;
		}
	}



	return bReturn;
}


everything works when i set an EFX_PRESET but the preset wont change when entering a new zone

**Comment by marauder2k7** [comment]
heres a video of what im getting so far, i have made a few changes today in the hopes that it would get somewhere it changes but only changes once, https://youtu.be/G-Gd1RnFxDk

**Comment by marauder2k7** [comment]
I got it working!!

https://www.youtube.com/watch?v=NQRpTZ1vUZ0

**Comment by kcat** [comment]
> In sfxALVoice when each sound is played we have this
> ```
> device->createAuxEffectSlots(&device->effectSlot);
>
> device->createEffect(&device->effect, AL_EFFECT_EAXREVERB);
> ```

This looks like it creates (and overwrites) the effect and effect slot every time a sound is played. This should only need to be done once on initialization.

> ```
> SFXReverbProperties mReverb;
> const SFXReverbProperties& getReverb(mReverb);
> if (&device->mReverb != &mReverb)
> {
> 	device->setReverb(mReverb, device->effect);
> }
> else {
> 	device->setReverb(device->mReverb, device->effect);
> }
> 
> device->mOpenAL.alSource3i(sourceName, AL_AUXILIARY_SEND_FILTER, device->effectSlot, 0, AL_FILTER_NULL);
> ```

This looks really weird. It declares `mReverb` as a local variable, declares `getReverb` as a const reference to the local, then tests the address of the local to the address of the device property. The `m` prefix usually indicates a class member rather than a local, and the reference declaration looks like it's trying to call a function. The `mReverb` local is left with default initialization, and the address comparison should never be true, 

It may also be useful to test the return value of the `setReverb`, and log an error if it fails to set the reverb instead of silently not doing anything. You also don't need to change the effect type every time you change its parameters, just once on effect creation.

**Comment by marauder2k7** [comment]
Thanks for your help kcat, i have fixed the problems u can see the full changes listed here https://github.com/marauder2k7/Torque3D/commit/066046324a3177c4e2ae522c8b15305605964692 its going to be rolled into torque3d release 3.10.1 hopefully and people can enjoy better environment audio from their engine :D soon going to begin working on implementing all the other effects now too

**Comment by marauder2k7** [comment]
im implementing all the rest of the effects and filters to give people who use the engine more control over their sounds, does each effect require its own auxiliary slot?

**Comment by kcat** [comment]
Each concurrent effect requires its own auxiliary slot. If, for example, you want an option to have a Distortion effect instead of Reverb, the distortion effect object can be loaded into the same auxiliary slot that reverb normally would to replace it. If, however, you want to be able to do distortion simultaneously with reverb, then yes, the distortion effect will need to use a separate auxiliary slot.

In the latter case, don't forget that the effect slot can still be shared. If multiple sources want to use the same distortion effect, they can connect to the same auxiliary slot that has that effect. Each source won't need it own auxiliary slot if it wants a different effect concurrent with the global reverb.

**Comment by marauder2k7** [comment]
okay i understand, i think i will need a slot for each effect to give the developer the freedom to use whichever mix of effects they want

**Comment by marauder2k7** [comment]
understood :) i will create a function that will count how many effects a developer wants on each sound, then use that to iterate through a loop and then generate the effects and slots thanks for that torque3d isnt that popular atm but it has a small and devoted team any way we can save resources is really welcomed so thank you for your help i wouldnt of known otherwise lol
