### ISSUE TITLE
How can i set reverb effect to pcm data and get back the reverb date,but don't play

### ISSUE THREAD

**Issue by jie545098983** [kcat/openal-soft#245]
Can anybody tell me how to set reverb effect to pcm data and get back the reverb date,and i don't need to play the song,Please

**Comment by kcat** [comment]
You can use the [loopback extension](http://openal-soft.org/openal-extensions/SOFT_loopback.txt) to get the mixed audio samples. If you set an effect like reverb on a source, the mixed audio samples include the reverb. [This example](https://github.com/kcat/openal-soft/blob/master/examples/alloopback.c) shows the extension being used to get the mixed samples (that particular example has SDL play it, but you can do whatever else you want with the samples).

You can make an app that applies reverb to a source, "plays" the audio you want with that source, and reads the mixed samples from the device. You can then do whatever you want with the reverb samples.

**Comment by jie545098983** [comment]
> You can use the[loopback extension](http://openal-soft.org/openal-extensions/SOFT_loopback.txt)to get the mixed audio samples. If you set an effect like reverb on a source, the mixed audio samples include the reverb.[This example](https://github.com/kcat/openal-soft/blob/master/examples/alloopback.c)shows the extension being used to get the mixed samples (that particular example has SDL play it, but you can do whatever else you want with the samples).
> 
> You can make an app that applies reverb to a source, "plays" the audio you want with that source, and reads the mixed samples from the device. You can then do whatever you want with the reverb samples.

 when i openal.AL lib: UpdateDeviceParams: Missing attributes for loopback device

> You can use the [loopback extension](http://openal-soft.org/openal-extensions/SOFT_loopback.txt) to get the mixed audio samples. If you set an effect like reverb on a source, the mixed audio samples include the reverb. [This example](https://github.com/kcat/openal-soft/blob/master/examples/alloopback.c) shows the extension being used to get the mixed samples (that particular example has SDL play it, but you can do whatever else you want with the samples).
> 
> You can make an app that applies reverb to a source, "plays" the audio you want with that source, and reads the mixed samples from the device. You can then do whatever you want with the reverb samples.

that's right,thank you so much
