### ISSUE TITLE
'HrtfEntry': no appropriate default constructor available 

### ISSUE THREAD

**Issue by GekkieHenkie** [kcat/openal-soft#254]
Compiling 1.19.1 on Window VS2017, I get the following compile errors:
..\openal-soft-1.19.1\alc\hrtf.cpp(987): error C2512: 'HrtfEntry': no appropriate default constructor available 
..\openal-soft-1.19.1\alc\hrtf.cpp(1050): error C2512: 'HrtfEntry': no appropriate default constructor available 

Changing the constructor calls in both lines from HrtfEntry{} to HrtfEntry() should fix it.

**Comment by kcat** [comment]
Fixed with commit d7d98708 (added default construction; I prefer to stick with uniform initialization when possible).
