### ISSUE TITLE
AL lib: (WW) UpdateDeviceParams: SSE performs best with multiple of 4 update sizes (882)

### ISSUE THREAD

**Issue by GekkieHenkie** [kcat/openal-soft#255]
I know it is marked 'fixed' in #32, but it isn't. This still happens on Windows VS2017, latest release 1.19.1. The issue has always existed for at least all versions I've had of the OpenAL-soft library (which is the last two and a half years). The previous version I used (1.18.2) still had this problem for certain (also Windows VS 2017).

I know it's just a warning but some applications don't want anything printed to stdout (especially on embedded devices)

**Comment by kcat** [comment]
With Windows the situation is a bit different than OSX in that report. On OSX it was incorrectly reporting the size, making the warning erroneous. But on Windows that means the update size really is not a multiple of 4 (by default WASAPI uses a 10ms update size for the device, which for 44100hz playback equates to 441 samples; OpenAL Soft doubles this to 882 to get closer to the desired 1024 update size).

How did you get/build the library? By default on a release build, it shouldn't print warnings:
https://github.com/kcat/openal-soft/blob/d7d98708/Alc/alc.cpp#L875
Only Debug and RelWithDebInfo builds should define `_DEBUG`. MinSizeRel and Release define `NDEBUG` instead, making the default logging level be for errors instead.

**Comment by GekkieHenkie** [comment]
Aha. I hadn't noticed the Debug/Release difference of the logging system. I build a Debug build indeed. My bad, sorry for wasting your time :(
Though I do appreciate your explanation about the WASAPI update size! And good to know the warning logging disappears on Release builds, thanks!
