### ISSUE TITLE
alcCreateContext Cause 0xa004 ALC_INVALID_VALUE Error.

### ISSUE THREAD

**Issue by snowfoxer** [kcat/openal-soft#257]
The attrs are AL_STEREO_SOFT\AL_SHORT_SOFT\44100. When I use a former version, it works well. The device is create by alcLoopbackOpenDeviceSOFT.

**Comment by kcat** [comment]
I think I found the issue, and should be fixed with commit d49eeb576cbcba966f56aed0dccbdd4694ffbaf7. Can you check?

**Comment by snowfoxer** [comment]
Oh, I'm sorry that the issues occurs on my colleague's branch. To solve the problem, we just fall back to branch v1.19.
