### ISSUE TITLE
Opus ambisonics to openal

### ISSUE THREAD

**Issue by nkari82** [kcat/openal-soft#259]
Is there a way to output 'openal' to opus that supports 'ambisonics bformat'?

**Comment by kcat** [comment]
Not directly to Opus, no. However, with the wave writer backend you can set it to output `.amb` files using floats, which provides uncompressed first-, second-, or third-order B-Format.

With the `alsoft-config` utility you can set the playback Channels to the desired Ambisonic order, then under the Backends tab set the Wave Writer as the prioritized backend, and in the Wave Writer options set a filename and check to create amb files. Or check through the config file options if you don't want to use the GUI.

This is the first time I heard that Opus officially supports ambisonics (I knew it was being worked on, but I stopped watching for it prior to the release that included non-experimental support), so I'm not sure what, if any, tools can encode it from amb files. It should be fairly easy to do though, presuming the encoder understands and properly deals with the channel ordering and scaling differences (amb files use the old FuMa scheme, instead of AmbiX/ACN+SN3D).

**Comment by kcat** [comment]
That would be up to the encoder. [`amb` files have well-defined channel ordering and scaling](https://web.archive.org/web/20140422234520/http://people.bath.ac.uk/masrwd/bformat.html), so anything that encodes to Opus from such files needs to automatically handle it. It's not up to OpenAL Soft to change its amb file output, and doing so would produce incorrect files.

**Comment by kcat** [comment]
For OpenAL's `AL_EXT_BFORMAT` extension, yes, it needs FuMa channel ordering and scaling to play correctly. It also needs to be cut down to first order (the first 4 channels for 3D) if it's higher.

**Comment by nkari82** [comment]
Thank you.
It looks like you can manipulate the buffer like this:

https://en.m.wikipedia.org/wiki/Ambisonic_data_exchange_formats

AmbiX to FuMa
channel order	   scale
0 -> 0(W)	   0.7071067812	(1/sqrt(2))
1 -> 2(Y)		   1
2 -> 3(Z)		   1
3 -> 1(X)		   1

**Comment by kcat** [comment]
Yes, that's how you'd need to modify the samples you get from an Opus file to load into an OpenAL B-Format buffer.

**Comment by nkari82** [comment]
I am using the Unity3D coordinate system. + z (foward), + x (right), + y (up)

float orientation_ [6] = {0,}
orintation_ [0] = -foward.x;
orintation_ [1] = -foward.y;
orintation_ [2] = -foward.z;
orintation_ [3] = up.x;
orintation_ [4] = up.y;
orintation_ [5] = up.z;
alListenerfv (AL_ORIENTATION, orintation_)

``
Case 1
channel order,	    scale
0 -> 0 (W)           0.7071067812 (1 / sqrt (2))
1 -> 2 (Y)            1
2 -> 3 (Z)            1
3 -> 1 (X)            1
``
When the listener rotates left and right, the output is reversed.

``
Case 2
channel order,	   scale
0 - > 0 (W)         0.7071067812 (1 / sqrt (2))
1 -> 2 (Y)           1
2 -> 3 (Z)           1
3 - > 1 (X)        -1
``
It is output normally when the listener rotates left and right.

What I expected was Case 1, what went wrong?

**Comment by kcat** [comment]
> I am using the Unity3D coordinate system. + z (foward), + x (right), + y (up)
>
> float orientation_ [6] = {0,}
> orintation_ [0] = -foward.x;
> orintation_ [1] = -foward.y;
> orintation_ [2] = -foward.z;
> orintation_ [3] = up.x;
> orintation_ [4] = up.y;
> orintation_ [5] = up.z;
> alListenerfv (AL_ORIENTATION, orintation_)

This doesn't look right. From that description, it would be:
```
float orientation_ [6] = {0,}
orientation_ [0] = forward.x;
orientation_ [1] = forward.y;
orientation_ [2] = -forward.z;
orientation_ [3] = up.x;
orientation_ [4] = up.y;
orientation_ [5] = -up.z;
alListenerfv (AL_ORIENTATION, orientation_);
```

Note too that the B-Format soundfield is relative to the source's orientation, so if you rotate the listener right, the front of the soundfield will be on the left (if the source's `AL_SOURCE_RELATIVE` is false). If you set the source's AL_ORIENTATION property to face right (not `AL_DIRECTION`, that doesn't influence B-Format), then the front of the soundfield moves to the right.

**Comment by nkari82** [comment]
float orientation_ [6] = {0,}
orientation_ [0] = forward.x;
orientation_ [1] = forward.y;
orientation_ [2] = -forward.z;
orientation_ [3] = up.x;
orientation_ [4] = up.y;
orientation_ [5] = -up.z;
alListenerfv (AL_ORIENTATION, orientation_);

b-format is output normally, but mono 3dsound is attenuated gain reversely when the listener is rotated.

hm...

**Comment by kcat** [comment]
> b-format is output normally, but mono 3dsound is attenuated gain reversely when the listener is rotated.

Make sure the listener and source positions (and velocities, and source direction) also follow the similar assignment pattern. Unity3D's X, Y, and Z should be assigned to OpenAL as X, Y, and -Z. Negating the forward orientation vector fully and leaving the up orientation vector as-is will probably be causing incorrect vertical panning, and/or incorrect front-back panning.
