### ISSUE TITLE
[openal] no sound with some games (openal 1.17.0)

### ISSUE THREAD

**Issue by fafryd1125** [kcat/openal-soft#26]
Description: 
After upgrading to `openal 1.17.0-1` I noticed no sound with: minetest, supertux2, openra... Downgrade to 1.16.0-1 fixes it.

Additonal output generated:
```shell
AL lib: (EE) ALCplaybackAlsa_reset: snd_pcm_hw_params_get_periods(hp, &periods, NULL) failed: Invalid argument
```
RELATED: https://bugs.archlinux.org/task/47136

**Comment by mpan-pl** [comment]
Reverting 9891d61206faa8b4fb1bd146b74da010264a4b69 solves the problem for me.

Tested with [0AD a18](https://github.com/0ad/0ad) on Arch64, kernel 4.2.5, alsa 1.1.0.

**Comment by fafryd1125** [comment]
@mpan-pl  I confirm that work. Tested with openra.

**Comment by kcat** [comment]
Hmm, well, it seems there's a couple issues at play. First, there's an obvious bug in that commit -- the check for allow-resampler needs to be inverted, else ALSA's resampler gets used by default (unlike previously). The other issues us that snd_pcm_hw_params_get_periods needs the 'dir' parameter only sometimes, when the real output period count can't be expressed as an integer (such as when resampling). Kind of annoyed by ALSA with that latter one... either require a parameter or don't, not based on other non-obvious state.

Commit c8a3e51296d367990b9603a8e53f24dd1068b23d fixes the allow-resampler check, restoring the previous no-resampling behavior which should avoid the error. Commit 63567526b0a17449baf57053d11688aa277a7e40 fixes the erroneous call, so it should work even when the resampler is allowed.

Can you check to ensure it's working now?

**Comment by mpan-pl** [comment]
Current master (63567526b0a17449baf57053d11688aa277a7e40) works for me.

**Comment by fafryd1125** [comment]
Also it works for me. Thanks all
