### ISSUE TITLE
Crash in WASAPI probe_devices.

### ISSUE THREAD

**Issue by john-preston** [kcat/openal-soft#265]
I have at least one user who gets a crash on launch with `defdevid == nullptr && devid != nullptr` like this:

![image](https://user-images.githubusercontent.com/17900494/51387853-0d365700-1b41-11e9-8d18-2f721dfd4754.png)

The first attempt to fix that is to modify the check to `if(!defdevid || wcscmp(..) != 0)`, but I'm not sure if this is a legitimate case at all or we should've fail and get out earlier.

Anyway, this needs some fixing. It was not happening before f18d2f244554a7369bb6989721430ef2c7f0c90d, everything works without a crash with OpenAL built before that commit. So this is a regression.

**Comment by kcat** [comment]
I'm curious about what's failing. If `defdevid` is null, that would mean it couldn't get the default device's ID string, or it couldn't get the default device itself. According to [MSDN](https://docs.microsoft.com/en-us/windows/desktop/api/mmdeviceapi/nf-mmdeviceapi-immdeviceenumerator-getdefaultaudioendpoint) it can only fail to get the default audio device if there are no devices, but that's obviously not the case if it's in that loop.

**Comment by kcat** [comment]
This should be fixed with commit d1a860751524c60d4e225f74ae887346f3b89dd1. Would be nice to know why a default device string is null, but it shouldn't crash anymore.

**Comment by john-preston** [comment]
@kcat Thanks!

**Comment by john-preston** [comment]
@kcat Can you please cherry-pick this commit to v1.19 branch?

**Comment by kcat** [comment]
It unfortunately won't apply cleanly to 1.19, since the conversion to C++. I could commit a similar patch for it, although I don't currently have another 1.19 release planned. You could grab and build the 1.19 branch though.

**Comment by john-preston** [comment]
@kcat Ok, no problem.

So the next tagged release is planned already with all those huge migrate-to-C++ things?

**Comment by john-preston** [comment]
I still think it is better to fix in v1.19 branch, currently I have to use a fork instead of the official repository because of that (I try to stop pinning myself to some random commits and use tagged releases or at least release branches instead).

**Comment by kcat** [comment]
Added the fix to the v1.19 branch. Looking over the few extra commits in that branch, it may not be a bad idea for a 1.19.2 release, depending on how much longer 1.20 may take.
