### ISSUE TITLE
Poor audio quality on default Pulseaudio device?

### ISSUE THREAD

**Issue by PJB3005** [kcat/openal-soft#278]
So I'm writing a game using OpenAL on Linux, and thus I'm using OpenAL Soft.

Now, I'm live streaming development so I had my game playing into a pulseaudio null sink which OBS streamed, and then had a loopback module to play that into my regular audio output. This way only the thing I'm developing could be heard on stream and I could still listen to music like normal.

Everything worked just fine audio quality was good. But when I let the game output directly to my analog stereo, audio quality is noticeably worse.

I tried messing with the context's frequency, and doubling the frequency to I dunno `80000` did seem to fix it, but I'd prefer not doing such hacks to avoid other problems? Keep in mind, PulseAudio's sinks seem to be configured to 44100 Hz on my system, and explicitly setting it to 44100 Hz didn't fix it.

So to recap:
* Audio quality is bad when played directly to my analog stereo.
* Audio quality is fine when playing to a null sink to loopback to my analog stereo. 
* I can work around this setting the frequency manually to like 80000 Hz on context creation.

Am I doing something wrong or?

<details>
<summary>pactl sink information</summary>

```
$ pactl list sinks                                                                                                                                                           
Sink #0
        State: RUNNING
        Name: alsa_output.pci-0000_00_1f.3.analog-stereo
        Description: Built-in Audio Analog Stereo
        Driver: module-alsa-card.c
        Sample Specification: s16le 2ch 44100Hz
        Channel Map: front-left,front-right
        Owner Module: 6
        Mute: no
        Volume: front-left: 25557 /  39% / -24.54 dB,   front-right: 25557 /  39% / -24.54 dB
                balance 0.00
        Base Volume: 65536 / 100% / 0.00 dB
        Monitor Source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
        Latency: 7002 usec, configured 8333 usec
        Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
        Properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "ALC3246 Analog"
                alsa.id = "ALC3246 Analog"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "0"
                alsa.card_name = "HDA Intel PCH"
                alsa.long_card_name = "HDA Intel PCH at 0xed418000 irq 154"
                alsa.driver_name = "snd_hda_intel"
                device.bus_path = "pci-0000:00:1f.3"
                sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sound/card0"
                device.bus = "pci"
                device.vendor.id = "8086"
                device.vendor.name = "Intel Corporation"
                device.product.id = "a348"
                device.product.name = "Cannon Lake PCH cAVS"
                device.form_factor = "internal"
                device.string = "front:0"
                device.buffering.buffer_size = "352800"
                device.buffering.fragment_size = "176400"
                device.access_mode = "mmap+timer"
                device.profile.name = "analog-stereo"
                device.profile.description = "Analog Stereo"
                device.description = "Built-in Audio Analog Stereo"
                alsa.mixer_name = "Realtek ALC3246"
                alsa.components = "HDA:10ec0256,10280824,00100002 HDA:8086280b,80860101,00100000"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-pci"
        Ports:
                analog-output-speaker: Speakers (priority: 10000)
                analog-output-headphones: Headphones (priority: 9000, available)
        Active Port: analog-output-headphones
        Formats:
                pcm

Sink #1
        State: IDLE
        Name: null
        Description: Null Output
        Driver: module-null-sink.c
        Sample Specification: s16le 2ch 44100Hz
        Channel Map: front-left,front-right
        Owner Module: 28
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Base Volume: 65536 / 100% / 0.00 dB
        Monitor Source: null.monitor
        Latency: 6694 usec, configured 8333 usec
        Flags: DECIBEL_VOLUME LATENCY 
        Properties:
                device.description = "Null Output"
                device.class = "abstract"
                device.icon_name = "audio-card"
        Formats:
                pcm
```

</summary>

**Comment by kcat** [comment]
What exactly do you mean by "bad"? Static-y like there's heavy clipping? Crackling or clicking as if from drop-outs?

From what I see in the device properties, the analog stereo device's Active Port is set to `analog-output-headphones` (are you using headphones? I don't know how PulseAudio determines that). That would make OpenAL Soft treat the device as headphones and automatically enable HRTF, which is better to use when listening to 3D audio on headphones. Forcing a sample rate like 80000 would prevent HRTF from working since it's only supported with 44.1khz and 48khz playback, indicating it may be related.

**Comment by PJB3005** [comment]
> What exactly do you mean by "bad"?

I'm far from an audio expert but it just sounds compressed to a very low quality. I recorded samples of good (going through null sink) and bad (going directly to headphones) here for comparison:

[bad](https://changelog.ss13.moe/static/openal_soft_bad.wav) [good](https://changelog.ss13.moe/static/openal_soft_good.wav)

Recorded with KWave for what it's worth, but it sounds the same when played back via VLC.

Indeed, it does seem like it might be related to HRTF. If I unplug my headphones and record that the result seems good again even at 44100 Hz. For reference [here's the recording](https://changelog.ss13.moe/static/openal_soft_good_direct_speakers.wav).

Also [this is the sound file being played back](https://changelog.ss13.moe/static/airlock_open.ogg). I should mention that it's getting played back twice at once in my recordings because the effect is more clear. It's also being played back positionally of course.

**Comment by kcat** [comment]
I would guess it is the HRTF filtering. It changes the loudness of various frequencies when using headphones, to simulate the effect of a sound some place around you instead of directly on your ear. If you move the sound up, down, or to the back, the effect effect should be more apparent vs plain stereo. If you play a surround sound audio file (5.1 or 7.1, etc) it will be heard as if you had surround sound speakers set up.

If you really want to disable it, though, you can run `alsoft-config` and change the Stereo Mode setting to `Speakers`.

**Comment by PJB3005** [comment]
If it's not strictly a bug I'll just change my system config then. Thanks!
