### ISSUE TITLE
Is there a way to change the device while maintaining the context?

### ISSUE THREAD

**Issue by nkari82** [kcat/openal-soft#291]
I am making a video player for my MR headset.
 Unfortunately, when the MR headset enters sleep mode, the MR headset USB sound device is disconnected and another sound device is connected.  When you wake the MR headset from sleep mode, the pain begins.

**Comment by kcat** [comment]
What do you mean by "the pain begins" when the headset is woken from sleep mode? Does OpenAL Soft create noise on the device, or is there a problem calling functions?

Currently it's not possible to change which system device playback is on for a given ALCdevice. It may be possible to implement with some work, though I can't make any hard promises about when (maybe a preliminary option for the next release if it doesn't prove to be too troublesome, or maybe sometime afterward).

**Comment by nkari82** [comment]
The program must be run without interruption throughout the day.
When the MR headset enters sleep mode, the program must be shut down and re-run.
This is a pain.

**Comment by Pintea** [comment]
Would be awesome to have this. Most games nowadays support changing the output device on the fly, which I can't do with OpenAL.

**Comment by KinsonDigital** [comment]
This is something I as well am needing in my game.  I am trying to implement this myself but I don't know if it is possible

**Comment by monaghanwashere** [comment]
+1 for this as well

**Comment by kcat** [comment]
As noted in issue #533, commit e824c808a0662361c9acdd9f97390d2412f21981 added a function to change the output an `ALCdevice` is playing on. It's part of an in-progress extension that's subject to change, but it's available for testing and feedback.

**Comment by kcat** [comment]
This has been added with [ALC_SOFT_reopen_device](https://openal-soft.org/openal-extensions/SOFT_reopen_device.txt), in 1.22.
