### ISSUE TITLE
C++ 17 compilation issues on Windows

### ISSUE THREAD

**Issue by Slion** [kcat/openal-soft#292]
I could build OpenAL independently on Windows using CMake. I'm assuming it's configured to use C++ 11 by default.

Then I tried integrating it as a submodule from a project that's compiled using C++ 17 and I'm now getting the following build errors.

I'm not sure how to proceed next. Should I try to fix the compilation errors and submit a patch?
Should I somehow make sure C++ 11 is used to build OpenAL? Not sure that would even work if the rest of the project is using C++ 17. I was using master.

```
1>------ Build started: Project: OpenAL (OpenAL\OpenAL), Configuration: Debug x64 ------
1>mastering.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xutility(954): error C2794: 'difference_type': is not a member of any direct or indirect base class of 'std::iterator_traits<_Checked>'
1>        with
1>        [
1>            _Checked=const ALfloat *__restrict
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\algorithm(1495): note: see reference to function template instantiation 'auto std::_Idl_distance<_InIt1,_Ty*>(const _Iter &,const _Iter &)' being compiled
1>        with
1>        [
1>            _InIt1=const ALfloat *__restrict ,
1>            _Ty=const ALfloat,
1>            _Iter=const ALfloat *
1>        ]
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\mastering.cpp(472): note: see reference to function template instantiation '_OutIt *std::transform<const ALfloat*__restrict ,ALfloat*,ALfloat*,std::_Binder<std::_Unforced,std::multiplies<float>,const std::_Ph<1> &,const std::_Ph<2> &>>(const _InIt1,const _InIt1,const _InIt2,_OutIt,_Fn)' being compiled
1>        with
1>        [
1>            _OutIt=ALfloat *,
1>            _InIt1=const ALfloat *__restrict ,
1>            _InIt2=ALfloat *,
1>            _Fn=std::_Binder<std::_Unforced,std::multiplies<float>,const std::_Ph<1> &,const std::_Ph<2> &>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xutility(954): error C2938: '_Iter_diff_t<const float*__restrict >' : Failed to specialize alias template
1>hrtf.cpp
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\hrtf.cpp(677): warning C4244: 'initializing': conversion from '_Ty' to 'ALubyte', possible loss of data
1>        with
1>        [
1>            _Ty=ALushort
1>        ]
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\hrtf.cpp(776): warning C4244: 'initializing': conversion from '_Ty' to 'ALubyte', possible loss of data
1>        with
1>        [
1>            _Ty=ALushort
1>        ]
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\hrtf.cpp(987): warning C4244: 'initializing': conversion from '_Ty' to 'ALubyte', possible loss of data
1>        with
1>        [
1>            _Ty=ALushort
1>        ]
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\hrtf.cpp(1026): warning C4834: discarding return value of function with 'nodiscard' attribute
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\hrtf.cpp(1051): warning C4834: discarding return value of function with 'nodiscard' attribute
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xutility(954): error C2794: 'difference_type': is not a member of any direct or indirect base class of 'std::iterator_traits<_Checked>'
1>        with
1>        [
1>            _Checked=const ALfloat *__restrict
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\algorithm(1495): note: see reference to function template instantiation 'auto std::_Idl_distance<_InIt1,_Ty*>(const _Iter &,const _Iter &)' being compiled
1>        with
1>        [
1>            _InIt1=const ALfloat *__restrict ,
1>            _Ty=const ALfloat,
1>            _Iter=const ALfloat *
1>        ]
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\hrtf.cpp(284): note: see reference to function template instantiation '_OutIt *std::transform<const ALfloat*__restrict ,ALfloat*,ALfloat*,GetHrtfCoeffs::<lambda_808df462092b64ed3700f51d8ec49413>>(const _InIt1,const _InIt1,const _InIt2,_OutIt,_Fn)' being compiled
1>        with
1>        [
1>            _OutIt=ALfloat *,
1>            _InIt1=const ALfloat *__restrict ,
1>            _InIt2=ALfloat *,
1>            _Fn=GetHrtfCoeffs::<lambda_808df462092b64ed3700f51d8ec49413>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xutility(954): error C2938: '_Iter_diff_t<const float*__restrict >' : Failed to specialize alias template
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\numeric(26): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data
1>        with
1>        [
1>            _Ty=unsigned int
1>        ]
1>C:\Dev\VisualStudio\Gik\Subs\OpenAL\Alc\hrtf.cpp(1026): note: see reference to function template instantiation '_Ty std::accumulate<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>,unsigned int,`anonymous-namespace'::LoadHrtf02::<lambda_bd8776c793ccd3c69188c81791d80597>>(const _InIt,const _InIt,_Ty,_Fn)' being compiled
1>        with
1>        [
1>            _Ty=unsigned int,
1>            _InIt=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<ALubyte>>>,
1>            _Fn=`anonymous-namespace'::LoadHrtf02::<lambda_bd8776c793ccd3c69188c81791d80597>
1>        ]
1>Generating Code...
1>Done building project "OpenAL.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by kcat** [comment]
Hm, didn't realize MSVC allowed building in different standards modes, I thought it always used the latest supported. Regardless, OpenAL Soft only explicitly requests C++11 in case a compiler defaults to an earlier version, but it shouldn't have a problem building as C++17.

From the looks of it, the errors are a result of restrict pointers (e.g. `const ALfloat *__restrict`) not working with iterator traits to get a difference type. A few places explicitly pass restrict pointer types as template parameters (to help auto-vectorize certain loops), which appears to cause the compile errors.

The simplest solution would be to just not use `__restrict` (disable the check in `CMakeLists.txt`). The code will still work fine without it. However, it could inhibit the compiler from making certain optimizations, like automatically using SIMD instructions on targets that support them. Either that, or the compiler would add redundant checks prior to vectorized versions of the loop. I'm not sure what the suggested method is to tell the compiler some arrays don't overlap.

**Comment by Slion** [comment]
> Hm, didn't realize MSVC allowed building in different standards modes, I thought it always used the latest supported. 

[Yes it does.](https://stackoverflow.com/a/46759740/3969362)

>Regardless, OpenAL Soft only explicitly requests C++11 in case a compiler defaults to an earlier version, but it shouldn't have a problem building as C++17.

That explains why I was getting those errors only when building OpenAL as part of my C++17 project and not when building it on its own. I wonder if I will get the same errors with CLang when targeting Android.

**Comment by Slion** [comment]
> The simplest solution would be to just not use __restrict (disable the check in CMakeLists.txt).

Thanks, disabling `__restrict` worked. This is an issue both on VS2017 and VS2019.
How do you want to go about fixing this in CMake? Should we disable `__restrict` when using MSVC?
Should we add an ALSOFT_NO_RESTRICT option?

**Comment by kcat** [comment]
I think avoiding restrict completely would be the way to go, given that it's non-standard, has slightly different behavior on different compilers, and can apparently cause issues like this. AFAIK, the C++ committee has also been against adopting it because of disagreements over design, so it's unlikely to ever properly integrate into the language.

Ideally I would drop use of `__restrict` while replacing it with some other way to declare two arrays don't overlap and relevant loops can be vectorized. Perhaps some `__assume()` statement could clue the optimizer in, but I haven't found anything yet that the compiler actually picks up on.

**Comment by Slion** [comment]
Shall I push a patch that's disabling it from CMake?

**Comment by kcat** [comment]
I believe I've removed instances of restrict from template parameters, so the failures shouldn't happen anymore. If the master branch still fails to build, please let me know where (note that I'm currently fighting with MSVC 2015 over unrelated class template constructors or something it doesn't like; I don't know if this also affects 2017). Otherwise, as long as it builds I'd prefer removing use of `RESTRICT` from the codebase where it's obviously not necessary or performance-critical.

**Comment by Slion** [comment]
Thanks, it builds now.
> I'm currently fighting with MSVC 2015 over unrelated class template constructors or something it doesn't like

I feel your pain.

> I don't know if this also affects 2017

I switched to VS2019 as it builds C++ projects so much faster. VS2019 builds fine now and I do believe VS2017 was building fine too without `__restrict`
