### ISSUE TITLE
Capture on android with float extension.

### ISSUE THREAD

**Issue by rafirafi** [kcat/openal-soft#293]
Hi,
I have a multiplatform application that captures sound in 
AL_FORMAT_MONO_FLOAT32, on linux it works perfectly fine but 
on android it gives data which is definitively in the wrong format
if I switch to AL_FORMAT_MONO16 (and do the conversion to 
float myself which I was trying to avoid) it's ok.
If I understand correctly, according to the spec if an unsupported format 
is supplied, alcCaptureOpenDevice should return NULL.
openal is at 61f7e77, cmake 3.14.1, android ndk r17c 
and host is linux x86_64.

**Comment by kcat** [comment]
I guess that means float32 capture needs a version of the Android/OpenSL SDK that supports `SL_DATAFORMAT_PCM_EX`, otherwise 32-bit samples is ambiguous about meaning an integer or float type.

**Comment by rafirafi** [comment]
So if android api level is < 21 (android 5.0) or opensl 
version is < 1.1  then SL_DATAFORMAT_PCM_EX is not defined and 
alcCaptureOpenDevice doesn't suppport AL_FORMAT_MONO_FLOAT32 as format.

But the problem also appears with the emulator at android api level 28.

For information I've compiled openal for the emulator with :
`
cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/android/android-ndk-r17c/build/cmake/android.toolchain.cmake -DANDROID_NDK=/opt/android/android-ndk-r17c -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-28 -DALSOFT_BACKEND_WAVE=OFF -DCMAKE_BUILD_TYPE=Release `


Some log, the lines with "D libMyApp.so" are from the float32 buffer 
as returned by alcCaptureSamples, I expected the float values to be in 
the -1.,1. range.

```

D openal  : AL lib: alc_initconfig: Initializing library v1.19.1-unknown UNKNOWN
D openal  : AL lib: alc_initconfig: Supported backends: opensl, null
D openal  : AL lib: ReadALConfig: Loading config /etc/openal/alsoft.conf...
D openal  : AL lib: ReadALConfig: Loading config /etc/xdg/alsoft.conf...
D openal  : AL lib: GetProcBinary: Got: /system/bin, app_process32
D openal  : AL lib: ReadALConfig: Loading config /system/bin/alsoft.conf...
D openal  : AL lib: GetConfigValue: Key disable-cpu-exts not found
D openal  : AL lib: FillCPUCaps: Detected max CPUID function: 0xd (ext. 0x80000008)
D openal  : AL lib: FillCPUCaps: Vendor ID: "GenuineIntel"
D openal  : AL lib: FillCPUCaps: Name: "Android virtual processor"
D openal  : AL lib: FillCPUCaps: Extensions: +SSE +SSE2 +SSE3 +SSE4.1
D openal  : AL lib: GetConfigValue: Key rt-prio not found
D openal  : AL lib: GetConfigValue: Key resampler not found
D openal  : AL lib: GetConfigValue: Key trap-al-error not found
D openal  : AL lib: GetConfigValue: Key trap-alc-error not found
D openal  : AL lib: GetConfigValue: Key reverb/boost not found
D openal  : AL lib: GetConfigValue: Key drivers not found
D openal  : AL lib: operator(): Initialized backend "opensl"
D openal  : AL lib: operator(): Added "opensl" for playback
D openal  : AL lib: operator(): Added "opensl" for capture
D openal  : AL lib: GetConfigValue: Key excludefx not found
D openal  : AL lib: GetConfigValue: Key default-reverb not found
D openal  : AL lib: GetConfigValue: Key channels not found
D openal  : AL lib: GetConfigValue: Key sample-type not found
D openal  : AL lib: GetConfigValue: Key frequency not found
D openal  : AL lib: GetConfigValue: Key periods not found
D openal  : AL lib: GetConfigValue: Key period_size not found
D openal  : AL lib: GetConfigValue: Key sources not found
D openal  : AL lib: GetConfigValue: Key slots not found
D openal  : AL lib: GetConfigValue: Key sends not found
D openal  : AL lib: GetConfigValue: Key ambi-format not found
D openal  : AL lib: alcOpenDevice: Created device 0xce8ed000, "OpenSL"
D openal  : AL lib: GetConfigValue: Key hrtf not found
D openal  : AL lib: UpdateDeviceParams: Pre-reset: Stereo, Float, 44100hz, 1024 update size x3
D         : PlayerBase::PlayerBase()
D         : TrackPlayerBase::TrackPlayerBase()
I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 2124
D openal  : AL lib: UpdateDeviceParams: Post-reset: Stereo, Signed Short, 44100hz, 1024 update size x3
D openal  : AL lib: GetConfigValue: Key stereo-mode not found
D openal  : AL lib: GetConfigValue: Key cf_level not found
D openal  : AL lib: GetConfigValue: Key stereo-encoding not found
D openal  : AL lib: aluInitRenderer: Stereo rendering
D openal  : AL lib: InitPanning: Enabling first-order ambisonic decoder
D openal  : AL lib: UpdateDeviceParams: Channel config, Main: 3, Real: 2
D openal  : AL lib: UpdateDeviceParams: Allocating 5 channels, 20480 bytes
D openal  : AL lib: UpdateDeviceParams: Max sources: 256 (255 + 1), effect slots: 64, sends: 2
D openal  : AL lib: GetConfigValue: Key dither not found
D openal  : AL lib: GetConfigValue: Key dither-depth not found
D openal  : AL lib: UpdateDeviceParams: Dithering enabled (16-bit, 32768)
D openal  : AL lib: GetConfigValue: Key output-limiter not found
D openal  : AL lib: UpdateDeviceParams: Output limiter enabled
D openal  : AL lib: UpdateDeviceParams: Fixed device latency: 997732ns
D openal  : AL lib: GetConfigValue: Key volume-adjust not found
D openal  : AL lib: alcCreateContext: Created context 0xce9fb300
D openal  : AL lib: alcCaptureOpenDevice: Capture format: Mono, Float, 16000hz, 48000 update size x1
W libOpenSLES: Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
D openal  : AL lib: alcCaptureOpenDevice: Created device 0xceb9c000, "OpenSL"
D libMyApp.so: 2.6461e+28
D libMyApp.so: 1.24283e+38
D libMyApp.so: 2.61205e+29
D libMyApp.so: 398
D libMyApp.so: 2.54003e+18
D libMyApp.so: 8.25492e+20
D libMyApp.so: 4.48614e+36
D libMyApp.so: 1.9415e+06

....

D libMyApp.so: 2.59416e+12
D libMyApp.so: 0.0527344
D libMyApp.so: 8.47943e+15
D libMyApp.so: 5.31284e+15
D libMyApp.so: 9.63272e+27
D libMyApp.so: 0.0158691
D libMyApp.so: 1.05113e+15
D libMyApp.so: 1.84375
D libMyApp.so: 9.01375e+27
D libMyApp.so: 4.44885e+26
D libMyApp.so: 9.92137e+11
D libMyApp.so: 9.33291e+26
D libMyApp.so: 5.38991e+19
D libMyApp.so: 6.04731e+12
D libMyApp.so: 8.08141e+13
D         : PlayerBase::stop() from IPlayer
D AudioTrack: stop() called with 598003 frames delivered
D openal  : AL lib: ALCcontext::~ALCcontext: 0xce9fb300
D openal  : AL lib: ALCcontext::~ALCcontext: Freed 0 context property objects
D openal  : AL lib: ALCcontext::~ALCcontext: Freed 0 AuxiliaryEffectSlot property objects
D openal  : AL lib: ALCcontext::~ALCcontext: Freed 0 voice property objects
D openal  : AL lib: ALCcontext::~ALCcontext: Freed 1 listener property object
D openal  : AL lib: ALCdevice::~ALCdevice: 0xce8ed000
D openal  : AL lib: ALCdevice::~ALCdevice: 0xceb9c000
```

**Comment by kcat** [comment]
> But the problem also appears with the emulator at android api level 28.

The library needs to be built with the correct SDK version as well. If OpenAL Soft isn't built with knowledge of `SL_DATAFORMAT_PCM_EX`, it won't be able to specify floating-point samples regardless of the system it's run on.

> Some log, the lines with "D libMyApp.so" are from the float32 buffer as returned by alcCaptureSamples, I expected the float values to be in the -1.,1. range.

The normally would be betweem -1...+1, except OpenSL is giving int32 samples that OpenAL Soft (and your app) thinks are float32. Interpreting 32-bit ints as 32-bit floats would cause wrong values to appear like that.

The proper way to fix this would be to disallow 32-bit float if `SL_DATAFORMAT_PCM_EX` is unavailable at compile-time, or capture int samples internally and convert to float when writing to the app's buffer. Which makes me wonder, how are 8-bit samples handled without `SL_DATAFORMAT_PCM_EX`? OpenAL expects 8-bit samples to be unsigned, but without `SL_DATAFORMAT_PCM_EX` it can't specify whether it wants signed or unsigned samples. Most audio APIs treat 8-bit samples as unsigned by default, but you can't know for sure if it's not explicitly said anywhere. If OpenSL gives signed 8-bit samples, it's going to need conversion regardless.

**Comment by rafirafi** [comment]
> Which makes me wonder, how are 8-bit samples handled without SL_DATAFORMAT_PCM_EX?

I can only tell you that I fallback to capture in AL_FORMAT_MONO16 and 
the data is in the expected format in this case.

> The library needs to be built with the correct SDK version as well. 

As I understand it, this was taken care of by cmake when building openal 
with the argument -DANDROID_PLATFORM=android-28.

So I've begin to dig and found that the Android ndk doesn't use 
opensl 1.1 as expected by openal, from OpenSLES_Android.h :
> "/* The following pcm representations and data formats map to those in OpenSLES 1.1 */"

In Alc/backends/opensl.cpp for a quick test I've mapped back to opensl 1.1 with the following defines:

```
#define SL_PCM_REPRESENTATION_SIGNED_INT SL_ANDROID_PCM_REPRESENTATION_SIGNED_INT
#define SL_PCM_REPRESENTATION_UNSIGNED_INT  SL_ANDROID_PCM_REPRESENTATION_UNSIGNED_INT  
#define SL_PCM_REPRESENTATION_FLOAT SL_ANDROID_PCM_REPRESENTATION_FLOAT          
#define SL_DATAFORMAT_PCM_EX SL_ANDROID_DATAFORMAT_PCM_EX 
#define SLDataFormat_PCM_EX SLAndroidDataFormat_PCM_EX

```
And recompiled and this time it works in the emulator with api level 28.

```
D openal  : AL lib: ALCdevice::~ALCdevice: 0xca3f7000
D openal  : AL lib: alcCaptureOpenDevice: Capture format: Mono, Float, 16000hz, 48000 update size x1
W libOpenSLES: Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
D openal  : AL lib: alcCaptureOpenDevice: Created device 0xca3f7000, "OpenSL"
D libMyApp.so: 0.164673
D libMyApp.so: 0.0824585
D libMyApp.so: 0.0721741
D libMyApp.so: 0.0948181
D libMyApp.so: 0.151245
D libMyApp.so: 0.0897217
D libMyApp.so: 0.129333
D libMyApp.so: 0.0960083
D libMyApp.so: 0.135651
D libMyApp.so: 0.1922
D libMyApp.so: 0.0684204
D libMyApp.so: 0.0871887
D libMyApp.so: 0.089447
```

**Comment by kcat** [comment]
I see, I wonder why it doesn't use/support the standard `SL_DATAFORMAT_PCM_EX` and uses its own custom thing which is just a mirror of it. Either way, I've changed to use it with commit 01f717ae. It's available even in my r16b SDK, so should work on older devices that only support lower API levels.

**Comment by rafirafi** [comment]
I just tested 8c4a9a5 and for android version >= 5 it now works as intended 
and for android < 5 the issue is as initially reported.

> Which makes me wonder, how are 8-bit samples handled without SL_DATAFORMAT_PCM_EX? OpenAL expects 8-bit samples to be unsigned, but without SL_DATAFORMAT_PCM_EX it can't specify whether it wants signed or unsigned samples.

For buffer queues, from
https://developer.android.com/ndk/guides/audio/opensl/opensl-for-android#pcm-data-format
only 8-bit unsigned or 16-bit signed are supported before android 5 
then float can be, and for recording only 16-bit signed 16KHz is mandatory.

**Comment by kcat** [comment]
This should be a bit better now with commit e16e2269b6a18c960a25d58f43ffad5ed408bee9. If the device fails to accept a `SL_ANDROID_DATAFORMAT_PCM_EX` format, it'll try `SL_DATAFORMAT_PCM`.

**Comment by rafirafi** [comment]
Hi, this works for me, 
if you're curious about what this was about you can visit  github.com/rafirafi/rGuitarTuner
Thanks.
