### ISSUE TITLE
Wrong templates called in converter LoadSample.

### ISSUE THREAD

**Issue by rafirafi** [kcat/openal-soft#296]
Hi,
the wrong template is called from LoadSample<DevFmtUShort> and LoadSample<DevFmtUInt> in Alc/converter.cpp, see patch below for details.
Regards.

[0001-Call-the-intended-templates-to-get-the-correct-float.patch](https://gist.github.com/rafirafi/8c233e7f1c977dec38689693db747031)

**Comment by kcat** [comment]
Thanks for pointing that out. Not sure it's actually possible for the incorrect methods to get used currently, but it's fixed now anyway in commit a478fd4b.
