### ISSUE TITLE
Can this be made to be built via visual studio with a .sln file?

### ISSUE THREAD

**Issue by LethalManBoob** [kcat/openal-soft#299]
Command line so far has been a major headache for me and the last time i installed a git users recommened build app, i was permanently stuck with open with prompts after uninstall.

Could such a thing be made avaliable for us visual studio users? Or at least a more detailed guide on how to do so?
edit: did not mean to close and reopen

**Comment by kcat** [comment]
The `cmake-gui.exe` app should let you create a Visual Studio project file, which it can use to build OpenAL Soft. I'm not too familiar with VS itself, but I know CMake can create VS project files.

**Comment by jhasse** [comment]
Yes, this works perfectly fine with CMake. Can this issue be closed?

**Comment by kcat** [comment]
It's been nearly a year without any followup questions, so, sure.
