### ISSUE TITLE
How to select a backend?

### ISSUE THREAD

**Issue by Slion** [kcat/openal-soft#303]
Is there a way to select which backend is used when multiple are built?

**Comment by kcat** [comment]
A user can, but not the app. The backend used is invisible to apps as it will always select the appropriate one given the OS/platform, and the app gets the same behavior regardless. If there's a difference in behavior, it's either because certain information is simply not available, or there's a bug in the library.

**Comment by Slion** [comment]
> same behavior regardless

In theory yes. In practise some backends will probably work better than others as with issue#302.
Selecting backends at compile time is totally acceptable. However maybe the cmake configuration could force the user to select only one backend. That would make it clearer.

Regardless that issue is solved. Backends can only be selected during cmake configuration. Do select only one backend to make sure that's the one you will be running.

**Comment by sapien2** [comment]
Is there any way to query which backend was selected after the device was created?

**Comment by kcat** [comment]
Not from in the app. Is there an issue where that info is relevant?

**Comment by sapien2** [comment]
There is no issue, but it may be helpful for logging purposes.

**Comment by kcat** [comment]
OpenAL Soft's trace log (enabled by setting the `ALSOFT_LOGLEVEL` environment variable to `3` when running the app, and optionally redirected to a file by setting `ALSOFT_LOGFILE`) will show which backend(s) got selected.
