### ISSUE TITLE
Windows store apps XAudio2

### ISSUE THREAD

**Issue by jazzbre** [kcat/openal-soft#31]
Any plans for supporting XAudio2? 
There's already a backend implemented in SDL, so it shouldn't be that hard to implement.

**Comment by kcat** [comment]
As far as I know, XAudio2 uses MMDevAPI under the hood, which OpenAL Soft already uses. Is there a benefit to using XAudio2?

**Comment by jazzbre** [comment]
I'm not so sure that it would work, because Windows Store Apps have a limited feature set and lots of functions are not supported.
I've found a fork of OpenAL-soft that implements this:
https://github.com/kakashidinho/openal-soft-winphone

**Comment by mirh** [comment]
XAudio2 is implemented on top of [WASAPI](http://www.gamasutra.com/view/feature/131931/sponsored_feature_an_introduction_.php?page=4)

**Comment by kcat** [comment]
Given that OpenAL Soft is now written in C++, it will be a lot easier to adapt the WASAPI backend for proper Windows Store/UWP support. Plus there's also an SDL2 backend now, which can target XAudio2 if it's really needed. I currently have no plans to add an XAudio2 backend directly (if there's a good reason why modifying the existing WASAPI backend isn't enough, feel free to bring it up and I may reconsider).
