### ISSUE TITLE
makemhr build error on visual studio

### ISSUE THREAD

**Issue by PenguinDOOM** [kcat/openal-soft#313]
Error code C4576 is displayed and can not be built.
![sofa2](https://user-images.githubusercontent.com/50603637/61172447-6ac2d200-a5bf-11e9-889d-4345f95f7261.png)

Applicable place.
![sofa3](https://user-images.githubusercontent.com/50603637/61172451-862ddd00-a5bf-11e9-9bbf-3a15e5c9f8ad.png)
![sofa4](https://user-images.githubusercontent.com/50603637/61172452-862ddd00-a5bf-11e9-961e-1c2e065be6e3.png)
![sofa5](https://user-images.githubusercontent.com/50603637/61172453-862ddd00-a5bf-11e9-8872-87f0d14e76dd.png)

And what is MYSOFA_M_LIBRARY?
![sofa1](https://user-images.githubusercontent.com/50603637/61172466-b5dce500-a5bf-11e9-8305-cb958bddd17e.png)

**Comment by kcat** [comment]
> Error code C4576 is displayed and can not be built.

Should be fixed now with commit 363e2fb73a6dea31db4164531016879aa188da84.

> And what is MYSOFA_M_LIBRARY?

It's the math library `m`, if your system has it (not all systems need/have it, but for those that do, `mysofa` needs to be linked with it for math certain functions).

**Comment by PenguinDOOM** [comment]
Duplicate of #

**Comment by PenguinDOOM** [comment]
Is the math library math.h? Or is it an external math library?

**Comment by PenguinDOOM** [comment]
> It's the math library `m`, if your system has it (not all systems need/have it, but for those that do, `mysofa` needs to be linked with it for math certain functions).

Is the math library math.h? Or is it an external math library?

**Comment by kcat** [comment]
> Is the math library math.h? Or is it an external math library?

`math.h` is the math header. The math library would be `libm.a` or `libm.so` or something. You shouldn't need to worry about it though, that's what the check is for; it'll be added if it's there, and skipped if it's not.

**Comment by PenguinDOOM** [comment]
Thanks. I was able to build.
