### ISSUE TITLE
Android bformat does not work in the latest branch

### ISSUE THREAD

**Issue by nkari82** [kcat/openal-soft#319]

**Comment by kcat** [comment]
What do you mean "bformat does not work"? What are you doing, what are you expecting to happen, and what's actually happening?

**Comment by nkari82** [comment]
If you specify AL_FORMAT_BFORMAT3D_16 simply and playback, sound is output, but sound is not output in recent branch.

**Comment by kcat** [comment]
It's working fine here. Which commit are you on? Can you do a bisect to find when the problem started? It would also help to see your code, to check for problems there.

**Comment by nkari82** [comment]
I am looking at the log, but AL_FORMAT_BFORMAT3D_16 does not seem to be a problem.

my log
[2019-07-24 10:19:06.276][info] Available Output Devices are:-
[2019-07-24 10:19:06.277][info] Device: No Output  <-- whats wrong?
[2019-07-24 10:19:06.277][info] ALC_SOFT_HRTF supported
[2019-07-24 10:19:06.277][info] ALC_EXT_EFX supported
[2019-07-24 10:19:06.277][info] AL_EXT_STEREO_ANGLES not supported
[2019-07-24 10:19:06.277][info] Available HRTFs
[2019-07-24 10:19:06.277][info] 0: Built-In 44100hz
[2019-07-24 10:19:06.277][info] 1: Built-In 48000hz
[2019-07-24 10:19:06.277][info] Selecting HRTF 1...
[2019-07-24 10:19:06.283][info] HRTF enabled, using Built-In 48000hz
[2019-07-24 10:19:06.283][info] Active: OpenAL Soft

initialize code
`const ALchar* outputDevice = alcGetString(nullptr, ALC_ALL_DEVICES_SPECIFIER);
const ALchar* nextDevice = outputDevice + 1;
auto encodings = Text::GetEncodings("UTF-8");

if (outputDevice)
{
	Log(LOG_NORMAL, "Available Output Devices are:-");

	while (outputDevice && *outputDevice != '\0' && nextDevice && *nextDevice != '\0')
	{
		string out;
		encodings->Convert((const char*)outputDevice, strlen(outputDevice), out);
		Logf(LOG_NORMAL, "Device: {}", out.c_str());

		size_t len = strlen(outputDevice);
		outputDevice += len + 1;
		nextDevice += len + 2;
	}
}

const ALchar* defaultOutputDevice = alcGetString(nullptr, ALC_DEFAULT_DEVICE_SPECIFIER);
const ALchar* activeOutputDevice = defaultOutputDevice;

s_device = std::make_shared<Device>();
if (!s_device->Open(activeOutputDevice))
{
	s_device.reset();
	return false;
}

if (s_device != nullptr)
{
	Logf(LOG_NORMAL, "Active: {}", activeOutputDevice);
	s_ctx = alcCreateContext(s_device->Get(), nullptr);
	alcMakeContextCurrent(s_ctx);
}`

**Comment by nkari82** [comment]
I seem to have found a problem.

-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Could NOT find OSS (missing: OSS_INCLUDE_DIR)
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR)
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR)
-- Could NOT find QSA (missing: QSA_LIBRARY QSA_INCLUDE_DIR)
-- Could NOT find PortAudio (missing: PORTAUDIO_LIBRARY PORTAUDIO_INCLUDE_DIR)
-- Could NOT find PulseAudio (missing: PULSEAUDIO_LIBRARY PULSEAUDIO_INCLUDE_DIR)
-- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
-- Could NOT find OPENSL (missing: OPENSL_LIBRARY OPENSL_INCLUDE_DIR  OPENSL_ANDROID_INCLUDE_DIR)

OpenSL backend was not found.
