### ISSUE TITLE
EAXREVERB vs REVERB

### ISSUE THREAD

**Issue by kunaljathal** [kcat/openal-soft#332]
Apologies if this has been covered elsewhere, but I'm seeing multiple definitions of the exact same reverb effect parameter, egs: `AL_REVERB_REFLECTIONS_GAIN` as well as `AL_EAXREVERB_REFLECTIONS_GAIN`.

What is the difference, and more importantly, which one should I use?

**Comment by kcat** [comment]
The `AL_REVERB_`* parameters are for when you use the `AL_EFFECT_REVERB` effect type, and the `AL_EAXREVERB_`* parameters are for when you use the `AL_EFFECT_EAXREVERB` type. The `AL_EFFECT_EAXREVERB` type is a more advanced reverb effect with extra parameters, and is generally the one to use when available, though some hardware OpenAL drivers might not support it (OpenAL Soft will support it regardless).

**Comment by kunaljathal** [comment]
Thanks for the quick response. How do I know if `AL_EFFECT_EAXREVERB` is available/supported by my system? Should I simply try to load it and see if there are any error messages?

**Comment by kcat** [comment]
If `alEffecti(effect, AL_EFFECT_TYPE, AL_EFFECT_EAXREVERB);` works without generating an error (make sure any existing error is cleared before making the call), it's supported. With OpenAL Soft you can instead call `alGetEnumValue("AL_EFFECT_EAXREVERB")`, and if that returns something other than 0 or -1 then it's supported (though some drivers may return 0 for this even if it is supported).

**Comment by kunaljathal** [comment]
Gotcha. I have loaded `AL_EFFECT_EAXREVERB` and seems to work just fine. Thanks!
