### ISSUE TITLE
Connecting to multiple ALSA devices

### ISSUE THREAD

**Issue by minghia** [kcat/openal-soft#348]
I have a need to connect to a speaker as one output and a headset to have different channels on it. Is is it possible to open two different devices with openal-soft with an ALSA backend? We currently do this using the ALSA library calls directly but I would like to know how do do this in openal-soft. 

The alsoftrc.sample file refers to a card number and a device number. I have tried to call alcOpenDevice with the argument set to "hw:1" and "plughw:1" but to no avail. So how do I specify a specific ALSA device?

Thanks in advance.

**Comment by kcat** [comment]
OpenAL Soft doesn't pass the name through directly to ALSA, since there's no guarantee a Linux system is using ALSA for output. You can use the ALC_ENUMERATE_ALL_EXT extension to get a list of outputs, and when using ALSA, you'll get results like this:
```
ALSA Default
HDA NVidia, ALC888 Analog (CARD=NVidia_1,DEV=0)
HDA NVidia, ALC888 Digital (CARD=NVidia_1,DEV=1)
HDA NVidia, HDMI 0 (CARD=NVidia,DEV=3)
HDA NVidia, HDMI 1 (CARD=NVidia,DEV=7)
HDA NVidia, HDMI 2 (CARD=NVidia,DEV=8)
```
In this case, `ALSA Default` maps to the `"default"` ALSA device, while the remaining map to `"plughw:CARD,DEV"`, e.g. `"plughw:NVidia_1,0"`. In the config file, you can setup custom device names for ALSA, or change it to use a different prefix instead of `plughw:`.

**Comment by minghia** [comment]
So how do you specify multiple device names? Or are the elements of the config file just a key value pair and it's just the case of querying for the key to get the value and then passing it into  alcOpenDevice?

**Comment by kcat** [comment]
To specify multiple custom devices, separate them with semicolons. Like this:
```
[alsa]
custom-devices = Device Name 0=alsa_name0;Device Name 1=alsa_name1
```
That will then add
```
Device Name 0
Device Name 1
```
to the enumerated devices, and will map to ALSA devices `"alsa_name0"` and `"alsa_name1"` respectively.

**Comment by minghia** [comment]
Is this for playback devices and capture devices? I notice in the alsoftrc.sample there are _capture_ and _device_ tokens. We have a need for multiple playback and multiple recording devices.

**Comment by kcat** [comment]
`custom-devices` is for playback devices. However, I just added a `custom-captures` option to master for specifying extra ALSA capture devices the same way.

**Comment by minghia** [comment]
I will update and give it a try.

**Comment by minghia** [comment]
Okay I have started to try this anger. Unfortunately I have had no success. This is our /etc/asound.conf
`pcm.playmix {
  type softvol
  slave {
    pcm "hw:1,0"
  }
  control.name "VCSHeadsetVolume"
  control.card 1
}

pcm.dsp0 {
  type plug
  slave.pcm "playmix"
}
`
and my matching /etc/openal/alsoft.conf:
`#
## ALSA backend stuff
##
[alsa]

## device:
#  Sets the device name for the default playback device.
device = default

## capture:
#  Sets the device name for the default capture device.
#capture = default
custom-devices = ICS Speaker="dsp1";ICS Headset="dsp0"
`

The message I get from OpenAL are the following:
`ALSA lib pcm.c:2209:(snd_pcm_open_noupdate) Unknown PCM "dsp0"
AL lib: (WW) Failed to open playback device: Could not open ALSA device ""dsp0""
AL lib: (WW) Error generated on device (nil), code 0xa005` 

The only difference I can see between your call to `snd_pcm_open` is that in our original ALSA code we set the mode to 0, whereas your code set the value to `SND_PCM_NONBLOCK`.

Any thoughts.

**Comment by minghia** [comment]
I could get it to work with the alias. I had two problems, I put "dsp0" instead of dsp0 in the alsoft.conf. The other problem was that I had a stray process from a previous run that still had the device. Killing the process and fixing the alsoft.conf to remove the double quotes and it is now working.

**Comment by minghia** [comment]
I'm not sure when I'll have a chance to test the twin microphones as I am currently having issues with our targetted headset's microphone. Thanks for your good work.
