### ISSUE TITLE
lately branch deadlock! (wasapi)

### ISSUE THREAD

**Issue by nkari82** [kcat/openal-soft#352]
Opening the wasapi device and using 'alGetSourceXXX' causes a deadlock. (Visual Studio 2017 disable optimization /Od)

**Comment by kcat** [comment]
Is there any source code available that the deadlock happens with, at least a small test case? Can you provide a backtrace to where it gets stuck?

**Comment by nkari82** [comment]
Using two threads, one handles alGetSourcei (id_, AL_BUFFERS_PROCESSED, & processed) and the other seems to be deadlock when executing alSourcePlay (id_).

std :: lock_guard <std :: mutex> __ {context-> mSourceLock}; <-occur !!

Aren't you thread safe?

**Comment by kcat** [comment]
It is thread-safe, that's what the lock is for. If one thread blocks when trying to take the source lock, that means another thread already has the source lock and isn't able to release it for some reason. Can you provide backtraces for the two threads that are stuck in `alGetSourcei` and `alSourcePlay`?

**Comment by nkari82** [comment]
I found a branch with a problem.
	SHA-1: ddf7e0f07c658a1754f108d43f5d35615488d2b9
	It's exactly a problem from this branch.
	Use a std::array for the reverb sample buffers 2019-08-18

My playback generation flow
1. Open Device.
2. Multiple Generate Effects alGenAuxiliaryEffectSlots & alAuxiliaryEffectSloti
	EFX_REVERB_PRESET_CONCERTHALL, 
	EFX_REVERB_PRESET_SPACESTATION_HALL,
	EFX_REVERB_PRESET_ICEPALACE_HALL,
	EFX_REVERB_PRESET_STONEROOM,
	EFX_REVERB_PRESET_LIVINGROOM, 
	EFX_REVERB_PRESET_PREFAB_PRACTISEROOM

3. Play sources

If you do not load the effect, no deadlock occurs.
Am I stupid to use open al?

**Comment by nkari82** [comment]
Close this issue as it works in release mode.
