### ISSUE TITLE
Unresolved external symbol errors for ALCcontext_struct and ALCdevice_struct

### ISSUE THREAD

**Issue by modderwizard** [kcat/openal-soft#354]
I'm making a project using the pre-compiled 1.19.1 files from the website.

When compiling, I get two linker errors

`LNK2001	unresolved external symbol "private: static struct ALCcontext_struct * AudioLoader::audioContext" (?audioContext@AudioLoader@@0PEAUALCcontext_struct@@EA)`
`LNK2001	unresolved external symbol "private: static struct ALCdevice_struct * AudioLoader::audioDevice" (?audioDevice@AudioLoader@@0PEAUALCdevice_struct@@EA)`

I'm using Visual Studio 2019, the project is set to 64-bit (tried using both Release and Debug configurations... didn't change anything).

I tried searching for these errors but I can't find anything on them so obviously I'm doing _something_ wrong.

**Comment by kcat** [comment]
It looks like you're declaring and using two functions, `AudioLoader::audioDevice` and `AudioLoader::audioContext`, which aren't defined or found during linking.

**Comment by modderwizard** [comment]
They're actually variables. Your comment was helpful though because I was fixated on the issue being the ALCcontext_struct part, instead of the actual variables themselves.

I had a little brainfart and forgot to initialize them in the cpp file:

`ALCcontext *AudioLoader::audioContext = nullptr;
ALCdevice *AudioLoader::audioDevice = nullptr;`

I just started learning C++ earlier this year and haven't gotten entirely used to the differences between it and C#.

Thanks!
