### ISSUE TITLE
Feature request: Per-source HRTF

### ISSUE THREAD

**Issue by aeonofdiscord** [kcat/openal-soft#357]
Hey there. I'm running into an issue with centre-panned audio sounding "weird" (muddy/downsampled) when using headphone output with HRTF enabled. If I disable HRTF using alsoft.conf or alcResetDeviceSOFT the problem goes away, but of course then I'm unable to use HRTF for spatialised sounds.

I think the problem I'm having is similar to these other users: https://github.com/kcat/openal-soft/issues/278 https://github.com/kcat/openal-soft/issues/211

Ideally what I'd like to be able to do would be to mark some sources as non-HRTF, so that I can play background music and ambience without distortion but still benefit from HRTF for sound effects. I have no idea how feasible this is to implement, though!

**Comment by kcat** [comment]
You can sort of do this with the `AL_SOFT_direct_channels` extension. If you set the source's `AL_DIRECT_CHANNELS_SOFT` property to `AL_TRUE`, it'll skip all panning and just feed the input channels to the matching output channels. This does have a few problems though. In particular, any input that doesn't have a matching output is simply dropped. So a mono sound won't be heard on stereo output, and even stereo sounds will be lost if output is set to an ambisonic configuration.

I do have plans to address those issues, though I can't say if they will be fixed for 1.20.

**Comment by kcat** [comment]
1.20.1 should deal with all this now. The `AL_SOFT_direct_channels_remix` extension lets you set the `AL_DIRECT_CHANNELS_SOFT` property to `AL_REMIX_UNMATCHED_SOFT` (instead of `AL_TRUE`) to ensure input channels won't be lost even if there isn't a matching output, while still avoiding HRTF/virtualization. It also ensures ambisonic output doesn't lose anything.

**Comment by kcat** [comment]
If there's still any issues here, let me know and I'll reopen.
