### ISSUE TITLE
How to achieve shared sound in openal？

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#362]
Dear developer, hi:
There is a question here I would like to ask; I have two static libraries, which are played by openal respectively, and each static library is played through the same (or shared) context environment;
When I used two static libraries together, the following situation appeared. I first started static lib A, heard the sound of A playback, and then started static lib B. When B starts the sound playback, A has no sound. Look at the error is alGetSourcei (al_source_state), state returns 0x8000000B, and the number of buffers returned by alGetSourcei (al_buffer_queue) is 0, can not get the buffer to unqueue.
I want to know what is the reason, how to use the openal to play the respective audio when the two static libraries are open.
I use it in windows  and linux has the same result .

**Comment by xuandu** [comment]
sorry，I use the dll lib in windows (or linux ); And the same problem with #361.

**Comment by kcat** [comment]
I'm not sure what exactly your asking. What do you mean that you have two static libraries played by openal? Are you able to provide any code for what you're doing?
