### ISSUE TITLE
alsoft.ini is not created and alsoft-config.exe does not apply changes when Windows username has foreign characters?

### ISSUE THREAD

**Issue by InigoMontoya8D** [kcat/openal-soft#363]
I've been trying to use alsoft-config.exe to select a custom HRTF for headphone listening through OpenAL but I noticed that an alsoft.ini file is not created after applying changes in the alsoft-config.exe.

I also tried copying an existing alsoft.ini file (provided to me by another user) to appdata\Roaming and this file would still not update with the changes set in the alsoft-config.exe.

After running through every other possibility and coming up short it occurred to me that this is most likely happening because the folder path to my appdata folder contains a non-english character from my Windows username. Specifically, the character in question is 'ã'.

**Comment by kcat** [comment]
This should be fixed now with commit f2eab3e919aa06b72ad467118db3269fe2571bbb. If you're able to build it from source (with Qt support for alsoft-config), can you double-check?

**Comment by InigoMontoya8D** [comment]
Sorry for only just now getting back to you. I can confirm that this issue is solved on the latest release (1.20.0).

Thank you, kcat.
