### ISSUE TITLE
Android: sound keeps going after app minimizes

### ISSUE THREAD

**Issue by marcakafoddex** [kcat/openal-soft#365]
I'm using OpenAL SOFT for the game I'm developing, currently only working with Android. When the app loses focus (it "minimizes"), the sound keeps on playing for about 5 seconds, with a lot of jitter. This is of course not desired.

I tried calling alcSuspendContext the moment the app loses focus, but it doesn't help the problem at all (and calling alcProcessContext when it regains focus). Maybe I misunderstand what alcSuspendContext is intended to do?

Is there a way to stop all audio without having to pause all sources?

**Comment by kcat** [comment]
`alcSuspendContext` stops updating property values, but keeps mixing. `alcProcessContext` then applies the pending updates (and starts applying changes as they're made, like normal). This allows you to update multiple properties and have the changes all apply at once, e.g.
```
alcSuspendContext(context);
alSource3f(source, AL_POSITION, source_x, source_y, source_z);
alListener3f(AL_POSITION, listener_x, listener_y, listener_z);
alcProcessContext(context);
```
That ensures you won't hear the source change position without the listener also changing position.

To temporarily stop output, OpenAL Soft has the `ALC_SOFT_pause_device` extension which has two functions: `alcDevicePauseSOFT` and `alcDeviceResumeSOFT`. Load the functions like this:
```
#include "AL/alext.h"
...
LPALCDEVICEPAUSESOFT alcDevicePauseSOFT;
LPALCDEVICERESUMESOFT alcDeviceResumeSOFT;

...
    if(alcIsExtensionPresent(Device, "ALC_SOFT_pause_device"))
    {
        alcDevicePauseSOFT = alcGetProcAddress(Device, "alcDevicePauseSOFT");
        alcDeviceResumeSOFT = alcGetProcAddress(Device, "alcDeviceResumeSOFT");
    }
```
Then when you want to stop output, call `alcDevicePauseSOFT(Device);` and to resume, call `alcDeviceResumeSOFT(Device);`

Be aware that the calls aren't reference counted. You can call `alcDevicePauseSOFT` once, twice, or ten times, and playback will resume on the first call to `alcDeviceResumeSOFT`.

**Comment by marcakafoddex** [comment]
Epic quick reply, big kudos! And thanks for the extensive answer, I will try this soon!

**Comment by marcakafoddex** [comment]
Works like a charm! Thanks!
