### ISSUE TITLE
Repeat region

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#366]
Hi, is it possible to set a custom repeat region in the file with openal-soft?
Ex. play starting beginning of file, but repeat from region 1min~3min

**Comment by kcat** [comment]
For such a long sound, you should probably use streaming. In which case the region that plays is entirely in your control. After reading and buffering samples up to the 3-minute mark, rewind/seek your input to the 1-minute mark and continue reading and buffering samples from there.

If you must use a single pre-loaded buffer for whatever reason, OpenAL Soft has the [`AL_SOFT_loop_points` extension](https://openal-soft.org/openal-extensions/SOFT_loop_points.txt), which allows setting the loop start and end points on a buffer. When looping is enabled on the source, it will start from the beginning of the buffer and play until the loop end point (the end point's sample itself will not play), where it'll then go back to the loop start point and continue playing from there.

**Comment by hsdk123** [comment]
Oh nice, thanks kcat! Sounds great
