### ISSUE TITLE
1.20 UT3 issues

### ISSUE THREAD

**Issue by donizettilorenzo** [kcat/openal-soft#367]
1) OpenAL Soft official 1.20 release + UseEffectsProcessing=True crashes the game @ start
2) Setting UseEffectsProcessing=False -> The game runs but there are exceptions exiting the game

_SYMBOL_NAME:  soft_oal!alDistanceModel+313
MODULE_NAME: soft_oal
IMAGE_NAME:  soft_oal.dll
STACK_COMMAND:  ~0s ; .ecxr ; kb
FAILURE_BUCKET_ID:  INVALID_POINTER_READ_c0000005_soft_oal.dll!alDistanceModel

**Comment by kcat** [comment]
Is this 32-bit or 64-bit? If I'm reading the symbol+offset correctly, it would have to be 32-bit, though where it crashes doesn't make too much sense. Are you able to get a backtrace to the crash?

**Comment by donizettilorenzo** [comment]
32 bit

**Comment by donizettilorenzo** [comment]
Built my own DLL vith MSVC 2019 from the master three, no more problems.

**Comment by kcat** [comment]
Are you able to build with MinGW-w64 and see if the problem returns?
