### ISSUE TITLE
[Request]Extension to apply effect to all sources

### ISSUE THREAD

**Issue by Raulshc** [kcat/openal-soft#368]
Hello Chris,

I think this doesn't currently exist in the library so I make the request.
It could be interesting and productive to have a mechanism (via extension) to attach all the playing sources to a slot where an effect is loaded.
It would be like the `default-reverb` parameter in alsoft.ini files but applied to desired effect. When the effect is a reverb, this is equivalent to the EAX listener environment.
The hypothetical extension could simplify a lot the equivalence between EAX and EFX when you want to develop listener environments (a la EAX).

Thank you very much in advance.

**Comment by kcat** [comment]
I'm not sure this would be that useful. You can get the same behavior by connecting each source to the desired effect slot once when the source is created, then it will stay with that effect slot until it's deleted. Either way, it's just one or two extra lines after the `alGenSources` call.

**Comment by Raulshc** [comment]
The principal motivation of this request is develop the famous EAX to EFX translation layer (#62) in OpenAL to give support to the games that use EAX with OpenAL API (Doom 3, Quake 4, Prey, UT 2k3, STALKER,...) .

Currently, I working on that and I've defined a couple of prerequisites that should be met but there are a few difficulties that I should be to resolve.

The prerequisites are:

1.- The layer must be modular.
2.- The layer must interact with the rest of the library ONLY with the API calls (and its extensions).

The first requisite is useful for conditional builts based on platforms. In this way, you could build the library with this feature on the windows platform if you wanted to support those old OpenAL games that make use of EAX, but not on other platforms, where this makes no sense (EAX is obsolete).
For the second requisite, to interact with the rest of the library only with the API calls and its extensions stimulate the first requisite and have the advantage that the layer is reusable. On the other hand, the library has a certain complexity already and my desire is not to touch anything.

I've made a tiny and incomplete draft of the layer working on openal 1.19.1 (C based). The ultimate goal is to run it on the latest version of openal soft (C++ based) and make a pull request for debugging and integrate it if you see fit. The draft actually works with Quake 4 (EAX 5), Doom 3 (EAX 4), UT2003 (EAX 3) and STALKER (EAX 2), more compatibility is in progress.
For the implementation, I have needed for now, apart from the API calls, the function `alcResetDeviceSOFT` from the `ALC_SOFT_HRTF` and `ALC_SOFT_output_limiter` extensions and the extension `AL_SOFTX_filter_gain_ex` for some EAX gains. The EAX calls relative to Context / Listener are a problem when a sources are created after call them.

For example, I want to create a translation of EAX 2.0 call `DSPROPSETID_EAX20_ListenerProperties` with the param `DSPROPERTY_EAX20LISTENER_ENVIRONMENT` and I suppose that the game created all the sources before call `eaxset` with the previous parameters. Well, this eaxset call goes through to create an auxiliary slot, efx reverb effect and the appropiate dry and wet filters and then attach the filters of all created sources using this aproach:
```
for (uSource = 1; uSource < MAX_SOURCES; uSource++)			
{										   			
	if (alIsSource(uSource))
	{				
	    //Attach and load direct filter to the source
            alSourcei(uSource, AL_DIRECT_FILTER, EFXSessionData.FilterSource.uDry);
            //Attach and load auxiliary filter to the source. Non-filtered uses AL_FILTER_NULL.
            alSource3i(uSource, AL_AUXILIARY_SEND_FILTER, 
                            EFXSessionData.uEffectSlot[uSend], 0, EFXSessionData.FilterSource.uWet[uSend]);
	}		
}

```
but if the game created a source(s) after the eax call, this source(s) will not be able processed correctly. This issue seems to occur with STALKER games, id games and ut2k3 seems to create and load all sources before to use eax calls.

I made test with OpenAL hardware implementation and all sources created after and eax context/listener call are attached to the (implicit or not) effect indicated by the call.

This is the reason of the request.

**Comment by Raulshc** [comment]
*#&@! Close and comment button :/

**Comment by kcat** [comment]
> The principal motivation of this request is develop the famous EAX to EFX translation layer (#62) in OpenAL to give support to the games that use EAX with OpenAL API (Doom 3, Quake 4, Prey, UT 2k3, STALKER,...) .

In that case, I think it would make more sense to implement the behavior as part of the EAX extension, as opposed to its own separate extension.

As it is, the `default-reverb` option is a (relatively small) hack. If there's such a global effect set, a hidden effect slot is initialized in the context when the context is created. Then when processing a source's updates, if there's nothing on slot 0, target that hidden slot instead. There's otherwise no way to access the slot since it has no ID, and it's created ahead of time. Consequently, this isn't a good basis for the EAX implementation, especially with EAX4's support for multiple simultaneous effects.

It's notable that it's very unlikely for an app to use EAX and EFX together. So you can make it in a way that on the first (or relevant) EAX call, it initializes internal effect stuff and not worry about EFX calls interfering later on. The various EAX calls will have access to the allocated sources, and when a source is generated it can check to see if EAX is being used and initialize it as appropriate.

> In this way, you could build the library with this feature on the windows platform if you wanted to support those old OpenAL games that make use of EAX, but not on other platforms, where this makes no sense (EAX is obsolete).

That will be necessary anyway, since the EAX API relies on the Windows-specific GUID type which isn't available on other platforms. Even if you made a custom GUID struct as a fallback for non-Windows systems, if existing apps made their own fallback there's no way to guarantee compatibility.

> Well, this eaxset call goes through to create an auxiliary slot, efx reverb effect and the appropiate dry and wet filters and then attach the filters of all created sources using this aproach:
> ...
> but if the game created a source(s) after the eax call, this source(s) will not be able processed correctly.

If a source is created after the EAX call, you can check to see if the (internal) EAX effect slot exists in the `alGenSources` call, and if so, attach the source to the slot right away.

**Comment by Raulshc** [comment]
> In that case, I think it would make more sense to implement the behavior as part of the EAX extension, as opposed to its own separate extension.

Of course, everything that I can implement within the extension will be implemented, but following the **requirement 2**, there are things that I cannot easily implement if I don't recode parts of the library or use some of the existing extensions. The example of EAX gains, a lot of them have a max. value of 1000 miliBells and its EFX equivalent have a value of 0 milliBells. The `AL_SOFTX_filter_gain_ex` extension solves this problem very well. (I know, is an inprogress extension, possibly created for that purpose) 

> As it is, the `default-reverb` option is a (relatively small) hack. If there's such a global effect set, a hidden effect slot is initialized in the context when the context is created. Then when processing a source's updates, if there's nothing on slot 0, target that hidden slot instead. There's otherwise no way to access the slot since it has no ID, and it's created ahead of time. Consequently, this isn't a good basis for the EAX implementation, especially with EAX4's support for multiple simultaneous effects.

I see...

> It's notable that it's very unlikely for an app to use EAX and EFX together. So you can make it in a way that on the first (or relevant) EAX call, it initializes internal effect stuff and not worry about EFX calls interfering later on. The various EAX calls will have access to the allocated sources, and when a source is generated it can check to see if EAX is being used and initialize it as appropriate.

Mmmm, interesting... openal hadware implementation has implemented the EFX and EAX extensions together, I will make several tests to determine its behavior. The main objective is give support to the old games (obviously they only use EAX) although the possibility of an app using EAX and EFX must be considered.

> If a source is created after the EAX call, you can check to see if the (internal) EAX effect slot exists in the `alGenSources call`, and if so, attach the source to the slot right away.

I will see what I can do, I will tests before if EAX and EFX can be used together on hardware implementation to have a reference. I will put the results here...

Thanks

**Comment by kcat** [comment]
> Of course, everything that I can implement within the extension will be implemented, but following the requirement 2, there are things that I cannot easily implement if I don't recode parts of the library or use some of the existing extensions. The example of EAX gains, a lot of them have a max. value of 1000 miliBells and its EFX equivalent have a value of 0 milliBells. The AL_SOFTX_filter_gain_ex extension solves this problem very well. (I know, is an inprogress extension, possibly created for that purpose)

Either way, it's going to require extra changes outside of the new functions, whether or not there's standalone extensions for the behavior. The `AL_SOFTX_filter_gain` extension exists because DSOAL can only use the public API and doesn't have direct access to OpenAL Soft's internals (and standard EFX only supports gains up to 0dB). An internal EAX handler wouldn't need an extension to get the same behavior.

> Mmmm, interesting... openal hadware implementation has implemented the EFX and EAX extensions together, I will make several tests to determine its behavior. The main objective is give support to the old games (obviously they only use EAX) although the possibility of an app using EAX and EFX must be considered.

As long as they operate fine independently, and don't crash if used together for some reason, I'll be fine with it. If anything, I might put a hard restriction on it... i.e. if an EFX function gets used first, EAX functions will just error, or if an EAX function gets used first, EFX functions will just error. But sure, it'll be interesting to see how existing implementations behave.

**Comment by Raulshc** [comment]
I have already done the tests (Hardware and Host OpenAL implementations), with the following results:

**Hardware**
The driver doesn't prioritize the EFX calls over EAX, but of course, it does prioritize EAX from major to minor version. The sequence of priority in the calls is:

--> EAX 5 -> EAX 4 -> EAX 3 -> EAX 2
|-> EFX

The hardware resources (4 slots) are shared between the two implementations, making own every available slot the first call (EAX or EFX) in reserved it while there are available slots. The slot is owned by EAX or EFX until it is released. The EAX hasn't a mechanism of set free a reserved slot, so ...

**Host OpenAL (software)**
It is very similar to the previous one, but the priority between EAX 2 - 3 with EAX 4 - 5 and EFX isn't clear. In HW, a slot reserved by a set of EFX calls cannot be used by any EAX call, however, in HOAL can be used by EAX2-3, but not by EAX 4-5, it's strange...

**Comment by Raulshc** [comment]
Hello,

because the EAX extensions are integrated into the master now, this request isn't necessary.
Thank you very much.
