### ISSUE TITLE
How to get  pcm data in openal Buffer before rendering

### ISSUE THREAD

**Issue by hy-chao** [kcat/openal-soft#370]
I need to get pcm data in openal buffer before rendering to do echo cancellation. 
But have no idea to get the next rendering pcm data.

**Comment by kcat** [comment]
Currently you can't. Though in general, it would be a better idea to do it at a lower level anyway, rather than on just OpenAL Soft's mix (for Windows there's probably a WASAPI APO, on Linux, PulseAudio and ALSA have echo cancellation modules I believe, and Android should have something too).

**Comment by hy-chao** [comment]
I have echo cancellation method but need the next rendering pcm data.   Does opanal soft have no interface to get the pcm data to be played in the cache?  If not i am thinking of other ways.

**Comment by kcat** [comment]
> Does opanal soft have no interface to get the pcm data to be played in the cache?

It doesn't currently, no. You're better off doing it through WASAPI or whatever your system has.

**Comment by hy-chao** [comment]
Thank you for your reply. I'll think of other ways！
