### ISSUE TITLE
AL:LIB<EE>ALCdsoundCapture_open:DEVICE init failed :0x88780078?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#374]
hi：
windows :win7 computer VoIP（intercom） use Double hole headset。use openal capture pcm .
connect mic  and start voip. and then, pull out mic ,I checked the device change and  use alcCaptureStop , alcCaptureCloseDevice  close the device . After a moment connect mic hole ,and alcCaptureopenDevice  alcCaptureStart, but occasionally show the error ：AL:LIB<EE>ALCdsoundCapture_open:DEVICE init failed :0x88780078，and stop。Sometimes IT is success ，and openal can capture continue。 
How to avoid this error 88780078 ?

**Comment by kcat** [comment]
Hmm, I'm not familiar with that error code. As best I can tell, perhaps it's `DSERR_NODRIVER`. If you say it only happens occasionally, maybe OpenAL Soft is trying to open it before the system has the device fully ready.

However, that error message indicates you're using an older version of OpenAL Soft. I would suggest trying the latest version (1.20.0, or the latest git master if you can build it) to see if it's still a problem.

**Comment by xuandu** [comment]
thanks, I used 1.17 before. Change to  the 1.20  from https://kcat.strangesoft.net/openal-binaries/ ,it is ok .when I pull out microphone ,it is record voice also(0x00).

**Comment by xuandu** [comment]
thanks, I used 1.17 before. Change to  the 1.20  from https://kcat.strangesoft.net/openal-binaries/ ,it is ok .when I pull out microphone ,it is record voice also(0x00).

**Comment by xuandu** [comment]
thanks, I used 1.17 before. Change to  the 1.20  from https://kcat.strangesoft.net/openal-binaries/ ,it is ok .when I pull out microphone ,it is record voice also(0x00).

**Comment by xuandu** [comment]
thanks, I used 1.17 before. Change to  the 1.20  from https://kcat.strangesoft.net/openal-binaries/ ,it is ok .when I pull out microphone ,it is record voice also(0x00).
