### ISSUE TITLE
CMake options do not propagate to native-tools build

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#375]
Hi, I'm getting errors due to what seems like my cmake options not being propagated to the native-tools build:

https://github.com/kcat/openal-soft/blob/master/CMakeLists.txt#L1087

I'm unsure why we're not just doing ex. a
```
add_subdirectory(native-tools)
```

**Comment by hsdk123** [comment]
For the moment, is there a cmake option that I can use to prevent these from attempting to build?

**Comment by kcat** [comment]
The native-tools need a clean build environment. It contains tools that need to run during the build, which it wouldn't be able to do if it got a cross-compiler toolchain or other settings that would create executables the system can't run. There is an option to use premade versions of the tools (`ALSOFT_NATIVE_TOOLS_PATH`), but the tools still need to be built and kept up-to-date one way or another.

What are the errors you're getting?

**Comment by kcat** [comment]
`native-tools` is no longer used, so this is no longer an issue.
