### ISSUE TITLE
AL_REMIX_UNMATCHED_SOFT is undeclared build failure

### ISSUE THREAD

**Issue by hhyyrylainen** [kcat/openal-soft#377]
My jenkins jobs started failing yesterday while trying to compile openal-soft, and they are still failing today. This is on Windows using visual studio 2017.
This is the compilation error:
```
     3>C:\jenkins\workspace\Thrive-Windows-Random-Branch\ThirdParty\Leviathan\ThirdParty\openal-soft\examples\alffplay.cpp(1774): error C2065: 'AL_REMIX_UNMATCHED_SOFT': undeclared identifier [C:\jenkins\workspace\Thrive-Windows-Random-Branch\ThirdParty\Leviathan\ThirdParty\openal-soft\build\alffplay.vcxproj]
     3>C:\jenkins\workspace\Thrive-Windows-Random-Branch\ThirdParty\Leviathan\ThirdParty\openal-soft\examples\alffplay.cpp(1779): error C2065: 'AL_DROP_UNMATCHED_SOFT': undeclared identifier [C:\jenkins\workspace\Thrive-Windows-Random-Branch\ThirdParty\Leviathan\ThirdParty\openal-soft\build\alffplay.vcxproj]
     3>Done Building Project "C:\jenkins\workspace\Thrive-Windows-Random-Branch\ThirdParty\Leviathan\ThirdParty\openal-soft\build\alffplay.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "c:\jenkins\workspace\Thrive-Windows-Random-Branch\ThirdParty\Leviathan\ThirdParty\openal-soft\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
```

The build should be using the latest commit `819763a6`.

**Comment by kcat** [comment]
That's odd. Those macros are there in alext.h, which is being included. Do you possibly have a different or older header somewhere that it may be picking up by mistake?

**Comment by hhyyrylainen** [comment]
Doing a manual build on the build server succeeded. I'll try clearing out stuff from the jenkins build and trying again.

**Comment by hhyyrylainen** [comment]
Okay so after quite a bit of investigating, I found out that the build was using the alext.h file from the previous openal soft version. I have setup my project's dependencies to install to a folder, and it seems that openal-soft picked up the previously installed openal headers, instead of the ones in the openal-soft folder. After deleting the previously installed files the build now worked.
