### ISSUE TITLE
100% wet effects

### ISSUE THREAD

**Issue by Omegastick** [kcat/openal-soft#379]
I would like to use a 100% wet reverb (only the effected audio, none of the source). AFAIK, the only way to use effects in OpenAL is an auxiliary send. If that's the case, then the way to get a 100% wet effect would be to have the source gain at 100%, the aux gain at 100%, then mute the source channel so it can't be heard.

Is there a way to do this in OpenAL?

**Comment by Omegastick** [comment]
I managed to get the effect but adding a lowpass filter with the gain set to 0 on the dry path. This seems to work, but it feels like a bit of a hack. Is this the recommended way to achieve 100% wet effects?

**Comment by kcat** [comment]
That's the way to do it, yes. The source's normal gain controls the volume for all (dry and wet) paths, while a low-pass filter can be placed on each individual path to control its gain and high-frequency gain (normally used for occlusion and exclusion-style effects, which includes completely blocking the dry path).

**Comment by Omegastick** [comment]
Okay, thanks!
