### ISSUE TITLE
AGC on microphone input

### ISSUE THREAD

**Issue by minghia** [kcat/openal-soft#381]
Does OpenAL soft implement any form of automatic gain control on inputs? Or is that something I would have to implement?

**Comment by kcat** [comment]
It would be something to implement either in the app, or the system's audio input path (assuming something like WASAPI or PulseAudio, where you can set up plugins that process the audio before the app gets it). OpenAL Soft itself doesn't alter the audio it gets at all if possible, except to ensure it matches the requested format.
