### ISSUE TITLE
Master Tree - Right Channel issues

### ISSUE THREAD

**Issue by donizettilorenzo** [kcat/openal-soft#382]
Just downloaded lastest master tree version and I've found an issue with the 3D sound spatialization, an issue NOT present in released official 1.20: the right channel volume is totally wrong.

I tipically downmix from 5.1 to 2 with Equalizer APO and I don't know if the issue is about the "proper" right channel or the original FR / RR channels that go in the downmix process.

Please fix / check ! Using official 1.20 binaries -> no problem at all !

I'm using WASAPI as the only backend (Windows 10 1909 x64)

**Comment by kcat** [comment]
There was an off-by-one error with the output setup, causing it to miss the last (back-right) channel. Commit 43780913cd8eec5f81626850055f60442b2bce2a should fix this.

**Comment by donizettilorenzo** [comment]
Thanks man!
