### ISSUE TITLE
Compile issues on android

### ISSUE THREAD

**Issue by TheMasterMaind** [kcat/openal-soft#386]
Hello!

With the new OpenAL 1.20.1 release. Clang 8 complains when building for android (also the cross-compile cmake script have to altered in order to find OpenSL...):

Scanning dependencies of target native-tools
[  1%] Generating native-tools/bin2h, native-tools/bsincgen
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pow in m
-- Looking for pow in m - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marvin/Downloads/openal-build/native-tools
Scanning dependencies of target bin2h
[ 25%] Building C object CMakeFiles/bin2h.dir/bin2h.c.o
[ 50%] Linking C executable bin2h
[ 50%] Built target bin2h
Scanning dependencies of target bsincgen
[ 75%] Building C object CMakeFiles/bsincgen.dir/bsincgen.c.o
[100%] Linking C executable bsincgen
[100%] Built target bsincgen
[  1%] Built target native-tools
Scanning dependencies of target common
[  3%] Building CXX object CMakeFiles/common.dir/common/alcomplex.cpp.o
[  4%] Building CXX object CMakeFiles/common.dir/common/alexcpt.cpp.o
[  6%] Building CXX object CMakeFiles/common.dir/common/alfstream.cpp.o
[  8%] Building CXX object CMakeFiles/common.dir/common/almalloc.cpp.o
[  9%] Building CXX object CMakeFiles/common.dir/common/alstring.cpp.o
[ 11%] Building CXX object CMakeFiles/common.dir/common/dynload.cpp.o
[ 12%] Building CXX object CMakeFiles/common.dir/common/polyphase_resampler.cpp.o
[ 14%] Building CXX object CMakeFiles/common.dir/common/strutils.cpp.o
[ 16%] Building CXX object CMakeFiles/common.dir/common/threads.cpp.o
[ 17%] Linking CXX static library libcommon.a
[ 17%] Built target common
[ 19%] Generating bsinc_inc.h
[ 20%] Generating hrtf_default.h
Scanning dependencies of target OpenAL
[ 22%] Building CXX object CMakeFiles/OpenAL.dir/al/auxeffectslot.cpp.o
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/auxeffectslot.cpp:38:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alcontext.h:15:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/listener.h:12:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:5:
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:314:9: error: 
      no member named 'signbit' in the global namespace; did you mean 'sigwait'?
using ::signbit;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/sysroot/usr/include/signal.h:129:5: note: 
      'sigwait' declared here
int sigwait(const sigset_t* __set, int* __signal);
    ^
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/auxeffectslot.cpp:38:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alcontext.h:15:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/listener.h:12:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:5:
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:315:9: error: 
      no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:316:9: error: 
      no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/sysroot/usr/include/math.h:375:5: note: 
      'finite' declared here
int finite(double __x) __attribute_const__;
    ^
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/auxeffectslot.cpp:38:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alcontext.h:15:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/listener.h:12:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:5:
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:319:9: error: 
      no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:320:7: error: 
      no member named 'isgreater' in the global namespace; did you mean
      '::std::greater'?
using ::isgreater;
      ^~
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/functional:728:29: note: 
      '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/auxeffectslot.cpp:38:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alcontext.h:15:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/listener.h:12:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:5:
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:321:7: error: 
      no member named 'isgreaterequal' in the global namespace; did you mean
      '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/functional:757:29: note: 
      '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/auxeffectslot.cpp:38:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alcontext.h:15:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/listener.h:12:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:5:
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:322:9: error: 
      no member named 'isless' in the global namespace
using ::isless;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:323:9: error: 
      no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:324:9: error: 
      no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:325:9: error: 
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/home/marvin/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:326:9: error: 
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/auxeffectslot.cpp:38:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alcontext.h:15:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/listener.h:12:
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:35:28: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float'
      in initializer list [-Wc++11-narrowing]
  ...std::sqrt(mVals[0]*mVals[0] + mVals[1]*mVals[1] + mVals[2]*mVals[2])};
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:35:28: note: 
      insert an explicit cast to silence this issue
  ...std::sqrt(mVals[0]*mVals[0] + mVals[1]*mVals[1] + mVals[2]*mVals[2])};
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     static_cast<float>(                                                 )
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/common/vecmat.h:35:28: warning: 
      implicit conversion loses floating-point precision: 'double' to
      'const float' [-Wimplicit-float-conversion]
  ...{std::sqrt(mVals[0]*mVals[0] + mVals[1]*mVals[1] + mVals[2]*mVals[2])};
     ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/al/auxeffectslot.cpp:38:
In file included from /home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alcontext.h:18:
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:123:19: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float'
      in initializer list [-Wc++11-narrowing]
    const float x{-std::sin(azimuth) * std::cos(elevation)};
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:123:19: note: 
      insert an explicit cast to silence this issue
    const float x{-std::sin(azimuth) * std::cos(elevation)};
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  static_cast<float>(                     )
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:123:38: warning: 
      implicit conversion loses floating-point precision: 'double' to
      'const float' [-Wimplicit-float-conversion]
    const float x{-std::sin(azimuth) * std::cos(elevation)};
                 ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:124:20: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float'
      in initializer list [-Wc++11-narrowing]
    const float y{ std::sin(elevation)};
                   ^~~~~~~~~~~~~~~~~~~
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:124:20: note: 
      insert an explicit cast to silence this issue
    const float y{ std::sin(elevation)};
                   ^~~~~~~~~~~~~~~~~~~
                   static_cast<float>()
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:124:20: warning: 
      implicit conversion loses floating-point precision: 'double' to
      'const float' [-Wimplicit-float-conversion]
    const float y{ std::sin(elevation)};
                 ~ ^~~~~~~~~~~~~~~~~~~
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:125:20: error: 
      non-constant-expression cannot be narrowed from type 'double' to 'float'
      in initializer list [-Wc++11-narrowing]
    const float z{ std::cos(azimuth) * std::cos(elevation)};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:125:20: note: 
      insert an explicit cast to silence this issue
    const float z{ std::cos(azimuth) * std::cos(elevation)};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   static_cast<float>(                    )
/home/marvin/Downloads/openal-soft-openal-soft-1.20.1/alc/alu.h:125:38: warning: 
      implicit conversion loses floating-point precision: 'double' to
      'const float' [-Wimplicit-float-conversion]
    const float z{ std::cos(azimuth) * std::cos(elevation)};
                 ~ ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
4 warnings and 15 errors generated.
make[2]: *** [CMakeFiles/OpenAL.dir/build.make:71: CMakeFiles/OpenAL.dir/al/auxeffectslot.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/OpenAL.dir/all] Fehler 2
make: *** [Makefile:118: all] Fehler 2

**Comment by kcat** [comment]
It looks like there's a problem with the compiler's `cmath` header. Like it's trying to declare the math functions in the `std` namespace by `using` the global functions, but it didn't include what it needed to for the global math functions to be declared.

What changes did you make to the cross-compile cmake script? The Android NDK should actually come with a cross-compile cmake script/toolchain file, and it would probably be better to use that if you can.

**Comment by TheMasterMaind** [comment]
Thank you for pointing out there is a cross compilation file for cmake included with the ndk!

With the toolchain file in the ndk I was able to build openal without problems. Works like a charm!

Thanks. Keep up the great work!
