### ISSUE TITLE
Loop points

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#387]
Hi, is there a way to set 'loop points' within a source? s.t. it would be possible to

a. play until the start of the first loop point
b. once reaching the end of the loop point, loops back to start of loop point (repeat)

**Comment by kcat** [comment]
You can set loop points on a buffer with the [`AL_SOFT_loop_points`](https://openal-soft.org/openal-extensions/SOFT_loop_points.txt) extension. If the extension is available, set it like this:
```
ALint loop_points[2] = { startpoint, endpoint }; /* in sample frames */
alBufferiv(buffer, AL_LOOP_POINTS_SOFT, loop_points);
```
Then when you play the buffer on a looping source, it will play from the beginning up to `endpoint` and then go back to `startpoint` and repeat. Note that the `endpoint` is exclusive, it's not played itself; when the source would reach `endpoint`, it goes to `startpoint` instead (i.e. `[startpoint, endpoint)`). Consequently, `endpoint` must be greater than `startpoint`, and must not be greater than the buffer's length in sample frames. Also, calling `alBufferData` will reset the loop points, and they can't be changed after the buffer has been attached to a source.

**Comment by hsdk123** [comment]
Thanks for the update! How do I know if the extension is available?

**Comment by kcat** [comment]
`alIsExtensionPresent("AL_SOFT_loop_points")` will return `AL_TRUE` if it's available on the current context.

**Comment by kcat** [comment]
Assuming this is all set, then. If you have any problems, feel free to ask or open a new issue.

**Comment by hsdk123** [comment]
Sorry for the late update - yup, that cleared things. Thank you!
