### ISSUE TITLE
Segfaults on setting stereo angles

### ISSUE THREAD

**Issue by McSinyx** [kcat/openal-soft#390]
Hi,

I'm trying to build my Python extension which uses alure on manylinux2014 (a fancy way to call CentOS 7) and the HRTF example segfault after a few seconds.  While the issue is probably not on OpenAL Soft, I need some help debugging the build since my knowledge on OpenAL (as well as C++ development in general) is quite limited.

The extension is linked with alure and openal-soft compiled from `master` branches on manylinux2014, and I'm testing it on Debian testing.  The bug has something to do with setting the source's stereo angles repeatedly (setting position instead, however, does not cause segfault):
```gdb
$ gdb python3
GNU gdb (Debian 8.3.1-1) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) run examples/palace-hrtf.py /home/cnx/Music/3005.mp3 
Starting program: /usr/bin/python3 examples/palace-hrtf.py /home/cnx/Music/3005.mp3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4800700 (LWP 342118)]
[New Thread 0x7ffff3fbf700 (LWP 342120)]
Opened Built-in Audio Analog Stereo
Available HRTFs:
    default-44100
    default-48000
    Built-In HRTF
[New Thread 0x7ffff361e700 (LWP 342121)]
Using HRTF "default-44100"
[New Thread 0x7ffff2268700 (LWP 342122)]
Playing /home/cnx/Music/3005.mp3 (32-bit float, Stereo, 44100 Hz)
 00:05 / 03:55
Thread 3 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3fbf700 (LWP 342120)]
0x00007ffff7099f0f in MixHrtfBlendBase<(anonymous namespace)::ApplyCoeffs> (
    BufferSize=<optimized out>, newparams=<optimized out>, oldparams=<optimized out>, 
    IrSize=32, AccumSamples=0xa2f260, InSamples=0xa2e160)
    at /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/include/xmmintrin.h:976
976	/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/include/xmmintrin.h: No such file or directory.
```

Discussion on freenode#python resolved that `/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/include/xmmintrin.h: No such file or directory.` is not related to the crash (well to be specific manylinux2014 is CentOS 7 with development libraries installed in `/opt`).  I can provide the full back trace if that'd be useful anyhow, it's just telling something about calls though PulseAudio to me.

**Comment by kcat** [comment]
> The bug has something to do with setting the source's stereo angles repeatedly

What values are you setting for the stereo angles? I think I see a potential issue if you set an angle to something less than `-pi*2` (or much larger than 4 billion). If that's the issue you're having, keeping the angles wrapped between `[-pi, +pi]` should avoid the crash, and I can add a fix to master.

**Comment by McSinyx** [comment]
> If that's the issue you're having, keeping the angles wrapped between [-pi, +pi] should avoid the crash, and I can add a fix to master.

Thank you, it seems so!  Somehow this is not a problem on OpenAL Soft 1.19.1 on Debian but on `master`.

**Comment by McSinyx** [comment]
Thank you, building against ebb1aaa06d1149a2a1a5d2c20bae8d84096c38dd fixed the problem!
