### ISSUE TITLE
[linux] [regression] no sound in openal if other programs play something

### ISSUE THREAD

**Issue by axredneck** [kcat/openal-soft#392]
When i just start any openal app (e.g. GZDoom or FTEQW) it produces sound, but when i start openal app when something is already playing in background (e.g. any music player) there is no sound in openal app.
Arch Linux, openal 1.20.1, pulseaudio 13.0, sound through HDMI on Geforce GTX 1050, Nvidia driver 440.59, kernel 5.5.1.
Downgrading openal to 1.19.1 helps to workaround this problem.

**Comment by kcat** [comment]
Can you provide a trace log? Set the `ALSOFT_LOGLEVEL` environment variable to `3` when you run the app to have it output a log to `stderr`. A log from both 1.20.1 and 1.19.1 would be helpful.

That behavior makes it sound like it's using JACK or ALSA with a direct hardware device, preventing the openal app from using the device at the same time as another. 1.20.1 shouldn't change anything about this, unless the older version wasn't initializing JACK properly and the new version does and tries to use it, or the new version fails to initialize PulseAudio and makes it fallback to ALSA.

**Comment by axredneck** [comment]
1.19.1: [openal.log](https://github.com/kcat/openal-soft/files/4162645/openal.log) (sound presents)
1.20.1: [openal.log](https://github.com/kcat/openal-soft/files/4162647/openal.log) (no sound)
Both logs from GZDoom while foobar2000 (using Wine) plays in background
Should i make logs with FTEQW too ?

**Comment by kcat** [comment]
> Should i make logs with FTEQW too ?

No, this should be fine. This is odd though, PulseAudio is initializing and opening playback just fine. But this:
```
AL lib: (EE) ALCpulsePlayback_reset: Non-0 prebuf, 2206 samples (17648 bytes), device has 3528 samples
```
in the 1.19 log may be indicative of the underlying issue. I've seen it once before, but it's not something that's supposed to happen and I couldn't find the cause of it.

The message means the PulseAudio stream is in auto mode, where it'll automatically start the stream after it's filled with enough samples and automatically stop when it's empty. But the OpenAL Soft configures the stream to be in manual mode so it can be started and stopped on-demand, which the backend depends on and the docs don't mention it can be changed by the server. So OpenAL Soft starts the stream and waits to hear from PulseAudio that it's ready for more samples, but PulseAudio ignores the call to start it and waits until it's proactively given enough samples. The old version just happened to be written in a way that it worked, whereas the new version expects proper behavior from PulseAudio.

But what's extra odd is that this should have nothing to do with whether an app is already playing or not. Unless PulseAudio is being extra weird and changing OpenAL Soft's stream behavior depending if it's already playing another stream.

**Comment by kcat** [comment]
Commit 8731accd3f40b25632fa0f90c8954a5f0b1fd5a5 should deal with the prebuf issue now. I can't guarantee completely correct behavior if the pulseaudio stream can't be properly stopped and started on demand, but I believe it should work.

**Comment by axredneck** [comment]
Thank You! Looks like it's fixed. I'll reopen the issue if it's not.
