### ISSUE TITLE
[GCC bug] 32-bit soft_oal.dll crashes on process exit

### ISSUE THREAD

**Issue by skullernet** [kcat/openal-soft#394]
Not strictly OpenAL Soft issue, but worth reporting because binaries from kcat.strangesoft.net are affected.

Currently, any x86 Windows application that has 32-bit soft_oal.dll loaded crashes on process exit in ~ThreadCtx() destructor due to GCC bug [83562](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83562).

openal-info32.exe crashes for example, and even the trivial application that only does LoadLibrary("soft_oal.dll") and exits crashes.

Possible solution is to use 64-bit version of DLL, which should be unaffected, or to rebuild 32-bit DLL using MSVC until GCC bug is fixed.

**Comment by drfrag666** [comment]
Attached 1.20.1 VS v141 default Release 32 bit build.
[OpenAL32.zip](https://github.com/kcat/openal-soft/files/4219611/OpenAL32.zip)

**Comment by kcat** [comment]
Commit 4277c05b0c41923af7ab852a63b1984b277a638a should work around this issue. If you need a 32-bit DLL for 1.20.1 specifically, you can use one built with MSVC like the above attachment (just be aware it's without XP support, I'm led to believe), or backport that commit directly onto 1.20.1 to build with GCC.

**Comment by skullernet** [comment]
No longer crashes with that commit.

**Comment by drfrag666** [comment]
This one is compiled with FORCE_STATIC_VCRT. VS v141 Release 32 bit build.
[OpenAL32.zip](https://github.com/kcat/openal-soft/files/4742261/OpenAL32.zip)

**Comment by alexey-lysiuk** [comment]
Well, it still imports dynamic runtime. Maybe the option itself is a bit broken.

**Comment by kcat** [comment]
Commit 3001d56d4b6c6daa63b8d789a7c094bbdf626974 (first commit after the 1.20.1 release) fixes that.

**Comment by drfrag666** [comment]
Here's a custom build with both fixes.
[OpenAL32.zip](https://github.com/kcat/openal-soft/files/4742651/OpenAL32.zip)
