### ISSUE TITLE
AL_REVERB values are out of range

### ISSUE THREAD

**Issue by tek256** [kcat/openal-soft#398]
Hello! 
I'm running into an issue with setting some reverb effect values. 
Running `alGetError()` before and after yields no flags. Running `alGetError()` after the `alEffectf` calls yields the error code: `40963`.  When setting the variables for AL_REVERB it throws errors for the following parameters: 
- AL_REVERB_GAIN
- AL_REVERB_GAINHF
- AL_REVERB_DECAY_HFRATIO
- AL_REVERB_REFLECTIONS_GAIN
- AL_REVERB_REFLECTIONS_DELAY
- AL_REVERB_LATE_REVERB_GAIN
- AL_REVERB_AIR_ABSORPTION_GAINHF

I've tested with and get the same errors on both release versions `1.20.0` and `1.20.1`. 

Here is the relevant code snippet:
``` 
    alGenEffects(1, &fx.id);
    alEffecti(fx.id, AL_EFFECT_TYPE, AL_EFFECT_REVERB);
    alEffectf(fx.id, AL_REVERB_GAIN, 0.32f);
```

I modified `alc/effects/reverb.cpp` 's `StdReverb_setParamf` function to output the value when the error is thrown, (this is the only modified case in the function)
```
case AL_REVERB_GAIN:
    if (!(val >= AL_REVERB_MIN_GAIN && val <= AL_REVERB_MAX_GAIN)) {
      SETERR_RETURN(context, AL_INVALID_VALUE, , "Reverb gain out of range %f",
                    val);
    }
    props->Reverb.Gain = val;
    break;
```

The modified error output gives me: 

```
L lib: (WW) Error generated on context 0x2799540, code 0xa003, "Reverb gain out of range 2.000000"
```

I've gone ahead and made a small table of inputs & what the debug outputs.
| Input | Output |
| ------ | --------- |
| 0.0f | No error | 
| 0.1f | -0.0000 |
| 0.3f | 2.000 |
| 0.32f | 2.000 |
| AL_REVERB_DEFAULT_GAIN (0.32) | 2.000 |
| 0.49f | No error |
| 0.5f | No error |
| 0.7f | 36893488147419103232.000000 | 
| 0.9f | -2.000 |
| 2.0f | No error |

Info about my setup:
- All built dynamically
- Compiled & tested with both Clang (9.0.1, posix) and GCC (9.3.0)
- Void Linux (XFCE) X86-64 (Ryzen 7)
- All other features appear to work correctly

Thank you for reading! 
If there is any info I can provide to help please let me know!

**Comment by kcat** [comment]
How are you declaring the `alEffect`* functions and loading them? It looks like it's not getting the parameter value correctly, which could be the result of calling into the function with the wrong parameter types.

**Comment by tek256** [comment]
Adding the function loading from the example worked! Silly thing to overlook, thank you!
For those with similar issues I solved it with the following code from the example: 

Define the function pointers:
```
static LPALGENEFFECTS    alGenEffects;
static LPALDELETEEFFECTS alDeleteEffects;
static LPALISEFFECT      alIsEffect;
static LPALEFFECTI       alEffecti;
static LPALEFFECTIV      alEffectiv;
static LPALEFFECTF       alEffectf;
static LPALEFFECTFV      alEffectfv;
static LPALGETEFFECTI    alGetEffecti;
static LPALGETEFFECTIV   alGetEffectiv;
static LPALGETEFFECTF    alGetEffectf;
static LPALGETEFFECTFV   alGetEffectfv;

static LPALGENAUXILIARYEFFECTSLOTS    alGenAuxiliaryEffectSlots;
static LPALDELETEAUXILIARYEFFECTSLOTS alDeleteAuxiliaryEffectSlots;
static LPALISAUXILIARYEFFECTSLOT      alIsAuxiliaryEffectSlot;
static LPALAUXILIARYEFFECTSLOTI       alAuxiliaryEffectSloti;
static LPALAUXILIARYEFFECTSLOTIV      alAuxiliaryEffectSlotiv;
static LPALAUXILIARYEFFECTSLOTF       alAuxiliaryEffectSlotf;
static LPALAUXILIARYEFFECTSLOTFV      alAuxiliaryEffectSlotfv;
static LPALGETAUXILIARYEFFECTSLOTI    alGetAuxiliaryEffectSloti;
static LPALGETAUXILIARYEFFECTSLOTIV   alGetAuxiliaryEffectSlotiv;
static LPALGETAUXILIARYEFFECTSLOTF    alGetAuxiliaryEffectSlotf;
static LPALGETAUXILIARYEFFECTSLOTFV   alGetAuxiliaryEffectSlotfv;
```

Then load the function pointers with this:
```
#define LOAD_PROC(T, x)  ((x) = (T)alGetProcAddress(#x))
    LOAD_PROC(LPALGENEFFECTS, alGenEffects);
    LOAD_PROC(LPALDELETEEFFECTS, alDeleteEffects);
    LOAD_PROC(LPALISEFFECT, alIsEffect);
    LOAD_PROC(LPALEFFECTI, alEffecti);
    LOAD_PROC(LPALEFFECTIV, alEffectiv);
    LOAD_PROC(LPALEFFECTF, alEffectf);
    LOAD_PROC(LPALEFFECTFV, alEffectfv);
    LOAD_PROC(LPALGETEFFECTI, alGetEffecti);
    LOAD_PROC(LPALGETEFFECTIV, alGetEffectiv);
    LOAD_PROC(LPALGETEFFECTF, alGetEffectf);
    LOAD_PROC(LPALGETEFFECTFV, alGetEffectfv);

    LOAD_PROC(LPALGENAUXILIARYEFFECTSLOTS, alGenAuxiliaryEffectSlots);
    LOAD_PROC(LPALDELETEAUXILIARYEFFECTSLOTS, alDeleteAuxiliaryEffectSlots);
    LOAD_PROC(LPALISAUXILIARYEFFECTSLOT, alIsAuxiliaryEffectSlot);
    LOAD_PROC(LPALAUXILIARYEFFECTSLOTI, alAuxiliaryEffectSloti);
    LOAD_PROC(LPALAUXILIARYEFFECTSLOTIV, alAuxiliaryEffectSlotiv);
    LOAD_PROC(LPALAUXILIARYEFFECTSLOTF, alAuxiliaryEffectSlotf);
    LOAD_PROC(LPALAUXILIARYEFFECTSLOTFV, alAuxiliaryEffectSlotfv);
    LOAD_PROC(LPALGETAUXILIARYEFFECTSLOTI, alGetAuxiliaryEffectSloti);
    LOAD_PROC(LPALGETAUXILIARYEFFECTSLOTIV, alGetAuxiliaryEffectSlotiv);
    LOAD_PROC(LPALGETAUXILIARYEFFECTSLOTF, alGetAuxiliaryEffectSlotf);
    LOAD_PROC(LPALGETAUXILIARYEFFECTSLOTFV, alGetAuxiliaryEffectSlotfv);
#undef LOAD_PROC
```

Thank you for your help @kcat !
