### ISSUE TITLE
Problem with alcGetString and Unicode sound card names

### ISSUE THREAD

**Issue by daniilpetrov** [kcat/openal-soft#399]
alcGetString returns Char and Unicode in the same string: OpenAL Soft on ￐ﾔ￐ﾸ￐ﾽ￐ﾰ￐ﾼ￐ﾸ￐ﾺ￐ﾸ (High Definition Audio Device). FMOD shows the name as «Динамики (High Definition Audio Device)».

**Comment by kcat** [comment]
Make sure to interpret the string as UTF-8 (all strings returned by OpenAL Soft should be UTF-8). Either have your logger set to expect UTF-8 for char strings, or use `MultiByteToWideChar` to convert from UTF-8 to a wchar string and print that.

**Comment by daniilpetrov** [comment]
```
// Code Example
// Here 'const char *List' includes char and wchar_t symbols
printDeviceList(alcGetString(NULL, ALC_ALL_DEVICES_SPECIFIER));

* * *
inline void ClassLogFile::printDeviceList(const char *List)
{
	if (!List || *List == '\0') WriteLog(L"  * !!! none !!!\n");
	else do {
		std::string String = List;
		std::wstring ConvertedString = std::wstring(String.begin(), String.end());

		WriteLog(L"  * " + ConvertedString + L"\n");
		List += strlen(List) + 1;
	} while (*List != '\0');
}
```

**Comment by kcat** [comment]
> `std::wstring ConvertedString = std::wstring(String.begin(), String.end());`

That doesn't convert UTF-8, that just copies each char value into a wchar, which is only valid for the ASCII-7 (0...127) characters. You need to do something like this to convert UTF-8 to a wstring:
```
std::wstring utf8_to_wstr(const char *str)
{
    std::wstring ret;

    int len = MultiByteToWideChar(CP_UTF8, 0, str, -1, nullptr, 0);
    if(len > 0)
    {
        ret.resize(len);
        MultiByteToWideChar(CP_UTF8, 0, str, -1, &ret[0], len);
        ret.pop_back();
    }

    return ret;
}
```

**Comment by daniilpetrov** [comment]
Everything is okay, thank you very much!
