### ISSUE TITLE
wasapi audio backend returns a non-empty list of audio devices when there are no any audio devices in the system

### ISSUE THREAD

**Issue by victorshcherbakov** [kcat/openal-soft#400]
It's easy to reproduce.
You need to get the list of audio devices, when at least one device is presented:
`alcGetString(nullptr, ALC_ALL_DEVICES_SPECIFIER)`
Then you disable all your audio devices, e.g. in this way:
![image](https://user-images.githubusercontent.com/2960246/77420037-eede8200-6dfb-11ea-9a53-c55b779ab06a.png)

The second call of `alcGetString(nullptr, ALC_ALL_DEVICES_SPECIFIER)` will return the previous list of devices, because the function `WasapiProxy::messageHandler` doesn't clear the vector PlaybackDevices or CaptureDevices before invoking `probe_devices`. Although dsound backend does it and doesn't have such a problem.

**Comment by kcat** [comment]
Fixed with commit cc27bbb680aa6aaca9e5ed5c5777b9d227a62505. The WASAPI device list is now cleared before re-enumerating the available devices.
