### ISSUE TITLE
wasapi audio backend stops working after an unsuccessful attempt to initialize the audio device

### ISSUE THREAD

**Issue by victorshcherbakov** [kcat/openal-soft#401]
There are steps to reproduce:

1. Disable all audio devices
![image](https://user-images.githubusercontent.com/2960246/77421745-ed628900-6dfe-11ea-9d5d-b6d8a7620a61.png)
2. Call in the code `alcOpenDevice(nullptr)` and it's all.

Even you enable any audio device, second calls will fail, e.g. `alcOpenDevice(nullptr)` or `alcGetString(nullptr, ALC_ALL_DEVICES_SPECIFIER)`.

It will happen, because `deviceCount` variable in the function `WasapiProxy::messageHandler` is overflowed. It has a value - 4294967295. It happens, because it's decreased two times here:
![image](https://user-images.githubusercontent.com/2960246/77422897-cdcc6000-6e00-11ea-96ca-c8eedc1b373b.png)

**Comment by McSinyx** [comment]
I don't think the reasoning is valid here though (notice the `continue` statement), so this is worth further investigation.  BTW you can always reference using GitHub, e.g. https://github.com/kcat/openal-soft/blob/2acdcba8d19cc84fb06f0fbe1df4bc26c0e2c009/alc/backends/wasapi.cpp#L565-L589

In order for underflow to occur (if you got traced back to the given method), then somehow `CloseDevice` message would have been sent multiple times.

**Comment by victorshcherbakov** [comment]
Thank you, I know about `continue'.
These are rough steps, how it happens:

1. `WasapiPlayback` is created.
2. And `MsgType::OpenDevice` is sent to `WasapiProxy::messageHandler`.
3. Then `openProxy()` fails.
4. `deviceCount` is decremented and it is equal to `0`
![image](https://user-images.githubusercontent.com/2960246/77444484-789f4700-6e1e-11ea-9620-2b75b813e4cc.png)
5. `WasapiPlayback` is destroyed, because it cannot be initialized successfully.
6. `WasapiPlayback::~WasapiPlayback()` sends `MsgType::CloseDevice`.
7. `deviceCount` is decremented again and it's equal to `4294967295`
![image](https://user-images.githubusercontent.com/2960246/77444938-0713c880-6e1f-11ea-9f51-812d0656a50b.png)

**Comment by kcat** [comment]
Good catch. The `WasapiPlayback` and `WasapiCapture` destructors shouldn't send a `CloseDevice` message if the device never opened. Should be fixed now with commit 62f17d8763503b0cb924566c9ab75f8bf3ac123e.
