### ISSUE TITLE
how to recover openal playing status?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#402]
I have a screen ，Sound card on the screen；use openal play sound；when I  Disable default speakers or pluck out HDMI link the computer ，the openal status change to al_stopped.and then  I enable the default speaker,but when I  alSourcePlay(isource）,the status is still  al_stopped. I try to （alsourceRewind before alSourcePlay ）or （Turn off sound source and recreate the source ），but still can not recover playing status.(and can not play sound )
(windows dll)
what is the reason ? I use it on windows 7 ,win 10,use openal 1.17  and 1.20 ,still can not recover playing status

**Comment by kcat** [comment]
When a sound device is lost or disabled, it becomes disconnected. You can detect this by calling:
```
ALCint connected;
alcGetIntegerv(device, ALC_CONNECTED, 1, &connected);
if(!connected)
    ... device is disconnected ...
```
Sources become stopped and will not play on a disconnected device, and a disconnected device won't reconnect on its own. With 1.20, the `alcResetDeviceSOFT` function (from the `ALC_SOFT_HRTF` or `ALC_SOFT_output_limiter` extension) can try to reconnect with the device. If `alcResetDeviceSOFT(device, ...);` returns true, it's connected again. Sources won't automatically restart playing, but you can call `alSourcePlay` to play them again at that point.

There's currently no way to 'move' playback from one device to another. So if you're playing audio on an HDMI connection, the HDMI connection becomes disabled and a default internal speaker device becomes enabled, the OpenAL device will still be associated with the HDMI device and not move to the internal speaker device. The only way around this currently is to have a virtual system device that will move playback between devices for the app, but I don't know if Windows has that ability.

**Comment by xuandu** [comment]
I have two computer 
1 :General computer and display screen, speaker in the computer not in the screen；
2：computer link（with hdmi，Physical connector）large display screen,the speaker in the screen(like tv,emmm...). I get the same Situation ，when I use  1 to disable speaker,or when I use 2 to pull out the screen connector. and I just have one device(speaker) It is default .

I don't need it to continue playing when it's disabled, just hope it can continue playing when this device enabled again (I don't need it to continue playing when it's pull out the hdmi link the screen, just hope it can continue playing when it's connect link  again)

but when I enable this device again(after disable),it is still AL_STOPPED. I will try your method 1.
thank you so much .

**Comment by kcat** [comment]
> and I use "alcGetIntegerv" to detect the disable .but this function alcResetDeviceSOFT ,can not be analysised(I delete the #ifdef AL_ALEXT_PROTOTYPES in alext.h line 463)，when I build my code,it NEED Recompile?

You load it at runtime using OpenAL's extension mechanism. Like this:
```
#include "alext.h"

// Somewhere in your code
if(!connected)
{
    // Check for one of the extensions that has the function
    if(alcIsExtensionPresent(device, "ALC_SOFT_HRTF") || alcIsExtensionPresent(device, "ALC_SOFT_output_limiter"))
    {
        // Get the function address
        LPALCRESETDEVICESOFT alcResetDeviceSOFT = alcGetProcAddress(device, "alcResetDeviceSOFT");
        // Call the function. If it returns true, the device should be working again
        connected = alcResetDeviceSOFT(device, NULL);
    }
}
```

**Comment by xuandu** [comment]
thank you so much, This method solved my problem
