### ISSUE TITLE
Problems with std::threads after recent update to Version 16.5.2

### ISSUE THREAD

**Issue by NiklasTreutner** [kcat/openal-soft#408]
Hi,

after an Update to Visual Studio 16.5.2 i have issues using threads with OpenAL. The Problems seem to occur in other threads, but only if i use OpenAL capturing from a mic in a different thread. It's a bit difficult to pinpoint the offending lines of code, but i think the problem lies here:

 ```
recordThread = std::thread([&]
	{ 

		while (recording && (err = alcGetError(mDevice)) == ALC_NO_ERROR && !ferror(mFile))
		{
			storeData(toDisk);
		}

		alcCaptureStop(mDevice);
		mDataSize;
		fprintf(stderr, "\rCaptured %u samples\n", allData.size());
		if (err != ALC_NO_ERROR)
			fprintf(stderr, "Got device error 0x%04x: %s\n", err, alcGetString(mDevice, err));

	});
```

("recording" is a bool that is used to terminate the recording)

If i don't use this code in a thread but for a limited amount of samples, it seems to work fine. If i use this code and then use a simple std::this_thread::sleep_for(std::chrono::seconds(1)); in a different thread, something in the thread-sleep breaks.
Also, in a windows environment, Sleep(1000); also works fine for now.

I'm sorry that i can't be more specific, but it's difficult to pinpoint what exactly causes the problem, since not the actual OpenAL-code but something unrelated crashes.

Does anybody else have similar issues? Any idea what might have caused it?
Thanks for your time!

**Comment by kcat** [comment]
I'd have to see the rest of the function, as well as the `storeData` function and `toDisk` variable. In particular, the calling function must not return before the thread is joined/terminated since it captures local variables, `recordering` would need to be atomic, and any other shared resource should be handled in a thread-safe manner.

**Comment by NiklasTreutner** [comment]
Hey again,

so after a while i figured out that the problem had nothing to do with OpenAL but with my usage of threads (i referenced a variable that went out of scope...). I don't really know why it didn't occur previously or why only when using OpenAL (i made the same mistake with other libs too) but that is not your concern ;)

Sorry for taking up your time and thanks again for your help!
