### ISSUE TITLE
Win32 build on visual studio

### ISSUE THREAD

**Issue by jkstpierre** [kcat/openal-soft#409]
When I try to compile OpenAL as a Win32 project on VS 2019, compilation fails due to '_BitScanForward64' not being found. Is there a way to build OpenAL for x86 architectures or am I stuck with the x64 option only?

**Comment by kcat** [comment]
It should work fine for x86. That function is only used if CMake detected it. 32-bit doesn't have that function, so it should fail that check and use `_BitScanForward` instead. See [this build log](https://ci.appveyor.com/project/ChrisRobinson/openal-soft/build/job/6mxvplqeaeeqpjvg:
```
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC - Failed
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC - Success
```

**Comment by kcat** [comment]
One thing to be careful of is using cmake to generate a 64-bit project, then using VS to change it to 32-bit. The cmake script does some checks with the compiler to generate a configuration header (`config.h`) and add include paths and libs to link for the project, which may not work if the project is simply retargeted to 32-bit. If you want a 32-bit target, it's best to use a 32-bit generator with cmake.

**Comment by kcat** [comment]
This is no longer checked for at cmake time, so shouldn't be a problem anymore. There's also more generally fewer cmake checks that depend on win32 vs win64, though I can't guarantee there's none. So I'd still recommend using the appropriate 32-bit or 64-bit generator, instead of changing the generated VS project target.
