### ISSUE TITLE
Thread alsoft-mixer still running for lock screen on Android

### ISSUE THREAD

**Issue by wbbtcool** [kcat/openal-soft#410]
openal-soft  version：1.20.0
platform：Android 9.0
tool：Android Studio 3.6.1

I have a power consumption problem. Thread alsoft-mixer still running for lock screen on Android. 

![image](https://user-images.githubusercontent.com/7963418/78758223-5e35a380-79b0-11ea-89e4-b93d9ebdb97c.png)

<img width="415" alt="WX20200408-155419@2x" src="https://user-images.githubusercontent.com/7963418/78758791-3eeb4600-79b1-11ea-9724-2f2fb4da2002.png">

opensl.cpp

```
int OpenSLPlayback::mixerProc()
{
    ......

    while(SL_RESULT_SUCCESS == result && !mKillNow.load(std::memory_order_acquire) &&
          mDevice->Connected.load(std::memory_order_acquire))
    {
        if(mRing->writeSpace() == 0)
        {
            SLuint32 state{0};

            result = VCALL(player,GetPlayState)(&state);
            PRINTERR(result, "player->GetPlayState");
            if(SL_RESULT_SUCCESS == result && state != SL_PLAYSTATE_PLAYING)
            {
                result = VCALL(player,SetPlayState)(SL_PLAYSTATE_PLAYING);
                PRINTERR(result, "player->SetPlayState");
            }
            if(SL_RESULT_SUCCESS != result)
            {
                aluHandleDisconnect(mDevice, "Failed to start platback: 0x%08x", result);
                break;
            }

            if(mRing->writeSpace() == 0)
            {
                dlock.unlock();
                mSem.wait();          // mSem always wait.
                dlock.lock();
                continue;
            }
        }

        ......
    }

    return 0;
}
```
Is it possible to sleep/hang the thread on device lock srceen ?
Thanks.

**Comment by kcat** [comment]
The `ALC_SOFT_pause_device` extension has the `alcDevicePauseSOFT` function, which you can call to stop playback processing. You can then call `alcDeviceResumeSOFT` to restart playback right where it left off. See: https://openal-soft.org/openal-extensions/SOFT_pause_device.txt

**Comment by wbbtcool** [comment]
Thank you for your reply. I try alcDevicePauseSOFT/alcDeviceResumeSOFT function but it can't used. I only use LPALCDEVICEPAUSESOFT/LPALCDEVICEPAUSESOFT function. it don't take effect on Background or Foreground.  Thread alcmixer still running on Background. 
```
#ifndef ALC_SOFT_pause_device
#define ALC_SOFT_pause_device 1
typedef void (ALC_APIENTRY*LPALCDEVICEPAUSESOFT)(ALCdevice *device);
typedef void (ALC_APIENTRY*LPALCDEVICEPAUSESOFT)(ALCdevice *device);
#ifdef AL_ALEXT_PROTOTYPES
ALC_API void ALC_APIENTRY alcDevicePauseSOFT(ALCdevice *device);
ALC_API void ALC_APIENTRY alcDeviceResumeSOFT(ALCdevice *device);
#endif
#endif
```
 Is it the wrong way I use？

**Comment by kcat** [comment]
You need to check for and load the function at runtime, after the app is put into the background. Something like this when you detect the app is in the background:
```
if(alcIsExtensionPresent(Device, "ALC_SOFT_pause_device")
{
    LPALCDEVICEPAUSESOFT alcDevicePauseSOFT = alcGetProcAddress(Device,
        "alcDevicePauseSOFT");
    alcDevicePauseSOFT(Device);
}
```
And similar for when you detect the app returns to the foreground (using `LPALCDEVICERESUMESOFT`/`alcDeviceResumeSOFT` instead).

**Comment by wbbtcool** [comment]
@kcat Cool. Thank you very much. It work fine now. I add enterBackground/enterForeground function. 
```
void AudioEngineImpl::enterBackground() {
    if(alcIsExtensionPresent(s_ALDevice, "ALC_SOFT_pause_device"))
    {
        LPALCDEVICEPAUSESOFT alcDevicePauseSOFT = (LPALCDEVICEPAUSESOFT)alcGetProcAddress(s_ALDevice,
                                                                    "alcDevicePauseSOFT");
        alcDevicePauseSOFT(s_ALDevice);
    }
}

void AudioEngineImpl::enterForeground() {
    if(alcIsExtensionPresent(s_ALDevice, "ALC_SOFT_pause_device"))
    {
        LPALCDEVICEPAUSESOFT alcDeviceResumeSOFT = (LPALCDEVICEPAUSESOFT)alcGetProcAddress(s_ALDevice,
                                                                    "alcDeviceResumeSOFT");
        alcDeviceResumeSOFT(s_ALDevice);
    }
}
```
