### ISSUE TITLE
Sourcery ARM Toolchain after 1.19.1

### ISSUE THREAD

**Issue by AndreRH** [kcat/openal-soft#412]
**With**
gcc version 4.8.3 20140320 (prerelease) (Sourcery CodeBench Lite 2014.05-29) 

**I get:**
/sata/src/buildroot3/openal/sourcery-arm/build/openal-1.20.1/common/aloptional.h: In instantiation of 'class al::optional<std::basic_string<char> >':
/sata/src/buildroot3/openal/sourcery-arm/build/openal-1.20.1/common/strutils.cpp:46:53:   required from here
/sata/src/buildroot3/openal/sourcery-arm/build/openal-1.20.1/common/aloptional.h:38:5: error: function 'al::optional<T>::optional() [with T = std::basic_string<char>]' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'al::optional<std::basic_string<char> >::optional()'
     optional() noexcept = default;

**Easily reproducable with buildroot:**
git clone git://git.buildroot.net/buildroot
cd buildroot
echo "BR2_PACKAGE_OPENAL=y" > openal.snippet
rm package/openal/openal.hash # only contains hash for 1.19.1, so don't use it
#now change version in package/openal/openal.mk to desired version, e.g. 1.20.0 and run:
./utils/test-pkg -c openal.snippet -d openal -p openal

**Comment by kcat** [comment]
GCC 4.8 is very old (about 6 years, according to those dates), and has problems with its C++11 support. I'd strongly recommend updating to GCC 5 (or Clang 3.6 or 3.8), especially since the latest master now uses C++14.

**Comment by AndreRH** [comment]
good point, thanks :) closing then
