### ISSUE TITLE
openal32.dll not found error

### ISSUE THREAD

**Issue by SeanTolstoyevski** [kcat/openal-soft#419]
Hello,

I am trying to use OpenAL in my Golang project.

Everywhere wants openal32.dll.
I can't find the file.

OpenAL32.dll file does not occur when I compile it with CMake.
There are .lib and .exp files.

I download the files here, there are no dlls in those files.
http://openal.org/downloads/

When I run the .exe, I get the DLL not found error.

I'm new to C ++ and OpenAL.

I'm about to eat the head. 😢😢😢

I need files to import the DLL into Golang.
How can I create OpenAl32.dll or Openal64.dll?

Please help me.

**Comment by kcat** [comment]
> OpenAL32.dll file does not occur when I compile it with CMake.
> There are .lib and .exp files.

There should be an OpenAL32.dll after compiling. What compiler and compiler version are you using? What commands did you run and what was the output? The .lib file is created with the .dll, so if you have the former there should also be the latter.

**Comment by SeanTolstoyevski** [comment]
1. ```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.3
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64_x86'


D:\>cd d\github\C-Cpp\openal-soft\CMAKEBUILD

D:\d\github\C-Cpp\openal-soft\CMAKEBUILD>cmake CMAKE_BUILD_TYPE=RELEASE BUILD_SHARED_LIBS=ON ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18358.
-- The C compiler identification is MSVC 19.24.28315.0
-- The CXX compiler identification is MSVC 19.24.28315.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Performing Test HAVE___RESTRICT
-- Performing Test HAVE___RESTRICT - Success
-- Performing Test HAVE_LIBATOMIC
-- Performing Test HAVE_LIBATOMIC - Failed
-- Looking for __android_log_print in log
-- Looking for __android_log_print in log - not found
-- Performing Test HAVE_PERMISSIVE_SWITCH
-- Performing Test HAVE_PERMISSIVE_SWITCH - Success
-- Performing Test HAVE_MSSE2_SWITCH
-- Performing Test HAVE_MSSE2_SWITCH - Failed
-- Performing Test HAVE_MFPU_NEON_SWITCH
-- Performing Test HAVE_MFPU_NEON_SWITCH - Failed
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for pmmintrin.h
-- Looking for pmmintrin.h - found
-- Looking for smmintrin.h
-- Looking for smmintrin.h - found
-- Looking for arm_neon.h
-- Looking for arm_neon.h - not found
-- Performing Test HAVE_SSE_INTRINSICS
-- Performing Test HAVE_SSE_INTRINSICS - Success
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for cpuid.h
-- Looking for cpuid.h - not found
-- Looking for intrin.h
-- Looking for intrin.h - found
-- Looking for guiddef.h
-- Looking for guiddef.h - found
-- Looking for pow in m
-- Looking for pow in m - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - not found
-- Performing Test HAVE_CPUID_INTRINSIC
-- Performing Test HAVE_CPUID_INTRINSIC - Success
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD64_INTRINSIC - Success
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC
-- Performing Test HAVE_BITSCANFORWARD_INTRINSIC - Success
-- Looking for posix_memalign
-- Looking for posix_memalign - not found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - found
-- Looking for proc_pidpath
-- Looking for proc_pidpath - not found
-- Looking for getopt
-- Looking for getopt - not found
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Could NOT find OSS (missing: OSS_INCLUDE_DIR)
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR)
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR)
-- FindWindowsSDK: Detected Visual Studio 2012 or newer, not using the _xp toolset variant: including SDK versions that drop XP support in search!
-- Found WindowsSDK: C:/Program Files (x86)/Windows Kits/10
-- Looking for include files windows.h, mmsystem.h
-- Looking for include files windows.h, mmsystem.h - found
-- Found DSound: C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x86/dsound.lib
-- Looking for mmdeviceapi.h
-- Looking for mmdeviceapi.h - found
-- Could NOT find PortAudio (missing: PORTAUDIO_LIBRARY PORTAUDIO_INCLUDE_DIR)
-- Could NOT find PulseAudio (missing: PULSEAUDIO_LIBRARY PULSEAUDIO_INCLUDE_DIR)
-- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
-- Could NOT find OpenSL (missing: OPENSL_LIBRARY OPENSL_INCLUDE_DIR OPENSL_ANDROID_INCLUDE_DIR)
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.23.0.windows.1")
-- Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR)
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
--
-- Building OpenAL with support for the following backends:
--      WinMM, DirectSound, WASAPI, WaveFile, Null
--
-- Building with support for CPU extensions:
--     Default, SSE, SSE2, SSE3, SSE4.1
--
-- Embedding HRTF datasets
--
-- Installing sample configuration
--
-- Installing HRTF definitions
--
-- Installing AmbDec presets
--
-- Found ZLIB: C:/coding/main/ac3/Library/lib/z.lib (found version "1.2.11")
-- Could NOT find MySOFA (missing: MYSOFA_LIBRARY MYSOFA_INCLUDE_DIR)
-- Building utility programs
-- Building configuration program
--
-- Building example programs
--
-- Configuring done
-- Generating done
-- Build files have been written to: D:/d/github/C-Cpp/openal-soft/CMAKEBUILD

D:\d\github\C-Cpp\openal-soft\CMAKEBUILD>
```
2. Openal.sln opens VS2019
3. Menu > Build > Build ALL_BUILD

VS Compile Log: 
```
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: build_version, Configuration: Debug x64 ------
3>------ Build started: Project: common, Configuration: Debug x64 ------
2>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8065: Custom build for item "D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\CMakeFiles\df1e664e840dca97a67707675079816a\build_version.rule" succeeded, but specified output "d:\d\github\c-cpp\openal-soft\cmakebuild\cmakefiles\build_version" has not been created. This may cause incremental build to work incorrectly.
2>Done building project "build_version.vcxproj".
4>------ Build started: Project: alsoft-config, Configuration: Debug x64 ------
4>Generating ui_mainwindow.h
4>Generating moc_mainwindow.cpp
3>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
4>Building Custom Rule D:/d/github/C-Cpp/openal-soft/utils/alsoft-config/CMakeLists.txt
4>main.cpp
3>alcomplex.cpp
3>alexcpt.cpp
3>alfstream.cpp
4>mainwindow.cpp
3>almalloc.cpp
3>alstring.cpp
3>bsinc_tables.cpp
3>dynload.cpp
4>verstr.cpp
3>polyphase_resampler.cpp
4>moc_mainwindow.cpp
3>strutils.cpp
3>threads.cpp
4>Generating Code...
3>Generating Code...
3>common.vcxproj -> D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\common.lib
4>alsoft-config.vcxproj -> D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\alsoft-config.exe
5>------ Build started: Project: OpenAL, Configuration: Debug x64 ------
5>Generating hrtf_default.h
5>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
5>auxeffectslot.cpp
5>buffer.cpp
5>effect.cpp
5>error.cpp
5>event.cpp
5>extension.cpp
5>filter.cpp
5>listener.cpp
5>source.cpp
5>state.cpp
5>alc.cpp
5>alu.cpp
5>alconfig.cpp
5>ambdec.cpp
5>bformatdec.cpp
5>bs2b.cpp
5>converter.cpp
5>cpu_caps.cpp
5>autowah.cpp
5>chorus.cpp
5>Generating Code...
5>Compiling...
5>compressor.cpp
5>dedicated.cpp
5>distortion.cpp
5>echo.cpp
5>equalizer.cpp
5>fshifter.cpp
5>modulator.cpp
5>pshifter.cpp
5>reverb.cpp
5>vmorpher.cpp
5>biquad.cpp
5>nfc.cpp
5>splitter.cpp
5>fpu_ctrl.cpp
5>helpers.cpp
5>hrtf.cpp
5>D:\d\github\C-Cpp\openal-soft\alc\hrtf.cpp(974,24): warning C4834: discarding return value of function with 'nodiscard' attribute
5>D:\d\github\C-Cpp\openal-soft\alc\hrtf.cpp(1009,24): warning C4834: discarding return value of function with 'nodiscard' attribute
5>mastering.cpp
5>panning.cpp
5>D:\d\github\C-Cpp\openal-soft\alc\panning.cpp(811,14): warning C4834: discarding return value of function with 'nodiscard' attribute
5>ringbuffer.cpp
5>uhjfilter.cpp
5>Generating Code...
5>Compiling...
5>uiddefs.cpp
5>voice.cpp
5>mixer_c.cpp
5>mixer_sse.cpp
5>mixer_sse2.cpp
5>mixer_sse3.cpp
5>mixer_sse41.cpp
5>base.cpp
5>loopback.cpp
5>winmm.cpp
5>dsound.cpp
5>wasapi.cpp
5>wave.cpp
5>Generating Code...
5>null.cpp
5>null.cpp
5>   Creating library D:/d/github/C-Cpp/openal-soft/CMAKEBUILD/Debug/OpenAL32.lib and object D:/d/github/C-Cpp/openal-soft/CMAKEBUILD/Debug/OpenAL32.exp
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutGetNumDevs referenced in function "void __cdecl `anonymous namespace'::ProbePlaybackDevices(void)" (?ProbePlaybackDevices@?A0xd9d59cae@@YAXXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutGetDevCapsW referenced in function "void __cdecl `anonymous namespace'::ProbePlaybackDevices(void)" (?ProbePlaybackDevices@?A0xd9d59cae@@YAXXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutOpen referenced in function "public: virtual void __cdecl `anonymous namespace'::WinMMPlayback::open(char const *)" (?open@WinMMPlayback@?A0xd9d59cae@@UEAAXPEBD@Z)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutClose referenced in function "public: virtual __cdecl `anonymous namespace'::WinMMPlayback::~WinMMPlayback(void)" (??1WinMMPlayback@?A0xd9d59cae@@UEAA@XZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutPrepareHeader referenced in function "public: void __cdecl <lambda_795bc9ba38ce0ef4aaaa278ee0196ae8>::operator()(struct wavehdr_tag &)const " (??R<lambda_795bc9ba38ce0ef4aaaa278ee0196ae8>@@QEBAXAEAUwavehdr_tag@@@Z)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutUnprepareHeader referenced in function "public: void __cdecl <lambda_623e7d5c1dad6585d97e577013341838>::operator()(struct wavehdr_tag &)const " (??R<lambda_623e7d5c1dad6585d97e577013341838>@@QEBAXAEAUwavehdr_tag@@@Z)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutWrite referenced in function "public: int __cdecl `anonymous namespace'::WinMMPlayback::mixerProc(void)" (?mixerProc@WinMMPlayback@?A0xd9d59cae@@QEAAHXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInGetNumDevs referenced in function "void __cdecl `anonymous namespace'::ProbeCaptureDevices(void)" (?ProbeCaptureDevices@?A0xd9d59cae@@YAXXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInGetDevCapsW referenced in function "void __cdecl `anonymous namespace'::ProbeCaptureDevices(void)" (?ProbeCaptureDevices@?A0xd9d59cae@@YAXXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInOpen referenced in function "public: virtual void __cdecl `anonymous namespace'::WinMMCapture::open(char const *)" (?open@WinMMCapture@?A0xd9d59cae@@UEAAXPEBD@Z)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInClose referenced in function "public: virtual __cdecl `anonymous namespace'::WinMMCapture::~WinMMCapture(void)" (??1WinMMCapture@?A0xd9d59cae@@UEAA@XZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInPrepareHeader referenced in function "public: virtual bool __cdecl `anonymous namespace'::WinMMCapture::start(void)" (?start@WinMMCapture@?A0xd9d59cae@@UEAA_NXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInUnprepareHeader referenced in function "public: virtual void __cdecl `anonymous namespace'::WinMMCapture::stop(void)" (?stop@WinMMCapture@?A0xd9d59cae@@UEAAXXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInAddBuffer referenced in function "public: int __cdecl `anonymous namespace'::WinMMCapture::captureProc(void)" (?captureProc@WinMMCapture@?A0xd9d59cae@@QEAAHXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInStart referenced in function "public: virtual bool __cdecl `anonymous namespace'::WinMMCapture::start(void)" (?start@WinMMCapture@?A0xd9d59cae@@UEAA_NXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInStop referenced in function "public: virtual void __cdecl `anonymous namespace'::WinMMCapture::stop(void)" (?stop@WinMMCapture@?A0xd9d59cae@@UEAAXXZ)
5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveInReset referenced in function "public: virtual void __cdecl `anonymous namespace'::WinMMCapture::stop(void)" (?stop@WinMMCapture@?A0xd9d59cae@@UEAAXXZ)
5>C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x86\WinMM.Lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
5>D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\OpenAL32.dll : fatal error LNK1120: 17 unresolved externals
5>Done building project "OpenAL.vcxproj" -- FAILED.
6>------ Build started: Project: ex-common, Configuration: Debug x64 ------
7>------ Build started: Project: openal-info, Configuration: Debug x64 ------
6>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
7>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
6>alhelpers.c
7>openal-info.c
6>ex-common.vcxproj -> D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\ex-common.lib
8>------ Build started: Project: alrecord, Configuration: Debug x64 ------
9>------ Build started: Project: altonegen, Configuration: Debug x64 ------
7>openal-info.vcxproj -> D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\openal-info.exe
8>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
8>alrecord.c
8>D:\d\github\C-Cpp\openal-soft\examples\alrecord.c(57,1): warning C4204: nonstandard extension used: non-constant aggregate initializer
8>D:\d\github\C-Cpp\openal-soft\examples\alrecord.c(63,1): warning C4204: nonstandard extension used: non-constant aggregate initializer
8>alrecord.vcxproj -> D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\alrecord.exe
8>Done building project "alrecord.vcxproj".
9>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
9>altonegen.c
9>altonegen.vcxproj -> D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\altonegen.exe
10>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
10>Building Custom Rule D:/d/github/C-Cpp/openal-soft/CMakeLists.txt
========== Build: 9 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
4. Go to Debug folder.
Dll cannot be found
5. Return to the main folder to be sure. "*.Dll" is written in the search box.
Zero result.

But the following files exist in the Debug folder:
* OpenAL32.exp
* OpenAL32.lib 
* OpenAL32.pdb

**Comment by kcat** [comment]
> 4. Go to Debug folder.
> Dll cannot be found

Because it didn't build:
> 5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutGetNumDevs ...
> 5>winmm.obj : error LNK2019: unresolved external symbol __imp_waveOutOpen ...
> ... etc ...
> 5>C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x86\WinMM.Lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
> 5>D:\d\github\C-Cpp\openal-soft\CMAKEBUILD\Debug\OpenAL32.dll : fatal error LNK1120: 17 unresolved externals

I'm not sure why that's happening, though. As a temporary workaround, you should be able to change the project so OpenAL links with `x64\WinMM.Lib` instead of `x86\WinMM.Lib`. I'll need to look into what's going wrong with the cmake check that's making it find the 32-bit lib on a 64-bit target.

I would note though that your cmake command is a bit wrong. Variable definitions on the command line need to be done with the `-D` switch, like this:
`cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=ON ..`
But also, for MSVC those options don't do anything. The generated project always handles Release and Debug builds, so `CMAKE_BUILD_TYPE` is essentially ignored. And `BUILD_SHARED_LIBS` isn't an option OpenAL Soft uses (it builds shared by default, and static builds are handled a different way).

**Comment by SeanTolstoyevski** [comment]
Hi,
I didn't understand what I had to do to build the DLL.
Would you tell?

**Comment by kcat** [comment]
> I didn't understand what I had to do to build the DLL.
> Would you tell?

I don't know exactly, since I don't use MSVC. However, in the project's configuration somewhere, it seems to be linking to
`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x86\WinMM.Lib`
You need to change that `x86` to `x64`.

**Comment by SeanTolstoyevski** [comment]
I can select which platform to build in Visual Studio.
Choosing x86 or x64 does not resolve the errors.

**Comment by kcat** [comment]
> I can select which platform to build in Visual Studio.
> Choosing x86 or x64 does not resolve the errors.

What it's configured to build as is separate from what it's configured to link with. The DLL is being linked with
`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x86\WinMM.Lib`
in the project. That needs to be changed to
`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\WinMM.Lib`

**Comment by alexey-lysiuk** [comment]
Yet another victim of CMake shipped with Visual Studio...

Something named `cmake version 3.16.19112601-MSVC_2` and installed with VS2019 selects 32-bit library for 64-bit target.
The official version works fine, tested with [3.16.3](https://github.com/Kitware/CMake/releases/tag/v3.16.3).

**Comment by SeanTolstoyevski** [comment]
hi @alexey-lysiuk 

I'm using Visual Studio 2019 and I could not solve problems with cMake.
Can you tell me what components to install?

I'm using windows 10 64bit.
I spent a lot of time solving the problem, I was very tired.
Visual Studio Installer has a function to export the component list.
You will see when you press the More button.

Thank.

**Comment by alexey-lysiuk** [comment]
Please read my previous comments again. You need to use CMake from Kitware instead of a broken one provided by Microsoft. At least, this solved the problem for me.
You need to do a solution generation from scratch, so remove all files from build folder first.

**Comment by SeanTolstoyevski** [comment]
Sorry, I couldn't understand what you wrote.
I have now tried it with other cmake and it has been compiled successfully.
Thank you so much.
