### ISSUE TITLE
Sound loops playing only once

### ISSUE THREAD

**Issue by xorw** [kcat/openal-soft#42]
Looped sounds are played only once since commit b3338d25f6d4fd02935ac83d0d3f227b145307d1 
(previous commit 0f7e4993237e83ddc53a958a6369924da53c4a99 still works fine).

Tested with:
https://github.com/yquake2/yquake2.git commit 6f64efbd17f73cf3d507f13c9dc6cd39ae9f8a4d
and  git://github.com/RobertBeckebans/RBDOOM-3-BFG.git  commit 884b08010799b6009e0c7641324cecf1277a0c7

but 
https://github.com/dhewm/dhewm3.git commit 89f227b365c2086dbe8818d82324f074a8ab4792
does not have any problems (maybe because it is using reverb?)

Tested on: amd64, debian testing, openal with alsa backend.

**Comment by kcat** [comment]
Can you check to see if it's fixed in commit d80f00173f0ef623f69a9cc307457b198186ded8 now?

**Comment by xorw** [comment]
yep, problem is fixed commit d80f001, thanks :)
