### ISSUE TITLE
Writing to two different ALSA devices at the same time.

### ISSUE THREAD

**Issue by minghia** [kcat/openal-soft#423]
We have got to the point where we are trying to write different audio data to the speaker as well as the headset.  Trying to get the different audio out at the same time doesn't seem to work. From our understanding each device needs its own OpenAl context. However there appears to be a limitation that only one context may be current at any one time. Rapidly switching between contexts produces no output, though switching every 50000 samples gave output out of the desired device. Any ideas on how to get this working without delays?

**Comment by kcat** [comment]
Changing the context only changes which is "given" AL commands. e.g.
```
alcMakeContextCurrent(Context1);
alGenSources(1, &source1); // generates a source ID on Context1
alcMakeContextCurrent(Context2);
alGenSources(1, &source2); // generates a separate source ID on Context2

alSourcei(source1, AL_SAMPLE_OFFSET, 0); // undefined behavior.
// source1 is part of Context1, but commands are currently being given to Context2.
// Depending on the exact value source1 has, it may affect a different source on this
// context (e.g. source2) or generate an error.

alSourcei(source2, AL_SAMPLE_OFFSET, 0); // okay, setting source2 on Context2
alcMakeContextCurrent(Context1);
alSourcei(source1, AL_SAMPLE_OFFSET, 0); // okay, setting source1 on Context1
```

The current context doesn't affect what device is playing audio. If a context has a source and that source is playing, it will play on that context's device regardless of what context (if any) is current.

**Comment by minghia** [comment]
If you had each context in their own thread would it be possible to play the sounds simultaneously?

**Comment by kcat** [comment]
> If you had each context in their own thread would it be possible to play the sounds simultaneously?

That would allow you to independently control them without changing the current context back and forth, but it's not necessary to use a separate thread per context to have them both play sounds at the same time.

**Comment by kcat** [comment]
Closing as resolved. If you still have questions, feel free to ask.
