### ISSUE TITLE
Alsoft working as an apart audio-server with JACK

### ISSUE THREAD

**Issue by Porrumentzio** [kcat/openal-soft#428]
I'm using Manjaro MATE and JACK2 audio-server, which I launch with Cadence.

I have sound-level adjusting problems with some applications such as _Telegram_ and _Minetest_, and I see and audio-port-out instance called Alsoft when these apps send sound. Searching, I think it's OpenAL Soft.
![irudia](https://user-images.githubusercontent.com/61913683/82657564-d89b4980-9c25-11ea-86d7-f2342bb500c8.png)

The sound-level adjusting issue is because Alsoft works as an apart audio-server that won't go through PulseAudio. This way the system-volume adjusting is **not** working for Alsoft.

The solution I see is to **re-route** Alsoft to go via PulseAudio, but for this I need a way to configure it.

Is there any way to configure Alsoft? Any file or CLI or GUI client?
I've read about openal-config with qt5, but I do not find it anywhere.

Help is apreciated.

Related posts:
https://forum.manjaro.org/t/alsoft-and-jack2-sound-level-adjusting-issue/143988
https://forum.manjaro.org/t/telegram-desktop-without-sound-adjustment-while-running-jack-audio-server/137463

**Comment by Porrumentzio** [comment]
I have found alsoftrc.sample on /usr/share/openal , but I still don't know what to do.

**Comment by kcat** [comment]
By default, OpenAL Soft will use JACK directly if it's running, since that will provide the lowest latency and reduce the overall workload. If you instead want it to use PulseAudio anyway even when JACK is running, create/edit the file `~/.config/alsoft.conf` and add the lines:
```
[general]
drivers="-jack,"
```
(note that the comma is important).

The `alsoft-config` GUI utility is part of OpenAL Soft, but your distro may have it as a separate package.

**Comment by Porrumentzio** [comment]
Hi! I managed to open the GUI utility and I disabled there JACK. No it works perfectly! A lot of thanks!

**Comment by Porrumentzio** [comment]
Type on terminal
$ `alsoft-config`
And that will open a GUI utility. There go to _Backends > General_. There on _Disabled Backends_, right click and choose JACK, in order to do not work as a JACK instance.

![irudia](https://user-images.githubusercontent.com/61913683/82728106-9722a100-9cee-11ea-9cb4-865ec0350518.png)

**Comment by Porrumentzio** [comment]
Type on terminal
$ `alsoft-config`
And that will open a GUI utility. There go to _Backends > General_. There on _Disabled Backends_, right click and choose JACK, in order to do not work as a JACK instance.

![irudia](https://user-images.githubusercontent.com/61913683/82728106-9722a100-9cee-11ea-9cb4-865ec0350518.png)
