### ISSUE TITLE
Can't build on MSVC 2017 due to span casting error

### ISSUE THREAD

**Issue by mxhpns** [kcat/openal-soft#431]
How to reproduce:
git clone --depth 1 https://github.com/kcat/openal-soft

Open cmake-gui.exe:
1. Where is the source code: openal-soft
2. Where to build the binaries: openal-soft\build
3. Configure
4. Choose VS2017 and Win32
5. Finish
6. Uncheck ALSOFT_UTILS
7. Configure
8. Generate

Open "openal-soft/build/OpenAL.sln" in Visual Studio:
1. Change configuration to "Release"
2. Change configuration to "Win32"
3. Project "OpenAL" -> Right Mouse Click -> Build.

Result:
```
Error C2664 "void BandSplitterR<double>::applyAllpass(const al::span<Real,4294967295>) const": cannot cast argument 1 from "const al::span<double,512>" to "const al::span<Real,4294967295>"	OpenAL	D:\...\openal-soft\alc\hrtf.cpp line number: 394
```

The same error for line number: 419 in the same file.

I analyzed the code and noticed, that the reason is that BandSplitterR uses argument of type ```al::span<Real>``` in ```applyAllpass()``` method:
```
template<typename Real>
void BandSplitterR<Real>::applyAllpass(const al::span<Real> samples) const;
```
, and I noticed in file common/alspan.h
```
template<typename T, size_t E=static_cast<size_t>(-1)>
class span;
```
, but in file "hrtf.cpp" tempir is initialized as
```
const al::span<double,HRIR_LENGTH*4> tempir{tmpflt[2]};
```
, where
```HRIR_LENGTH*4```
evaluates to 512.

So, how to solve the problem with building the project.

Thanks

**Comment by kcat** [comment]
That's odd, it should build fine. It does on AppVeyor, which uses VS2017 to build both 32-bit and 64-bit: https://ci.appveyor.com/project/ChrisRobinson/openal-soft

That particular initialization should use this constructor:
```
template<typename U, size_t N, REQUIRES((!std::is_same<element_type,U>::value || extent != N) && std::is_convertible<U(*)[],element_type(*)[]>::value)>
constexpr span(const span<U,N> &span_) noexcept : span{al::data(span_), al::size(span_)} { }
```
In this case, `Real=double`, `U=double`, and `N=512`, while `extent=size_t(-1)`. Subsequently, `size_t(-1) != 512`, and `double(*)[]` is convertible to `double(*)[]`, so it should match, initializing the dynamic-extent span with the data in `tempir.data()` and a size of `tempir.size()`, i.e. `512`.

**Comment by mxhpns** [comment]
Thank you for the answer and explanation. Something strange with my compiler. I also checked the version of standard my msvc uses, ```/std:c++14```, also tried to change it to ```/std:c++latest```, but the same error appeared

**Comment by kcat** [comment]
As a workaround, you might be able to use `/std:c++latest` and change the line
```
if /*constexpr*/(!DualBand)
```
to
```
if constexpr(!DualBand)
```
Though it may be worth finding out what's different about your version of VS2017 compared to AppVeyor's that causes this error. Is there a way to check if there's any bug fixes or updates for VS2017?

**Comment by kcat** [comment]
This particular error shouldn't happen anymore, since the call was removed. However, a similar error might show up elsewhere. Can you check?

**Comment by kcat** [comment]
That particular line is gone, VS2017 on AppVeyor is working, and there haven't been any further problems mentioned, so there's no point leaving this open. Feel free to open a new issue if you run into another problem.
