### ISSUE TITLE
Question: How to prepare buffer for MSADPCM-4bit .wav to OpenAL?

### ISSUE THREAD

**Issue by halx99** [kcat/openal-soft#432]
Hello, I have a .wav file witch format is ADPCM, bit depth is 4 bits, I can't find any ext enum to specific format when call ```alBufferData``` from alext.h, how can I play that file with openal?

**Comment by kcat** [comment]
If it's MSADPCM, the `AL_SOFT_MSADPCM` extension provides the formats `AL_FORMAT_MONO_MSADPCM_SOFT` and `AL_FORMAT_STEREO_MSADPCM_SOFT` (in `alext.h`). However, you may also need the `AL_SOFT_block_alignment` extension since ADPCM files may use different block sizes (by default, 64 sample frames per block are assumed for MSADPCM).

The .wav file header contains the block size in bytes, which you can easily convert to sample frames, so you can then load it like this:
```
int samples_per_block = (bytes_per_block/num_channels - 7)*2 + 2;
alBufferi(buffer, AL_UNPACK_BLOCK_ALIGNMENT_SOFT, samples_per_block);
alBufferData(buffer, AL_FORMAT_MONO_MSADPCM_SOFT, data, data_size_in_bytes, samplerate);
```
Replace `MONO` with `STEREO` as needed.

**Comment by halx99** [comment]
Thanks for your help, I will try it later

**Comment by halx99** [comment]
[openal-soft-test.zip](https://github.com/kcat/openal-soft/files/4716962/openal-soft-test.zip)

Hi, dear kcat
I just tried as your said, but doesn't work, I wrote a simple play ```alplay-wav```, the file structure:
- examples:
  - alplay-wav.cpp: just same as alplay.c, but use the simple wav decoder
  - AudioDecoderWav.h, AudioDecoderWav.cpp: the simple wav decoder  wrote by me
- CMakeLists.txt: just replace the original of openal-soft, will generate a project ```alplay-wav```
- sounds: 
  - ok.wav: can be play by alplay-wav well.
  - not-ok.wav: can't be play which format is MSADPCM.
Looking forward your help, thanks.

**Comment by kcat** [comment]
The dataSize calculation isn't correct for ADPCM. It's not just 4 bits per sample like `_bitsPerFrame` would suggest, but there are a few extra bytes to start each block that the subsequent samples build off of. It would be better to use the size of the data chunk to get the total size in bytes, making sure it's a multiple of the block size in bytes (it generally should be, but who knows what a random file may have).

`AudioDecoderWav::read` has the same issue, where it does `(_bitsPerFrame * framesToRead) >> 3` and `(bytesRead << 3) / _bitsPerFrame` to convert back and forth. The number of `framesToRead` needs to be converted to the number of blocks, which is then converted to the number of bytes (i.e. `framesToRead / samplesPerBlock * bytesPerBlock`). Then `bytesRead` needs to be converted to the number of blocks then the number of samples (i.e. `bytesRead / bytesPerBlock * samplesPerBlock`).

**Comment by halx99** [comment]
Thanks, I will check later.

**Comment by halx99** [comment]
Thanks, I have tried, and works fine

**Comment by halx99** [comment]
Another question, does IMA_ADPCM should do same same process with MS_ADPCM?

**Comment by halx99** [comment]
Got it at here: https://github.com/openalext/openalext/wiki/AL_SOFT_block_alignment, no need to reply me.
