### ISSUE TITLE
AL_EAXREVERB_GAIN vs. AL_LOWPASS_GAIN on Reverb Path

### ISSUE THREAD

**Issue by kunal-vzw** [kcat/openal-soft#436]
Let's say I have an `AL_EFFECT_EAXREVERB` effect loaded onto an aux effect slot, and a source feeding this aux effect slot. Is there a difference in the final output between the following 2 scenarios?

(1) Setting the `AL_EAXREVERB_GAIN` to `0.5f`
vs.
(2) Setting the `AL_LOWPASS_GAIN` on the source aux send filter to `0.5f`

I understand that (1) sets the reverb output gain to 0.5, while (2) sets the gain of the source feeding the reverb path to 0.5, but as I'm not familiar with the implementation of `AL_EAXREVERB` under the hood, I'm not sure if the two scenarios above are mathematically equivalent.

**Comment by kcat** [comment]
The reverb includes delays and feedback loops. Setting AL_LOWPASS_GAIN to change the input will mean the samples currently being delayed or running through the feedback loops will remain as they were, with the volume change occurring later as those new samples make their way through processing. In contrast, AL_EAXREVERB_GAIN will change the output of the effect right away, not waiting for the samples currently being processed.

**Comment by kunal-vzw** [comment]
Gotcha. If I set AL_LOWPASS_GAIN _prior_ to calling play on the source (so there are no samples being currently delayed or running through feedback loops), will both scenarios then produce identical output?

**Comment by kcat** [comment]
They should effectively be the same then, yes.

**Comment by kunal-vzw** [comment]
Thanks! Before closing out this issue, I had a quick question (unrelated) -- what is the behavior when trying to set a value on a parameter that is out of range? Does the closest allowable value get set, or is the set simply skipped?

For egs: EAX Reverb Density takes in a max value of 1.0. If I pass in 1.5 for egs, I see an alSetError. But is 1.0 set in this case, or is the call simply ignored?

**Comment by kcat** [comment]
The call is ignored. Unless otherwise specified, any time a call generates an error nothing gets changed.
