### ISSUE TITLE
Mingw64-gcc - example\alplay.c compile error

### ISSUE THREAD

**Issue by SeanTolstoyevski** [kcat/openal-soft#437]
Hi all,
I'm trying to understand OpenAL.
I'm trying to compile the file alplay.c in the examples folder to use OpenAL.
I am using Windows 10 64bit.
My DLLs are 64bit.
Mingw64 is installed.

The requirements of OpenAL and sndfile are in the "inc" folder.
So "AL", "common" folders and "sndfile.h", and "sndfile.hh".

DLL files and DLL's .lib, .def and .a files are also located in the "lib" folder.
The name of the soft_oal.dll file was changed to OpenAL32.

I get an error in compiling.

Can you help?

### main folder:
* inc - include folder
* lib - DLL and dll require files folder
* alplay.c - I want compile file

### inc folder - include folder
* AL - folder
* sndfile.h
* sndfile.hh 
* common - folder - from examples\common

### lib folder content:
* pkgconfig 
* libsndfile-1.def 
* libsndfile-1.dll 
* libsndfile-1.lib 
* OpenAL32.def 
* OpenAL32.dll 
* OpenAL32.dll.a 
* OpenAL32.lib 

```
D:\op>gcc -I"D:\op\inc" -L"d:\op\lib" -lsndfile-1 -lOpenAL32 alplay.c
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x1dc): undefined reference to `__imp_alGenBuffers'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x1fc): undefined reference to `__imp_alBufferData'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x21d): undefined reference to `__imp_alGetError'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x234): undefined reference to `__imp_alGetString'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x26c): undefined reference to `__imp_alIsBuffer'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x285): undefined reference to `__imp_alDeleteBuffers'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x313): undefined reference to `InitAL'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x33f): undefined reference to `CloseAL'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x363): undefined reference to `__imp_alGenSources'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x37e): undefined reference to `__imp_alSourcei'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x387): undefined reference to `__imp_alGetError'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x3b2): undefined reference to `__imp_alSourcePlay'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x3be): undefined reference to `al_nssleep'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x3d6): undefined reference to `__imp_alGetSourcei'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x3f0): undefined reference to `__imp_alGetSourcef'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x434): undefined reference to `__imp_alGetError'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x465): undefined reference to `__imp_alDeleteSources'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x47a): undefined reference to `__imp_alDeleteBuffers'
C:\Users\DAWNLI~1\AppData\Local\Temp\ccijkrX9.o:alplay.c:(.text+0x481): undefined reference to `CloseAL'
collect2.exe: error: ld returned 1 exit status
```

**Comment by kcat** [comment]
It should be built as part of the project, it's not meant to be built stand-alone like that.

The undefined references to `__imp_` functions are because the order of libraries are important. `-lOpenAL32` needs to come after the source files (and any other libs) that use OpenAL functions.

Though it will still leave the errors about `InitAL`, `CloseAL`, and `al_nssleep`. They're from the `libex-common.a` static library that's built before the examples in the project. Is there a reason you need to compile it manually?

**Comment by SeanTolstoyevski** [comment]
I wanted to compile it with VS2019.
But VS2019 seems too complicated for me.


How can I compile this file with gcc?

I can write a batch script.

**Comment by SeanTolstoyevski** [comment]
Hi @kcat,

I understood that I writed gcc parameters wrong. The code was compiled successfully, but it still doesn't play .wav files.
I compiled the common file with gcc with the **-shared** parameter.
I also define the common.dll to linker.
There was no error during compilation anyway.

The file "a.exe" has occurred.
`a.exe examplesound.wav`
No sound is played.

**Comment by McSinyx** [comment]
@SeanTolstoyevski, I think you'd need libsndfile to decode WAVs.  If you have any experience installing and linking it on Windows, please share it with me because I need it for a project of mine but I don't have Windows running.

**Comment by SeanTolstoyevski** [comment]
No sndfile is required to process .Wav files.
I know wav codec as content of Windows.

And a.exe does not tell me that sndfile is missing.
If a DLL is missing, the .exe shows it as a error message.


The fact that a very popular library is so challenging makes me think a lot.
No one is asking these topics. I can't find content to fix my problems on Google.
On the other hand, the documents are outdated. And there is no document on how we should install enviromment.

**Comment by kcat** [comment]
Have you built and installed the main library and its examples (with cmake) yet? Can you show exactly what commands you ran and what the output of those commands are?

**Comment by SeanTolstoyevski** [comment]
I solved all the problems.
Many of these issues are related to the hierarchy of Windows.

**Comment by SeanTolstoyevski** [comment]
Hello again @kcat,

of topic,
I have a few questions and requests can you answer them?

1. I'm writing a game that should work on Mac and Windows.
In this case, I have to package wav files for Windows.
However, I can't test other Oss right now because I don't have a Mac right now.
 * q1: Will wav files that play successfully on Windows play on Mac?
 * q2: Is wav support in OpenAL built-in or do we need to convert a separate format for each OS?
2. No matter how little I set the parameters of wav files, the size of the files is large. I still have to make a design thinking that not everyone can reach a powerful system.
This also causes buffers to take up a lot of space on the ram.
 * q1: Can you add an example to OpenAL's examples folder that offers .ogg support? ogg files are smaller.

**Comment by kcat** [comment]
> * q1: Will wav files that play successfully on Windows play on Mac?
> * q2: Is wav support in OpenAL built-in or do we need to convert a separate format for each OS?

OpenAL doesn't concern itself with file formats, it just takes the raw PCM samples however you get them. It's up to you to load wav files, either by reading the file directly or using a library like libsndfile or SDL_sound (those libraries support multiple OSs, and your code can too as long as you don't use OS-specific functions).

> * q1: Can you add an example to OpenAL's examples folder that offers .ogg support? ogg files are smaller.

OpenAL Soft's examples already do, using libsndfile which supports ogg, flac, wav, and some other formats.

**Comment by SeanTolstoyevski** [comment]
thanks @kcat
