### ISSUE TITLE
How to handle iOS audio interruptions correctly ?

### ISSUE THREAD

**Issue by fbirot** [kcat/openal-soft#440]
Hello,

I've read in the book "Beginning iPhone Games Development" that handling audio interruptions with OpenAL on iOS should be done like this:
1/ When an interruption starts, suspend the current context and set the current context pointer to NULL using alcSuspendContext and alcMakeContextCurrent functions
2/ When the interruption ends, reactivate the AVAudioSession, set the current context to the one used before, using alcMakeContextCurrent and call alcProcessContext

See here the explanation in the book: [https://books.google.fr/books?id=xtrEvAdSOWEC&pg=PA386](https://books.google.fr/books?id=xtrEvAdSOWEC&pg=PA386)

Yet, this doesn't work with OpenAL Soft: the CoreAudioPlayback::MixerProc callback is never called again after that the audio interruption finishes. I looked a bit at the code of alcSuspendContext, and it seemed to me that it only defers parameter updates, and can thus be used to group a certain number of parameter updates together, so that those parameters are changed at the same time. 

I think that the coreaudio backend should actually be stopped at the beginning of the interruption and started again when it ends.

I've thus tried to call alcDevicePauseSOFT when the interruption starts and call alcDeviceResumeSOFT when the interruption ends. And this seems to work correctly.

But is the second method the good way to do it ? Is it normal that alcSuspendContext doesn't work for this, like explained in this book ? Or should I both suspend the context and stop audio unit with alcDevicePauseSOFT ?

**Comment by fbirot** [comment]
One addition: when I call alcDevicePauseSOFT when an audio interruption starts, I never get a notified that the interruptions has ended. (It seems that we don't receive audio interruptions notifications anymore if AudiUnit is stopped).

So in order to re-activate AudioUnit, I call alcDeviceResumeSOFT in applicationDidBecomeActive (which is called when the app becomes active again, and so when the audio interruption finishes)

**Comment by kcat** [comment]
The proper way to pause/resume playback with OpenAL Soft is `alcDevicePauseSOFT` and `alcDeviceResumeSOFT`. The spec doesn't say `alcMakeContextCurrent(NULL)` should stop playback (and it would break multi-device/context setups if non-current contexts didn't continue to play), though some implementations apparently do that.

As for not getting notified when an interruption ends, that is unfortunately out of my league. I don't know what iOS expects apps to do when an interruption starts and stops. To me, at least, it makes sense to stop the AudioUnit when it shouldn't being trying to play anything, and from what you say, the callback is stopped and doesn't automatically restart when the interruption ends anyway. I couldn't guess why it doesn't explicitly notify when an interruption is over and the AudioUnit is stopped; surely even non-audio apps would want to know that kind of thing?

**Comment by fbirot** [comment]
Thanks a lot your for your answer. It is more clear to me now.
I'll try to find out why I get this weird behavior (no audio interruption end notifications when AudioUnit is stopped). I'll post what I find here

**Comment by fbirot** [comment]
My mistake .. The problem of the AVAudioSessionInterruptionTypeEnded notification not being sent was because of the fact that I re-activated AudioUnit inside applicationDidBecomeActive. I had forgotten to remove it when doing my tests. When an audio interruptions ended, the applicationDidBecomeActive function was called before that the notification was sent. And then because the audio was already reactivated, iOS didn't send the AVAudioSessionInterruptionTypeEnded notification anymore.
Using alcDevicePauseSOFT and alcDeviceResumeSOFT works perfectly.
Thank you !
