### ISSUE TITLE
Sofa-info returns some azimuths as 0.

### ISSUE THREAD

**Issue by PenguinDOOM** [kcat/openal-soft#443]
I don't know when it started because I haven't been following it recently, but it returns 0.
It used to return the correct value.
The correct value can be found in SCUT_KEMAR.def.

<details>
<summary>SCUT_KEMAR_radius_all.sofa</summary>
<br>
<pre>
Info.Author: Bosun Xie@
Info.ListenerShortName: KEMAR
Info.DatabaseName: SCUT
Info.Title: HRTF
Info.DateModified: 2014-03-20 16:43:45
Info.DateCreated: 2008-09-23 23:10:34
Info.Origin:
Info.RoomType: free field
Info.References: Bosun Xie, 2013, "Head-Related Transfer Function and Virtual Auditory Display", J Ross Publishing Inc., Plantation, FL, USA
Info.Organization: South China University of Technology, Guangzhou, China
Info.License: CC 3.0 BY-SA-NC
Info.History: Converted from the SCUT format
Info.DataType: FIR
Info.Comment: Converted from the original file format by Piotr Majdak (piotr@majdak.com), Acoustics Research Institute, OeAW
Info.AuthorContact: phbsxie@scut.edu.cn
Info.ApplicationVersion: 0.1
Info.ApplicationName: ARI converter
Info.APIVersion: 0.4.0
Info.APIName: ARI SOFA API for Matlab/Octave
Info.SOFAConventionsVersion: 0.4
Info.SOFAConventions: SimpleFreeFieldHRIR
Info.Version: 0.6
Info.Conventions: SOFA
Measurements: 4930
Receivers: 2
Emitters: 1
Samples: 512
SampleRate.DIMENSION_LIST: I
SampleRate.Units: hertz
SampleRate[0]: 44100.000000
DataDelay.DIMENSION_LIST: I,R
DataDelay[0]: 0.000000
DataDelay[1]: 0.000000

Compatible Layout:

distance = 0.200, 0.250, 0.300, 0.400, 0.500, 0.600, 0.700, 0.800, 0.900, 1.000
azimuths = 0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1;
           0, 0, 0, 0, 72, 72, 72, 72, 72, 72, 36, 24, 1
</pre>
</details>

**Comment by PenguinDOOM** [comment]
I found the cause of the commit.
4867f93

**Comment by kcat** [comment]
Should be fixed with commit 8ea7d5183b3e28a44e42a68441f67212803f0404.
