### ISSUE TITLE
MingW64 macro pollute global namespace of OpenAL

### ISSUE THREAD

**Issue by LemonHX** [kcat/openal-soft#445]
```cpp
#define strncasecmp _strnicmp
```
Exist in mingw 64 string.h
and that cause al::strncasecmp compiles to al::_strnicmp which cause an error in linking
a simple solution is just adding another definition of that function

such as
```cpp
namespace al{
 // ...
 #ifdef __MINGW64__
 int _strnicmp(const char *str0, const char *str1, std::size_t len) noexcept;
 #endif
}
```

**Comment by iSLC** [comment]
Or you could check for existence of `strncasecmp` as a macro. Since there are likely mingw distributions that don't included it. Assuming all mingw environments have that could lead to liner errors as well.

**Comment by LemonHX** [comment]
( the problem is not exist is the C macro makes the compiler compiles to another name

**Comment by LemonHX** [comment]
```cpp
#undef _strnicmp
``` 
also causes errors, the only way prob is just warp function names with macro

**Comment by LemonHX** [comment]
#446 pulled

**Comment by kcat** [comment]
It looks to me that the simplest option would be to include `string.h` (or `cstring`) in `alstring.h`. That way all instances of `al::strncasecmp` get replaced with `al::_strnicmp` (including the definition, declaration, and calls) if the header sets the macro, ensuring the name stays consistent. I just did this with commit 31791c9997d06a3a315d2b936515f643430cd5e9, can you check to see if it works for you?

**Comment by LemonHX** [comment]
K thanks for your reply, Checking now

**Comment by enginmanap** [comment]
Hi,

I had the exact same issue. adding  `#include <cstring>` to alstring.h fixes the issue. 

Is it possible such change can be included in the upstream, would you consider it a hack?

**Comment by kcat** [comment]
> Is it possible such change can be included in the upstream, would you consider it a hack?

It's already included with commit 31791c9997d06a3a315d2b936515f643430cd5e9.

**Comment by kcat** [comment]
Closing as fixed.

**Comment by encelo** [comment]
I can see this issue back with OpenAL-soft 1.22.0 on MSYS2 in debug mode, on both GCC and Clang.
