### ISSUE TITLE
Compiler Problems

### ISSUE THREAD

**Issue by BlubBlab** [kcat/openal-soft#45]
I found something strange when I tried to built the code from here with my : 
Microsoft Visual Studio Community 2015
Version 14.0.25421.03 Update 3

It protest about 
In common/thread.c line line 416, 417
` void *ptr = altss_get(TlsDestructors.array[i].key);
altss_dtor_t callback = (altss_dtor_t)TlsDestructors.array[i].value;`

with  struct "UIntMap" has no field "array", so far I can tell the compiler is right:
in common/uintmap.h 11,20

`typedef struct UIntMap {
    ALuint *keys;
    /* Shares memory with keys. */
    ALvoid **values;

    ALsizei size;
    ALsizei capacity;
    ALsizei limit;
    RWLock lock;
} UIntMap;`

I'm not sure what happened here first I thought somebody meant array as some language syntax I don't know but it doesn't match up (spelling) and. I don't see any macro around it either so there must be something wrong

**Comment by kcat** [comment]
Should be fixed now with commit fe2fb8104774580b074429055083be3b125be95d. Can you double-check?

**Comment by BlubBlab** [comment]
I used the same solution strangely my app protested about a NULL Mutex but it is gone so this should work

**Comment by kcat** [comment]
If you can replicate that null mutex and get information about it, feel free to open a new issue.
