### ISSUE TITLE
Linker error when using Xcode to build dylib

### ISSUE THREAD

**Issue by Ravbug** [kcat/openal-soft#451]
I used the Xcode cmake generator, which created an Xcode project named OpenAL.xcodeproj, and I added it as a sub-project in my main Xcode project. 

When I use the ALL BUILD target in OpenAL.xcodeproj, the library builds successfully. However, when I try to use Xcode to link the dylib in my main project, the link fails. 
<img width="388" alt="Screen Shot 2020-07-14 at 9 55 41 AM" src="https://user-images.githubusercontent.com/22283943/87454690-2b0b3d80-c5b9-11ea-9ec0-3f2fcd7fd71c.png">

<img width="1055" alt="Screen Shot 2020-07-14 at 9 58 20 AM" src="https://user-images.githubusercontent.com/22283943/87454746-3cece080-c5b9-11ea-9526-a7b37607fa6a.png">

Output as text: 
```bash
Ld /Users/main/Library/Developer/Xcode/DerivedData/RavEngine_Mac-bvozqrtakaizvzfnarxbkcarbbbt/Build/Products/Debug/libopenal.1.20.1.dylib normal x86_64 (in target 'OpenAL' from project 'OpenAL')
    cd /Users/main/Documents/RavEngine/openal-soft
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.15 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/main/Library/Developer/Xcode/DerivedData/RavEngine_Mac-bvozqrtakaizvzfnarxbkcarbbbt/Build/Products/Debug -F/Users/main/Library/Developer/Xcode/DerivedData/RavEngine_Mac-bvozqrtakaizvzfnarxbkcarbbbt/Build/Products/Debug -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks -filelist /Users/main/Library/Developer/Xcode/DerivedData/RavEngine_Mac-bvozqrtakaizvzfnarxbkcarbbbt/Build/Intermediates.noindex/OpenAL.build/Debug/OpenAL.build/Objects-normal/x86_64/openal.1.20.1.LinkFileList -install_name /libopenal.1.20.1.dylib -Xlinker -object_path_lto -Xlinker /Users/main/Library/Developer/Xcode/DerivedData/RavEngine_Mac-bvozqrtakaizvzfnarxbkcarbbbt/Build/Intermediates.noindex/OpenAL.build/Debug/OpenAL.build/Objects-normal/x86_64/openal.1.20.1_lto.o -Xlinker -no_deduplicate -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/libopenal.1.dylib /Users/main/Documents/RavEngine/openal-soft/Debug/libcommon.a -pthread -framework AudioToolbox -framework CoreAudio -framework AudioUnit -framework ApplicationServices -ldl -lm -compatibility_version 1.0.0 -current_version 1.20.1 -Xlinker -dependency_info -Xlinker /Users/main/Library/Developer/Xcode/DerivedData/RavEngine_Mac-bvozqrtakaizvzfnarxbkcarbbbt/Build/Intermediates.noindex/OpenAL.build/Debug/OpenAL.build/Objects-normal/x86_64/openal.1.20.1_dependency_info.dat -o /Users/main/Library/Developer/Xcode/DerivedData/RavEngine_Mac-bvozqrtakaizvzfnarxbkcarbbbt/Build/Products/Debug/libopenal.1.20.1.dylib

clang: error: no such file or directory: '/Users/main/Documents/RavEngine/openal-soft/Debug/libcommon.a'
Command Ld failed with a nonzero exit code
```
How can I resolve this problem?

**Comment by kcat** [comment]
I don't know how exactly Xcode works in this regard, but when building the libopenal target under your own project, it needs to include the targets that libopenal needs, such as libcommon (a static lib with common code that multiple OpenAL Soft project targets use). By the looks of it, your Xcode project doesn't include the libcommon target that libopenal needs.

**Comment by Ravbug** [comment]
I had tried that too, but I got the same result.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/22283943/87503578-77866580-c619-11ea-94a3-3b218bc01acf.png">
`clang: error: no such file or directory: '/Users/main/Documents/RavEngine/openal-soft/Debug/libcommon.a'`

It appears to be building everything into the DerivedData directory like normal, but expecting the built libcommon.a to be in my project directory (`openal-soft/Debug/libcommon.a`), perhaps Cmake is responsible? 
Using this method in Xcode to link other libraries that use Cmake like PhysX works correctly.

**Comment by kcat** [comment]
`libcommon.a` should be linked to `libopenal.dylib`, rather than your binary.

If your project uses CMake too, you should use `add_subdirectory(...)` to include OpenAL Soft as a sub-project in your main project (you can set the appropriate options to disable building the utilities and examples and such as desired), and you then link your target to `OpenAL`. I would presume generating an Xcode project for your project would then properly include libopenal.dylib and its dependency hierarchy.

Otherwise, if your project doesn't use CMake, I'm not really sure if or how an Xcode project can include another Xcode project and link to its targets. I'd be surprised if they can't be combined in some way, though I don't use Xcode (or have a Mac) to know how.
