### ISSUE TITLE
Github Wiki "Programmers Guide" - The wiki page took too long to render. Please edit this wiki page’s content so it renders faster.

### ISSUE THREAD

**Issue by matts-dev** [kcat/openal-soft#459]
I can't read the programmer's guide. :(

**Comment by McSinyx** [comment]
Apparently it is close to 4000 lines (I'm pretty sure that I've read it just a few months ago though, so it's GitHub that did something that now it's no longer renderable).  I propose to move the entire guide to reST/Sphinx and (optionally) use Read the Docs for hosting, which has always been a pleasure to setup [for](https://mcsinyx.github.io/palace/html/) [me](https://brutalmaze.rtfd.io/).

**Comment by matts-dev** [comment]
This is now rendering for me.
https://github.com/kcat/openal-soft/wiki/Programmer%27s-Guide

Something resolved it. Perhaps change in the way github renders.
Closing issue.
