### ISSUE TITLE
AlHrtf Android bug -DHAVE_NEON=1 -mfpu=neon -mfloat-abi=softfp

### ISSUE THREAD

**Issue by fatalfeel** [kcat/openal-soft#47]
APP_DEBUG := $(strip $(NDK_DEBUG))
ifeq ($(APP_DEBUG),0)
	LOCAL_CFLAGS := -DAL_ALEXT_PROTOTYPES -DAL_BUILD_LIBRARY -DANDROID_NDK -DBUILD_ANDROID -DGC_BUILD_ANDROID -DNDEBUG -DHAVE_NEON=1 -mfpu=neon -mfloat-abi=softfp
	LOCAL_CPPFLAGS := -DGC_BUILD_C -DANDROID_NDK -DBUILD_ANDROID -DNDEBUG -DHAVE_NEON=1 -mfpu=neon -mfloat-abi=softfp
else
	LOCAL_CFLAGS := -DAL_ALEXT_PROTOTYPES -DAL_BUILD_LIBRARY -DANDROID_NDK -DBUILD_ANDROID -DGC_BUILD_ANDROID -D_DEBUG -DHAVE_NEON=1 -mfpu=neon -mfloat-abi=softfp
	LOCAL_CPPFLAGS := -DGC_BUILD_C -DANDROID_NDK -DBUILD_ANDROID -D_DEBUG -DHAVE_NEON=1 -mfpu=neon -mfloat-abi=softfp
endif

its my android define

and build with mixer_neon.c ////////////////

the the sound will produce some noise~~~~

after remove -DHAVE_NEON=1 -mfpu=neon -mfloat-abi=softfp   and  mixer_neon.c
the sound perfect 

mixer_neon.c have some problem but I do not know where

here is my example hrtf and i remove mixer_neon.c. if test bug then add it and define
 -DHAVE_NEON=1 -mfpu=neon -mfloat-abi=softfp
http://www.mediafire.com/download/4v01owbdb90j242/openal-soft-android.zip

**Comment by kcat** [comment]
Unfortunately I don't know what those variables you set do. CMake handles setting up the necessary defines for building on Android, and will include ```mixer_neon.c``` as needed. What kind of noise are you experiencing with it?

**Comment by fatalfeel** [comment]
Like sound bi bi bo bo

**Comment by kcat** [comment]
Can you record an example?

**Comment by fatalfeel** [comment]
in android~~~~hard to record~~~~i will try ~~~

**Comment by fatalfeel** [comment]
today i try this Eax effect is ok
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
396000
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
996000
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
396000 792000 996000 
echo 996000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

//////////
another question, the opensl_callback will do many many times and go to hrtf.c work
if i want to add hrtf buffer do less times how do i do, need ur help thanks

**Comment by fatalfeel** [comment]
another question, the opensl_callback will do many many times and go to hrtf.c work
if i want to add hrtf process buffer and do callback less times how do i do? 

need ur help thanks

**Comment by kcat** [comment]
The only way to have ```opensl_callback``` called less times is to use a larger buffer size, though it will then do more samples on each call. It's going to do the same amount of work overall, since it needs to mix 44100 sample frames per second regardless.

What do you mean by "add hrtf process buffer"?

**Comment by fatalfeel** [comment]
yes add larger buffer size for every opensl_callback, not only for hrtf process buffer
also fro eax reverb.c. could you tell me how to add hrtf and reverb process buffer. many thanks

**Comment by kcat** [comment]
A larger buffer size isn't going to change the amount of processing that needs to be done (it's going to do 44100 samples every second, regardless if it's in 1024 sample chunks or 2048 sample chunks), and it's even possible it'll become worse since the callback thread is going to have to stay awake longer on each iteration. It can cause issues with the kernel's thread scheduler, which prefers time-sensitive things like this to act quickly then sleep as soon as possible. It'll also increase latency. But if you really want to, you can try to edit ```~/.alsoftrc``` and add:
```
[general]
period_size=1280  # or 1536
```

And I'm sorry, but I still don't know what you mean by "add hrtf and reverb process buffer".

**Comment by fatalfeel** [comment]
many thanks
in android opensl_callback to process reverb or hrtf will cause sound buffer lag, android arm cpu
not fast enough, so i wan to add  each call process buffer. 
period_size=1280 is default right?

**Comment by kcat** [comment]
The default is ```period_size=1024```. Increasing the buffer length will make the buffer lag worse since that will increase the time between what OpenAL Soft is processing and what's being played by the speaker. To improve the lag you actually want a smaller size, like 768 or 512, since that will have less time between what OpenAL Soft is processing and what you hear played.

**Comment by fatalfeel** [comment]
ok i wll try thanks  a lot~~~

**Comment by fatalfeel** [comment]
not modify android yet, code in android http://www.mediafire.com/download/4v01owbdb90j242/openal-soft-android.zip

**Comment by sriharshachilakapati** [comment]
Here is the [config.h](https://github.com/sriharshachilakapati/AndroidOpenAL/blob/master/android-openal/src/main/jni/include/config.h) that I use. The pro for this is that it uses preprocessor conditionals to specify values based on architecture, and thus it takes advantage of the NEON or SSE extensions where enabled.

And the [Android.mk](https://github.com/sriharshachilakapati/AndroidOpenAL/blob/master/android-openal/src/main/jni/Android.mk) file is the make file. It includes the mixer_neon.c or mixer_sse*.c files only when the sources should be compiled. This should help maybe.

Hope this helps.

**Comment by fatalfeel** [comment]
in android only NEON can use.. but still slow. thanks for help

**Comment by fatalfeel** [comment]
report -->
in target android 6.0 i.mx6 arm dual 1G cortex-a9
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
396000

cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
996000

cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
396000 792000 996000 

i try three cpu freq
echo 396000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 792000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 996000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

in alc.c 
device->UpdateSize = 128;
device->UpdateSize = 256;
device->UpdateSize = 512;
device->UpdateSize = 1024;

follows are work
echo 792000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
device->UpdateSize = 512;
and 
echo 396000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
device->UpdateSize = 128;

thanks  kcat  and u are my sunshine
https://www.youtube.com/watch?v=BPjXOFW8HrQ

**Comment by fatalfeel** [comment]
this case i dont use neon on imx6 arm dual but after tune NumUpdates and UpdateSize 
works so good~~~~
And thanks Kcat a good kind person, who helps me a lot~~~~

**Comment by fatalfeel** [comment]
today i try in mixer_inc.c
//#define MAX_UPDATE_SAMPLES 128
#define MAX_UPDATE_SAMPLES 128*4

this works perfect too
