### ISSUE TITLE
alcOpenDevice() with GUID string, and the DSound backend

### ISSUE THREAD

**Issue by pachuco** [kcat/openal-soft#471]
While tinkering with DSOAL and porting it from MMDevice* to DSound, I noticed that SoftOAL will succeed on former, but fail on latter when provided a GUID string.

AL lib: (WW) Failed to open playback device: Device name "{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}" not found.

Testing was done between win XP and 7.

**Comment by kcat** [comment]
Should work now with commit a4bfba4cb56686860c3edd9d910703b1c0caf209.
