### ISSUE TITLE
Soft OAL errors on unloading

### ISSUE THREAD

**Issue by pachuco** [kcat/openal-soft#472]
Since version 1.20.0, programs using Soft OAL tend emit Application error on exit.
I have produced log using openal-info32 and SoftOAL v1.20.1, with ALSOFT_LOGLEVEL=4.
Testing has been done using official binaries provided on openal-soft.org.
Specs:
OS: winXP SP3 x86

[zsoftoal_error.txt](https://github.com/kcat/openal-soft/files/5216818/zsoftoal_error.txt)
![onclose_error](https://user-images.githubusercontent.com/1591054/93057430-92577380-f676-11ea-9805-3b95a7f7be2c.png)

**Comment by pachuco** [comment]
Related to this, I stumbled upon another issue while fuffing around with DSOAL code.

Rightmark 3d sound process remains after closing window(requiring task manager intervention) in x86 win7 VM.
http://audio.rightmark.org/products/rm3ds.shtml 
The versions of Soft OAL that cause remaining process coincide with ones in OP bug report.

To reproduce this issue, I use DSOAL binary(attached) of at least below commit.
https://github.com/pachuco/dsoal/commit/80083953c6e7d6f4e202b7b80d23e3adeb134909
[dsound.zip](https://github.com/kcat/openal-soft/files/5217000/dsound.zip)

**Comment by kcat** [comment]
Not sure about the DSOAL/Rightmark hang, but the crash sounds like issue #394. Depending on what's in the junk pointer value, I suppose it could cause a hang in certain situations rather than a crash.

**Comment by pachuco** [comment]
Confirming that the custom build in the mentioned issue solves both XP crashes and win7 hangs.
