### ISSUE TITLE
WASAPI backend doesn't work with microphone arrays

### ISSUE THREAD

**Issue by ilya-fedin** [kcat/openal-soft#473]
For some reason, alcCaptureOpenDevice doesn't work if AL_FORMAT_MONO16 is requested and the device has 4 channels set in Windows settings.

This could be easily reproduced with Virtual Audio Cable: set maximum number of channels to 4 in VAC settings and set a 4-channels mode on VAC microphone in Windows sound settings

alcCaptureOpenDevice won't work with WASAPI with a error like `AL lib: (EE) ALCwasapiCapture_resetProxy: Failed to get matching format, wanted: Mono Signed Short 48000hz, got: 4 channels 32-bit 16000hz`, but will work with DSound or WinMM backends.

**Comment by kcat** [comment]
How are the channels expected to be downmixed? With DSound, does it just add them all together and apply a fixed attenuation factor (like `1.0/channels` or `sqrt(1.0/channels)`), does it give more preference to the front channels, or does it drop the back channels and combine the front as stereo?

**Comment by ilya-fedin** [comment]
I don't think I'm able to check this, I don't have such hardware, I re produce this with VAC to report :(
This was originally reported at https://github.com/telegramdesktop/tdesktop/issues/8579
And I have a feel that there are [similar problems with playback](https://github.com/telegramdesktop/tdesktop/issues/8183)

**Comment by ilya-fedin** [comment]
Can openal have a more high-level backend on Windows? Like Media Foundation?

**Comment by kcat** [comment]
APIs like that tend to have issues with latency, as it's designed for more general media (de)muxing, decoding, and encoding.

As of commit 7fb6d64ca81d68f74a254c097d511d8863453000, mono capture should be more flexible with various input configurations, so WASAPI should work when recording mono from 4-channel input devices.

**Comment by ilya-fedin** [comment]
> APIs like that tend to have issues with latency, as it's designed for more general media (de)muxing, decoding, and encoding.

Well, latency is not an issue for most applications :thinking: 

> As of commit [7fb6d64](https://github.com/kcat/openal-soft/commit/7fb6d64ca81d68f74a254c097d511d8863453000), mono capture should be more flexible with various input configurations, so WASAPI should work when recording mono from 4-channel input devices.

Thanks!
