### ISSUE TITLE
"Invalid resampler: linear" when setting resampler=linear?

### ISSUE THREAD

**Issue by KynikossDragonn** [kcat/openal-soft#475]
The alsoftrc sample file shows linear as a choice, but OpenALSoft logs a error saying it's a invalid resampler.

I'm using the current 1.20.1 release.

What was this resampler actually renamed to? Or is it saying it's invalid because it's the default if resampler is not set in the alsoftrc file?

**Comment by kcat** [comment]
It was a completely silly oversight. Linear is the default so it is still the one being used despite the error, but it shouldn't print an error. I just fixed this in commit 39f4ea61c5978b7abca0ef79de0b207638e7175f.

**Comment by KynikossDragonn** [comment]
Oh, I guess in the mean time if I want to avoid the "error" I can just not set resampler= in my alsoftrc?

As much as I could just diff certain things to make my own custom package in Void Linux, I rather be patient and wait until you're ready to push a new release version instead.

**Comment by kcat** [comment]
> Oh, I guess in the mean time if I want to avoid the "error" I can just not set resampler= in my alsoftrc?

Yeah, if you want the `linear` resampler, rather than `cubic`, `fast_bsinc12`/`24`, or `bsinc12`/`24`.
