### ISSUE TITLE
Feature req: logging via OutputDebugString

### ISSUE THREAD

**Issue by pachuco** [kcat/openal-soft#476]
Requesting option to write debug logs through OutputDebugStringA/W API.
Request applies to both OpenAL-soft and DSOAL.
Also prefix OutputDebugString logs with something like [ALSOFT] and [DSOAL], for identification.

Such output can be captured with Sysinternals's DebugView.

**Comment by kcat** [comment]
This is now done for OpenAL Soft with commit f02bc1354d406707619c3f4704e06c9d15b24f63. I don't know if it's a good idea to always log every message (given OutputDebugString doesn't seem to have a severity property), but that's basically how it is with Android's system log.
