### ISSUE TITLE
Setting AL_GAIN on a 3D source has no effect

### ISSUE THREAD

**Issue by Vercidium** [kcat/openal-soft#481]
I'm having issues playing 3D sounds at different volumes.

Every frame I set the following values for the listener:
```csharp
void UpdateAudio(float[] listenerPos, float[] listenerVel, float[] listenerOri)
{
    AL10.alDistanceModel(AL11.AL_EXPONENT_DISTANCE_CLAMED);
    AL10.alListenerfv(AL10.AL_POSITION, listenerPos);
    AL10.alListenerfv(AL10.AL_VELOCITY, listenerVel);
    AL10.alListenerfv(AL10.AL_ORIENTATION, listenerOri);
    AL10.alListenerf(AL10.AL_GAIN, 0.35f);
}
```

When playing a sound I set the following values:
```csharp
SFXResult PlaySound(int bufferID, SoundType type, Vector3 pos, Vector3 vel, Vector3 dir, float pitch, float gain, float maxDistance, bool loop)
{
    uint[] sources = new uint[1];
    AL10.alGenSources(1, sources);

    var s = sources[0];

    // Convert Vector3 to float[]
    float[] sourcePos = new float[3] { (float)pos.X, (float)pos.Y, (float)pos.Z };
    float[] sourceVel = new float[3] { (float)vel.X, (float)vel.Y, (float)vel.Z };
    float[] sourceDir = new float[3] { (float)dir.X, (float)dir.Y, (float)dir.Z };

    // The sound is not positioned relative to the listener
    AL10.alSourcei(s, AL10.AL_SOURCE_RELATIVE, 0);

    // Set these just in case
    AL10.alSourcei(s, AL10.AL_SOURCE_STATE, AL10.AL_STOPPED);
    AL10.alSourcei(s, AL10.AL_SOURCE_TYPE, AL10.AL_STATIC);

    // Vec3 values
    AL10.alSourcefv(s, AL10.AL_POSITION, sourcePos);
    AL10.alSourcefv(s, AL10.AL_VELOCITY, sourceVel);
    AL10.alSourcefv(s, AL10.AL_DIRECTION, sourceDir);

    // Gain values
    AL10.alSourcef(s, AL10.AL_GAIN, gain);
    AL10.alSourcef(s, AL10.AL_MIN_GAIN, 0f);
    AL10.alSourcef(s, AL10.AL_MAX_GAIN, 10f);

    // Other values 
    AL10.alSourcef(s, AL10.AL_REFERENCE_DISTANCE, maxDistance / 2);
    AL10.alSourcef(s, AL10.AL_ROLLOFF_FACTOR, 1.0f);
    AL10.alSourcei(s, AL10.AL_LOOPING, loop ? 1 : 0);
    AL10.alSourcef(s, AL10.AL_PITCH, pitch);

    // Play the sound
    AL10.alSourcei(s, AL10.AL_BUFFER, bufferID);
    AL10.alSourcePlay(s);

    // Check if there's an error and print it
    AudioManager.CheckError();

    return new SFXResult(s, 0);
}
```

Setting AL_GAIN to 0.02f, 1.0f, 20f or 100f doesn't change how loud it sounds.

I've tried with different distance models but am still facing the same issue.

I'm using C# bindings from https://github.com/flibitijibibo/OpenAL-CS, however I think the bindings are correct as setting AL_GAIN for the listener works properly.

Any help with this would be greatly appreciated.

**Comment by kcat** [comment]
> ```cs
>     // Set these just in case
>     AL10.alSourcei(s, AL10.AL_SOURCE_STATE, AL10.AL_STOPPED);
>     AL10.alSourcei(s, AL10.AL_SOURCE_TYPE, AL10.AL_STATIC);
> ```

These are errors, `AL_SOURCE_STATE` and `AL_SOURCE_TYPE` aren't set this way. It shouldn't cause the problem here, but it'll generate errors that get picked up by `alGetError`.

> ```cs
>     AL10.alSourcef(s, AL10.AL_GAIN, gain);
> ```

What value is `gain`?

> ```cs
>     // Gain values
>     AL10.alSourcef(s, AL10.AL_GAIN, gain);
>     AL10.alSourcef(s, AL10.AL_MIN_GAIN, 0f);
>     AL10.alSourcef(s, AL10.AL_MAX_GAIN, 10f);
> ```

Is `10f` being interpreted as a floating-point number `10.0f`, or a hex value `0x10f`?

> ```cs
>     AL10.alSourcef(s, AL10.AL_REFERENCE_DISTANCE, maxDistance / 2);
> ```

What value is `maxDistance`? `AL_REFERENCE_DISTANCE` determines the distance where sounds are at normal volume (`source_gain * listener_gain`), and for non-`_CLAMPED` distance models the source gets louder when closer, up to `AL_MAX_GAIN`.

**Comment by Vercidium** [comment]
Thank you, that worked!

I changed the distance model to `AL_EXPONENT_DISTANCE` and now control the gain of the sound using `AL_MAX_GAIN`.

I removed the `AL_SOURCE_STATE` and `AL_SOURCE_TYPE` sets, as well as the `AL_GAIN` and `AL_MAX_DISTANCE` sets and changed the other parameters to:

```
AL10.alSourcefv(s, AL10.AL_POSITION, sourcePos);
AL10.alSourcefv(s, AL10.AL_VELOCITY, sourceVel);
AL10.alSourcefv(s, AL10.AL_DIRECTION, sourceDir);

AL10.alSourcei(s, AL10.AL_SOURCE_RELATIVE, 0);
AL10.alSourcef(s, AL10.AL_REFERENCE_DISTANCE, 14.0f * maxDistance);
AL10.alSourcef(s, AL10.AL_MIN_GAIN, 0.0f);
AL10.alSourcef(s, AL10.AL_MAX_GAIN, gain);
AL10.alSourcef(s, AL10.AL_ROLLOFF_FACTOR, 1.0f / maxDistance);

AL10.alSourcei(s, AL10.AL_LOOPING, loop ? 1 : 0);
AL10.alSourcei(s, AL10.AL_BUFFER, bufferID);
```

`gain` is now clamped to the range 0-1 and `maxDistance` is a multiplier for how far the sound should carry relative to the other sound types.

Thanks again for the quick response.
