### ISSUE TITLE
alcOpenDevice returns sometimes NULL

### ISSUE THREAD

**Issue by MonRoyals** [kcat/openal-soft#482]
I try to open the device for Android 
_**_alcOpenDevice(NULL)_**_
which returns NULL. 

Iterating over
const OALCEnum	aDevices[] = { ALC_DEVICE_SPECIFIER, ALC_ALL_DEVICES_SPECIFIER };
finds "Default Audio Device". Trying to open it also returns NULL.

This does not happen regulary. It happens occasionally and not on my phone. I only saw it at some customers logs.

Any idea?

**Comment by kcat** [comment]
Hmm, `"Default Audio Device"` isn't a string that's returned with OpenSL/Android output. Is there anything more in the log? If `alcOpenDevice(NULL)` fails, it likely means the backend couldn't open a device on the system. On Android, the system log should contain messages about any errors that happen when trying to open the system device, like if `slCreateEngine` or `engine->CreateAudioPlayer` or something fails.

**Comment by MonRoyals** [comment]
This is our code to get the device:

`m_pDevice = :::alcOpenDevice(AL_NULL);
ALC_CHECK_ERROR("CSoundSystemOAL::init::alcOpenDevice(AL_NULL)");
if( m_pDevice == AL_NULL )
{
	// Maybe there already exists a context? Just make sure we reuse it, if available
	if( m_pContext = ::alcGetCurrentContext(); m_pContext )
	{
		TRACE(I, "CSoundSystemOAL::init() : Existing context found. Trying to resuse device");
		m_pDevice = ::alcGetContextsDevice(m_pContext);
		TRACE(I, "CSoundSystemOAL::init() : Reusable device: %p", m_pDevice);
	}
	
	if( m_pDevice == AL_NULL )
	{
		// Now get the default device name and try to open that explicitly
		if( const OALChar* pchDefaultDevice = ::alcGetString(AL_NULL, ALC_DEFAULT_DEVICE_SPECIFIER); pchDefaultDevice )
		{
			TRACE(I, "CSoundSystemOAL::init() : Found ALC_DEFAULT_DEVICE_SPECIFIER = \"%s\"", pchDefaultDevice);
			m_pDevice = ::alcOpenDevice(pchDefaultDevice);
			ALC_CHECK_ERROR("CSoundSystemOAL::init::alcOpenDevice(...)");
		}

		// Last try is to enumerate all devices and try to open each of them until we succeed
		if( m_pDevice == AL_NULL )
		{
			char*			ppchDevices[16];
			const OALCEnum	aDevices[] = { ALC_DEVICE_SPECIFIER, ALC_ALL_DEVICES_SPECIFIER };

			// There are two sources for the device list. We're going to try both:
			// ALC_DEVICE_SPECIFIER = the default way
			// ALC_ALL_DEVICES_SPECIFIER = by extension which almost all implementations provide
			// Note: Intentionally don't break out of the loop if we found a device, so that we trace
			// the upcoming lists too. The inner for-loop already ensures to not open multiple times.
			for( size_t d = 0; d < ARRAY_LENGTH(aDevices); ++d )
			{
				const size_t szDevices = EnumDevices(ppchDevices, ARRAY_LENGTH(ppchDevices), aDevices[d]);

				TRACE(I, "CSoundSystemOAL::init() : Enumerated %u devices in list %u", szDevices, d);
				for(size_t i = 0; i < szDevices; ++i)
				{ TRACE(I, "CSoundSystemOAL::init() : - Device %u = %s", i, ppchDevices[i]); }

				for( size_t i = 0; i < szDevices && m_pDevice == AL_NULL; ++i )
				{
					TRACE(I, "CSoundSystemOAL::init() : alcOpenDevice(\"%s\")", ppchDevices[i]);
					m_pDevice = ::alcOpenDevice(ppchDevices[i]);
					ALC_CHECK_ERROR("CSoundSystemOAL::init::alcOpenDevice(...)");
					TRACE_IF(I, m_pDevice != AL_NULL, "CSoundSystemOAL::init() : Open succeeded.");
				}
			}
		}
	}
}`

This is the logoutput. We don't have any device logs. I have never seen it on my development devices. Only in production at the customer side, where I have no access:

12:53:51:327 CSoundSystemOAL::init(6) : m_pDevice(0x0), m_pContext(0x0)
12:53:51:416 CSoundSystemOAL::init::alcOpenDevice(AL_NULL) : ERROR, m_pDevice = NULL, alcError = ALC_INVALID_VALUE, default device = Default Audio Device 
12:53:51:417 CSoundSystemOAL::init() : Found ALC_DEFAULT_DEVICE_SPECIFIER = "Default Audio Device"
12:53:51:430 CSoundSystemOAL::init::alcOpenDevice(...) : ERROR, m_pDevice = NULL, alcError = ALC_INVALID_VALUE, default device = Default Audio Device 
12:53:51:431 CSoundSystemOAL::init() : Enumerated 1 devices in list 0
12:53:51:435 CSoundSystemOAL::init() : - Device 0 = Default Audio Device
12:53:51:436 CSoundSystemOAL::init() : alcOpenDevice("Default Audio Device")
12:53:51:443 CSoundSystemOAL::init::alcOpenDevice(...) : ERROR, m_pDevice = NULL, alcError = ALC_INVALID_VALUE, default device = Default Audio Device 
12:53:51:444 CSoundSystemOAL::init() : Enumerated 0 devices in list 1
12:53:51:447 CSoundSystemOAL::init() : Failed to open any device!

**Comment by MonRoyals** [comment]
I found the issue. The app was send to the background but still was executing and tried to configure OpenAL. Retrying solved it for me.

**Comment by kcat** [comment]
If it's due to `slCreateEngine` or something failing when the app isn't in the foreground, there isn't really anything OpenAL Soft can do. Except maybe report the error better, but that's a more general short-coming of the API.
