### ISSUE TITLE
All input and output halts when OpenAL starts (excluding OpenAL itself)

### ISSUE THREAD

**Issue by OoLunar** [kcat/openal-soft#493]
Hello!
I'm coming from https://github.com/zevv/bucklespring/issues/92, where all media playback stops when bucklespring starts. After some discussing with @zevv, they seem to believe this:
> Your openAL is likely configured to talk directly to the alsa hardware device, effectively locking it out for any other users. On a common desktop Linux, you'll likely be using Pulseaudio as your audio backend, so OpenAL needs to be configured to use the pulse driver to play nicely with the rest of the system.

I've altered my `~/.alsoftrc` accordingly to use the pulse driver, however nothing has changed. Are there any other configs or settings that I should be aware of?
```
drivers = pulse
period_size = 8
periods = 4
```

**Comment by kcat** [comment]
Those `period_size` and and `periods` settings are unnecessary (and `period_size` is unreasonably small). I'd leave those out.

If you're able to run the app from the command line, you can set the `ALSOFT_LOGLEVEL` environment variable to `3` when you run it, like this:
```
ALSOFT_LOGLEVEL=3 ./app
```
That will make OpenAL print out logging information to the terminal, which will say what settings its getting from which config files, and what backend it's using for the device.

**Comment by OoLunar** [comment]
Apologies for the delay. 

Turns out that it wasn't reading the config that I was modifying. I was modifying `/home/lunar/.alsoftrc` instead of `/root/.alsoftrc`, since 

https://hastebin.com/vebuqaxufi.yaml
At this point, the error looks Googlable.

**Comment by kcat** [comment]
You're running the app as root. It won't be able to connect to the PulseAudio server, then normally fall back to ALSA which will lock out other apps from accessing the device. You should run the app as a normal user, which will let it use the audio device normally like other apps.

**Comment by OoLunar** [comment]
I started pulseaudio with the `--system` option, and then started buckle with root. Everything ran smoothly except that there was a bit of audio lag (say anywhere between 0.2s and 0.7s).

```bash
# Had to run twice since first run failed to locate /var/run files and generated them. Not sure if the explanation is correct, but running it twice fixed the error nonetheless.
sudo pulseaudio --system &
sudo ./buckle
```

Unfortunately, seeing as how not only is other media not playing, nor is this how the programs are meant to be ran, I'll still be looking for alternative solutions. I posted this one here for others who are having similar issues with no luck.

Buckle is having user permission issues accessing `/dev/input/event*` files, so I'll get back to Zevv with that particular issue.

Seeing as how this is no longer related to OpenAL, I'll close the issue. Thank you for your work, and I wish you the best of luck with it!
