### ISSUE TITLE
Compiling for Windows 10 ARM64

### ISSUE THREAD

**Issue by MikuAuahDark** [kcat/openal-soft#494]
Hello, I try to compile OpenAL-soft latest `master` branch targetting Windows 10 ARM64 and getting these errors.

```
D:\omitted\oals-master\alc\cpu_caps.cpp(127,14): error C2039: 'close': is not a member of 'al::ifstream' [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(73,40): warning C4838: conversion from 'const float' to 'unsigned __int64' requires a narrowing conversion [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(73,40): warning C4244: 'initializing': conversion from 'const float' to 'unsigned __int64', possible loss of data [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(73,51): warning C4838: conversion from 'const float' to 'unsigned __int64' requires a narrowing conversion [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(73,51): warning C4244: 'initializing': conversion from 'const float' to 'unsigned __int64', possible loss of data [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(73,62): error C2078: too many initializers [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(74,42): warning C4838: conversion from 'const float' to 'unsigned __int64' requires a narrowing conversion [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(74,42): warning C4244: 'initializing': conversion from 'const float' to 'unsigned __int64', possible loss of data [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(74,55): warning C4838: conversionfrom 'const float' to 'unsigned __int64' requires a narrowing conversion [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(74,55): warning C4244: 'initializing': conversion from 'const float' to 'unsigned __int64', possible loss of data [D:\omitted\oals-master\build\OpenAL.vcxproj]
D:\omitted\oals-master\alc\mixer\mixer_neon.cpp(74,68): error C2078: too many initializers [D:\omitted\oals-master\build\OpenAL.vcxproj]
```
Looks like wrong codepath taken for `alc/cpu_caps.cpp` and tries to read `/proc/cpuinfo` instead. While it select `mixer_neon.cpp` as the accelerated mixer which is correct, MSVC doesn't like some codes there, which can be pinpointed at error message above. ~~I also noticed that DSound backend must be disabled, otherwise it picks wrong DSound.lib from Windows SDK v7.1A which is for x64. On unrelated note, I don't think DSound is supported in Windows 10 ARM64 anyway.~~

So far, that's the error I observed and probably more will come. Would it be possible to compile OpenAL-soft for Windows 10 ARM64 later on, or do you have no interest on this?

My CMake invocation command is: `cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=%CD%\build\installdir -A ARM64 -DALSOFT_BACKEND_DSOUND=0`

Thanks.

**Comment by kcat** [comment]
Those errors seem to be a problem with the compiler. The `close` method is completely valid, and it seems to think `float32x4_t` is `unsigned __int64`.

Regarding `/proc/cpuinfo`, that code is built when the compiler doesn't have NEON enabled at compile time, which is checked with the `__ARM_NEON` macro. If MSVC uses a different macro to indicate NEON support on ARM targets, that will also need to be checked.

If Windows 10 officially supports ARM64, then any issues OpenAL Soft has with it should be fixed. Though even if it doesn't officially support it, unintrusive fixes for it would be acceptable.

**Comment by MikuAuahDark** [comment]
From all the compiler existing, MSVC is probably the most annoying compiler that it diverges between GCC and Clang. I double checked and `std::istream` (which `al::ifstream` inherits from) doesn't have `.close()` method, so I'm not completely sure if that's valid. Also I double checked arm64 header definition and looks like `float32x4_t` is defined as follows:

```cpp
typedef union __declspec(intrin_type) _ADVSIMD_ALIGN(16) __n128
{
     unsigned __int64   n128_u64[2];
     unsigned __int32   n128_u32[4];
     unsigned __int16   n128_u16[8];
     unsigned __int8    n128_u8[16];
     __int64            n128_i64[2];
     __int32            n128_i32[4];
     __int16            n128_i16[8];
     __int8             n128_i8[16];
     poly64_t           n128_p64[2];
     poly32_t           n128_p32[4];
     poly16_t           n128_p16[8];
     poly8_t            n128_p8[16];
     float              n128_f32[4];
    double              n128_f64[2];
    struct
    {
        __n64  low64;
        __n64  high64;
    } s;
} __n128;
```

`__n128` type is same across various 128-bit width type like `float32x4_t`, `int32x4_t`, `uint32x4_t` and their reasoning was ["backward compatibility"](https://developercommunity.visualstudio.com/content/problem/335464/arm64-vector-intrinsics-typedefs-float32x4-t-and-i.html).

Back to `/proc/cpuinfo` thingy, according to SDL's CPU info code, [all WinRT devices which runs ARMv7 is required to support NEON](https://github.com/spurious/SDL-mirror/blob/b380f23c5dd740b4b769d89f2a9039f7f387587e/src/cpuinfo/SDL_cpuinfo.c#L451-L455) so it's safe to assume NEON is available for Windows/ARM(64) combination.

And to answer your last question, yes. Windows 10 officially supports ARM64 now. Visual Studio Code has been ported to [ARM64](https://code.visualstudio.com/updates/v1_46) at v1.46, so I think this should be fixed?

**Comment by kcat** [comment]
Commits 1869dc14d498be4dbe771a898b995ae6eb372083 and 88cb398a836bb8b2d4038edcedff5167886e2d51 should fix the errors. I'm not sure about DSound though, why CMake is finding the x64 lib when building for ARM64 or how to make it not do that.

**Comment by MikuAuahDark** [comment]
Thanks. Can confirm those commits fixed the compile error. I still have to patch the CMakeLists.txt slightly so it links properly (and build OpenAL32.dll) though.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 06dc5f9c..c1c3342c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -900,7 +900,7 @@ if(WIN32)
             set(HAVE_WINMM 1)
             set(BACKENDS  "${BACKENDS} WinMM,")
             set(ALC_OBJS  ${ALC_OBJS} alc/backends/winmm.cpp alc/backends/winmm.h)
-            set(EXTRA_LIBS ${WINMM_LIBRARY} ${EXTRA_LIBS})
+            set(EXTRA_LIBS WinMM ${EXTRA_LIBS})
         endif()
     endif()
 
```

Anyway I was wrong about DSound is not supported in Windows 10 ARM64. I double-checked and the relevant .lib file is there.

Also, for some reason WinMM linking fails because it picks x64 .lib instead of arm64 .lib, so I have to add "WinMM" explicitly. Strangely, DSound also uses x64 .lib but has no problems when linking. In my Windows SDK, DSound.lib (and WinMM.lib) is available at:

* `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\arm\dsound.lib` for ARMv7 (older WinRT?) devices
* `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\arm64\dsound.lib` for ARM64 devices
* `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\dsound.lib` for x86-64 devices
* `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\dsound.lib` for x864 devices

So maybe that's something that need to be worked around, or is this too much?

**Comment by kcat** [comment]
My first thought would be something wrong with the FindWindowsSDK.cmake script causing it to think it's targeting x86-64 instead of ARM64. Though I do see version `10.0.19041.0` listed, and it does attempt to work out ARM/ARM64 targets. Maybe the
```
if("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "ARM")
```
check is failing for some reason. The CMake docs are really confusing about the VS variables, what they can get set to, by what, and why.

**Comment by MikuAuahDark** [comment]
Alright I tried to print out the `CMAKE_VS_PLATFORM_NAME` variable and my conclusion goes to this patch.
```diff
diff --git a/build/.empty b/build/.empty
deleted file mode 100644
index e69de29b..00000000
diff --git a/cmake/FindWindowsSDK.cmake b/cmake/FindWindowsSDK.cmake
index cbb0ee4a..bc9f87e8 100644
--- a/cmake/FindWindowsSDK.cmake
+++ b/cmake/FindWindowsSDK.cmake
@@ -485,6 +485,9 @@ if(WINDOWSSDK_FOUND)
 			set(_winsdk_arch arm) # what the architecture used to be called
 			set(_winsdk_arch8 arm) # what the WDK for Win8+ calls this architecture
 		endif()
+	elseif("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "ARM64")
+		# Only supported in Win10 SDK and up.
+		set(_winsdk_arch8 arm64) # what the WDK for Win8+ calls this architecture
 	else()
 		if(CMAKE_SIZEOF_VOID_P MATCHES "8")
 			set(_winsdk_archbare /x64) # what the architecture used to be called in oldest SDKs
```

Not sure if that's redundant, but I think you get the idea.

**Comment by kcat** [comment]
Commit ee9f0fe3063c61584e7a34d7b3ddc73d8464a29c should fix that. I'm not sure what the correct fix should be (can `ARM` be either 32-bit or 64-bit, while `ARM64` is 64-bit only? or is `ARM` 32-bit only and `ARM64` 64-bit only?), but it should do the job.

**Comment by MikuAuahDark** [comment]
I think `ARM` is for 32-bit WinRT-era devices and `ARM64` is for the recent full Windows 10 ARM64.

Anyway, got OpenAL-soft working in Windows 10 ARM64 under QEMU, so I'll close this as solved.
![gambar](https://user-images.githubusercontent.com/7500438/99642011-f7b84e00-2a85-11eb-9948-99399763ea32.png)
