### ISSUE TITLE
Capture regression on macOS (1.19 fine, 1.20.1 and after bad).

### ISSUE THREAD

**Issue by john-preston** [kcat/openal-soft#495]
After migrating to 1.20.1 (and 1.21.0 was tested too and has the same problem) capture works fine only when the `frequency` specified in `alcCaptureOpenDevice` matches exactly the Input device frequency. Otherwise the sound get artefacts and usually also is sped up.

On macOS in Settings right now I have two Input devices (default mic and airpods). If I view them in Audio MIDI Setup, mic works on 48'000 and airpods on 16'000 frequencies.

On version 1.19 both those devices capture with great quality no matter what frequency I use in alcCaptureOpenDevice (I tried both 48'000 and 16'000, so four tests were made).

On version 1.20.1 and 1.21.0 it sounds fine only if I pass in alcCaptureOpenDevice the exact frequency I have for the device in Audio MIDI Setup.

I can provide any additional information, voice message samples, assist with debugging if needed.

**Comment by kcat** [comment]
That would align with the CoreAudio backend switching from CoreAudio's resampler to OpenAL Soft's internal one. Maybe the internal resampler is being used wrong, though it's used the same way in Windows/WASAPI and there isn't a known issue there.

It's also possible some related changes affected proper capture from the system, perhaps the internal ring buffer size was being set wrong. I pushed a fix for that with commit 0024ea229b415fcbb3bdbd5eb0bfc60685c64b58. If it's still bad, samples of what it does and should sound like would be helpful.

**Comment by john-preston** [comment]
@kcat I've built it and it fails capture initialization with a message:

`Failed to open capture device: Could not get input frame count: 4294956430`

**Comment by john-preston** [comment]
This looks like `kAudioUnitErr_InvalidScope`.

**Comment by ilya-fedin** [comment]
> though it's used the same way in Windows/WASAPI and there isn't a known issue there

There are some complains about the same issue on Windows: https://github.com/telegramdesktop/tdesktop/issues/1548#issuecomment-406820251

**Comment by kcat** [comment]
> This looks like `kAudioUnitErr_InvalidScope`.

I wish Apple's docs were clearer with this stuff. Does it work if you change `alc/backends/coreaudio.cpp` around line 565 from
```c++
    err = AudioUnitGetProperty(mAudioUnit, kAudioUnitProperty_MaximumFramesPerSlice,
        kAudioUnitScope_Output, 0, &outputFrameCount, &propertySize);
```
to
```c++
    err = AudioUnitGetProperty(mAudioUnit, kAudioUnitProperty_MaximumFramesPerSlice,
        kAudioUnitScope_Input, 0, &outputFrameCount, &propertySize);
```
? If not, try `kAudioUnitScope_Global` instead.

> There are some complains about the same issue on Windows (even on 1.19.1): [telegramdesktop/tdesktop#1548 (comment)](https://github.com/telegramdesktop/tdesktop/issues/1548#issuecomment-406820251)

That doesn't seem to be the same issue. The issue here is OpenAL Soft getting capture samples from the system at a certain fixed sample rate, using its own converter to resample and fix it to the app's requested capture rate, and there being problems with the resampled results given back to the app.

The issue in that comment seems to be Windows changing the device's playback sample rate (which OpenAL Soft shouldn't be able to do since it opens it in shared mode) and other apps not being able to recognize or respond to the rate change. It doesn't seem to have anything to do with OpenAL Soft's internal converter/resampler.

**Comment by ilya-fedin** [comment]
> That doesn't seem to be the same issue.

Oops.

**Comment by john-preston** [comment]
@kcat kAudioUnitScope_Input gives the same error, kAudioUnitScope_Global works. It records in nice quality on different devices. But there is a different problem.

In Telegram Desktop I have capture frequency 48000. If I use the built in microphone with 48000 frequency it works great. But if I switch to AirPods with 16000 frequency it captures fine, but the resulting voice message contains between one third and one half (!) of what I've said. So I speak for 60 seconds, count to 60 and then listen to the result - it contains 25 seconds with first 25 numbers.

If I change capture frequency in Telegram to 16000 it records all the data from both of the devices.

**Comment by kcat** [comment]
> In Telegram Desktop I have capture frequency 48000. If I use the built in microphone with 48000 frequency it works great. But if I switch to AirPods with 16000 frequency it captures fine, but the resulting voice message contains between one third and one half (!) of what I've said. So I speak for 60 seconds, count to 60 and then listen to the result - it contains 25 seconds with first 25 numbers.
> 
> If I change capture frequency in Telegram to 16000 it records all the data from both of the devices.

It captures fine if the OpenAL device is set to 16khz while the system device is 48khz? Okay, so it captures all the audio as long as the OpenAL capture frequency is equal to or less than the system device frequency. But when the device is less, it captures less than half of what it should while not skipping anything either.

What capture buffer size do you specify for `alcCaptureOpenDevice`, and do you notice `ALC_CAPTURE_SAMPLES` getting limited to some value regardless of how many samples you read with `alcCaptureSamples`?

I pushed some fixes for the `kAudioUnitScope` error, as well as some buffer size bugs. This may help, though it's still odd for 60 seconds of recording to only give the first 25 seconds worth, without skipping anything.

**Comment by john-preston** [comment]
On the latest master when recording in AirPods (16000 recording device) I see a lot of "[ALSOFT] (EE) AudioUnitRender error: -10863" in console (kAudioUnitErr_CannotDoInCurrentContext). Then it has all audio, but sped up and with glitches (like it was when I first reported this issue) :(

**Comment by john-preston** [comment]
@kcat Ok, the exact commit is https://github.com/kcat/openal-soft/commit/31c7eb5c552482cc782b1599c94532cecf09851a

Without that commit the recording from 16000 device to 48000 tdesktop sounds fine, but I get only ~40% of the data. With that commit I get full voice message, but it is sped up (it sounds faster than it was recorded) + with glitches and with a lot of "[ALSOFT] (EE) AudioUnitRender error: -10863" in console.

**Comment by kcat** [comment]
With a bit of reading, it's possible it was getting confused since I didn't explicitly disable automatic buffer allocation with recording. Can you try now with commit ba39c622efc2bd0e832c0573748fec47bcc3bd6c?

**Comment by john-preston** [comment]
Ok, so now it doesn't have clicks (that I called "with glitches" in the previous message), but it is still sped up (the recorded voice message plays faster than it is really) and a lot of "[ALSOFT] (EE) AudioUnitRender error: -10863" in console while recording.

**Comment by john-preston** [comment]
@kcat But it sounds really as it should if I revert those two commits about the buffer size:

Revert d08d6b18, revert 31c7eb5c. The funny thing with the numbers. If those commits are reverted (and the recording sounds nice, but is cut to ~40% of its length) I log those variables:

`ERR("Got: %u, Counted: %llu\n", (unsigned int)outputFrameCount, FrameCount64);`

I get those values: `[ALSOFT] (EE) Got: 1411, Counted: 153600048`

And when I use your `master` commit and log them (and get sped up, not nice voice and a lot of -10863 errors) I get those values: `[ALSOFT] (EE) Got: 1411, Counted: 3248`

So the nice-souding recording has the ring buffer size A LOT larger than the new commits make it.

If I take your `master` commit and just hardcode:

`outputFrameCount = 153600048;//static_cast<UInt32>(maxu64(outputFrameCount, FrameCount64));`

it works with nice sound, but with cut to ~40% length. As I understand, this is the correct way for that part of code (it should work with a very large buffer, right?), but the cutting of the resulting data happens in some other place because of some other reason :(

**Comment by john-preston** [comment]
I open the device like that:

alcCaptureOpenDevice(nullptr, kCaptureFrequency, AL_FORMAT_MONO16, kCaptureFrequency / 5)

Maybe that's not the right way (the sizes)? But it worked before.

**Comment by john-preston** [comment]
Also, if I do this change:

![image](https://user-images.githubusercontent.com/17900494/100205775-f9b75c80-2f1e-11eb-9e89-5affb8419add.png)

strangely it doesn't crash and work perfectly (giving me the whole recorded data).

So it looks like the current `master` branch code (a) has a wrong ring buffer size (too small) and (b) has wrong `mConverter->availableOut` result (which may be so, because `availableOut` is used only in CoreAudio backend).

**Comment by john-preston** [comment]
So, it looks like the `clamp(.., 1, BUFFERSIZE)` in `availableOut` is wrong (because it can have more available than BUFFERSIZE really). This patch makes it work correctly with AirPods microphone and with default microphone, (but of course it should be done somehow better, without hardcoded values):

![image](https://user-images.githubusercontent.com/17900494/100221290-e661bc80-2f31-11eb-8555-21a1275051aa.png)

**Comment by kcat** [comment]
> As I understand, this is the correct way for that part of code (it should work with a very large buffer, right?), but the cutting of the resulting data happens in some other place because of some other reason :(

That value was from a bad calculation that didn't properly scale the result. A sample count of 153,600,048 will be about 300MB of RAM for 16-bit mono, doubled for stereo (600MB) and doubled again for 32-bit float (1.2GB). At 16khz, that's one hour of audio. The lower value was correct; a buffer size of `kCaptureFrequency / 5` provides for 200ms of audio, and with the device running at 16khz, that means a buffer of 3200 samples will take 200ms to fill with 200ms of audio as requested. An additional 48 samples is added for resampling purposes, to ensure the full `kCaptureFrequency / 5` can be provided with the full buffer. That would thus be 3248 total.

Forcing a really large buffer is just hiding the problem. OpenAL only guarantees a buffer as large as the size given to `alcCaptureOpenDevice`, though it generally also enforces a 100ms minimum, with the sample count rounded up to the next power of 2 minus 1. So with the 3248 sample buffer, it gets rounded up to 4095 samples (really 4096, but at least one sample needs to remain unfilled), for a ~253ms buffer.

> Also, if I do this change:
> 
> ![image](https://user-images.githubusercontent.com/17900494/100205775-f9b75c80-2f1e-11eb-9e89-5affb8419add.png)
> 
> strangely it doesn't crash and work perfectly (giving me the whole recorded data).

This seems to be the culprit. The count from `availableOut` shouldn't be limited as that would cause `ALC_CAPTURE_SAMPLES` to never report more than 1024 samples. It should probably be limited to `INT_MAX` for practical overflow protection, but yeah. Commit 3970252da9d3148ea0b45990bb2476ee3b99fb0c should fix it.

**Comment by john-preston** [comment]
@kcat Thanks for the buffer size explanation.

The latest commit works good on both devices. Thanks!
