### ISSUE TITLE
Not-Realtime "Batch" Processing

### ISSUE THREAD

**Issue by caliuf** [kcat/openal-soft#496]
Hi everyone,
I know that this is a corner use case, but I was wondering if there's a way to handle this scenario: 

I'd like to produce an audio file with sounds moving in a 3d space. I'm doing it in the standard way, so I play sources and then make them move according to what I want to obtain. This way in order to record a 3 min audio I need to wait 3 minutes, since the processing is "wall clock based".

Is there a way to process audio and source position changes in a "CPU-clock based" fashion (forgive me for the poor terminology) so that I can get the same output in, say, just 10s (according to cpu power)? I would call it "batch processing", but I know that this term can be misleading.

If this is possible, how can I record the output wav? I'm currently jack for this, but I think will not be feasible for not-realtime audio processing.

Thanks a lot in advance for any answer!

**Comment by kcat** [comment]
You can use a loopback device (with the `ALC_SOFT_loopback` extension) to render audio as fast as the CPU allows. Something like this:
```c++
LPALCLOOPBACKOPENDEVICESOFT alcLoopbackOpenDeviceSOFT;
LPALCISRENDERFORMATSUPPORTEDSOFT alcIsRenderFormatSupportedSOFT;
LPALCRENDERSAMPLESSOFT alcRenderSamplesSOFT;

// ... first time init...

if(!alcIsExtensionSupported(NULL, "ALC_SOFT_loopback"))
    error("Loopback rendering not supported");

alcLoopbackOpenDeviceSOFT = alcGetProcAddress(NULL, "alcLoopbackOpenDeviceSOFT");
alcIsRenderFormatSupportedSOFT = alcGetProcAddress(NULL, "alcIsRenderFormatSupportedSOFT");
alcRenderSamplesSOFT = alcGetProcAddress(NULL, "alcRenderSamplesSOFT");

// ... open and set up a device...

device = alcLoopbackOpenDeviceSOFT(NULL);
/* Attributes for the rendered output. Most standard context creation attributes are
 * supported, and must include the format. */
ALCint attributes[] = {
    /* 16-bit stereo 44.1khz for example. Change as desired. */
    ALC_FORMAT_CHANNELS_SOFT, ALC_STEREO_SOFT,
    ALC_FORMAT_TYPE_SOFT, ALC_SHORT_SOFT,
    ALC_FREQUENCY, 44100,
    0 /* end-of-list */
};
context = alcCreateContext(device, attributes);
alcMakeContextCurrent(context);

/* Normal context functionality is now available. Create buffers, sources, etc, as normal.
 * Nothing will play and state won't progress at this time. */

// ... core render loop...
#define UPDATE_SIZE 1024 /* number of samples per update. Can be any reasonable size. */

char rendered_samples[UPDATE_SIZE * 2 * sizeof(short)];
while(running)
{
    // Check sources' states, update positions, all the normal stuff you'd do in an update loop here...

    /* Now render samples into the provided buffer. This will advance time by the given number
     * of samples, updating the sources' playback offsets and queues, stop finished sources, etc. */
    alcRenderSamplesSOFT(device, rendered_samples, UPDATE_SIZE);
    // Handle the samples in rendered_samples however you need.
}
```
Function typedefs and necessary enums are in OpenAL Soft's `alext.h` header.

**Comment by caliuf** [comment]
Thanks a lot @kcat for your quick and thorough answer!

I will give it a try
