### ISSUE TITLE
3rd order output

### ISSUE THREAD

**Issue by venetanji** [kcat/openal-soft#50]
Not really an issue here. I would like to get openal to output the entire set of 16 channels for 3rd order ambisonics over jack. I get the quad output, but that's decoded by ambdec already, I would need to get to the encoded channels. I have my own decoder running in faust (3h3p for a 24 speaker array).

Any pointers? Would it be possible?

**Comment by kcat** [comment]
I was curious if anyone would actually be interested in direct Ambisonics output.

Aside from the wave writer's amb format output (which is only first order), it is unfortunately not currently possible. However I'm more than willing to add such an option. I could add something like a new "ambisonic3h3p" channel configuration, which would output the full third order ambisonic mix over 16 channels.

I'm curious though about certain details. What should the default channel ordering and normalization scheme be? FuMa seems to be the defacto standard for ambisonics, however it's limited to third order and the normalization scheme is kind of weird. ACN+SN3D was adopted by the AmbiX format, which Google has recently adopted for 3D video on YouTube. Meanwhile, ACN+N3D normalization is apparently the standard for math and physics work dealing with spherical harmonics. Internally, OpenAL Soft uses ACN+N3D, though can easily convert it to anything else for output. I can add an option for users to set, though a sensible default would be nice.

**Comment by kcat** [comment]
Git head now has an option to output a third order mix (first and second order too). The output channel order is ACN with SN3D normalization (there will be an option to change this, but it's not currently there). You can select it either with ```alsoft-config```, which has new ```Ambisonics *``` channel configurations, or by specifying ```channels = ambi3``` in the config file.

Also, this will currently only work on backends that do not use explicit channel labels: JACK, ALSA, and OSS (the others either want to know what the individual channels are, will always match the output channels, or only do mono and stereo).

**Comment by kcat** [comment]
And now it also has an option to change the ambisonic output format, either in ```alsoft-config``` or by setting the ```ambi-format``` config option to ```acn+sn3d``` (default), ```acn+n3d```, or ```fuma```.

**Comment by venetanji** [comment]
WOW, this is awesome, thanks so much. I think AmbiX is a good default, people fiddling with this feature will likely know what they are doing. I'll give this a go in a few hours and let you know!

**Comment by venetanji** [comment]
It works great! Next step for me is to get this going on windows and test the speakers with a VR headset!

Maybe a stupid question, but does openal rotate the soundfield according to the camera movement, or does each implementation address that? I ask because with the speaker array we built, we just need to output the absolute sound field rather than relative to the camera. I've tried with minecraft and it seems that when you look up the sound still comes from the "front".

Anyways, thanks so much, this opened up a few possibilities for our research!

**Comment by kcat** [comment]
> Maybe a stupid question, but does openal rotate the soundfield according to the camera movement, or does each implementation address that?

OpenAL rotates according to the listener's ```AL_ORIENTATION``` property (as well as a source's ```AL_SOURCE_RELATIVE``` property). Or more specifically, it converts each source's location from the (app specified) global position to a head-relative position based on the listener's (app specified) position and orientation, and encodes that relative position onto the soundfield (the soundfield itself is never directly rotated; the sources are just encoded onto it as if the listener was the center looking at the front). It's up to each app to determine if it wants a Y-locked (Z-locked in ambisonics) orientation for yaw-only rotation, or a full 3D rotation. It sounds like Minecraft only specifies a Y-locked orientation.

If you're using it with your own app, you can simply leave the listener's ```AL_ORIENTATION``` at its default, to avoid having the sound pre-rotated (or if the problem was it being Y-locked, you can specify a full rotation to match the headset). For existing apps, I could see about adding an option to ignore the listener's orientation to allow you to do what you need with it.

**Comment by venetanji** [comment]
Ok I see what you mean, thanks for the explanation! I found the bits in the code that deal with this, I'll try to fiddle around and see what works.

On the side and kinda off topic, I did not manage to successfully build the library on Windows with jack support. To be precise, it builds ok but then it fails to open the device. I sense this may be due to the toolchain used (I used mingw64) but really not sure. I'm not very familiar with building on windows, I was wondering if jack was ever tested on windows?

**Comment by kcat** [comment]
Jack hasn't really been tested on Windows, no. The main problem is that it'll try to dynamically load ```libjack.so.0``` at runtime, which is obviously not the correct name on Windows. I can fix that though, what's the DLL name on WIndows?

**Comment by venetanji** [comment]
libjack.dll
Replacing that in the backend implementation was enough for me to get it working! That's awesome. I'll dive into AL_ORIENTATION next :)

**Comment by venetanji** [comment]
Ok, I'm a little baffled, I'm trying to understand how this all works, please bear with my ignorance for a second.

So I'm trying to get blender to output to the 24-speaker system and it does send out accurate 3rd-order ambisonic, but only recreating the original speaker configuration specified in blender settings. I've tested with a single source going around the camera and if I set mono, I get all the sound from the front (changing amplitude accordingly to the motion of the object), setting 7.1 gives an ambisonic rendering of 7.1 surround, with no elevation.

I looked into blender to try to understand how it does things, it uses this additional layer audaspace which sets up the sources/listeners etc. It's definitely doing its job, because in 7.1 (and other formats) the output is correct, but I'm not sure at what point this decoding to 7.1 happens and really confused on how it goes back to 3rd order from there.

This only happens in blender, in Minecraft and other games I get the full output, no issues.

I'll keep trying to understand the code, maybe you can point me in the right direction :)

**Comment by kcat** [comment]
By the looks of it, Blender does its own mixing to the specified format and just uses OpenAL to play it. OpenAL Soft virtualizes multichannel buffers, such that each channel is positioned relative to the center listener in the soundfield (so it'll sound like a 7.1 recording encoded into an ambisonic buffer). Unfortunately there's nothing I can do, since Blender already has it mixed before OpenAL Soft touches it. You'd have to ask the Blender devs to add an option to use OpenAL's 3D rendering to get a proper 3D soundfield out of it.

**Comment by venetanji** [comment]
Yeah I thought that was the case, but couldn't really figure out where this is happening in audaspace:

https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob/HEAD:/intern/audaspace/OpenAL/AUD_OpenALDevice.cpp

It's using OpenAL API calls for the sources and listeners, no idea how it does the rendering. I'll dig more into blender!

**Comment by kcat** [comment]
Hmm, that's odd, yeah. It looks like it should be able to do 3D sound rendering through OpenAL, instead of just playing a pre-made mix. I'm not very familiar with Blender so I don't know much about it, though. It might be worth asking them.

**Comment by venetanji** [comment]
Hi @kcat!

It seems this commit has broken higher order output in jack: 
https://github.com/kcat/openal-soft/commit/901804d724d49f316cd2bf51ec1cd2cd9fb9eb91

Creating a context with ambi3 on jack backend will now segfault.

I will look into it, maybe you have an idea why?

Also I have successfully compiled with jack support on windows using msys2/mingw64, we'll be using openal-soft in unity (vr + ambisonic 32-speaker array)

**Comment by kcat** [comment]
Looks like I accidentally inverted a check for allocating the ambisonic upsampler with higher order output, causing it to try initializing a null object. Fixed in commit 44f026220fba39a3211b82d5c1fa5ad071ea461e.

**Comment by kcat** [comment]
Closing as implemented. No idea what was up with Blender, but if that's still an issue hopefully they can help.

**Comment by marijncin** [comment]
> libjack.dll
> Replacing that in the backend implementation was enough for me to get it working! That's awesome. I'll dive into AL_ORIENTATION next :)

Hi, I am also trying to get Jack to run on Windows. sending audio from Unity3D using this example: [https://github.com/rodrigodzf/Jack-Audio-For-Unity](url) . altho everything seems to work okay, I can't get any sound out of it. What exactly did you do get this working? I would be very interested.
