### ISSUE TITLE
Android crash due to potential thread issue

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#500]
My android app crashes momentarily after this line here
```
12-01 12:17:30.099 32761   392 E openal  : [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
```
Followed by this log:
https://gist.github.com/hsdk123/c5fd88482508457c10e3e0c936edb516

Would this seem familiar?

**Comment by kcat** [comment]
The ALSOFT error shouldn't be related to the crash, it's just saying it can't set the mixer thread to real-time priority (which might make it more sensitive to underruns/dropouts, but shouldn't crash). Are you able to get a backtrace from the crash? Does it happen with a debug build?

**Comment by MikuAuahDark** [comment]
Quick look at the logs, looks like the crash is from your app (libLightApp.so), assume you compiled OpenAL-soft as shared object (libopenal.so).

**Comment by hsdk123** [comment]
Seems this was unrelated
