### ISSUE TITLE
when will appear AL_stopped ?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#503]
hello:

I was testing 1.17 version of openal

I found that if I didn't push in the data for a period of time, the status of the openal sound source would become AL_stopped

and，if I  push in the '0x00',sometimes ,will also appear AL_stopped.

I  want to know ，Is there any other situation  the source status is AL_STOPPED?

**Comment by kcat** [comment]
The source status becomes `AL_STOPPED` when it plays to the end of the buffered samples. If you attach a buffer with `alSourcei(source, AL_BUFFER, buffer);` it will become stopped at the end of the sound. If you queue buffers with `alSourceQueueBuffers(source, ...);`, it will become stopped at the end of the last queued buffer. Once a source becomes `AL_STOPPED`, it will stay stopped even if you queue more buffers, until you call `alSourcePlay`.
