### ISSUE TITLE
OGG Audio Clipping

### ISSUE THREAD

**Issue by RobertBColton** [kcat/openal-soft#505]
This issue was reported by an ENIGMA user trying to play an OGG sound in their game.
https://github.com/enigma-dev/enigma-dev/issues/2140

I have created a single SSCCE C++ console program that reproduces the issue outside of ENIGMA for convenience. Included is the source file, the OGG audio file (with user's permission priorly obtained), a simple makefile, and the executable I built on Windows with MSYS2/MinGW64.
Download: [openal-ogg.zip](https://github.com/kcat/openal-soft/files/5683880/openal-ogg.zip)

What happens is that I hear static noise added to the sound on Windows, very different output than VLC Media Player. The user on Linux experiences what they call "clipping" which I assume is short gaps in the audio. After creating this non-ENIGMA related reproducible, I am not sure what to make of the issue. I don't know if it's libogg, libvorbis, Alure, or default configuration of the OpenAL source and or device (especially odd since VLC is actually using libogg if I'm not mistaken). I figured that the OpenAL soft devs would maybe have a better inclination as to what the issue might be, and that is why I am asking that if anybody could be so kind as to help we would greatly appreciate it!

**Comment by kcat** [comment]
I believe this is an issue with libsndfile's Vorbis decoder when samples hit max amplitude for 16-bit output. I get noise/static/clipping with OpenAL Soft's `alstream` example (which uses libsndfile) but not `alffplay` (which uses ffmpeg). With Alure, libvorbisfile should normally take priority for Vorbis files, but if that's been disabled, libsndfile will be used as a fallback.

**Comment by arthurt** [comment]
The OggVorbis file in this issue contains sample data over 0db. I see a peak sample value of 2.4 (3db ish).

It is the explicit behaviour of libsndfile that when reading sample data as an integer type that 0db is mapped to the maximum representation of that integer type. If the audio data is being read as ints or shorts, this is not a bug, it is an explicit behaviour. The audio is clipped because the input file contains out-of-range data.

To play back this audio correctly, it needs to be normalized. Libsndfile includes commands to find the signal max in a file, so that callers can normalize the audio. To read samples greater than 0db, read the data as float or double.

Admittedly, libsndfile does have an issue with how it reports signal max varying over different supported codecs.

**Comment by kcat** [comment]
> It is the explicit behaviour of libsndfile that when reading sample data as an integer type that 0db is mapped to the maximum representation of that integer type. If the audio data is being read as ints or shorts, this is not a bug, it is an explicit behaviour. The audio is clipped because the input file contains out-of-range data.

More than being clipped/clamped, it wraps:
https://github.com/libsndfile/libsndfile/blob/master/src/ogg_vorbis.c#L551

There appears to be no range check before writing to the `short*` buffer (`float_int_mult` seems to be false by default, and requires explicitly setting `SFC_SET_SCALE_FLOAT_INT_READ` on the opened file to attenuate the whole file). So if the vorbis samples exceed `+`/`-1.0`, the integer sample value ends up outside of `+`/`-32767` when read as shorts. Normally one would expect such samples to be clamped to the representable range, but instead libsndfile lets it over/underflow (`+32768+n` becomes `-32768+n`, and similarly `-32769-n` becomes `+32767-n`, which is far more audible than clamping).

Noteworthy also is that int reading has another nasty surprise:
https://github.com/libsndfile/libsndfile/blob/master/src/ogg_vorbis.c#L572

32-bit floating point can't represent `2147483647.0f`. That requires 31 mantissa bits, but a single-precision float only has a 24-bit mantissa. As a result, it gets rounded to `2147483648.0f` at compile time. When that gets converted to a 32-bit int, `+2147483648` is out of range and you get `-2147483648` instead, wrapping even for a file that stays within the `+`/`-1.0` sample range. The next value less than `2147483648.0f` that a float can hold is `2147483520.0f`.

**Comment by RobertBColton** [comment]
Thanks @kcat for directing me to the real libsndfile source of the problem. For now, we've directed the user to normalize their audio for their game using Audacity until libsndfile fixes the normalization. Closing this one out now since it's not your repo's fault.
