### ISSUE TITLE
what is the mean about alcCaptureOpenDevice's param 4,buffersize ?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#507]
hello :
alcCaptureOpenDevice(const ALCchar *devicename, ALCuint frequency, ALCenum format, ALCsizei buffersizeInSamples)
what is mean about the buffersizeInSamples?
is min capture buffersize ? or max? I test some value ,from 20~2000,but I can not confirm it means.

**Comment by kcat** [comment]
It's the minimum buffer size. It means the device will be able to internally hold at least that many samples before you capture/read them. It can potentially hold more, but that's not guaranteed.

**Comment by kcat** [comment]
Closing as resolved.
