### ISSUE TITLE
Stereo Mix record internal voice？

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#508]
hello： 
I use openal and the stereo mix to record the computer internal voice.the stereo mix is 2channel 48000samplerate,and 16bitwidth;
I use the openal record param is 1channel or 2 channel, 8Khz, 16 bit-width;
so ,I want to know Dose the openal  resample（downsampling）？and if I set the openal 1channel，but the stereo_mix's real param is  two channel ,the capture voice is left channel? right ? or mix and resample?

**Comment by kcat** [comment]
OpenAL resamples, yes (or the system does, either way it ensures it's resampled to the requested rate if the device opens). The quality of the resample can vary between devices and systems, but it gets resampled.

If you request a mono format when the device records in stereo, it will typically be a mix of the left and right channels, but it ultimately depends on the device and system. In OpenAL Soft's case, it requests a mono capture input from the system, and if it gets that, it gives the app whatever the system provides. OpenAL doesn't know whether that one channel is just the left or right input or a mix of the two.

**Comment by kcat** [comment]
Closing as resolved.
