### ISSUE TITLE
pulseaudio DONT_MOVE flag is causing trouble

### ISSUE THREAD

**Issue by isjerryxiao** [kcat/openal-soft#509]
This is causing many apps to have no sound output after connecing a new bluetooth headset / connecting a new hdmi monitor, etc. After some research, I found out that according to https://github.com/kcat/openal-soft/commit/346f1ac29368ffff4bc2e0e9dc1f809f077cb5bc, this is temporary and should be addressed later.  
I'm glad to see a fix for this problem. 
Thanks in advance.

**Comment by kcat** [comment]
There's been [a config option](https://github.com/kcat/openal-soft/blob/openal-soft.1.15/alsoftrc.sample#L313) since 1.15 to allow moves with PulseAudio. However, the DONT_MOVE flag isn't used by default since 1.20.

**Comment by isjerryxiao** [comment]
I am on archlinux stable with openal version 1.21.0. Setting this [https://github.com/kcat/openal-soft/blob/openal-soft.1.15/alsoftrc.sample#L313](config option) is still required to allow moves. 
Also, It seems that archlinux is not using any legacy build options.
https://github.com/archlinux/svntogit-packages/blob/packages/openal/trunk/PKGBUILD

**Comment by kcat** [comment]
Make sure you don't have a config file somewhere setting it to false. If you set the `ALSOFT_LOGLEVEL` env var to `3`, OpenAL will print out logging info to `stderr`, which will include what config files its loading and what settings its getting from them.

**Comment by isjerryxiao** [comment]
![image](https://user-images.githubusercontent.com/14978021/105148263-23ff5200-5b3d-11eb-8a38-e1ebb3a6d5e9.png)
There seems to be none.

**Comment by isjerryxiao** [comment]
Also I removed ~/.alsoftrc, openal-info showed
```
[ALSOFT] (II) Key pulse/allow-moves not found
[ALSOFT] (II) Key pulse/adjust-latency not found
[ALSOFT] (II) Key pulse/fix-rate not found
```

**Comment by isjerryxiao** [comment]
Ah the problem is solved.  
AL lib: (II) alc_initconfig: Initializing library v1.19.1-36a084a HEAD  
The application packed its own openal...
Thanks for your patience.
