### ISSUE TITLE
"pi po" noises on android.

### ISSUE THREAD

**Issue by wangii** [kcat/openal-soft#51]
In my project I use OpenALsoft to playback TTS generated by Flite. There are periodical "pi po" noises, trivial but noticeable. 

It appears to happen when switching buffers. I tried to play it in one buffer and there is no such artefacts.

the original file:
[openal.wav.zip](https://github.com/kcat/openal-soft/files/392097/openal.wav.zip)

playback android:
[1.amr.zip](https://github.com/kcat/openal-soft/files/392098/1.amr.zip)

in my codes, I use usleep to wait for any available buffer, is it the right choice?

code snippet:
```
int
speak_stream_chunk_cb(const cst_wave *w,
                      int start,
                      int size,
                      int last,
                      cst_audio_streaming_info *asi)
{
  __android_log_print(4, "LogFilter", "start: %d, size: %d, last: %d", start, size, last);

  Speaker* speaker = (Speaker*)(asi->userdata);

  // pause;
  if(speaker->state == STATE_PAUSE){
    while(true){
      usleep(100 * 1000);
      if(speaker->state != STATE_PAUSE){
        break;
      }
    }
  }

  // stop;
  if(speaker->state == STATE_STOP) {
    return CST_AUDIO_STREAM_STOP;
  }

  SpeakingContext* ctx = speaker->context;

  // pre-buffer;
  if(ctx->pre_bufferred_count < ctx->alBufferCount){

    ALuint buff = *(ctx->alBuffers + ctx->pre_bufferred_count);
    alBufferData(buff,
                 AL_FORMAT_MONO16,
                 (w->samples + start),
                 size,
                 w->sample_rate * w->num_channels);
    alSourceQueueBuffers(ctx->alSource, 1, &buff);

    ctx->pre_bufferred_count += 1;

    if(ctx->pre_bufferred_count == ctx->alBufferCount || last) {
      alSourcePlay(ctx->alSource);
      svrsound_send_event(SPEAKER_EVENT_STARTED, speaker->sender, speaker->uid);
    }
  }else{
    int count = 0;
    alGetSourcei(ctx->alSource, AL_BUFFERS_PROCESSED, &count);

    while(count < 1){
      usleep(100 * 1000);
      alGetSourcei(ctx->alSource, AL_BUFFERS_PROCESSED, &count);
    }

    __android_log_print(4, "LogFilter", "empty buffer count: %d", count);

    ALuint buff;
    alSourceUnqueueBuffers(ctx->alSource, 1, &buff);

    alBufferData(buff,
                 AL_FORMAT_MONO16,
                 (w->samples + start),
                 size,
                 w->sample_rate * w->num_channels);
    alSourceQueueBuffers(ctx->alSource, 1, &buff);
  }

  return CST_AUDIO_STREAM_CONT;
}

void* _SpeakThreadFunc(void* args){

  SpeakArg* arg = (SpeakArg*)args;

  Speaker* speaker = arg->speaker;
  char* text = arg->text;

  // setup context;
  SpeakingContext* ctx = malloc(sizeof(SpeakingContext));

  ctx->pre_bufferred_count = 0;
  ctx->alBufferCount = 2;

  // alBuffers
  ALuint* buffs = malloc(sizeof(ALuint) * ctx->alBufferCount);
  alGenBuffers(ctx->alBufferCount, buffs);
  ctx->alBuffers = buffs;

  // alSource;
  ALuint source;
  alGenSources(1, &source);
  ctx->alSource = source;

  Vector3 p = speaker->pos;
  alSource3f(source, AL_POSITION, p.x, p.y, p.z);
  alSourcef(source, AL_GAIN, speaker->vol);
  speaker->context = ctx;

  // setup flite;
  // voice
  cst_voice* voice = speaker->gender ? new_cmu_us_rms() : new_cmu_us_slt();

  // streaming_info
  cst_audio_streaming_info asi = {0};
  /* asi = new_audio_streaming_info(); */
  asi.min_buffsize = 16000 * 2 * 1 * 0.4;
  asi.asc = speak_stream_chunk_cb;
  asi.userdata = speaker;

  feat_set(voice->features,
           "streaming_info",
           audio_streaming_info_val(&asi));

  // speak
  __android_log_print(4, "LogFilter", "tts will start");
  flite_text_to_speech(text, voice, "stream");
  __android_log_print(4, "LogFilter", "tts call end");

  // done, cleanup;
  feat_remove(voice->features, "streaming_info");
  delete_voice(voice);

  if(speaker->context && speaker->context->alSource){
    int state;

    alGetSourcei(speaker->context->alSource, AL_SOURCE_STATE, &state);
    while(state != AL_PLAYING){
      usleep(100 * 1000);
      alGetSourcei(speaker->context->alSource, AL_SOURCE_STATE, &state);
    }
  }

  __android_log_print(4, "LogFilter", "tts ended");
  /* cst_free(asi); */

  // notify speaker is done;
  svrsound_send_event(SPEAKER_EVENT_ENDED, speaker->sender, speaker->uid);

  // free args;
  free(arg);
  pthread_exit(NULL);
}

```

**Comment by kcat** [comment]
Using ```usleep``` is fine. Just be careful about the sleep length, and make sure you don't end up sleeping too long and let both buffers get processed (which would cause the source to underrun and stop).

From what I can tell, you're only filling the AL buffer with part of the audio, so each buffer keeps skipping which causes the clicking noises. The Flite examples seem to suggest the ```size``` parameter of the callback is the number of samples, while ```alBufferData``` takes the number of bytes, so try multiplying the size by 2.

**Comment by wangii** [comment]
thanks! I did take a mental note about the `size` parameter when reading the doc but still fell at such a silly mistake.

I don't know if you develop & maintain OpenAL-soft as a job or hobby. Is there anyway I can support?

**Comment by kcat** [comment]
The best way to support right now is extra testing (particularly on mobile and OSX), and code submissions for bug fixes and improvements.

**Comment by wangii** [comment]
I don't think folks would use OpenAL-soft on OS X and iOS since both has official OpenAL support, and OpenAL-Soft and OpenAL are interchangeable on API level. It leaves us Android and Windows Phone.  how about we donate through Paypal to get you Android devices?

**Comment by kcat** [comment]
Some people do use OpenAL Soft on OSX because of the available feature set being more standard (e.g. EFX for environmental audio, which Apple's doesn't support), and being more stable. I actually have an Android phone, but I've never really figured out how to use it with my stuff (I have the cross-compiler for it working and can build binaries, but I haven't had any luck getting the emulator to work nor have I figured out how to get things onto the real device to run things there).

**Comment by wangii** [comment]
coming from the iOS side of world, I'd say Android is a disaster for native dev.  documentations, toolchains, standard libraries, emulators are all in poor shape. for example, i have 3 devices and 2 of them has no TTS lib, which is supposed to be part of the standard lib, its OpenSLES URI streaming function has been broken since 5.0, never mention the lacks of curl, openssl and other basic libs. 

I want to support, please let me know when you figure out "how".

**Comment by kcat** [comment]
I'll be sure to post a message about it when I have something.
