### ISSUE TITLE
openal-soft patch for macports

### ISSUE THREAD

**Issue by metbic** [kcat/openal-soft#512]
Dear Sirs!

Could any one of you kindly please take a look at this macports ticket thread?

https://trac.macports.org/ticket/61431

it's about a patch of openal-soft.

Best regards, PS

**Comment by kcat** [comment]
Does commit 1327aca9d7605b33a0f8c0776276187254c3b451 fix the issue?

**Comment by ryandesign** [comment]
Yes it does, thanks. We've applied the patch in MacPorts.
