### ISSUE TITLE
Website HTTPS certificate expired

### ISSUE THREAD

**Issue by rversteegen** [kcat/openal-soft#513]
Hello. The certificate for https://openal-soft.org/ expired today.

I'm very amused to see that the certificate is apparently shared with wiki.allegro.cc, since I visited www.allegro.cc just minutes ago (which is still up).

**Comment by SoapyMan** [comment]
Oh yeah it broke CI/CD. Not quite important to me but idk about other projects

**Comment by kcat** [comment]
Should be fixed now.
