### ISSUE TITLE
alcOpenDevice fails when getting CPU info

### ISSUE THREAD

**Issue by CaptainHorse** [kcat/openal-soft#514]
When trying to open a device with `alcOpenDevice(nullptr);` it throws an error: `"Expression: cannot dereference string iterator because it is out of range (e.g. an end iterator)"`

[I tracked the issue to cpu_caps.cpp line 72](https://github.com/kcat/openal-soft/blob/master/core/cpu_caps.cpp#L72)

**Comment by kcat** [comment]
Should be fixed with commit 537fd6d0a15fda5f4b6ed3f767aa9bf6f15caa21.
