### ISSUE TITLE
alcCaptureSamples returning more samples than buffer size?

### ISSUE THREAD

**Issue by kunal-vzw** [kcat/openal-soft#528]
I'm openining a capture device and specifying a buffer size of 1024 samples (`alcCaptureOpenDevice(..., 1024)`). However, when I query the number of samples available via `alcCaptureSamples(..., &numSamplesAvailable)` (this is happening in an update loop in my code, which executes every frame), there are instances where the number of samples is greater than the buffer size specified at open device time i.e. `numSamplesAvailable > 1024`. 

How is this possible?

**Comment by kcat** [comment]
The buffer size given to `alcCaptureOpenDevice` is the minimum amount the device will be guaranteed to hold. If the call is successful, it won't be less, but it can be more depending on whether the audio system needs or prefers it to be a multiple of some other value or one of a few predefined sizes.

**Comment by kunal-vzw** [comment]
Got it, thanks!
