### ISSUE TITLE
gcc11: error: 'sleep_for' is not a member of 'std::this_thread'

### ISSUE THREAD

**Issue by lnussel** [kcat/openal-soft#529]
Building with gcc11 yields the following error:

> [   53s] /home/abuild/rpmbuild/BUILD/openal-soft-1.21.1/utils/makemhr/loadsofa.cpp:554:27: error: 'sleep_for' is not a member of 'std::this_thread'
> [   53s]   554 |         std::this_thread::sleep_for(std::chrono::milliseconds{50});
> [   53s]       |                           ^~~~~~~~~

Full build log:
https://build.opensuse.org/package/live_build_log/home:lnussel:branches:games/openal-soft/gcc11/x86_64

**Comment by kcat** [comment]
Should be fixed now with commit 302e88dbf0f10224a5b87be4ce43b3fdd9d20184 (can be applied right on top of 1.21.1 if needed).

**Comment by lnussel** [comment]
works, thanks!
