### ISSUE TITLE
Jack error message on Ubuntu

### ISSUE THREAD

**Issue by CreamyCookie** [kcat/openal-soft#53]
I'm getting the following message when I use LibGDX with lwjgl3, which uses OpenAl-Soft:

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

I get this whether or not I'm playing or initializing a sound. Audio works though.

I'm on Ubuntu 16.04. I don't know what else I need to provide, so feel free to ask me about any information you need to fix this.

**Comment by kcat** [comment]
Those messages come from libjack, and unfortunately OpenAL Soft can't control them. OpenAL Soft tries to initialize the JACK backend first by trying to connect to a JACK server, in case that's the user's desired output method. If the server is not running, libjack will print that and fail (letting OpenAL Soft try PulseAudio next, then ALSA, etc), but there doesn't seem to be a way to tell libjack that a failed connection isn't a problem and don't print that.

The best you can do to get rid of those messages, aside from uninstalling the libjack client if you don't need it, is to tell OpenAL Soft to not try the JACK backend. If your distro provided the ```alsoft-config``` utility, run it, and under the Backends tab, right-click on the Disabled Backends box and select Add JACK. Make sure Allow Other Backends remains checked, then click Apply.

If you do not have ```alsoft-config```, then create or edit ```~/.alsoftrc``` and add the lines:
```
[general]
drivers = -jack,
```
Note that the ending comma is important, as it tells OpenAL Soft to try other backends.

**Comment by CreamyCookie** [comment]
@kcat Thanks for the info and quickfix! I've posted it here: jackaudio/jack1#46
