### ISSUE TITLE
What's the difference between these attributes?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#530]
alc_device_specifier 
alc_all_device_specifier
alc_default_all_device_specifier

I didn't find a clear explanation. But when I use them, they return different values to get the device number?
such as my computer have two speaker，stereo mix device,external speaker, sperker in screen...

and this :alclsExtensionPresent? is use for capture ? play ? and what is means?

**Comment by kcat** [comment]
If the device handle given to `alcGetString` is `NULL`:
* `ALC_DEVICE_SPECIFIER` essentially returns a list of available "driver" names, like "OpenAL Soft", "Generic Hardware", "Generic Software", a hardware-specific driver, etc.
* `ALC_ALL_DEVICES_SPECIFIER` returns a list of specific playback device names from the available drivers, like "OpenAL Soft on Speakers (...)".
* `ALC_CAPTURE_DEVICE_SPECIFIER` returns a list of specific capture device names from the available drivers, like "OpenAL Soft on Microphone (...)".

The returned string is a list of strings. For each name, after the null char is another name, and the list ends when encountering an 0-length name:
```c
/* Get all available outputs, and while not at the end of the list... */
const char *names = alcGetString(NULL, ALC_ALL_DEVICES_SPECIFIER);
while(names && *names != '\0')
{
    /* Print the current name, then move the pointer to the next name. */
    printf("%s\n", names);
    names += strlen(names)+1;
}
```

If a valid non-null device handle is given to `alcGetString`:
* `ALC_DEVICE_SPECIFIER` returns the driver name the given device is using.
* `ALC_ALL_DEVICES_SPECIFIER` returns the specific device name the given device plays on (if the device supports the `ALC_ENUMERATE_ALL_EXT` extension, playback devices only).
* `ALC_CAPTURE_DEVICE_SPECIFIER` returns the specific capture name the given device reads from (capture devices only).

 `ALC_DEFAULT_DEVICE_SPECIFIER` returns the driver name that would open a device by default (e.g. if you call `alcOpenDevice(NULL);`).
 `ALC_DEFAULT_ALL_DEVICES_SPECIFIER` returns the specific playback device name that would open by default.
 `ALC_DEFAULT_CAPTURE_DEVICE_SPECIFIER` returns the specific capture device name that would open by default (e.g. if you call `alcCaptureOpenDevice(NULL, ...);`).

These are just single names, not lists.

> and this :alclsExtensionPresent? is use for capture ? play ? and what is means?

That's for checking whether the system or a specific device supports some extension:
```c
if(alcIsExtensionPresent(device, "ALC_ENUMERATE_ALL_EXT"))
    printf("Device supports the ALC_ENUMERATE_ALL_EXT extension\n");
```

**Comment by xuandu** [comment]
thanks
