### ISSUE TITLE
alcGetString(playback_device, ALC_CAPTURE_DEVICE_SPECIFIER) does not generate error?

### ISSUE THREAD

**Issue by MFHava** [kcat/openal-soft#531]
Based on my reading of the specification (OpenAL 1.1), shouldn't the following code fail?

    ALCdevice * dev = alcOpenDevice(nullptr);
    const ALCchar * str = alcGetString(dev, ALC_CAPTURE_DEVICE_SPECIFIER);
    ALCenum err = alcGetError(dev);
    assert(err != ALC_NO_ERROR); //expecting ALC_INVALID_DEVICE as alcOpenDevice returns playback-device, not capture-device...

NOTE:
In my (albeit limited) tests it not only works, but generates more information than ALC_DEVICE_SPECIFIER!
ALC_DEVICE_SPECIFIER simply returns "OpenAL Soft" where as ALC_CAPTURE_DEVICE_SPECIFIER returns "OpenAL Soft on <OutputDevice>"

**Comment by kcat** [comment]
Fixed with commit d750983a58dfc3ea95976dcc5e8d9b8ed19a1a6a.
