### ISSUE TITLE
How to use openal to play audio data to different devices in the same process？

### ISSUE THREAD

**Issue by hy-chao** [kcat/openal-soft#532]
I try to use different devices to play in two threads, but only one device will have sound output at the same time;
Two processes can use different devices to play audio at the same time；

**Comment by kcat** [comment]
Make sure the correct context is set when you try to make AL calls. With OpenAL Soft, you have the `ALC_EXT_thread_local_context` extension so each thread can independently set and use a different context.

**Comment by hy-chao** [comment]
Thank you very much.
Different threads use different devices and play at the same time normally after I use the alcSetThreadContext(...)  instead of the alcMakeContextCurrent(...).
