### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#535]
Hi, are openal functions thread safe?

**Comment by kcat** [comment]
Individually, yes. If there's two threads, one calls `alSource3f(source, AL_POSITION, x, y, z);` at the same time another calls `alSourcef(source, AL_GAIN, 0.5f);` on the same source, the end result is both properties being set to those values as expected.

However, if one thread calls `alSource3f(source, AL_POSITION, x0, y0, z0);` at the same time another calls `alSource3f(source, AL_POSITION, x1, y1, z1);` on the same source, there's no guarantee about which position the source will end up as (though it will be either`{x0,y0,z0}` or `{x1,y1,z1}`; it won't end up as `{x0,y1,z0}` or some undefined mixture).

**Comment by hsdk123** [comment]
Gotcha, that's great to hear, in any event, can I be assured that there won't be any crashes due to attempting to set properties from multiple threads?

**Comment by kcat** [comment]
There shouldn't be any issue with OpenAL Soft. I can't guarantee Creative's or Apple's OpenAL will be thread-safe, but OpenAL Soft is (if you run into any issues, please do report them).

**Comment by hsdk123** [comment]
Neat, sounds great!
