### ISSUE TITLE
MSVC debug build is very slow

### ISSUE THREAD

**Issue by stgatilov** [kcat/openal-soft#540]
I'm trying to switch TheDarkMod from OpenAL 1.19.1 to 1.21.1, and the biggest problem for me is migration from C to C++.

Note that we link all third-party dependencies statically in TDM.

In MSVC world, trying to link together debug and release objects usually gives the following linker errors:
```
4>OpenAL32.lib(mixer_sse41.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in CollisionModel_contacts.obj
4>OpenAL32.lib(mixer_sse41.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in CollisionModel_contacts.obj
```

The first error is due to STL. Basically, debug version of VC++ STL is not binary compatible with release version, so it is forbidden to link them. One solution to this problem is to not use STL.

The second error is about different versions of CRT. It can be solved if library was built with Static Release CRT (/MT), but I think using STL again removes this option.

Note that if a library is implemented in C, then it is perfectly normal to link its release build into debug build of application. Out of 17 third-party libraries TDM uses, 13 are written in C (including OpenAL 1.19.1), and all of them are built as release only.

C++ library without STL can also be combined in release+debug mix. One such example is ImGui library. Another one is FLTK.

---------

Now there is an obvious question: why can't we use debug version of OpenAL for debug TDM application?

Unfortunately, OpenAL is very slow in VC debug build. Up to the point that it cannot stream sound data fast enough. There are two obvious reasons for it:

1. SSE intrinsics are slow without optimization.
2. STL is very slow without optimization and with this stupid "_ITERATOR_DEBUG_LEVEL".

My current plan is to create optimized build of OpenAL with "debug CRT" and "iterator debugging" enabled, and use it in debug build of the game. I'm pretty sure it will fix the point 1 about intrinsics, but I'm not so sure about point 2. If STL is used in tight loops, I'm afraid there would be no way around it.

Here are profiling results of the hottest function in debug build:
![DebugOpenALSlow](https://user-images.githubusercontent.com/13484213/110970333-3b63fa00-838c-11eb-83c8-8d2ae000081a.png)

You might think that using `std::array<X, 2>` is cool, but you can't believe how slow it is in debug build of VC !

I know my use case (static linking) is not encouraged, but... maybe it is possible to avoid using `std::array` everywhere? It can be reimplemented in 5 minutes, and all such platform-specific issues will be gone. Your own wheel would be cross-platform, unlike STL (STL is not cross-platform, only its interface is).

**Comment by stgatilov** [comment]
Would it make sense if I profile TheDarkMod in debug and provide a merge request for fixing such issues?

I can move such hidden function calls to outside the loop.
Or if you are OK with having custom array equivalent, I can provide implementation and switch from std::array.

**Comment by kcat** [comment]
Would it be reasonable to use a DLL when building TDM in debug mode? Actually, having a general option to use a DLL in place of the default static-linked version would be useful. SDL has a built-in option for something like that, but with OpenAL Soft it could be done with function pointers (that default to the static-linked methods).

More to the actual question, though. I'm not keen on the idea of avoiding `std::array`. It seems to me that there should be a way to build a debug version with at least light optimizations to avoid significant overhead from simple inline accessors and intrinsics like that. With GCC there's the `RelWithDebInfo` build type, which is a debug build with optimizations enabled. Does MSVC not have a similar option?

Given what's shown in the screenshot, you could also try disabling HRTF to see if that improves mixing performance enough.

**Comment by stgatilov** [comment]
> Would it be reasonable to use a DLL when building TDM in debug mode? Actually, having a general option to use a DLL in place of the default static-linked version would be useful. SDL has a built-in option for something like that, but with OpenAL Soft it could be done with function pointers (that default to the static-linked methods).

The reasons we don't use DLLs are:
1. If we use library as DLL with statically linked CRT, then the library must not pass memory across DLL boundary (plus some other restrictions like own printf buffers). Perhaps OpenAL is careful to do so, but I'm not sure about other libraries. So it would be some sort of mixed solution: something is linked statically, something dynamically.
2. If we use library as DLL with dynamically linked CRT, then we have to provide CRT. Since we have two executables in same directory, we cannot simply place CRT in that directory (its DLL name does not depend on bitness). Moving executables to their own subdirectories would require changes to paths, which is likely to cause problems (previous attempts did not work well). Using system-wide CRT means we have to install it to players, which means installing TDM would require admin rights (which it does not now). We did try to install VC redistributable from C++ installer, and for some reason it did not work well.

As you see, static linkage for everything is the easiest solution.

> With GCC there's the `RelWithDebInfo` build type, which is a debug build with optimizations enabled. Does MSVC not have a similar option?

RelWithDebInfo is full release with debug information (just as it says). I can build it with MSVC, but it won't differ from release build at all. It won't be compatible with debug application.

Yes, it is possible to do optimized build with these two settings switched to debug, and I will definitely do it. But I'm afraid that iterator debugging will still eat a lot of time in operator[].

> More to the actual question, though. I'm not keen on the idea of avoiding `std::array`. It seems to me that there should be a way to build a debug version with at least light optimizations to avoid significant overhead from simple inline accessors and intrinsics like that. 

I'm not sure operator[] is a simple inline accessor when iterator debugging is enabled. At the very least, it checks if index is out of bounds. I'll build optimized library with iterator debugging, and will report how much time it eats.

**Comment by kcat** [comment]
> If we use library as DLL with statically linked CRT, then the library must not pass memory across DLL boundary (plus some other restrictions like own printf buffers). Perhaps OpenAL is careful to do so, but I'm not sure about other libraries. So it would be some sort of mixed solution: something is linked statically, something dynamically.

You can pass memory across the DLL boundary. What you can't do is something like split `malloc`/`free` across the DLL boundary, or share resources that different C runtimes won't recognize between each other. OpenAL couldn't work as a shared DLL if it wasn't designed with that in mind.

Using certain specific libraries as a DLL can be a build-time option that's intended for debug builds, so you can build your code for debugging without also debugging OpenAL, while the release builds are still static-linked. Or it can be a run-time option. Static-link OpenAL Soft and create a set of function pointers to point to the static-linked OpenAL functions, but at initialization, you can optionally load `OpenAL32.dll` and change them to point to the DLL functions instead. That way, when the audio code calls the function pointers, it'll transparently use either the static-linked OpenAL or the OpenAL DLL without any code changes or recompilation needed.

> Yes, it is possible to do optimized build with these two settings switched to debug, and I will definitely do it. But I'm afraid that iterator debugging will still eat a lot of time in operator[].

With optimizations enabled, the compiler should be pretty good at removing much of the redundant and unnecessary debug work. There will still be some overhead, as you should expect of a debug build whether or not it's also optimized, but it should be more practical to actually run.

**Comment by stgatilov** [comment]
Actually, `_ITERATOR_DEBUG_LEVEL` is by default tied to CRT version: default value is 0 for /MT (release CRT) and 2 for MTd (debug CRT). So in order to make release build "debug-compatible", I only have to change CRT version, which is pretty easy to do in conan.

Interestingly, I'm not the only one who wants to use release third-party libraries with debug build. For instance, Unreal Engine 4 uses release CRT in debug build by default ([link](https://forums.unrealengine.com/development-discussion/c-gameplay-programming/34307-building-engine-with-debug-runtime-library)) to achieve it. TheDarkMod goes the opposite way yet... maybe we should also ditch debug CRT in future.

-----

Anyway, I have compiled OpenAL as "optimized release with debug CRT", and it is pretty fast. Those 54223 samples has gone down to 1994 samples, where it is barely noticeable among other TDM threads. That's perfect for me! =)

Regardless, I'd suggest avoiding STL calls in the most performance-critical loops =)

-----

Speaking of "smart compiler", which should optimize away everything.

Here is std::array<float,2>::operator[] with optimized build and iterator debugging: [ArrayIndexationOptimized.asm.txt](https://github.com/kcat/openal-soft/files/6135153/ArrayIndexationOptimized.asm.txt)
Still a lot of garbage. Most of it is for "fail case", which is never executed, and so only trashes the code. The somewhat lengthy preamble should be removed by inlining.

Here is ApplyCoeffs in Release + Release CRT: [ApplyCoeffs_Release_ReleaseCRT.asm.txt](https://github.com/kcat/openal-soft/files/6135162/ApplyCoeffs_Release_ReleaseCRT.asm.txt)
Here is ApplyCoeffs in Release + Debug CRT: [ApplyCoeffs_Release_DebugCRT.asm.txt](https://github.com/kcat/openal-soft/files/6135163/ApplyCoeffs_Release_DebugCRT.asm.txt)
Assembly with debug CRT is almost three times longer, but it is not much slower. Luckily, optimizer has removed bounds checking for float2[0] accesses, and only the check for HrirArray[i+1] remains.

**Comment by stgatilov** [comment]
My problem is solved, so I close the issue,
