### ISSUE TITLE
Compiler error on SSE intrinsics with GCC 32-bit

### ISSUE THREAD

**Issue by stgatilov** [kcat/openal-soft#541]
Tried to build OpenAL 1.21.1 with gcc 5.4.0 for x86/32-bit, using Linux x86/64-bit.
To be honest, can't say for sure how exactly 32-bit option is set: I pass `-s arch=x86` to conan build. If it is important, I can look it up.

I get compile errors due to SSE intrinsics. The errors look pretty weird to me:
```
In file included from /home/user/tdm/conan_cache/.conan/data/openal/1.21.1/thedarkmod/local/build/582f54fdf8e290e24a7424ad8faa5117ae0c0387/source_subfolder/alc/alcmain.h:22:0,
                 from /home/user/tdm/conan_cache/.conan/data/openal/1.21.1/thedarkmod/local/build/582f54fdf8e290e24a7424ad8faa5117ae0c0387/source_subfolder/alc/alu.cpp:47:
/home/user/tdm/conan_cache/.conan/data/openal/1.21.1/thedarkmod/local/build/582f54fdf8e290e24a7424ad8faa5117ae0c0387/source_subfolder/common/alnumeric.h: In function ‘int float2int(float)’:
/home/user/tdm/conan_cache/.conan/data/openal/1.21.1/thedarkmod/local/build/582f54fdf8e290e24a7424ad8faa5117ae0c0387/source_subfolder/common/alnumeric.h:146:26: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
     return _mm_cvtt_ss2si(_mm_set_ss(f));
                          ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:31:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/32/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/user/tdm/conan_cache/.conan/data/openal/1.21.1/thedarkmod/local/build/582f54fdf8e290e24a7424ad8faa5117ae0c0387/source_subfolder/alc/alu.cpp:25:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h: In function ‘int fastf2i(float)’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:512:1: error: inlining failed in call to always_inline ‘int _mm_cvt_ss2si(__m128)’: target specific option mismatch
 _mm_cvt_ss2si (__m128 __A)
 ^
```
As far as I understand, it means that SSE intrinsics are compiled without setting `-msse` compiler flag. For some reason, it is required by GCC. The problem seems to be similar to [the old issue](https://github.com/kcat/openal-soft/issues/54).

Here is [CMakeCache.txt](https://github.com/kcat/openal-soft/files/6136792/CMakeCache.txt) from the build.

Passing "ALSOFT_REQUIRE_SSE2" to CMake does not help. "ALSOFT_ENABLE_SSE2_CODEGEN" does not help either.

**Comment by stgatilov** [comment]
Bruteforce approach worked:

    self._cmake.definitions["CMAKE_C_FLAGS"] = "-msse2 -mfpmath=sse"
    self._cmake.definitions["CMAKE_CXX_FLAGS"] = "-msse2 -mfpmath=sse"

**Comment by kcat** [comment]
Are you able to show the command line it tried to use when it failed? The `_mm_cvtt_ss2si` and `_mm_cvt_ss2si` calls are done under the `HAVE_SSE_INTRINSICS` macro check, which gets set when
```cmake
    foreach(flag_var ${SSE_FLAGS})
        set(CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS} ${flag_var}")
    endforeach()

    check_c_source_compiles("#include <emmintrin.h>
        int main() {_mm_pause(); return 0;}" HAVE_SSE_INTRINSICS)
```
succeeds in CMake. The `SSE_FLAGS` were added to the project's compiler flags, and should include `-msse2 -mfpmath=sse` if it got to that point with 32-bit GCC.

**Comment by stgatilov** [comment]
I started putting `message` command over the CMake code, and found out that `CMAKE_SIZEOF_VOID_P` is 8 =)
I'm pretty sure it is the problem of conan recipe, and not of OpenAL itself.

Sorry for bothering.

**Comment by stgatilov** [comment]
Here is the conan issue: https://github.com/conan-io/conan-center-index/issues/4889
