### ISSUE TITLE
Check current timepoint that's playing

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#545]
Hi, I was wondering how I'd be able to get the current timepoint (ex. in ms) within the source that openal is currently playing

**Comment by kcat** [comment]
You can get the current time point in bytes, samples, or seconds, which would be easy enough to convert to milliseconds.
```c++
float seconds;
alGetSourcef(source, AL_SEC_OFFSET, &seconds);
```
```c++
int isamples;
alGetSourcei(source, AL_SAMPLE_OFFSET, &isamples);
// or
float fsamples;
alGetSourcef(source, AL_SAMPLE_OFFSET, &fsamples);
```
On some implementations, getting the sample offset as a float may get you some sub-sample precision when the source needs resampling.
```c++
int bytes;
alGetSourcei(source, AL_BYTE_OFFSET, &bytes);
```
Additionally, with OpenAL Soft's [`AL_SOFT_source_latency`](https://openal-soft.org/openal-extensions/SOFT_source_latency.txt) extension, you can get the source's current timepoint as well as the latency indicating how long until that timepoint reaches the DAC (as best can be measured) for the listener to actually hear it. OpenAL Soft will have processed up to the timepoint, but it can take a little time to get to the physical device. Useful for A/V synchronization. These are 64-bit doubles and ints for increased precision.
```c++
double offset[2];
alGetSourcedvSOFT(source, AL_SEC_OFFSET_LATENCY_SOFT, offset);
offset[0]; // source timepoint in seconds
offset[1]; // latency in seconds until that timepoint reaches the DAC.
```
```c++
ALint64SOFT offset[2];
alGetSourcei64v(source, AL_SAMPLE_OFFSET_LATENCY_SOFT, offset);
offset[0]; // source timepoint in 32.32 fixed-point samples
offset[1]; // latency in nanoseconds until that timepoint reaches the DAC.
```

**Comment by hsdk123** [comment]
Thanks for all the info, this looks great!
