### ISSUE TITLE
Is this software still being developed?

### ISSUE THREAD

**Issue by RenanRischiotto** [kcat/openal-soft#549]
The main OpenAL website looks abandoned and amateur looking. This is like Dolby Atmos or DTS:X but its open-source right? Is this being developed full steam or its an abandonware? How many people are developing this?

**Comment by kcat** [comment]
It's sort of like them, from what I understand. It's a real-time 3D audio API, primarily intended for games (though isn't restricted to them). OpenAL Soft specifically is still being developed, by me mostly but I do accept help and contributions, from anyone that's able to.

**Comment by RenanRischiotto** [comment]
Oh I see. Well this API sounds decent, I use on EqualizerAPO+HeSuVi.
