### ISSUE TITLE
[Feature Request] AL_MAX_GAIN > 1.0

### ISSUE THREAD

**Issue by flibitijibibo** [kcat/openal-soft#55]
In XACT, volumes can range from -96.0dB to 6.0dB. This means that the amplitude ratio can range from [0, 2] instead of OpenAL's current limitation of [0,1]. FNA's XACT implementation currently calls alSourcef requesting higher AL_GAIN values, but because of the AL_MAX_GAIN value being clamped, we're stuck with a cap lower than what we need.

I was able to verify this locally by just skipping the clamps altogether...

https://gist.github.com/flibitijibibo/3f46b07df5e0ebba17b25a83d2581b6c

... but I'd love to be able to set AL_MAX_GAIN to higher values! Of course, the spec has stated the limit since 1.0, so I know it'd be a tough change to make (on top of the fact that having a hard maximum is kind of important for safety reasons!). Is there any way we could sidestep this without hacking Alu.c?

**Comment by kcat** [comment]
For OpenAL Soft, a quick'n'dirty workaround would be to double the desired listener gain and halve the desired gain of *all* sources. So a normal listener gain of 1.0 becomes 2.0, and a normal source gain of 1.0 becomes 0.5, which results in a normal mix gain of 1.0. But a desired source gain of 2.0 to become 1.0, which results in a mix gain of 2.0. The source gain clamping happens before the listener gain is applied (after distance attenuation, before filters and listener gain), so the listener gain can raise a source's output above 0dB.

I certainly wouldn't mind adding an extension to allow AL_MAX_GAIN > 1.0, though I wonder if the max limit should be raised to 2, 4, etc, or be completely unbounded.

**Comment by flibitijibibo** [comment]
A possible extension could be something like AL_SOFT_source_gain_clamp_control, where a context could specify both the lowest MIN and the highest MAX, allowing more flexibility with these parameters but still allowing boundaries to prevent dangerous volumes from being played. In our case, because volumes can be multiplied on top of each other, there's definitely a risk of 6dB values constantly multiplying into something really loud, so I'd probably cap it _somewhere_ for safety reasons, but unfortunately I don't know what a fixed value would be. In one instance, for example, the final AL_GAIN for a single XACT cue turned out to be ~5.5! Made sense for this dialog WaveBank, but yeah... pretty scary for a properly normalized metal song. :P

**Comment by flibitijibibo** [comment]
Here's an initial scribbling of such an extension:

```
diff --git a/Alc/ALc.c b/Alc/ALc.c
index dbda46f..2a3fd1b 100644
--- a/Alc/ALc.c
+++ b/Alc/ALc.c
@@ -715,7 +715,8 @@ static const ALchar alExtList[] =
     "AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES "
     "AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates "
     "AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM "
-    "AL_SOFT_source_latency AL_SOFT_source_length";
+    "AL_SOFT_source_gain_clamp_control AL_SOFT_source_latency "
+    "AL_SOFT_source_length";
 
 static ATOMIC(ALCenum) LastNullDeviceError = ATOMIC_INIT_STATIC(ALC_NO_ERROR);
 
@@ -2314,6 +2315,8 @@ static ALvoid InitContext(ALCcontext *Context)
     Context->DopplerFactor = 1.0f;
     Context->DopplerVelocity = 1.0f;
     Context->SpeedOfSound = SPEEDOFSOUNDMETRESPERSEC;
+    Context->MinGainLimit = 1.0f;
+    Context->MaxGainLimit = 1.0f;
     ATOMIC_INIT(&Context->DeferUpdates, AL_FALSE);
 
     Context->ExtensionList = alExtList;
diff --git a/OpenAL32/Include/alMain.h b/OpenAL32/Include/alMain.h
index 3b6113e..f6df0e4 100644
--- a/OpenAL32/Include/alMain.h
+++ b/OpenAL32/Include/alMain.h
@@ -727,6 +727,8 @@ struct ALCcontext_struct {
     volatile ALfloat DopplerFactor;
     volatile ALfloat DopplerVelocity;
     volatile ALfloat SpeedOfSound;
+    volatile ALfloat MinGainLimit;
+    volatile ALfloat MaxGainLimit;
     ATOMIC(ALenum) DeferUpdates;
 
     RWLock PropLock;
diff --git a/OpenAL32/alSource.c b/OpenAL32/alSource.c
index 0e98f2f..f2c158d 100644
--- a/OpenAL32/alSource.c
+++ b/OpenAL32/alSource.c
@@ -453,14 +453,14 @@ static ALboolean SetSourcefv(ALsource *Source, ALCcontext *Context, SourceProp p
             return AL_TRUE;
 
         case AL_MIN_GAIN:
-            CHECKVAL(*values >= 0.0f && *values <= 1.0f);
+            CHECKVAL(*values >= 0.0f && *values <= Context->MinGainLimit);
 
             Source->MinGain = *values;
             DO_UPDATEPROPS();
             return AL_TRUE;
 
         case AL_MAX_GAIN:
-            CHECKVAL(*values >= 0.0f && *values <= 1.0f);
+            CHECKVAL(*values >= 0.0f && *values <= Context->MaxGainLimit);
 
             Source->MaxGain = *values;
             DO_UPDATEPROPS();
@@ -2820,8 +2820,14 @@ static void UpdateSourceProps(ALsource *source, ALuint num_sends, ALCcontext *co
     ATOMIC_STORE(&props->Pitch, source->Pitch, almemory_order_relaxed);
     ATOMIC_STORE(&props->Gain, source->Gain, almemory_order_relaxed);
     ATOMIC_STORE(&props->OuterGain, source->OuterGain, almemory_order_relaxed);
-    ATOMIC_STORE(&props->MinGain, source->MinGain, almemory_order_relaxed);
-    ATOMIC_STORE(&props->MaxGain, source->MaxGain, almemory_order_relaxed);
+    ATOMIC_STORE(&props->MinGain,
+        clampf(source->MinGain, 0.0f, context->MinGainLimit),
+        almemory_order_relaxed
+    );
+    ATOMIC_STORE(&props->MaxGain,
+        clampf(source->MaxGain, 0.0f, context->MaxGainLimit),
+        almemory_order_relaxed
+    );
     ATOMIC_STORE(&props->InnerAngle, source->InnerAngle, almemory_order_relaxed);
     ATOMIC_STORE(&props->OuterAngle, source->OuterAngle, almemory_order_relaxed);
     ATOMIC_STORE(&props->RefDistance, source->RefDistance, almemory_order_relaxed);
diff --git a/OpenAL32/alState.c b/OpenAL32/alState.c
index 443ab88..a3c4960 100644
--- a/OpenAL32/alState.c
+++ b/OpenAL32/alState.c
@@ -663,3 +663,24 @@ AL_API ALvoid AL_APIENTRY alProcessUpdatesSOFT(void)
 
     ALCcontext_DecRef(context);
 }
+
+AL_API ALvoid AL_APIENTRY alMinMaxGainClampSOFT(ALfloat min, ALfloat max)
+{
+    ALCcontext *context;
+
+    context = GetContextRef();
+    if(!context) return;
+
+    if(!(min > 0.0f || max > 0.0f || min < max))
+        SET_ERROR_AND_GOTO(context, AL_INVALID_VALUE, done);
+
+    WriteLock(&context->PropLock);
+    context->MinGainLimit = min;
+    context->MaxGainLimit = max;
+    if(!ATOMIC_LOAD(&context->DeferUpdates, almemory_order_acquire))
+        UpdateAllSourceProps(context);
+    WriteUnlock(&context->PropLock);
+
+done:
+    ALCcontext_DecRef(context);
+}
diff --git a/include/AL/alext.h b/include/AL/alext.h
index 6af581a..f05429c 100644
--- a/include/AL/alext.h
+++ b/include/AL/alext.h
@@ -383,6 +383,14 @@ AL_API ALvoid AL_APIENTRY alProcessUpdatesSOFT(void);
 /*#define AL_SEC_LENGTH_SOFT                       0x200B*/
 #endif
 
+#ifndef AL_SOFT_source_gain_clamp_control
+#define AL_SOFT_source_gain_clamp_control 1
+typedef ALvoid (ALC_APIENTRY*LPALMINMAXGAINCLAMPSOFT)(ALfloat min, ALfloat max);
+#ifdef AL_ALEXT_PROTOTYPES
+AL_API ALvoid AL_APIENTRY alMinMaxGainClampSOFT(ALfloat min, ALfloat max);
+#endif
+#endif
+
 #ifndef ALC_SOFT_pause_device
 #define ALC_SOFT_pause_device 1
 typedef void (ALC_APIENTRY*LPALCDEVICEPAUSESOFT)(ALCdevice *device);
```

The only issue is how initialize and update the source MinGain/MaxGain properties. This patch only deals with the alSourcef call once the new limits are applied and clamps values greater than the limit when the limit is made lower later.

**Comment by kcat** [comment]
I don't see the point in having the app specify the values for what it can specify for the min/max gain (it's specifying what it can specify?). I'd rather just declare a new max value that ```AL_MIN_GAIN``` and ```AL_MAX_GAIN``` can be set to (whether it would be 2, 4, 128, 32768, FLT_MAX...). Or possibly leave it implementation-defined with a query for the implementation's max.

Since implementations are already free to clamp ```source_gain * listener_gain``` as needed to avoid overflow, it might make sense to have the max be FLT_MAX, with a query to get the effective gain limit an implementation may have to avoid overflow.

**Comment by flibitijibibo** [comment]
That'd work for me. Whatever makes the most sense to you will almost certainly work for me; you see way more data than I do and we don't need anything terribly fancy!

**Comment by flibitijibibo** [comment]
One more patch that simply removes the max gain limit and adds an enum to query the max gain limit, as discussed previously:

```
diff --git a/Alc/ALc.c b/Alc/ALc.c
index dbda46f..95b7292 100644
--- a/Alc/ALc.c
+++ b/Alc/ALc.c
@@ -715,7 +715,8 @@ static const ALchar alExtList[] =
     "AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES "
     "AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates "
     "AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM "
-    "AL_SOFT_source_latency AL_SOFT_source_length";
+    "AL_SOFT_source_gain_limit_query AL_SOFT_source_latency "
+    "AL_SOFT_source_length";
 
 static ATOMIC(ALCenum) LastNullDeviceError = ATOMIC_INIT_STATIC(ALC_NO_ERROR);
 
diff --git a/OpenAL32/alSource.c b/OpenAL32/alSource.c
index 0e98f2f..5388c86 100644
--- a/OpenAL32/alSource.c
+++ b/OpenAL32/alSource.c
@@ -453,14 +453,14 @@ static ALboolean SetSourcefv(ALsource *Source, ALCcontext *Context, SourceProp p
             return AL_TRUE;
 
         case AL_MIN_GAIN:
-            CHECKVAL(*values >= 0.0f && *values <= 1.0f);
+            CHECKVAL(*values >= 0.0f);
 
             Source->MinGain = *values;
             DO_UPDATEPROPS();
             return AL_TRUE;
 
         case AL_MAX_GAIN:
-            CHECKVAL(*values >= 0.0f && *values <= 1.0f);
+            CHECKVAL(*values >= 0.0f);
 
             Source->MaxGain = *values;
             DO_UPDATEPROPS();
diff --git a/OpenAL32/alState.c b/OpenAL32/alState.c
index 443ab88..61952b5 100644
--- a/OpenAL32/alState.c
+++ b/OpenAL32/alState.c
@@ -233,6 +233,9 @@ AL_API ALfloat AL_APIENTRY alGetFloat(ALenum pname)
         value = (ALfloat)ATOMIC_LOAD(&context->DeferUpdates, almemory_order_acquire);
         break;
 
+    case AL_MAX_GAIN_LIMIT_SOFT:
+        value = (ALfloat)FLT_MAX;
+
     default:
         SET_ERROR_AND_GOTO(context, AL_INVALID_ENUM, done);
     }
diff --git a/include/AL/alext.h b/include/AL/alext.h
index 6af581a..1cbaaa5 100644
--- a/include/AL/alext.h
+++ b/include/AL/alext.h
@@ -383,6 +383,11 @@ AL_API ALvoid AL_APIENTRY alProcessUpdatesSOFT(void);
 /*#define AL_SEC_LENGTH_SOFT                       0x200B*/
 #endif
 
+#ifndef AL_SOFT_source_gain_limit_query
+#define AL_SOFT_source_gain_limit_query 1
+#define AL_MAX_GAIN_LIMIT_SOFT                   0x1337 /* FIXME: ??? -flibit */
+#endif
+
 #ifndef ALC_SOFT_pause_device
 #define ALC_SOFT_pause_device 1
 typedef void (ALC_APIENTRY*LPALCDEVICEPAUSESOFT)(ALCdevice *device);
```

Obviously the enum value should be something that makes more sense, and there's almost certainly a better extension name, but this is what it could look like.

**Comment by kcat** [comment]
I think ```AL_SOFT_source_gain_clamp_ex``` or ```AL_SOFT_gain_clamp_ex``` may be a good name, since it's extending the gain clamping mechanism (by removing the source's AL_MAX_GAIN limit, and adding a query for the implicit maximum combined gain level).

**Comment by flibitijibibo** [comment]
Patch updated for the new extension name, and also picked out an enum value based on recent extensions' enums.

**Comment by flibitijibibo** [comment]
This is effectively fixed by https://github.com/kcat/openal-soft/commit/54649851fa8769c2290741c63e2255b13eec3824, though developers planning to use it may want to wait until it's AL_SOFT rather than AL_SOFTX.

**Comment by justinfx** [comment]
Hi. I was looking for a solution to this exact problem and came across this merged fix that lifts the cap on max gain. Is this going to be tagged and released anytime soon? I see the last tagged release was in Jan.

**Comment by kcat** [comment]
AL_SOFT_gain_clamp_ex is now finalized with commit 67c74e858bca5946cd4d0b5ccc912364a147e111, so feel free to start using it. If there's any remaining issues, please let me know here or open a new issue.

> Is this going to be tagged and released anytime soon?

I can't say exactly when, but it probably won't be too long (relatively speaking). I would expect a new release this year, as long as nothing serious crops up.
