### ISSUE TITLE
supported extension AL_SOFT_source_length not implemented?

### ISSUE THREAD

**Issue by Voax001** [kcat/openal-soft#556]
The extension "AL_SOFT_source_length" does not appear to be implemented, even though it is listed as supported.

`alIsExtensionPresent("AL_SOFT_source_length")` returns true, but calling e.g.:
`alGetSourcedvSOFT(state.m_alSource, AL_SEC_LENGTH_SOFT, &queueLen)` or `alGetSourcef `
prints the following error message:

> [ALSOFT] (EE) Unexpected property: 0x200b
> [ALSOFT] (WW) Error generated on context 00000298D168D870, code 0xa002, "Invalid source double property 0x200b"

where indeed 0x200b is AL_SEC_LENGTH_SOFT: 
`#define AL_SEC_LENGTH_SOFT                       0x200B`

A quick search through the repository shows that `AL_SEC_LENGTH_SOFT` or indeed any of the other symbols defined in the extension, `AL_BYTE_LENGTH_SOFT` and `AL_SAMPLE_LENGTH_SOFT` only appear in `alGetBufferiv` and `alGetBufferfv` but not in `alGetSourcef` or `alGetSourcei`, even though the extension states they should be accepted by `alGetSource`: https://github.com/openalext/openalext/wiki/AL_SOFT_source_length

**Comment by kcat** [comment]
Odd. Not sure what happened there, they must have been lost at some point when the buffer queue handling was being changed. Fixed in commit 784dbd7d21f36b0dbf034e7ac5d46cdc5533b91b.
