### ISSUE TITLE
Build failure on Visual Studio 2019

### ISSUE THREAD

**Issue by mlugo2** [kcat/openal-soft#568]
OS: Windows 10

Including output build log, not sure what other information is needed.

[Output-Build.txt](https://github.com/kcat/openal-soft/files/6481736/Output-Build.txt)

**Comment by lieff** [comment]
```
2>auxeffectslot.cpp
2>C:\msys64\usr\include\sys/cdefs.h(713,1): warning C4005: '__guarded_by': macro redefinition
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\concurrencysal.h(354): message : see previous definition of '__guarded_by'
2>C:\msys64\usr\include\sys/_intsup.h(71,1): fatal error C1189: #error:  "Unable to determine type definition of intptr_t"
```
There obviously mess-up msvc headers with msys headers. Nothing to do with openal itself.

**Comment by mlugo2** [comment]
Should I build with an older visual studio?

**Comment by mlugo2** [comment]
Ok, I think it was trying to use the msys libraries.  So I uninstalled it and deleted all the files, then ran "cmake .." again in the build file.  Now it compiles perfectly.
