### ISSUE TITLE
No support for enumerating devices on macOS

### ISSUE THREAD

**Issue by aisuneko** [kcat/openal-soft#572]
based on the issue referenced [here](https://github.com/telegramdesktop/tdesktop/issues/16360), it seems that your backend doesn't support multiple sound devices on macOS.
https://github.com/kcat/openal-soft/blob/8d868ff33f1c7ddf4c24e40215731a6d0721d182/alc/backends/coreaudio.cpp#L675-L687

**Comment by monaghanwashere** [comment]
+1 I have also hit this issue now.

We would like our application to allow the user to select a different output device on Mac OS X, but seems like OpenAL Soft only ever lists "Core Audio Default" as the only device, regardless of what output devices are actually available/connected...

**Comment by kcat** [comment]
Device enumeration for non-iOS/TV devices should work with commit 04a6e418d7c614e7ccab560d4f0084fa50587e26, for playback devices. Presuming it's working correctly, I will be able to extend it to capture, too.

**Comment by monaghanwashere** [comment]
Thanks for the quick turnaround! I'm testing this currently, and it seems like it has broken the ability to get the loopback device name, i.e. 

`const ALchar* deviceName = alcGetString(mDevice, ALC_ALL_DEVICES_SPECIFIER);`

now returns NULL when `mDevice` is a loopback device (it previously would return 'Loopback')

**Comment by kcat** [comment]
That would be a separate issue, caused by commit d750983a58dfc3ea95976dcc5e8d9b8ed19a1a6a.

**Comment by monaghanwashere** [comment]
I see; does this mean that the Loopback device is a capture device and not a playback device?

**Comment by kcat** [comment]
No, it meant the loopback devices didn't have an "all_devices" name. I just recently changed this with commit d28cf80b6f9801690cde3d64d638f2ed785dd3a6 so querying the loopback device's all_devices name now returns the basic/device name (`"OpenAL Soft"`), since that's the only valid name that can be used to open it.

**Comment by monaghanwashere** [comment]
Gotcha. I've been testing this on OS X and so far it seems to work promisingly. Unless I'm mistaken, however, the device naming paradigm isn't consistent across platforms. On Windows for egs, device names are prefixed by `OpenAL Soft on`, but this is not the case on OS X. Is it possible to have them be consistent?

**Comment by kcat** [comment]
The issue there is, on Windows there's the possibility of a user/app using a router DLL that exposes the same devices with multiple drivers/implementations, which can have different performance and capability characteristics. So if you have a `Sound Blaster X-Fi`, for example, a hardware driver can provide a `"Sound Blaster X-Fi"` device, while the wrapper driver can provide the same device as `"Generic Software on Sound Blaster X-Fi"`, and OpenAL Soft would provide the device as `"OpenAL Soft on Sound Blaster X-Fi"`. Unfortunately this naming scheme is not handled by the router itself, and the driver/implementation can't tell the difference between being used directly by the app or being used through the router, so it has to inherently name its devices this way to avoid conflicts.

On macOS, Linux, and other OSs, there isn't a router, so it's impossible for the same device to be provided by multiple implementations. Having all devices prefixed with `OpenAL Soft on` is unnecessary, redundant, and ugly, so it's preferred to leave it off and just provide the actual device name like other parts of the system show it.

Having an option to remove the `OpenAL Soft on` part even on Windows would be nice. I just don't want to have separate 'for-router' and 'not-for-router' builds, so would need to figure out a way to detect if a router is used or not. Though there's also the concern that the device names might be better to stay consistent on the same system/OS, so if the router is removed and OpenAL Soft used directly, the same names will still work for configuration and enumeration.

**Comment by kcat** [comment]
Commit fb2cb2bd064c681defda5f1019faa5189ec3bb34 attempts to add support for capture device enumeration on OSX. It should be checked to ensure the proper names are being reported, and the app can properly select them.

**Comment by monaghanwashere** [comment]
Thanks! I will test this in the near future. In the meanwhile, I had another device enumeration observation. On Android, the only device enumerated seems to be OpenSL (for egs, I connected bluetooth headphones, but I still only see OpenSL in the enumeration list). Is this by design? And if so, are there any plans/ways to get a list of audio devices connected on Android?

**Comment by kcat** [comment]
The Android/OpenSL backend doesn't support enumeration yet, for a similar reason OSX didn't. No clear or obvious way to do it. I'm actually not sure if Android allows enumerating through the OpenSL API. The Oboe API for Android says I'd need to use Java to get a list of device IDs, which isn't terribly easy to do from C/C++, and says the specified deviceId is ignored if it uses OpenSL under the hood.

**Comment by monaghanwashere** [comment]
I see. Is this also the case for iOS? i.e. does device enumeration support exist for iOS ?

**Comment by kcat** [comment]
In general? I don't know. But apparently the code used for enumerating devices doesn't compile on iOS, so if it can enumerate, it's done differently.

**Comment by kcat** [comment]
If enumeration on OSX still has issues, let me know and this can be reopened. If there's information about enumerating and selecting audio devices on iOS specifically, feel free to open a new issue for that.
