### ISSUE TITLE
I want to ask a question about the maximum number of playback channels?

### ISSUE THREAD

**Issue by xuandu** [kcat/openal-soft#573]
I have seen this description on the Internet, openal supports up to 32 sound-effects；
but in windows ,linux ,macOS ,I can new num:200 OBJ  ,every OBJ  to do :
alGenSources(1, &m_nSource[0-199]);  alSourcePlay(m_nSource[0~199]);  it will success;No blocking；
So I don’t know what went wrong; how to understand the maximum number of plays？

What is it related to? device ？ hard？the  number of  Object？

the max number of my question no the channel of one Source. I want to know the max Parallel-play number.

**Comment by kcat** [comment]
The number of sound sources is implementation-dependent. Some implementations may depend on hardware, others may depend on user configuration, and others may just have a fixed amount.

You can query the number of sources like this:
```c
ALCint num_mono, num_stereo, total_count;
alcGetIntegerv(device, ALC_MONO_SOURCES, 1, &num_mono);
alcGetIntegerv(device, ALC_STEREO_SOURCES, 1, &num_stereo);
total_count = num_mono + num_stereo;
```
You can safely allocate `total_count` sources, and you're guaranteed to be able to play `num_mono` mono sounds and `num_stereo` stereo sounds all at the same time, on the device. You may be able to play more, but it's not guaranteed.

**Comment by xuandu** [comment]
In fact, although I really created more than 200 objects to turn on more than 200 sound sources to play different audio files, I can not guarantee whether they are actually played, because I can only hear three or four of them.

I'm actually curious about the relationship between sound source, device and context, but the explanation（Framework dependencies） on the Internet is very vague;

thanks.
