### ISSUE TITLE
Build as a static library on Windows?

### ISSUE THREAD

**Issue by Leadwerks** [kcat/openal-soft#577]
I want to build openaL-soft as a pure static library so the user will not have to copy a DLL file with their executable. I tried changing the configuration type of "static library" in the project settings and I changed the "dll" option to "lib" in advanced settings, but the resulting static library does not appear to link when I import it into another project.

**Comment by kcat** [comment]
Pass `-DLIBTYPE=STATIC` to CMake. You'll also need to define `AL_LIBTYPE_STATIC` in your project where you include OpenAL Soft's headers.

**Comment by Leadwerks** [comment]
> Pass `-DLIBTYPE=STATIC` to CMake. You'll also need to define `AL_LIBTYPE_STATIC` in your project where you include OpenAL Soft's headers.

What does that actually mean? How do I "pass" a value to cmake?
