### ISSUE TITLE
iOS compile error in coreaudio.cpp  

### ISSUE THREAD

**Issue by 36yang** [kcat/openal-soft#583]
AudioDeviceID and AudioHardwarePropertyID are not defined on iOS

**Comment by 36yang** [comment]
help help help

**Comment by kcat** [comment]
Try now with commit c8cfdf6ddf22dd2055e7f0850aee45b7d7eecf9c.

**Comment by 36yang** [comment]
Stiil have some problems at audiocor.cpp
 line 376  to line 381:   audioDevice
line  916:   DeviceEntry

**Comment by kcat** [comment]
Fixed with commit 10d782502a9f99d42b56e034d2195ee0dc5034fb.

**Comment by 36yang** [comment]
Build success now!
