### ISSUE TITLE
AL_EXT_STATIC_BUFFER?

### ISSUE THREAD

**Issue by Micha0** [kcat/openal-soft#590]
Going through the alext.h source header, it seems the extension `AL_EXT_STATIC_BUFFER` is available. But whenever I try to hook it up it's failing.
```
alGetProcAddress("alBufferDataStatic") == nullptr
alcGetProcAddress(myDevice, "alBufferDataStatic") == nullptr
```
When I search the source it seems its not there, correct?

What would be the best approach of getting this or similar functionality into openal-soft? I like that `alBufferDataStatic` has a much cleaner and simpler API than `AL_SOFT_map_buffer` or `AL_SOFTX_callback_buffer`, which, if I understand that correctly, would be the alternative.

**Comment by kcat** [comment]
`AL_EXT_STATIC_BUFFER` is something Apple implemented in their implementation, and it was included in `alext.h` to allow code that (optionally) uses it to compile, even if it may not exist at run-time. OpenAL Soft doesn't currently implement it.

> What would be the best approach of getting this or similar functionality into openal-soft? I like that `alBufferDataStatic` has a much cleaner and simpler API than `AL_SOFT_map_buffer` or `AL_SOFTX_callback_buffer`, which, if I understand that correctly, would be the alternative.

The problem with `alBufferDataStatic` is that it's a very unsafe design. There's nothing to stop the pointer from being deleted (or reallocated which may or may not move it depending on a number of uncontrolled factors) while the buffer still has it, or while a source is still using it. This could happen inadvertently in a way in which the program still works, until some completely unrelated change elsewhere in the code or on the system causes it to start crashing in places that don't make it obvious where the error is. There's no alignment requirements, and no protection against things like being given mmap'd files (which can seem to work fine in some systems but fail sporadically on others).

It also can't use some advertised formats, with no way for an app to know which ones can or can't work, aside from trying and testing for failure (which is not a good way to check for support). Though admittedly the map_buffer and callback_buffer extensions have this same flaw, the former at least being fixable with internal double-buffering.

**Comment by Micha0** [comment]
Thanks Chris!
I am aware of the safety risks and the potential can of UBs you open up with if you'd use `alBufferDataStatic` incorrectly. But for memory constrained platforms, it's a welcome addition. And for me personally, I would not add double buffering to map_buffer either, as that would turn map_buffer into `alBufferData`. (Well, almost.)

**Comment by SephiRok** [comment]
This would actually be nice to have. Already for the performance case of not needing to perform a copy of the data after it's been decoded. The unsafe design aspect could be said about memory pointers in general. Maybe it would make sense to provide it with the down-to-the-metal C-style mentaility?
