### ISSUE TITLE
WASAPI Noise issue

### ISSUE THREAD

**Issue by Kasell777** [kcat/openal-soft#595]
Hello?

Playing audio using "WASAPI Backend" causes noise from certain audio files.

Changing the values "mmap" and "periods" showed the same result.

Please give me an advice.

Thank you.

```
[ALSOFT] (II) Got binary: D:\Visual Studio Projects\openal-impl-vid1\x64\Debug, openal-impl.exe
[ALSOFT] (II) Loading config D:\Visual Studio Projects\openal-impl-vid1\x64\Debug\alsoft.ini...
[ALSOFT] (II)  found 'drivers' = 'wasapi'
[ALSOFT] (II)  found 'mmap' = 'off'
[ALSOFT] (II)  found 'periods' = '16'
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 5 5600X 6-Core Processor"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Found drivers = "wasapi"
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Message thread initialization complete
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Initialized backend "wasapi"
[ALSOFT] (II) Added "wasapi" for playback
[ALSOFT] (II) Added "wasapi" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Got message "Open Device" (0x0000, this=0000021A155AD790)
[ALSOFT] (II) Key channels not found
[ALSOFT] (II) Key sample-type not found
[ALSOFT] (II) Key frequency not found
[ALSOFT] (II) Key period_size not found
[ALSOFT] (II) Found periods = "16"
[ALSOFT] (II) Key sources not found
[ALSOFT] (II) Key slots not found
[ALSOFT] (II) Key sends not found
[ALSOFT] (II) Key ambi-format not found
[ALSOFT] (II) Created device 0000021A155C2C90, "OpenAL Soft on [ALSOFT] (II) Key hrtf not found
[ALSOFT] (II) Pre-reset: Stereo, Float32, 44100hz, 882 / 14112 buffer
[ALSOFT] (II) Got message "Reset Device" (0x0001, this=0000021A155AD790)
[ALSOFT] (II) Requesting playback format:
    FormatTag      = 0xfffe
    Channels       = 2
    SamplesPerSec  = 48000
    AvgBytesPerSec = 384000
    BlockAlign     = 8
    BitsPerSample  = 32
    Size           = 22
    Samples        = 32
    ChannelMask    = 0x3
    SubFormat      = {00000003-0000-0010-8000-00aa00389b71}
[ALSOFT] (II) Post-reset: Stereo, Float32, 48000hz, 960 / 15360 buffer
[ALSOFT] (II) Key stereo-mode not found
[ALSOFT] (II) Key cf_level not found
[ALSOFT] (II) Key stereo-encoding not found
[ALSOFT] (II) Stereo rendering
[ALSOFT] (II) Channel config, Main: 3, Real: 2
[ALSOFT] (II) Allocating 5 channels, 20480 bytes
[ALSOFT] (II) Enabling single-band first-order ambisonic decoder
[ALSOFT] (II) Max sources: 256 (255 + 1), effect slots: 64, sends: 2
[ALSOFT] (II) Key dither not found
[ALSOFT] (II) Key dither-depth not found
[ALSOFT] (II) Dithering disabled
[ALSOFT] (II) Key output-limiter not found
[ALSOFT] (II) Output limiter disabled
[ALSOFT] (II) Fixed device latency: 0ns
[ALSOFT] (II) Got message "Start Device" (0x0002, this=0000021A155AD790)
[ALSOFT] (II) Increasing allocated voices to 256
[ALSOFT] (II) Key volume-adjust not found
[ALSOFT] (II) Created context 0000021A155E4FE0
```

**Comment by kcat** [comment]
The `mmap` option won't do anything since it's not a general option (it's for ALSA only). `periods=16` will add a lot of latency, though it could help if it was a result of underruns, so if it doesn't, that indicates it's not an underrun problem (you can remove that option to lower the latency back down, if you haven't already).

If you only get noise from certain sound files, first make sure the files are being decoded correctly. What are you using to decode them, and how are you loading them? When you say it "causes noise from certain audio files", does that mean an odd click or pop, or is it more like constant static or distortion?

**Comment by Kasell777** [comment]
The file format is ".ogg" and is loading the file in the same format as the "alplay" example.

The audio is mostly output normally, but there is a crackling sound in the loudest part.

The file that causes the problem is the file below.
[https://drive.google.com/file/d/17nusyjjiavZvZ00i2fCNZjEpBwdb3nAt/view?usp=sharing](url)

The points at which "crackling sound" is expected to occur are as follows.
![Wave](https://user-images.githubusercontent.com/49906265/132113171-d10619aa-be88-4e13-8b64-27e7937d9a93.png)

The code used to load the file is as follows.

    ALenum err, format;
	ALuint buffer;
	SNDFILE* sndfile;
	SF_INFO sfinfo;
	short* membuf;
	sf_count_t num_frames;
	ALsizei num_bytes;

	/* Open the audio file and check that it's usable. */
	sndfile = sf_open(filename, SFM_READ, &sfinfo);
	if (!sndfile)
	{
		fprintf(stderr, "Could not open audio in %s: %s\n", filename, sf_strerror(sndfile));
		return 0;
	}
	if (sfinfo.frames < 1 || sfinfo.frames >(sf_count_t)(INT_MAX / sizeof(short)) / sfinfo.channels)
	{
		fprintf(stderr, "Bad sample count in %s (%" PRId64 ")\n", filename, sfinfo.frames);
		sf_close(sndfile);
		return 0;
	}

	/* Get the sound format, and figure out the OpenAL format */
	format = AL_NONE;
	if (sfinfo.channels == 1)
		format = AL_FORMAT_MONO16;
	else if (sfinfo.channels == 2)
		format = AL_FORMAT_STEREO16;
	else if (sfinfo.channels == 3)
	{
		if (sf_command(sndfile, SFC_WAVEX_GET_AMBISONIC, NULL, 0) == SF_AMBISONIC_B_FORMAT)
			format = AL_FORMAT_BFORMAT2D_16;
	}
	else if (sfinfo.channels == 4)
	{
		if (sf_command(sndfile, SFC_WAVEX_GET_AMBISONIC, NULL, 0) == SF_AMBISONIC_B_FORMAT)
			format = AL_FORMAT_BFORMAT3D_16;
	}
	if (!format)
	{
		fprintf(stderr, "Unsupported channel count: %d\n", sfinfo.channels);
		sf_close(sndfile);
		return 0;
	}

	/* Decode the whole audio file to a buffer. */
	membuf = static_cast<short*>(malloc((size_t)(sfinfo.frames * sfinfo.channels) * sizeof(short)));

	num_frames = sf_readf_short(sndfile, membuf, sfinfo.frames);
	if (num_frames < 1)
	{
		free(membuf);
		sf_close(sndfile);
		fprintf(stderr, "Failed to read samples in %s (%" PRId64 ")\n", filename, num_frames);
		return 0;
	}
	num_bytes = (ALsizei)(num_frames * sfinfo.channels) * (ALsizei)sizeof(short);

	/* Buffer the audio data into a new buffer object, then free the data and
	 * close the file.
	 */
	buffer = 0;

	alGenBuffers(1, &buffer);
	alBufferData(buffer, format, membuf, num_bytes, sfinfo.samplerate);

	free(membuf);
	sf_close(sndfile);

	/* Check if an error occured, and clean up if so. */
	err = alGetError();
	if (err != AL_NO_ERROR)
	{
		fprintf(stderr, "OpenAL Error: %s\n", alGetString(err));
		if (buffer && alIsBuffer(buffer))
			alDeleteBuffers(1, &buffer);
		return 0;
	}

	return buffer;

**Comment by kcat** [comment]
That's because of a libsndfile bug: https://github.com/libsndfile/libsndfile/issues/194

Basically, Ogg files internally decode to float samples, and when `alplay` (or any other app using libsndfile) reads the samples as 16-bit shorts, the library scales but doesn't clamp the output, which causes samples to wrap when they're outside of the normalized amplitude range (resulting in clicks and static in the loud parts).

**Comment by Kasell777** [comment]
Thank you so much!

It was very helpful.
