### ISSUE TITLE
where to install openal-soft ?

### ISSUE THREAD

**Issue by foxer55** [kcat/openal-soft#599]
Good afternoon. I downloaded openal-soft-1.21.1-bin.zip. Could you please tell me where to install openal-soft ? which folder?

**Comment by kcat** [comment]
On Windows, you can either install it into the system32/syswow64 folder for it to be system-wide, or in the app's folder for it to be just for a particular app. But make sure to read the readme in the zip to know which files to copy where depending if you have 32-bit or 64-bit Windows:
```
Note that it is still expected to install the OpenAL redistributable provided
by Creative Labs (at http://openal.org/), as that will provide the "router"
OpenAL32.dll that applications talk to, and may provide extra drivers for the
user's system. The DLLs provided here will simply add additional devices for
applications to select from. If you do not wish to use the redistributable,
then rename soft_oal.dll to OpenAL32.dll (note: even the 64-bit DLL should be
named OpenAL32.dll). Just be aware this will prevent other system-installed
OpenAL implementations from working.

To set up the 32-bit DLL for use globally, copy it from the bin\Win32 folder to
the folder that the 32-bit OpenAL32.dll router is installed in.
For 32-bit Windows, the Win32 DLL will typically go into the system32 folder.
For 64-bit Windows, the Win32 DLL will typically go into the SysWOW64 folder.

To set up the 64-bit DLL for use globally, copy it from the bin\Win64 folder to
the folder that the 64-bit OpenAL32.dll router is installed in.
For 64-bit Windows, this will typically be the system32 folder.
```

**Comment by foxer55** [comment]
Thank you very much. Just a small question. Realtek is the only sound card in my computer. As I know any integrated sound card in system processes openal calls,eax and so on by the Generic Software device,rendered using the host CPU.If this is the case,why aida64 shows such data https://ibb.co/YjXf0QX. For a full explanation, data in red mark show that eax3 and  eax4 are emulated as I understand by cpu since there isn't  3D audio accelerator card but I don't understand why data in green mark (eax and eax 2.0) show without emulation?  does that mean that my  integrated sound card realtek  uses Hardware acceleration for processing eax and eax2.0?

**Comment by kcat** [comment]
I can't say for sure what the emulated extensions mean. OpenAL's EAX extensions are well-defined.

Generic Software does all-software mixing and processing, even for EAX and EAX2. It's possible `EAX3.0EMULATED` and `EAX4.0EMULATED` indicates the EAX3/4 APIs are supported, but only a subset of functionality is implemented. So the app can call functions as if EAX 3 and 4 are supported, but some calls are no-ops which can limit the resulting sound behavior. That would be my guess.
