### ISSUE TITLE
OpenAL Soft Library Licensing

### ISSUE THREAD

**Issue by daniilpetrov** [kcat/openal-soft#612]
Hello!

I am working on a game engine for my future game projects and am gradually getting closer to developing the first demo scene. And so I asked myself the question of licensing the libraries that I used to implement my game engine. The engine is developed exclusively for their own needs and only games made on it will be distributed. What conditions must be met in order not to violate the license to use this library?

To begin with, I indicated the use of this library in the user manual and in the future it will be so in all manuals. If you can provide a vector logo for the library, I will add it to the user manual. I also placed a copy of your license in the "documents / licenses" directory and would like to clarify if I took the correct text. If the text is different, please give the correct one.

Below I am attaching the license file and user manual for the future demo scene (one page is incomplete).
[OpenAL Soft BSD-3Clause.txt](https://github.com/kcat/openal-soft/files/7500453/OpenAL.Soft.BSD-3Clause.txt)
[manual EN.pdf](https://github.com/kcat/openal-soft/files/7500455/manual.EN.pdf)

Sincerely, Daniil Petrov.

**Comment by kcat** [comment]
OpenAL Soft is actually licensed under the [LGPL 2 (or later)](https://github.com/kcat/openal-soft/blob/b81fa0d/COPYING). It includes some code under the BSD 3-Clause license, but the library as a whole is LGPL, which it's compatible with.

Essentially, all that needs to be done to comply with the license is, if you use an unmodified version and dynamically link it (`.dll` on Windows, `.so` on Linux, `.dylib` on macOS, etc), just mention the library and its license somewhere, and provide a link to where they can find its source (its homepage or its github repo or something like that).

If it's a modified version, you'll need to provide the source changes you made, either publicly, or to whoever gets the binaries.

**Comment by daniilpetrov** [comment]
Everything is clear, thanks!

**Comment by daniilpetrov** [comment]
Are you satisfied with the hyperlink on the OpenAL Soft text on the user manual logo page?
[manual EN.pdf](https://github.com/kcat/openal-soft/files/7508468/manual.EN.pdf)

**Comment by kcat** [comment]
Looks good to me.

**Comment by daniilpetrov** [comment]
Then there are no more questions.
