### ISSUE TITLE
"Failed to open OpenAL device" and soft openal dont see my USB DAC

### ISSUE THREAD

**Issue by MrFreedman** [kcat/openal-soft#613]
Hello. OpenAL doesnt work properly and in all games is see massage "Failed to open OpenAL device". I use ALchemy Universal meybe problem in it? If i launch openal-info64 (or 32 bits) this program doesnt see my USB DAC called "Ifi Zen Dac Signature" in playback devices it see monitor (Nvidia high definition audio) and see my microphone but doesnt see my external card. I try use openal from creative site, i try use 2.1 and in both case i see this error massage. If i doesnt copy openlal soft it too doesnt work, if copy the same. Plz help. Thx.

**Comment by kcat** [comment]
Hi.

Can you provide the full output of openal-info64 (or 32)? If you set the `ALSOFT_LOGLEVEL` environment variable to `3` when you run it, it'll provide more helpful information for me to see what it's detecting:
```
set ALSOFT_LOGLEVEL=3
openal-info64
```
I presume other Windows apps see the USB device, and it's just OpenAL apps that don't?

**Comment by MrFreedman** [comment]
C:\Users\Aksel>C:\Users\Aksel\Desktop\openal-soft-1.21.1-bin\openal-soft-1.21.1-bin\openal-info64.exe set ALSOFT_LOGLEVEL=3
Available playback devices:
[ALSOFT] (II) Initializing library v1.21.1-ae4eacf1 master
[ALSOFT] (II) Supported backends: wasapi, dsound, winmm, null, wave
[ALSOFT] (II) Loading config C:\Users\Aksel\AppData\Roaming\alsoft.ini...
[ALSOFT] (II) Got binary: C:\Users\Aksel\Desktop\openal-soft-1.21.1-bin\openal-soft-1.21.1-bin, openal-info64.exe
[ALSOFT] (II) Loading config C:\Users\Aksel\Desktop\openal-soft-1.21.1-bin\openal-soft-1.21.1-bin\alsoft.ini...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 5 2600 Six-Core Processor"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Message thread initialization complete
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Initialized backend "wasapi"
[ALSOFT] (II) Added "wasapi" for playback
[ALSOFT] (II) Added "wasapi" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Got message "Enumerate Playback" (0x0005, this=0000000000000000)
[ALSOFT] (II) Got device "OpenAL Soft on [ALSOFT] (II) Got device "OpenAL Soft on Dell AW2720HF (NVIDIA High Definition Audio)", "{729BE1E1-6D85-4E8A-A413-CDD844332A2F}", "{0.0.0.00000000}.{729be1e1-6d85-4e8a-a413-cdd844332a2f}"
[ALSOFT] (II) Got message "Enumerate Capture" (0x0006, this=0000000000000000)
    Generic Software on     OpenAL Soft on     OpenAL Soft on Dell AW2720HF (NVIDIA High Definition Audio)
    Generic Software on Dell AW2720HF (NVIDIA High Definition Audio)
Available capture devices:
    !!! none !!!
Default playback device: Generic Software on Default capture device:
ALC version: 6619248.0

!!! Failed to open set !!!

This or it failed open set i dont know sry?

**Comment by kcat** [comment]
I didn't mean to run `openal-info64.exe set ALSOFT_LOGLEVEL=3`, that won't set the environment variable correctly, and it makes openal-info try to query a device named `set`, which doesn't exist. But it seems `ALSOFT_LOGLEVEL` was already set anyway since it gave a trace log.

It looks like you have a device that uses unicode characters, which can be an issue since Windows and some apps can have problems with it (Windows doesn't like displaying some extended characters in the command window when using `fputws()`, and will cut lines short instead). OpenAL Soft handles device names as UTF-8, so if a device name uses extended characters an app might not handle the name correctly depending on what it does with it.

**Comment by MrFreedman** [comment]
I see its fun, i rename my default sound device from russian name called "Динамики" to english calls "USB Device" and now it look likes:
PS C:\Users\Aksel> C:\Users\Aksel\Desktop\openal-soft-1.21.1-bin\openal-soft-1.21.1-bin\openal-info64.exe
Available playback devices:
    OpenAL Soft on USB Devices (2- iFi (by AMR) HD+ USB Audio)
    OpenAL Soft on Dell AW2720HF (NVIDIA High Definition Audio)
    Generic Software on USB Devices (2- iFi (by AMR) HD+ USB Audio)
    Generic Software on Dell AW2720HF (NVIDIA High Definition Audio)
Available capture devices:
    !!! none !!!
Default playback device: OpenAL Soft on USB Devices (2- iFi (by AMR) HD+ USB Audio)
Default capture device:
ALC version: 6619248.0

** Info for device "Generic Software on USB Devices (2- iFi (by AMR) HD+ USB Audio)" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE, ALC_EXT_EFX
HRTF extension not available
OpenAL vendor string: Creative Labs Inc.
OpenAL renderer string: Software
OpenAL version string: 1.1
OpenAL extensions:
    EAX, EAX2.0, EAX3.0, EAX4.0, EAX5.0, EAX3.0EMULATED, EAX4.0EMULATED,
    AL_EXT_OFFSET, AL_EXT_LINEAR_DISTANCE, AL_EXT_EXPONENT_DISTANCE
Resampler info not available
EFX version: 1.0
Max auxiliary sends: 1
Supported filters:
    !!! none !!!
Supported effects:
    !!! none !!!
PS C:\Users\Aksel>

Ok but if i use ALchemy Universal i continue see the message in dsoundlog file in game folder:

Logging Time : 13/11/2021 at 19:08:56

Loaded g:\games\warcraft iii\DSOUND.ini

Failed to open OpenAL device

Using Creative Software 3D Library
Failed to open OpenAL device

Why it happens and why openal is failed?

**Comment by kcat** [comment]
If the game is using DirectSound, I think ALchemy will only use hardware OpenAL devices, so it won't work with Generic Software or OpenAL Soft. You'd need to try an alternative like DSOAL, which can use OpenAL Soft, though I don't know if that will work with that game or not.

**Comment by MrFreedman** [comment]
Thx. Like i undestand i need use and DSOAL and ALchemy Universal together that automatic create profile the game and copy files from alchemy to game folder if dsoal is work im right? If yes in game Oblivion it doesnt work "openal failed" and in Half-Life 2 (hl2 i just test it doesnt have hardware sound and openal maybe im doesnt right). But...in Warcraft 3 and in Titan Quest is work i hear difference and some reverb in War3 with EAX2. But why it doesnt work in Oblivion i dont know...

**Comment by kcat** [comment]
Closing this since the device open failure was a result of ALchemy not having a hardware driver to work with. kcat/dsoal#32 is a followup for a separate DSOAL issue.
