### ISSUE TITLE
Channel Config Setting Not Effective With NVIDIA High Definition Audio Device

### ISSUE THREAD

**Issue by davidjoye** [kcat/openal-soft#614]
Windows 11, OpenAL Soft 1.21.1, I am using a Denon AVR-3806 receiver connected to an NVIDIA RTX 3090 via HDMI for 7.1 speaker output. I also have a Creative SB X-Fi PCIe card connected to the AVR via analog 7.1 connection. In Windows, both the X-Fi and HDMI AVR are set for 7.1 speaker output.

- When the X-Fi is the default device and set to 7.1 output, I can set OpenAL Soft to stereo and games configured to use OALS will output in stereo; I can change OALS to surround71 and the game will then output to the surround speakers.
- When the HDMI AVR is default and set to 7.1 and the game is configured to use OALS on the HDMI device, OpenAL Soft's channel setting appears to have no effect on the game's output.

The use case for controlling the speaker layout independent of the Windows setting is because some OpenAL-based games, particularly non-first-person games, will place sounds in arbitrary speakers in a surround speaker configuration; Steamworld Dig 2 (2D side-scroller) is an example of this. Steamworld Dig 2 sends some character sound effects to the surround speakers while most other sounds are up front. I can force Steamworld Dig 2 to use stereo regardless of Windows speaker config with these steps:

1. Rename the game's OpenAL32.dll to OpenAL32.dll.bak (or delete)
2. Copy in Win32\soft_oal.dll to game's directory and rename to OpenAL32.dll
3. Create alsoft.ini in the game directory with channels=stereo -- this overrides %AppData%\alsoft.ini settings
**The game's log.txt file will show `OpenAL.cpp:57 INFO: Sucessfully opened OpenAL device: Default`

Alternate method:
1. Copy the soft_oal.dll files to their respective Windows system directories
2. Use openal-info32.exe to get the name of the OpenAL device
3. Edit the game's config (settings.xml) and specify the OpenAL Soft device name for the Audio.OutputDevice value
**The game's log.txt file will show `OpenAL.cpp:57 INFO: Sucessfully opened OpenAL device: <specified device name>`

This works with the X-Fi set as the default output device, I can change channel output via alsoft.ini in the game's directory (channels=stereo, surround51, surround71) or in the AppData config location, and the game's output will change based on that, but this does not work when the NVIDIA High Definition Audio device is set as the default output device in Windows. With NVIDIA HD Audio, OpenAL Soft's channel output appears to be only affected by changing the Windows speaker configuration.

This is the openal-info32.exe output for Speakers on Creative SB X-Fi:
```
Available playback devices:
    SB X-Fi Audio [0001]
    Rapture3D
    OpenAL Soft on Speakers (Creative SB X-Fi)
    OpenAL Soft on Speakers (Logitech G933 Gaming Headset)
    OpenAL Soft on DENON-AVAMP (NVIDIA High Definition Audio)
    Generic Software on Speakers (Creative SB X-Fi)
    Generic Software on Speakers (Logitech G933 Gaming Headset)
    Generic Software on DENON-AVAMP (NVIDIA High Definition Audio)
Available capture devices:
    Microphone (Logitech G933 Gamin
    OpenAL Soft on Microphone (Logitech G933 Gaming Headset)
    OpenAL Soft on "What U Hear" (Creative SB X-Fi)
    OpenAL Soft on Digital-In (Creative SB X-Fi)
    "What U Hear" (Creative SB X-Fi
    Digital-In (Creative SB X-Fi)
Default playback device: SB X-Fi Audio [0001]
Default capture device: Microphone (Logitech G933 Gamin
ALC version: 6.6422036

ALC Error: Invalid enum parameter passed as an argument to an ALC call. (0xa003), @ 203
** Info for device "SB X-Fi Audio [0001]" **
ALC version: 1.1
ALC extensions:
    None
HRTF extension not available
OpenAL vendor string: Creative Labs Inc.
OpenAL renderer string: SB X-Fi Audio [0001]
OpenAL version string: OpenAL version 1.1
OpenAL extensions:
    EAX
EAX1.0
EAX2.0
EAX3.0
EAX4.0
EAX5.0

Resampler info not available
EFX version: 1.0
Max auxiliary sends: 2
Supported filters:
    !!! none !!!
Supported effects:
    !!! none !!!`
```
This is the openal-info32.exe output for the DENON-AVAMP on NVIDIA High Definition Device:
```
Available playback devices:
    OpenAL Soft on DENON-AVAMP (NVIDIA High Definition Audio)
    SB X-Fi Audio [0001]
    Rapture3D
    OpenAL Soft on Speakers (Logitech G933 Gaming Headset)
    OpenAL Soft on Speakers (Creative SB X-Fi)
    Generic Software on DENON-AVAMP (NVIDIA High Definition Audio)
    Generic Software on Speakers (Logitech G933 Gaming Headset)
    Generic Software on Speakers (Creative SB X-Fi)
Available capture devices:
    Microphone (Logitech G933 Gamin
    OpenAL Soft on Microphone (Logitech G933 Gaming Headset)
    OpenAL Soft on "What U Hear" (Creative SB X-Fi)
    OpenAL Soft on Digital-In (Creative SB X-Fi)
    "What U Hear" (Creative SB X-Fi
    Digital-In (Creative SB X-Fi)
Default playback device: OpenAL Soft on DENON-AVAMP (NVIDIA High Definition Audio)
Default capture device: Microphone (Logitech G933 Gamin
ALC version: 18.6422036

** Info for device "Generic Software on DENON-AVAMP (NVIDIA High Definition Audio)" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE, ALC_EXT_EFX
HRTF extension not available
OpenAL vendor string: Creative Labs Inc.
OpenAL renderer string: Software
OpenAL version string: 1.1
OpenAL extensions:
    EAX, EAX2.0, EAX3.0, EAX4.0, EAX5.0, EAX3.0EMULATED, EAX4.0EMULATED,
    AL_EXT_OFFSET, AL_EXT_LINEAR_DISTANCE, AL_EXT_EXPONENT_DISTANCE
Resampler info not available
EFX version: 1.0
Max auxiliary sends: 1
Supported filters:
    !!! none !!!
Supported effects:
    !!! none !!!
```

**Comment by kcat** [comment]
I'm actually a bit surprised it works with the X-Fi, since WASAPI itself doesn't handle upmixing for channel mismatches or reconfiguring the device based on app requests for shared devices, meaning apps always need to use the device's channel configuration with WASAPI. The behavior with the nVidia device is what I'd expect from the other devices, too. The X-Fi device must have some special functionality that allows streams to use different channel configs despite using a shared device.

That said, the current git head may work better here. OpenAL Soft can handle some cases where the requested output configuration is a subset of the actual output configuration (e.g. a device using 7.1 still has front-left and front-right channels to use for stereo; it simply leaves the remaining channels silent). There are some limits currently, but stereo requests should be easy for it to handle with most device configurations.

**Comment by davidjoye** [comment]
OK, I assumed that speaker channel output could be overridden by OpenAL Soft regardless of the system settings. I will close this since that is an unintended behavior.
