### ISSUE TITLE
Sample rate in pipewire can have enum choice type

### ISSUE THREAD

**Issue by etircopyh** [kcat/openal-soft#615]
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/alsa/alsa-pcm.c#L402-406

https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/bluez5/a2dp-codec-sbc.c#L408-409

**Comment by kcat** [comment]
Should be handled now with commit cf85ffd2, if you're able to verify.

**Comment by etircopyh** [comment]
> Should be handled now with commit [cf85ffd](https://github.com/kcat/openal-soft/commit/cf85ffd22fceeb4221a96b310f574f29a4b404ea), if you're able to verify.

Here is what I get trying to debug why openal enforces resampling for bluez devices: 
![image](https://user-images.githubusercontent.com/26657892/141693153-81e3313b-9787-46de-9a42-eb3839873400.png)

That's with additional `else` containing `TRACE("Device ID %u sample rate is empty\n", node->mId);` [here](https://github.com/kcat/openal-soft/blob/master/alc/backends/pipewire.cpp#L652)

Perhaps you can check it too, if you have an access to some bluetooth headset

**Comment by kcat** [comment]
I don't have a bluetooth audio device to test myself, unfortunately. But I added warnings in the latest commit to indicate more precisely what the issue is.

**Comment by etircopyh** [comment]
Seems like choice type can also be `None`.

`Enum` and `None`
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/bluez5/a2dp-codec-sbc.c#L385
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/bluez5/a2dp-codec-sbc.c#L408

`Range` and `None`
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/alsa/alsa-pcm.c#L396
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/alsa/alsa-pcm.c#L402

**Comment by kcat** [comment]
Kind of odd it's still provided as a "choice" when it's actually not. But it should be handled now with commit 7062de03.

**Comment by etircopyh** [comment]
Seems to be working alright now. Thanks.
