### ISSUE TITLE
Wave not linking error

### ISSUE THREAD

**Issue by Ily3s** [kcat/openal-soft#621]
I've tried to link openal-soft statically by adding -DLIBTYPE=STATIC when i used cmake and by defining AL_LIBTYPE_STATIC before including headers (first time i use openal so i don't know if the fact i'm linking statically is the problem)
When i link OpenAL32.lib (I'm building it for Win32) to my project an try to compile it with the MSVC (with Visual Studio 16 2019), i get 17 linking errors all starting with "_imp_waveOut" or with "_imp_waveIn" coming from OpenAL32.lib.

What i've tried so far :
I've paid attention to the cmake output to see OpenAL was trying to get support for backend WaveFile so I've gone into CmakeLists.txt to correct that by replacing "ON" by "OFF" line 1180. Somehow, that didn't fix the problem even tho the cmake output was no longer telling me OpenAL is building with support for WaveFile.
So i've tried to simply supress from line 1180 to line 1185 in CMakeLists.txt and i got the exact same issue
I deleted CMakeCache.txt as well each time i modified CMakeLists.txt

Am i missing something or is it a bug with static linking or something ?

**Comment by kcat** [comment]
The waveOut and waveIn functions are part of the WinMM (Windows MultiMedia) API. The WinMM backend is one of the few that can't dynamically load the DLL and its functions at runtime, so it needs to be linked with the app at build time. And a static library can't tell the compiler that it needs other libraries, so when linking with the static version of OpenAL32.lib, you also need to link with WinMM.lib.

**Comment by Ily3s** [comment]
Hey, thanks a lot for your fast answer, linking WinMM.lib fixed my issue, i'm colsing the issue
