### ISSUE TITLE
HRTF Attributes Not Recognized

### ISSUE THREAD

**Issue by Andrew123098** [kcat/openal-soft#622]
Hello! 
I am a beginning developer trying to use OpenAL-Soft to convert monaural audio files to directional binaural audio files using OpenAL-soft's default HRTF. I have created a sound device and am trying to use alcCreateContext's second "attributes" parameter to change the HRTF parameter of the device to true following along with this [documentation](https://openal-soft.org/openal-extensions/SOFT_HRTF.txt) I found. The issue I am having is that my system says the ALC_HRTF_SOFT is undefined and doesn't recognize any of the other attributes found in the documentation. Please let me know if there is anything or any files I can provide you with to help solve this problem more quickly. I greatly appreciate your time.
Thank you so much,
Andrew
![image](https://user-images.githubusercontent.com/51041426/144930507-cb58a8bb-d773-487f-b738-c750957fd578.png)

**Comment by kcat** [comment]
Hi.

Make sure to include `alext.h` to get the definitions for the HRTF (and other) extensions. If you're using the headers from OpenAL Soft, it should be there along side `alc.h` and `al.h`. If not, you can copy it (along with `efx.h`) from OpenAL Soft and add it directly to your project.

**Comment by Andrew123098** [comment]
Thank you so much for the quick response! This worked!
