### ISSUE TITLE
openal-info finds no PulseAudio devices with pipewire-pulse

### ISSUE THREAD

**Issue by UniqueActive** [kcat/openal-soft#623]
Hello!

While using Telegram, which uses openal-soft, I noticed that all other system sound would die as soon as I am on a call there. Not surprisingly, openal-info showed it using the ALSA backend, which meant that pipewire/pipewire-pulse suddenly couldn't access the output device anymore.

I tried to force it to use PulseAudio with ALSOFT_DRIVERS=pulse or setting drivers=pulse in the .alsoftrc, but this has the following result:
```
~$ openal-info
Available playback devices:
    !!! none !!!
Available capture devices:
    !!! none !!!
Default playback device:
Default capture device:
ALC version: 1.1

!!! Failed to open default device !!!
```

pactl list sinks shows my device correctly, other applications (eg. Firefox) correctly recognize and use the PulseAudio devices. I also want to add that I am not actually running an ALSA daemon on my system, the only ALSA-related package that I have installed is alsa-lib, which was installed as a dependency of another application. I have also not installed pipewire-alsa.

I have so far not been able to find the reason for this issue and would be very thankful for your help in diagnosing it! Please let me know if you need the output of any other commands to help me find the issue.

**Comment by kcat** [comment]
Are you able to generate a log file? Setting both `ALSOFT_DRIVERS=pulse` and `ALSOFT_LOGLEVEL=3` should provide more insight about why the PulseAudio backend is failing to initialize.

**Comment by UniqueActive** [comment]
@kcat Here's the output, thank you for having a look!

```
ALSOFT_DRIVERS=pulse ALSOFT_LOGLEVEL=3 openal-info
Available playback devices:
[ALSOFT] (II) Initializing library v1.21.1-unknown UNKNOWN
[ALSOFT] (II) Supported backends: alsa, oss, null, wave
[ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
[ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/unicorn/.alsoftrc...
[ALSOFT] (II)  found 'drivers' = 'pulse,alsa,'
[ALSOFT] (II) Loading config /home/unicorn/.config/alsoft.conf...
[ALSOFT] (II) Got binary: /usr/bin, openal-info
[ALSOFT] (II) Loading config /usr/bin/alsoft.conf...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: ""
[ALSOFT] (II) Name: "Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (WW) No playback backend available!
[ALSOFT] (WW) No capture backend available!
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
    !!! none !!!
Available capture devices:
    !!! none !!!
Default playback device:
Default capture device:
ALC version: 1.1
[ALSOFT] (WW) Error generated on device 0, code 0xa004

!!! Failed to open default device !!!
```

I spotted that it says "Supported backends: alsa,oss,null,wave", meaning that pulse is somehow not supported. Is this a compiletime flag or a missing dependency?

**Comment by kcat** [comment]
`Supported backends:` indicates compile-time support, yes. It will try the given backends by loading their corresponding library at runtime, and give some indication of why it can't be used if it can't.

If this is a custom build you made, you need to make sure to have the relevant development packages when configuring/building (on Debian derivatives, you need `libpulse-dev` for PulseAudio support; since you're using PipeWire, if you're using a recent Git version of OpenAL Soft, `libpipewire-0.3-dev` will get you native PipeWire support too). If it's instead being provided by your distro repository, you'll have to ask them to enable PulseAudio support at compile-time (it won't create a runtime dependency, unless dynamic library loading is disabled).

**Comment by UniqueActive** [comment]
> `Supported backends:` indicates compile-time support, yes. It will try the given backends by loading their corresponding library at runtime, and give some indication of why it can't be used if it can't.

Thank you for letting me know! I was using my distribution (Alpine Linux) package, so I will contact the maintainer to let them know about it, I will close this issue accordingly. :)
