### ISSUE TITLE
SBX Surround with OpenAL Soft

### ISSUE THREAD

**Issue by Kappa971** [kcat/openal-soft#625]
Sound Blaster audio cards allow you to convert a 5.1/7.1 source into "virtual" stereo surround sound. For example, with 2.1 speakers, Windows is set to 2.1 while the game (if possible) to 5.1/7.1, SBX Surround will take care of the conversion to stereo making the audio more spatial. SBX Surround works with both speakers and headphones. From what I understand OpenAL Soft does a similar thing (the HRTF option) but for headphones only, so I having only 2.1 speakers, I keep it off. 
Having said that I would like to ask: is it possible to use OpenAL Soft with SBX Surround and stereo speakers? For example setting the game audio output to 5.1, "channels" in OpenAL Soft to 5.1, Windows set to 2.1 and SBX Surround on is the correct solution? Or OpenAL Soft also manages the virtual surround on the speakers (even with HRTF off) and therefore would conflict with SBX Surround?

**Comment by kcat** [comment]
I don't know about how to set up SBX Surround or the corresponding Windows configuration, but if it accepts 7.1 and/or 5.1 streams you can configure OpenAL Soft to output 7.1 or 5.1. Run `alsoft-config.exe` and set the Channels option to 7.1 Surround or 5.1 Surround, then click Apply. If you don't have or can't use `alsoft-config`, you can create/edit the file `%AppData%\alsoft.ini` and add the lines:
```
[general]
channels = surround71  # or surround51
```

**Comment by Kappa971** [comment]
That's just what I wanted to know, thanks. I think it can close the issue.

**Comment by Kappa971** [comment]
Setting `channels=surround51` with 2.1 speakers (I don't know if it happens with surround speakers too), you will notice an increase in the reverb effect, with both SBX Surround on and off (so it probably concerns OpenAL Soft). It is easily solved by setting `boost=-4` (which appears to be similar to `boost=0` with `channels=stereo`), but should I open a new issue? Can this be considered a bug?

**Comment by kcat** [comment]
Can you provide trace logs from using `channels=stereo` and `channels=surround51` with SBX Surround on and off? If SBX Surround is responsible for downmixing 5.1 to 2.1 with a pseudo-surround effect, I wouldn't expect surround51 to be accepted by 2.1 speakers with it off (OpenAL Soft will fall back to stereo to match what's actually there). Unless it still does the downmixing, just plainly without the pseudo-surround effect. With SBX Surround on, does it create the surround effect?

The reverb itself isn't very different regardless of output mode, but the way SBX and/or Windows remixes 5.1 to 2.1 may cause a louder result compared to OpenAL Soft's own stereo mix.

**Comment by Kappa971** [comment]
These are the log files with `channels=stereo` (I don't seem to notice a difference in the reverb level):
[stereo+SBX_on.txt](https://github.com/kcat/openal-soft/files/7730707/stereo%2BSBX_on.txt)
[stereo+SBX_off.txt](https://github.com/kcat/openal-soft/files/7730708/stereo%2BSBX_off.txt)

These are the log files with `channels=surround51`:
[surround+SBX_on.txt](https://github.com/kcat/openal-soft/files/7730733/surround%2BSBX_on.txt)
[surround+SBX_off.txt](https://github.com/kcat/openal-soft/files/7730734/surround%2BSBX_off.txt)
By setting `channels=surround51` and SBX off, Windows appears to downmix to 2.1 (no virtual surround effect). Reverb with `channels=surround51` increases with both SBX on and off.

**Comment by Kappa971** [comment]
I have found in some forums that it isn't recommended to use SBX Surround in DirectSound3D/OpenAL games, as these have their own 3D sound (even if it sounds stereo to me). In effect starting a DirectSound game (which uses Alchemy) or Host OpenAL (by Creative), this will disable SBX Surround, so I'll keep OpenAL Soft in stereo and SBX off. I'm avoiding using Alchemy or Host OpenAL, as the reverb effect is exaggerated and in some games I have clicks and pops.

Returning to the problem of reverb with OpenAL Soft, if this is caused by the conversion of the 5.1 signal to 2.1 performed by Windows, I do not think it can be considered a bug of OpenAL Soft.
If the increase in reverb happens even with a real 5.1 speaker setup, then maybe it could be about OpenAL Soft (I can't run this test as I don't have a 5.1 setup).
