### ISSUE TITLE
PipeWire backend does not set node.rate property

### ISSUE THREAD

**Issue by etircopyh** [kcat/openal-soft#626]
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1915#note_1193527

**Comment by etircopyh** [comment]
[Here's SDL's implementation](https://github.com/libsdl-org/SDL/blob/3d5fcb5da64c89fc4a597ef8e11f3b52c13f48ef/src/audio/pipewire/SDL_pipewire.c#L1127) for the reference.

**Comment by kcat** [comment]
Should be fixed with commit 21bdea776a1fca9f009470c6e5753cf78e208593.
