### ISSUE TITLE
[Feature request] Portable alsoft.ini

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/openal-soft#636]
If I recall correctly, DSOAL looks for an alsoft.ini in the same folder as the executable, otherwise it'd fallback to [the one in %APPDATA%](https://github.com/kcat/openal-soft/blob/e32c214e9c8f2c1a9aab06ebd2bad8475c12949c/alsoftrc.sample#L19), which would be a useful behavior in OpenAL Soft as well, so we could specify settings like sample rate, reverb volume, HRTF, etc. on a per-game basis instead of restricting all games to the same settings or editing them manually every time we switch to a game that require or just works better with different settings.

**Comment by kcat** [comment]
It does already:
https://github.com/kcat/openal-soft/blob/e32c214e9c8f2c1a9aab06ebd2bad8475c12949c/alc/alconfig.cpp#L344

DSOAL uses a normal (if older) build of OpenAL Soft, which is where that behavior comes from. The only difference is the DLL has a different filename with DSOAL.

**Comment by ThreeDeeJay** [comment]
Mind=blown. I could've sworn I tried it multiple times and didn't seem to work but just tried it again and boom. Amazing.
Might be a good idea to point out the portable path [here](https://github.com/kcat/openal-soft/blob/e32c214e9c8f2c1a9aab06ebd2bad8475c12949c/alsoftrc.sample#L19), but either way I'll just go ahead and close this issue 👍
