### ISSUE TITLE
[Feature request] Reverse axes (like __ALSOFT_REVERSE_Z) in alsoft.ini

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/openal-soft#637]
Is there something similar to [__ALSOFT_REVERSE_Z](https://github.com/kcat/openal-soft/blob/master/docs/env-vars.txt#L61), but for the Y-axis and perhaps even X-axis?
 There are cases where even if using real X-Fi hardware on Windows XP or OpenAL Soft, the verticality is inverted so stuff above the listener sounds like it's below and viceversa. I even modified some HRTFs by manually flipping the elevation values in the .DEF file to fix vertical positioning but doing it in OpenAL Soft directly should be a lot more practical than having separate [MHRs with inverted elevation](https://airtable.com/shruimhjdSakUPg2m/tbloLjoZKWJDnLtTc/viwMmtPWIXCzhidSv/rec1Eswv5bccnzvM1).

Just Cause: [Inverted Y-axis](https://i.imgur.com/nrrshOo.mp4) - [Corrected](https://i.imgur.com/5HjR6Se.mp4)
Grand Theft Auto San Andreas: [Inverted Y-axis (X-Fi on XP)](https://youtu.be/Noa9K70OUcs) - [Corrected](https://youtu.be/SimGoYziLKM)
RightMark 3DSound Positioning Accuracy test: [Inverted Y-axis](https://youtu.be/Pkm648_rRGs?t=240)
Will Rock: [Inverted Y-axis](https://youtu.be/DsavG-lCfJo)

Call of Juarez: [Inverted Z-axis](https://youtu.be/63LTnsG69uk?t=6)
Sector's Edge: [Inverted Z-axis for some sounds](https://i.imgur.com/GXq469O.mp4)

Test Drive 6: [Inverted X-axis](https://youtu.be/3efHfHLgE4g) *Note: Also happens in Windows XP with native DS3D CMSS-3D/EAX

Perhaps it would be even better to add a setting to alsoft.ini to flip axes individually, as opposed to having to pass [environmental variables](https://github.com/kcat/openal-soft/blob/master/docs/env-vars.txt#L61) to the executable.

**Comment by ThreeDeeJay** [comment]
Update: Z-axis inversion in the config file was also discussed in #668 and implemented in https://github.com/kcat/openal-soft/commit/609ee742115aa10139d5e4c3f8915306751c227f
Now if we could only get the same for the Y and X axis to fix the other games, that would be neat 👀🤞

**Comment by kcat** [comment]
I really have to wonder how some games can end up shipped and leave such egregious bugs like inverted X positions unpatched. Y at least makes some sense, a bit more than Z even, since few people will have with-height setups to notice (and even with headphones/HRTF, it can be difficult to notice), but someone had to have noticed sounds to the left are coming from the right and vice-versa. Unless the game doesn't normally use DS3D and it can only be enabled with unofficial tweaks.

Added options with commit e28937d1f6704bcdc3f0a194744905906b106cdd.

**Comment by ThreeDeeJay** [comment]
I know, right? One would think they would pay the absolute minimal attention for AAA games like that, at least in the age of DirectSound3D. Test Drive 6 has EAX 1 so I guess it should be using DS3D.
But anyway, I tested all 3 axes inverters and they all work as intended in the RightMark 3D sound test tool so I'll go ahead and close this issue. 👍
