### ISSUE TITLE
Only EAXREVERB is supported - alEffecti

### ISSUE THREAD

**Issue by Ar-Ess** [kcat/openal-soft#644]
Hi!
I am having a problem with the effects again. Actually, the only effect I can use is EAXREVERB.
Whenever I use any of the other effects, the function "alEffeci()" returns a "AL_INVALID_VALUE".
Here is the code.

alGenEffects(1, &effect);
alEffecti(effect, AL_EFFECT_TYPE, AL_EFFECT_DISTORTION; // Error on the id, does not detect it
if (alGetError() == AL_INVALID_VALUE)
{
	printf("Effect not supported\n"); // Always enters here (Sample code taken from the documentation)
}
alGenAuxiliaryEffectSlots(1, &slot);
ToggleBypass(!bypass);
alSource3i(source, AL_AUXILIARY_SEND_FILTER, (ALint)slot, 0, AL_FILTER_NULL);

Is there a way to solve this? Or to make those effects supported?

Thanks so much!

**Comment by kcat** [comment]
Are you using an OpenAL Soft device, or a Creative hardware/software driver? What does `alcGetString(device, ALC_DEVICE_SPECIFIER);` give for the open device?

**Comment by Ar-Ess** [comment]
Hey, sorry for the late response. I've been busy.

Okey I used this code to get what you have asked me:

ALCdevice* device = alcOpenDevice(NULL);
const ALCchar* string = alcGetString(device, ALC_DEVICE_SPECIFIER);

And string returns Generic Software

**Comment by kcat** [comment]
That's Creative's software wrapper, which as far as I know only supports reverb effects. Unless you have capable hardware and drivers, you'll need to use OpenAL Soft instead. Which means either using the OpenAL Soft DLL directly instead of the router DLL, or explicitly open OpenAL Soft devices (which may not be the default).

**Comment by mirh** [comment]
EAX was completely revamped in the last versions. Is this still a thing?

**Comment by kcat** [comment]
The issue here seems to be a result of using Creative's software driver, which only supports reverb effects. It doesn't have anything to do with the EAX extensions.
