### ISSUE TITLE
OpenAL Soft listed on Conan under MIT license

### ISSUE THREAD

**Issue by cchulo** [kcat/openal-soft#649]
I was wondering if this is a legitimate distribution of this library: https://conan.io/center/openal

If so, the license on there appears to be incorrect.

**Comment by okuoku** [comment]
Hmm wrong from its beginning https://github.com/conan-io/conan-center-index/commit/195b579b79e0b9febc4fe1489f50ad5fe4dc1abe 

It should say `LGPL-2.0-or-later` (Conan's license identifier uses SPDX ones).

**Comment by cchulo** [comment]
I'll contact Conan devs and reference this issue
