### ISSUE TITLE
How to build and compile on VirtualBox Ubuntu?

### ISSUE THREAD

**Issue by zqstack** [kcat/openal-soft#658]
When running my audio application, ported from Windows, on Ubuntu Virtualbox, it reports the following:

```
Devices found:
OpenAL Soft

OpenAL Soft 40964 in alcOpenDevice: AL_INVALID_OPERATION
```

The line it runs on:

`ALCdevice device = alcOpenDevice( NULL ); // Also tried "OpenAL Soft"`

Ubuntu audio is working properly. What am I missing?

CMakeLists:

```
target_link_libraries( ${PROJECT_NAME}
    "myengine"
    "openal"
)
```

I installed `libopenal1` and `libopenal-dev` on the target VM

**Comment by zqstack** [comment]
Found a solution!

https://stackoverflow.com/questions/71066647/openal-soft-40964-in-alcopendevice-al-invalid-operation/71069105#71069105

**Comment by kcat** [comment]
Yes, `alGetError` gets the error on the current context. If there's no current context, it can't get the error, which is itself an error. For ALC functions, you can check their return value (for functions that have one) and/or `alcGetError`, which takes a device handle for the device associated with the operation to check (e.g. if `alcCreateContext(MyDevice, ...)` fails, call `alcGetError(MyDevice)` to get an error code).
