### ISSUE TITLE
Segmentation Fault When LuaJIT Callback is Used in Linux

### ISSUE THREAD

**Issue by MikuAuahDark** [kcat/openal-soft#659]
Since I don't know what library to blame, I'll cross-post this to LuaJIT (LuaJIT/LuaJIT#811).

Someone in our issue tracker (love2d/love#1776) reported strange crashes when using callback which apparently gone when the audio subsystem in our game framework is not loaded. Since our game framework is too big for reproduction, I wrote this minimal code and was able to reproduce the segfault:

```lua
local ffi = require("ffi")
local OpenAL = ffi.load("libopenal.so.1")

ffi.cdef[[
void *alcOpenDevice(const char*);
void *alcCreateContext(void*, int*);
bool alcMakeContextCurrent(void*);
void alcDestroyContext(void*);
bool alcCloseDevice(void*);

int poll(void *fds, unsigned long nfds, int timeout);
]]

local device, context

function initOpenAL()
        device = OpenAL.alcOpenDevice(nil)
        context = OpenAL.alcCreateContext(device, nil)
        assert(OpenAL.alcMakeContextCurrent(context))
end

-- Problematic code below
function problematicCode()
        local test = function() end
        --jit.off(test) -- uncommenting this doesn't seem have any effect
        local cb = ffi.cast("void(*)()", test)
        print("Lua code calling cb() 1")
        cb()
        print("Lua code calling cb() 2")
        cb() -- segfault here
end

function deinitOpenAL()
        assert(OpenAL.alcMakeContextCurrent(nil))
        OpenAL.alcDestroyContext(context)
        assert(OpenAL.alcCloseDevice(device))
end

if arg[1] == "none" then
        problematicCode()
else
        initOpenAL()
        problematicCode()
        deinitOpenAL()
end
```

Running:
```
$ luajit testalsoft.lua
[ALSOFT] (EE) Failed to set Int16, got Float32 instead
Segmentation fault (core dumped)
$ luajit testalsoft.lua none
$ ALSOFT_DRIVERS=pulse luajit testalsoft.lua
[ALSOFT] (WW) pthread_setschedparam failed: Operation not permitted (1)
[ALSOFT] (WW) Failed to set real-time priority: Permission denied (13)
[ALSOFT] (WW) Failed to set high priority: Permission denied (13)
[ALSOFT] (WW) pthread_setschedparam failed: Operation not permitted (1)
[ALSOFT] (WW) Failed to set real-time priority: Permission denied (13)
[ALSOFT] (WW) Failed to set high priority: Permission denied (13)
$
```

Running the code above will result in segmentation fault. Passing `none` as additional argument will prevent it from crashing by preventing OpenAL device creation. Weirdly, forcing OpenAL-soft to use `pulse` audio backend does not trigger the crash. OpenAL-soft is able to open 3 backends in my laptop: JACK (through PipeWire), PipeWire, and Pulse (through PipeWire).

Please let me know if you need more information. Tests are done using 2212b8d8ade3816d954d920a3e117d36931bcf3a and LuaJIT/LuaJIT@1d7b5029c5ba36870d25c67524034d452b761d27

**Comment by kcat** [comment]
Doesn't seem to crash here, using LuaJIT 2.1.0~beta3+dfsg-6 from Debian (though the 2.1.0-beta3 version doesn't seem to mean much according to the love2d issue you linked, and I don't know where the date or git hash is that the build is made from so I don't know how different it may be from what's crashing). I tried with the JACK (through PipeWire), PulseAudio (through PipeWire), and PipeWire backends, and none crashed.

I'm guessing this is an x86-64 target? 32-bit x86 Linux has had a few hiccups relating to stack alignment (since the Linux 32-bit x86 ABI changed at one point), which a JIT compiler could easily trip over, but they should be fixed.

**Comment by MikuAuahDark** [comment]
Yes, it's x86-64 target. And yes LuaJIT no longer doing releases (see https://github.com/LuaJIT/LuaJIT/issues/665#issuecomment-784452583). Please test LuaJIT by compiling from latest commit which I linked in the original text (LuaJIT/LuaJIT@1d7b5029c5ba36870d25c67524034d452b761d27).

**Comment by kcat** [comment]
Yes, I'm seeing a crash with a local build of the latest LuaJIT commit too. Unfortunately I can't get any backtrace with gdb. It seems to crash some time after `alcCreateContext` and `alcMakeContextCurrent(context)`, but before `alcMakeContextCurrent(nil)` and `alcDestroyContext`, somewhere in the Lua code. Valgrind also doesn't seem to help, as it just causes valgrind itself to segfault without any memory warnings or errors.

**Comment by MikuAuahDark** [comment]
Right. I guess we'll wait for Mike Pall, the author of LuaJIT then.

**Comment by MikuAuahDark** [comment]
An update to this issue.

Someone mentioned (https://github.com/LuaJIT/LuaJIT/issues/811#issuecomment-1046559996) the crash happends because DAZ is set in the MXCSR register. Does OpenAL-soft set those flags in main thread and somehow did not set it back to their previous values?

**Comment by kcat** [comment]
> EDIT: Apparently it seems to be PipeWire's fault. pw_context_new sets the MXCSR flags but didn't set it back to the previous value. Should this be reported to PipeWire upstream?

Yes, it seems to set it [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/eae6517c84fe5963e92f4d982d3181cc0c25611e/src/pipewire/context.c#L295). I don't see why it does that, though. It should only set DAZ for the background thread(s) that do audio processing, not the caller's thread that doesn't do audio processing on. I would certainly suggest reporting that to PipeWire.

**Comment by MikuAuahDark** [comment]
Alright, reported it to upstream https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2160, thanks.
