### ISSUE TITLE
hrtf noise on pause and play looping

### ISSUE THREAD

**Issue by fatalfeel** [kcat/openal-soft#66]
/root/openal-soft-172/examples/alhrtf.c

do
    {
        al_nssleep(10000000);

```
    alSourcePause(al_source);
    alSourcei(al_source, AL_SOURCE_RELATIVE, AL_TRUE);
    alSource3f(al_source, AL_POSITION, 0.0f, 0.0f, -1.0f);
    alSourcePlay(al_source);

    alGetSourcei(al_source, AL_SOURCE_STATE, &state);
} while(alGetError() == AL_NO_ERROR && state == AL_PLAYING);
```

//////////////////
have little noise

**Comment by fatalfeel** [comment]
fixed way~~~
///root/openal-soft-172/OpenAL32/alSource.c
if( voice->Moving == AL_FALSE )  //--> add here
        {
			voice->Moving = AL_FALSE;
			for(i = 0;i < MAX_INPUT_CHANNELS;i++)
			{
				ALsizei j;
				for(j = 0;j < HRTF_HISTORY_LENGTH;j++)
					voice->Direct.Hrtf[i].State.History[j] = 0.0f;
				for(j = 0;j < HRIR_LENGTH;j++)
				{
					voice->Direct.Hrtf[i].State.Values[j][0] = 0.0f;
					voice->Direct.Hrtf[i].State.Values[j][1] = 0.0f;
				}
			}
        }

**Comment by kcat** [comment]
Please provide proper diffs so I can see exactly what's been changed, instead of having to look through a largely unmodified function.

**Comment by fatalfeel** [comment]
//only here
 if( voice->Moving == AL_FALSE )
    {
        //voice->Moving = AL_FALSE;
        for(i = 0;i < MAX_INPUT_CHANNELS;i++)
        {
            ALsizei j;
            for(j = 0;j < HRTF_HISTORY_LENGTH;j++)
                voice->Direct.Hrtf[i].State.History[j] = 0.0f;
            for(j = 0;j < HRIR_LENGTH;j++)
            {
                voice->Direct.Hrtf[i].State.Values[j][0] = 0.0f;
                voice->Direct.Hrtf[i].State.Values[j][1] = 0.0f;
            }
        }
    }

**Comment by kcat** [comment]
Does this still happen? The code relating to this has changed a fair amount, so it may not be a relevant change anymore.

**Comment by kcat** [comment]
This isn't related directly to HRTF, but the fact that you keep pausing and restarting the source. Until there's better handling of pausing sources (as per https://github.com/kcat/openal-soft/issues/103) you can't expect the sound to play smoothly while doing that.
