### ISSUE TITLE
Error after initializing device using alcOpenDevice

### ISSUE THREAD

**Issue by nv-piyush** [kcat/openal-soft#666]
I am using OpenAL shared library(.so) in my project. I ran a unit test and getting this error below,

![image](https://user-images.githubusercontent.com/40065258/155969386-8574a1d6-90b8-4187-b1e0-040bedab7ee2.png)

Please find my source code where I am using this OpenAL library,

```
//OpenAL headers
#include <al.h>
#include <alc.h>

...

bool OpenALSoundManager::Initialize(){
  bool lReturnedValue = false;
  // Opening device
  cout<<"Initializing device"<< endl;
  ALCdevice* lDevice = alcOpenDevice(NULL);

  if ( lDevice )
  {
    // Context creation
    cout<<"Creating OpenAL context"<< endl;
    ALCcontext* lContext = alcCreateContext(lDevice, NULL);

    if ( lContext )
    {
      ...
    }
  }
}
```

I have compiled this by passing -pthread option. Could you please let me know what maybe the issue?

**Comment by kcat** [comment]
Those warnings indicate OpenAL's not able to get real-time priority on your system. That the user doesn't have permission to set real-time priority using `pthread_setschedparam`, and DBus/RTKit aren't available to request real-time priority. These are just warnings, not errors, and won't be seen by default in Release builds. Although it means playback may be more prone to drop-outs or skipping when the system is under load.
