### ISSUE TITLE
Set __ALSOFT_REVERSE_Z in alsoft.ini

### ISSUE THREAD

**Issue by Vercidium** [kcat/openal-soft#668]
Hey,

Is it possible to set the __ALSOFT_REVERSE_Z setting in the alsoft.ini file? I'm having difficulties setting this environment variable when launching the game via Steam / EasyAntiCheat.

Thanks!

**Comment by kcat** [comment]
The compatibility options are mainly intended to be per-game, as they're only needed for particular apps that do something wrong, rather than a config file option since you wouldn't want them enabled for other apps that don't do the bad behavior. What game have you run into that needs `__ALSOFT_REVERSE_Z`?

**Comment by Vercidium** [comment]
This is for my own game, a user picked up that the Z axis was flipped. I set this environment variable locally and it fixed the issue, but I'm unable to figure out how to set this environment variable when running the game through Steam.

I already increase the max number of sources by shipping an `alsoft.ini` file alongside the game, so I was hoping there would be a way to do the same for `__ALSOFT_REVERSE_Z`.

One of my players user [created a fork here](https://github.com/PhoNoTheSky/openal-soft) that adds a setting called `reverse-z` to the `alsoft.ini` file. Is it best I build this fork myself and ship the game with that?

**Comment by kcat** [comment]
If possible, it would be best to fix the game itself (supply proper coordinates to OpenAL). But if you're unable to, and unable to start the game with the environment variable set using a script or something, a config file supplied with the game to set an option would probably be the best remaining alternative.

I just updated the master branch with a config option you can set:
```
[game_compat]
reverse-z = true
```

Something to note, if your X positioning is correct (proper left-right panning) but Z (front-back) is flipped, it would be a good idea to also check if Y (up-down) is also flipped. This will need headphones/HRTF to test, unless you or someone is capable of setting up a 3D7.1 configuration ("proper" with-height speaker setups aren't currently handled, so 3D7.1 and HRTF are the only practical ways OpenAL Soft can do it). If Y is also flipped and you can't fix the coordinates given to OpenAL, another compatibility option for that would be needed.

**Comment by Vercidium** [comment]
I'd love to fix this but have never been able to get the maths right.

The game uses Y as up for it's 3d coordinates and I set this in the AL_ORIENTATION value.

I calculate listener position, velocity and orientation like this:

```cs
var pos = CameraPosition().TF();
var vel = ThisPlayerBase.velocity.TF();
var ori = Helper.FromPitchYawF((float)cameraPitch, (float)cameraYaw); // Convert pitch and yaw to a Vector3F
```

I then convert these vectors to arrays and send them to OpenAL:
```cs
// Convert Vector3F to float[]
float[] posArray = new float[3];
float[] velArray = new float[3];
float[] oriArray = new float[6];

VecToArray(ref posArray, ref p);
VecToArray(ref velArray, ref v);
VecToArray(ref oriArray, ref o);


// Store (0, 1, 0) as the UP vector
oriArray[3] = 0;
oriArray[4] = 1;
oriArray[5] = 1;


// Send to OpenAL
AL.Listenerfv(AL10.AL_POSITION, posArray);
AL.Listenerfv(AL10.AL_VELOCITY, velArray);
AL.Listenerfv(AL10.AL_ORIENTATION, oriArray);
```

The issue is that the horizontal direction is inverted: https://youtu.be/CqyQhVFj8rQ

And when looking up/down, far-away sounds sound like they're a lot closer: https://youtu.be/6k9jAHcvze4

The same issues happen with HRTF enabled and disabled.

I play 3D sounds like this:

```cs
// Create a source and associate it with our buffer
uint ID = AL.GenSource();
AL.Sourcei(ID, AL10.AL_BUFFER, alBufferID);


// Spatialise stereo
AL.Sourcei(ID, AL10.AL_SOURCE_RELATIVE, false);
AL.Sourcei(ID, ALEXT.AL_SOURCE_SPATIALIZE_SOFT, true);


// Set basic parameters
AL.Sourcef(ID, AL10.AL_GAIN, 1.0f);
AL.Sourcef(ID, AL10.AL_PITCH, 1.0f);
AL.Sourcef(ID, AL10.AL_REFERENCE_DISTANCE, 8.0f);
AL.Sourcef(ID, AL10.AL_ROLLOFF_FACTOR, 1.0f);


// Set position, velocity and direction for each 3D sound
// The issue still occurs when commenting out the velocity and direction lines
AL.Sourcefv(ID, AL10.AL_POSITION, posArray);
AL.Sourcefv(ID, AL10.AL_VELOCITY, velArray);
AL.Sourcefv(ID, AL10.AL_DIRECTION, dirArray);
```

The only solution I've found so far is to adjust the yaw and clamp the pitch that I sent to OpenAL for the listener like this:

```cs
var ori = Helper.FromPitchYawF((float)cameraPitch * 0.6f, (float)cameraYaw - MathF.PI);
```

This seems like a good cover-up solution but I'd like to figure out what I'm doing wrong: https://youtu.be/Pz0PFYZrR2Q

@ThreeDeeJay pointed out that the front/behind directionality is flipped and provided a video visualising the 3D audio: https://youtu.be/jOhYFVi0dVc

Any advice on testing/debugging/fixing this would be greatly appreciated :)

**Comment by ThreeDeeJay** [comment]
> @ThreeDeeJay pointed out that the front/behind directionality is flipped and provided a video visualising the 3D audio: https://youtu.be/jOhYFVi0dVc

I should point out that this is an ambisonics recording played back in regular stereo so no HRTF, just for positional visualization; and that the Z axis was only flipped for *some* sounds, which is odd. 
In that video, you can see the nade launcher thump in front of the listener, but the nade bounce and explosion behind.
reverse-z fixed those flipped sounds without also flipping the ones that have correct z-axis coordinates, but yeah, the Y-axis still had the issue described above with the listener that doesn't rotate with the camera: https://i.imgur.com/08gKcVd.mp4

**Comment by kcat** [comment]
> The game uses Y as up for it's 3d coordinates

What directions do +X and +Z represent?

OpenAL uses a right-handed coordinate system, which means, **+X** points to the right (or east), **+Y** points up (or skyward), and **-Z** points forward (or north; note Z is negative, which means Z=-2 is more north than z=-1). This is the same coordinate system used by OpenGL.

Another (perhaps more widely used?) coordinate system is a left-handed coordinate system. Under this, **+X** is right/east (the same), **+Y** is up/skyward (the same), but **+Z** is forward/north (the reverse of OpenAL).

If using the vectors as-is doesn't work with OpenAL, and +Y is up, it's likely you're using a left-handed coordinate system. If this is the case, converting from left-handed to right-handed is actually very easy: simply negate Z on all vectors passed to OpenAL. Something like this:
```cs
// Convert left-handed to right-handed
posArray[2] *= -1; // pos.z
velArray[2] *= -1; // vel.z
oriArray[2] *= -1; // at.z
oriArray[5] *= -1; // up.z


// Send to OpenAL
AL.Listenerfv(AL10.AL_POSITION, posArray);
AL.Listenerfv(AL10.AL_VELOCITY, velArray);
AL.Listenerfv(AL10.AL_ORIENTATION, oriArray);
```
And similar for sources:
```cs
posArray[2] *= -1;
velArray[2] *= -1;
dirArray[2] *= -1;

// Set position, velocity and direction for each 3D sound
AL.Sourcefv(ID, AL10.AL_POSITION, posArray);
AL.Sourcefv(ID, AL10.AL_VELOCITY, velArray);
AL.Sourcefv(ID, AL10.AL_DIRECTION, dirArray);
```

And something for a bit of a clarification:
> The game uses Y as up for it's 3d coordinates and I set this in the AL_ORIENTATION value.
> ...
> ```cs
> // Store (0, 1, 0) as the UP vector
> oriArray[3] = 0;
> oriArray[4] = 1;
> oriArray[5] = 1;
> ```

If you think of the listener as an independent object in space, the listener's AL_ORIENTATION up vector is the direction the listener's top is pointing, not (strictly speaking) the up axis. Having the up vector be `(0, 1, 0)` would be true only when the listener is perfectly upright. If the listener is tilted forward, backward, or to the side, the up vector would change accordingly. And the way it's being set there, the up vector is being fixed to a 45-degree up-back direction, which is most likely incorrect. The "at" and "up" vectors should form a 90-degree angle, if they don't it can have odd effects on sound positioning.

**Comment by Vercidium** [comment]
That fixed it! I now negate Z on any position/velocity/direction/orientation I send to OpenAL, and the up vector is always perpendicular to where the player is looking:

```cs
var orientation = Helper.FromPitchYawF((float)cameraPitch, (float)cameraYaw);
var up = Helper.FromPitchYawF((float)cameraPitch + MathF.PI / 2, (float)cameraYaw);
```

This works perfectly, thank you so much for your help.
