### ISSUE TITLE
windows: international encoding not supported

### ISSUE THREAD

**Issue by snikulov** [kcat/openal-soft#67]
On windows with language others then English it is not possible to get correct device information because ALCchar is always char ```typedef char ALCchar;```

This will produce unreadable results as follows

![open-al](https://cloud.githubusercontent.com/assets/142123/18384380/e182c4a4-7692-11e6-89e4-a8ebca2f5154.png)

Is it possible to support international encoding on Windows platform?

**Comment by kcat** [comment]
With recent versions, the returned strings are UTF-8 encoded. You should be able to convert the names from UTF-8 to WCHAR with ```MultiByteToWideChar```, using the ```CP_UTF8``` codepage. For example:
```
WCHAR *FromUTF8(const char *str)
{
    WCHAR *out = NULL;
    int len;

    if((len=MultiByteToWideChar(CP_UTF8, 0, str, -1, NULL, 0)) > 0)
    {
        out = calloc(sizeof(WCHAR), len);
        MultiByteToWideChar(CP_UTF8, 0, str, -1, out, len);
    }
    return out;
}
```
(then make sure to call ```free()``` on the returned string, when you're done with it).

Unfortunately the ```openal-info``` utility doesn't currently do this, leading to the UTF-8 characters being displayed incorrectly. I'll see what I can do about fixing that.

**Comment by snikulov** [comment]
@kcat Thank you for explanation.
Sorry for noise :)

**Comment by kcat** [comment]
This should work now with commit ba449cc. Feel free to try, if you're able.

**Comment by snikulov** [comment]
@kcat Now it's just empty.
utf-8 -> wchar_t is good.
But Windows console (```cmd.exe```) does not support wchar_t (On higher windows (Vista +) should support utf-8 - CP 65001, which not set by default).
So additional conversion required wchar_t -> WideCharToMultiByte(CP_ACP, ...
to current Code Page and then simple ```printf(...)``` should work.

**Comment by snikulov** [comment]
@kcat So I think it's better to revert this change.
```chcp 65001``` in console with UTF-8 fonts solves issue with openal-info without any code changes.
