### ISSUE TITLE
How to set a source volume without changing effect volume ?

### ISSUE THREAD

**Issue by Lulu04** [kcat/openal-soft#673]
Hi kcat, first, thanks you for OpenAL-Soft !
I have translated header to FreePascal/Lazarus and write a pascal demo.
In this demo, user can load a sound file, apply an effect on it and set the volume effect, and source volume.

The effect volume is set with    alAuxiliaryEffectSlotfv( SlotID, AL_EFFECTSLOT_GAIN, @FEffectVolume)
The source volume is set with   alSourcef( FSource, AL_GAIN, FVolume ); 

The actual feature is when user change Source volume, the effect volume change accordingly.
There is a way to set the dry volume (source) and the effect volume separatly ?

Regards

**Comment by kcat** [comment]
You can use a filter to set separate volumes for the direct and room signals. In C it's something like this:
```c
// One time creation
ALuint filter;
alGenFilters(1, &filter);
alFilteri(filter, AL_FILTER_TYPE, AL_FILTER_LOWPASS);

...

// To set the dry gain for just this source:
alFilterf(filter, AL_LOWPASS_GAIN, drygain);
alSourcei(source, AL_DIRECT_FILTER, filter); // Copies the filter properties; the filter can be altered afterward without affecting the source

// To set the wet gain for just this source on the given effect send:
alFilterf(filter, AL_LOWPASS_GAIN, wetgain);
alSource3i(source, AL_AUXILIARY_SEND_FILTER, auxslot, sendindex, filter);
```
With a lowpass filter, you can also set `AL_LOWPASS_GAINHF` to reduce the high-frequency gain for the direct and room responses (relative to the overall gain set by `AL_LOWPASS_GAIN`). Alternatively, you can set the filter type to `AL_FILTER_HIGHPASS` and use `AL_HIGHPASS_GAIN` for the overall gain, and `AL_HIGHPASS_GAINLF` to control the low-frequency gain. Or `AL_FILTER_BANDPASS` and use `AL_BANDPASS_GAIN` for the overall gain, `AL_BANDPASS_GAINHF` for the high-frequency gain, and `AL_BANDPASS_GAINLF` for the low-frequency gain.

**Comment by Lulu04** [comment]
thank you for your clear answer. I tried what you wrote and it works very well.
Now the effect dry/wet gain can be set with
```
// To set the dry gain for just this source:
alFilterf(filter, AL_LOWPASS_GAIN, drygain);
alSourcei(source, AL_DIRECT_FILTER, filter); // Copies the filter properties; the filter can be altered afterward without affecting the source

// To set the wet gain for just this source on the given effect send:
alFilterf(filter, AL_LOWPASS_GAIN, wetgain);
alSource3i(source, AL_AUXILIARY_SEND_FILTER, auxslot, sendindex, filter);
```
and the global source volume (source + effect) can be set with
`alSourcef( FSource, AL_GAIN, SoundVolume );`

Thanks you very much kcat.
