### ISSUE TITLE
Multichannel to stereo downmix

### ISSUE THREAD

**Issue by zoluxsys** [kcat/openal-soft#676]
Hi,

I was watching this project for a while now, and I would like to thank you the amazing job you did!
And yes there is a question coming.
Is there any advantage to request higher then stereo channels (or ambi) and downmix them to stereo?
Yes, I am trying to do this, but it seems, Openal-soft still requesting stereo. Am I missing something?

If I do this:
channels=surround51 or higher
stereo-mode=headphones
stereo-encoding=hrtf or others
hrtf-mode=full
hrtf=true

Windrows sound set to stereo and using headphones, testing with FEAR (GoG latest) with latest DSOAL and Openal-soft.
The DLL reads the right config:
[ALSOFT] (II)  found 'channels' = 'surround51'
[ALSOFT] (II) Found channels = "surround51"

But, still request stereo:
[ALSOFT] (II) Pre-reset: *Stereo, Float32, *48000hz, 960 / 2880 buffer
[ALSOFT] (II) Requesting playback format:
    FormatTag      = 0xfffe
    Channels       = 2
    SamplesPerSec  = 48000
    AvgBytesPerSec = 384000
    BlockAlign     = 8
    BitsPerSample  = 32
    Size           = 22
    Samples        = 32
    ChannelMask    = 0x3
    SubFormat      = {00000003-0000-0010-8000-00aa00389b71}

**Comment by kcat** [comment]
Setting the `hrtf=true` config option overrides the `channels` config option. HRTF only works with stereo, so to give HRTF like you ask, it has to request stereo output from the device.

On Windows specifically, it's also unlikely OpenAL Soft could get a different channel configuration than the device is set for in the system. At most it can use a subset of the speaker configuration (e.g. if you have a 5.1 device and ask for stereo, OpenAL Soft can render stereo to the front-left and front-right of the 5.1 device, leaving the other channels silent).

**Comment by zoluxsys** [comment]
Understand, so my openal-soft channel layout also based on my windows channel layout.
Thank you!
