### ISSUE TITLE
Undefined behaviour in al::byte

### ISSUE THREAD

**Issue by kin4stat** [kcat/openal-soft#678]
unsigned char/char/signed char/std::byte marked as aliasing with any type. But user types defined like std::byte but not being typedef of std::byte or char won't alias with any type, so casting void* to al::byte like here https://github.com/kcat/openal-soft/blob/4999b5716cfbe95f3e8ed5e9dc3014c3ec8652c8/alc/alc.cpp#L3685 and subsequent dereferencing is UB

Possible solution is to replace definition of byte to 
`using byte = unsigned char;`
if __cplusplus <= 2017
and
`using byte = std::byte`
if __cplusplus >= 2017

But on MSVC without /permissive __cplusplus defined as 1997, so we need to handle this in special way

**Comment by kcat** [comment]
Fixed with commit abfb584f1493b6295093a73235f1cea77ec15575.
