### ISSUE TITLE
Reverb or Echo Bug

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/openal-soft#684]
In the very first level of Indiana Jones and the Infernal Machine there is a strong echo/reverb through almost the entire level emanating from the distant waterfall. This did not appear in older version of OpneAL-Soft nor does it show up when using ALchemy. There are a few other places in the game where the echo/reverb seem much stronger than they do with ALchemy as well. I think it could be a combination of the reverb/echo effect not properly culling as well as being set too strongly by default. Here is a link to a video recording I did to help you hear what it is I am talking about. https://youtu.be/HKDf3J5iQZM

**Comment by kcat** [comment]
Is this through DSound/DSOAL? What version/build are you using of OpenAL Soft and DSOAL? Are you able to get trace logs? Set the `DSOAL_LOGLEVEL` environment variable to `3`, and `DSOAL_LOGFILE` to a full path+filename to write it to.

**Comment by Jenavieve-Rose** [comment]
> Is this through DSound/DSOAL? What version/build are you using of OpenAL Soft and DSOAL? Are you able to get trace logs? Set the `DSOAL_LOGLEVEL` environment variable to `3`, and `DSOAL_LOGFILE` to a full path+filename to write it to.

So yes I am using DSOAL and I am using the ,a test build of both. I seem to be having an issue getting a log file to create, so are there directions on how to do it just to make sure I'm not missing a step somewhere?

**Comment by Kappa971** [comment]
![6dr1x](https://user-images.githubusercontent.com/62349018/163611559-d33df452-1608-4676-a09b-588379c46cb1.jpg)
This image found from the internet is self-explanatory.

**Comment by Jenavieve-Rose** [comment]
> ![6dr1x](https://user-images.githubusercontent.com/62349018/163611559-d33df452-1608-4676-a09b-588379c46cb1.jpg)
> 
> This image found from the internet is self-explanatory.

I have no idea what I'm looking at or what this is referencing?

**Comment by Kappa971** [comment]
> I have no idea what I'm looking at or what this is referencing?

On the Windows search type "environment variables" and this window will pop out. From here add the variables recommended by @kcat.

**Comment by Jenavieve-Rose** [comment]
I have tried two separate ways to add Environmental Variables as I am not sure how it is supposed to look as well as a batch file which has worked in the past and just can't get a log to create.

![Screenshot 2022-04-15 141143](https://user-images.githubusercontent.com/28971540/163622718-f62af76f-1ea4-4a17-bd19-754f11241212.png)
![Screenshot 2022-04-15 141326](https://user-images.githubusercontent.com/28971540/163622719-1660f528-11b2-471c-874a-6675d7d6b6d7.png)
![Screenshot 2022-04-15 141402](https://user-images.githubusercontent.com/28971540/163622720-72674e5d-cef1-4beb-b6d4-c8b7653a9038.png)

**Comment by Kappa971** [comment]
In "Variable" you must write the name of the variable without "set" (`DSOAL_LOGLEVEL` and `DSOAL_LOGFILE`), while in "Value" you must write only the value (`3` and `dsoal_log.txt`).

**Comment by Jenavieve-Rose** [comment]
Thank you for the assistance. I was able to get a trace.
[dsoal_error.txt](https://github.com/kcat/openal-soft/files/8498397/dsoal_error.txt)

**Comment by kcat** [comment]
Looks like a problem as a result of the issue mentioned here: https://github.com/kcat/openal-soft/issues/675#issuecomment-1079711208

In short, the game itself doesn't use EAX, but DSOAL makes a couple EAX calls during initialization that causes OpenAL Soft to "initialize" EAX support, which currently causes a default effect to initialize and be applied to sources. However, what it needs to do is track properties for the different versions of EAX, and only apply the last version set (i.e. nothing in the case of this game).

I added a workaround with commit 5c0eabc5264a58e8fe9f78da6198587d78770d01. It's not a proper fix, but should avoid this issue.

**Comment by Jenavieve-Rose** [comment]
> Looks like a problem as a result of the issue mentioned here: [#675 (comment)](https://github.com/kcat/openal-soft/issues/675#issuecomment-1079711208)
> 
> In short, the game itself doesn't use EAX, but DSOAL makes a couple EAX calls during initialization that causes OpenAL Soft to "initialize" EAX support, which currently causes a default effect to initialize and be applied to sources. However, what it needs to do is track properties for the different versions of EAX, and only apply the last version set (i.e. nothing in the case of this game).
> 
> I added a workaround with commit [5c0eabc](https://github.com/kcat/openal-soft/commit/5c0eabc5264a58e8fe9f78da6198587d78770d01). It's not a proper fix, but should avoid this issue.

This makes a lot of sense. I knew this game didn't use EAX and so far, the latest versions of OpenAL-Soft and DSOAL seem fine in games that do use EAX. This probably explains the reverb in several other places in the game too I never remember hearing before.

**Comment by Jenavieve-Rose** [comment]
The work around seems to do the trick for now.
