### ISSUE TITLE
How to build OpenAL-Soft Configurator

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/openal-soft#694]
I have no issues building the DLL using CMAKE and Visual Studio, but I cannot seem to figure out how to actually build the configurator tool.

**Comment by kcat** [comment]
You need Qt5 for the configuration tool, which cmake should detect and enable when found. If you have Qt5 and your compiler can use it, it would be helpful to see the cmake output from a fresh build/configuration (starting with an empty build directory).

**Comment by Jenavieve-Rose** [comment]
> You need Qt5 for the configuration tool, which cmake should detect and enable when found. If you have Qt5 and your compiler can use it, it would be helpful to see the cmake output from a fresh build/configuration (starting with an empty build directory).

When i download Qt5 what exactly do I need?

**Comment by Jenavieve-Rose** [comment]
Okay so I figured out how to download qt5 and configure Visual Studio to use it. i can build the .exe, but it does not build any of the qt5 DLL so it errors out when trying to launch the configurator.

**Comment by kcat** [comment]
You need `Qt5Core.dll`, `Qt5Gui.dll`, `Qt5Widgets.dll`, and `platforms/qwindows.dll` next to the executable for it to run.

**Comment by Jenavieve-Rose** [comment]
> 

I understand that, but where do i get them as those are not being built. Full disclosure I am very much an amateur at this.

**Comment by kcat** [comment]
I'm not too familiar with Qt's install tool either, particularly for Windows/MSVC. But there should be an option to get the runtime DLLs along with the development files.

**Comment by Jenavieve-Rose** [comment]
Thanks I figured it out. The QT build has the DLL but you have to creat the platform one. I followed this stackoverflow question to figure that out. https://stackoverflow.com/questions/33647986/qwindows-dll-never-found-in?msclkid=23680134c75611ecbddc397c3055ad79
