### ISSUE TITLE
AirAbsorption behavior on 1.22 differs from 1.21

### ISSUE THREAD

**Issue by badosu** [kcat/openal-soft#701]
On [BAR](https://github.com/beyond-all-reason/Beyond-All-Reason/) we allow users to configure air absorption to provide a realistic effect for distance over unit interactions.

We have a slider that ranges from 0.05 to 0.40, this updates the factor for the sound sources [here](https://github.com/badosu/spring/blob/c98266d1a9abed2175773769d917a2f249031845/rts/System/Sound/OpenAL/SoundSource.cpp#L67).

On 1.21 it works as expected, the chosen scale seems to offer good settings for users.

Some users on Arch updated openal to 1.22 and started claiming that the airabsorption is excessive, with almost all sounds having an extreme high pass filter applied.

I tested on 1.22-gc870e550 and can confirm indeed the behavior has changed. I couldn't find anything on our codebase that could be breaking. I also noticed a considerable amount of commits were introduced in 1.22 that touch this property.

I couldn't find anything on the changelog that could indicate a documented change in the property scaling or change of behavior, so for now I'm assuming this is unintended behavior or a bug.

**Comment by kcat** [comment]
Looks like the air absorption base was left unset, resulting in the high-frequency gain being set to 0 once air absorption kicked in (doesn't happen if the air absorption factor is left at 0, the default). Should be fixed in commit 23b4611cd093afa3301103ac5921755436168791.

**Comment by badosu** [comment]
I can confirm it is fixed in https://github.com/kcat/openal-soft/commit/23b4611cd093afa3301103ac5921755436168791

**Comment by badosu** [comment]
I (and the the BAR team) appreciate the quick response!
