### ISSUE TITLE
EAX Reverb Regression

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/openal-soft#706]
Looks like a problem as a result of the issue mentioned here: https://github.com/kcat/openal-soft/issues/675#issuecomment-1079711208

In short, the game itself doesn't use EAX, but DSOAL makes a couple EAX calls during initialization that causes OpenAL Soft to "initialize" EAX support, which currently causes a default effect to initialize and be applied to sources. However, what it needs to do is track properties for the different versions of EAX, and only apply the last version set (i.e. nothing in the case of this game).

I added a workaround with commit 5c0eabc5264a58e8fe9f78da6198587d78770d01. It's not a proper fix, but should avoid this issue.

_Originally posted by @kcat in https://github.com/kcat/openal-soft/issues/684#issuecomment-1100755947_

I have compiled the latest version of OpenAl-Soft as of writing this and I have the reverb back in games that do not use reverb.
[dsoal_log.txt](https://github.com/kcat/openal-soft/files/8771421/dsoal_log.txt)

**Comment by Jenavieve-Rose** [comment]
To clear up any confusion this is the same issue I had in issue #684. https://youtu.be/HKDf3J5iQZM It seems to have been reintroduced or the workaround disabled with the most recent commit.

**Comment by kcat** [comment]
Probably due to a recent commit introducing the per-version EAX property handling. While EAX2 has reverb silent by default, 3 and up don't. And when initializing a buffer, DSOAL makes an EAX4 call to set default source slots, which causes the effect to initialize with EAX4's non-silent defaults.

**Comment by Kappa971** [comment]
I tried GTA 3 (EAX 3) with DSOAL pre and after the last commit and in both cases, the reverb level is exaggerated. Considering that other games (even GTA Vice City) do not suffer from this problem, maybe the developers of GTA 3 have misadjusted the reverb? Here the log: [dsoal_log.txt](https://github.com/kcat/openal-soft/files/8779428/dsoal_log.txt)
With the old version of DSOAL (pre OpenAL Soft with EAX extensions), in GTA 3 the reverb was mild (but it could be that it was behaving the wrong way, I don't know).

The other games in my case seem to work fine (but I don't have an X-Fi to make comparisons).

**Comment by mirh** [comment]
Possibly related to what I complained here https://github.com/bibendovsky/eaxefx/issues/19

**Comment by Kappa971** [comment]
I don't know if this solved the problem @Jenavieve-Rose mentioned, but far GTA 3 there is still some exaggerated reverb. However, I don't know if this is the normal behavior of the game, as already mentioned. 

I bought an X-Fi Titanium, it should arrive next week. If I can get it to run on Windows 11 or 10 without a BSOD, I can say for sure how GTA 3 should "sound" with EAX.

**Comment by Kappa971** [comment]
>Stick with W7 if you can.

I can't, I would lose Freesync and it's not acceptable. I hope the X-Fi Support Pack 8.0 (Refresh 3) drivers work fine: https://danielkawakami.blogspot.com/.

**Comment by mirh** [comment]
I highly doubt @LAGonauta
And btw that's an nvidia limitation more than anything, and you don't really need vsync anyway on a high refresh rate monitor.

**Comment by Kappa971** [comment]
Maybe we should continue the discussion elsewhere, I don't think this is the right place.

**Comment by Kappa971** [comment]
The X-Fi was delivered to me early. All the games I have tried work perfectly, even OpenAL games like Doom 3, Quake 4, Bioshock, even Unreal 2 seem to work fine (I finished the training course with no problems).
But back to the main topic (I won't go off topic anymore), let's talk about the reverb on GTA 3. Even with the X-Fi, GTA 3 has an exaggerated reverb, but somehow different. It seems that the "echo" effect is less pronounced, the reverb is "shorter", I don't know how to describe it, and when you press the ESC key to go to the game menu, the reverb is stopped immediately (on the contrary, this doesn't happens with ALchemy "software" and DSOAL, entering the menu you will hear the reverb for a few seconds).

**Comment by mirh** [comment]
My hats off for doing what ***truly a lot of people*** couldn't be bothered to do (also interesting that you had no problem, maybe they used [this hack](https://www.reddit.com/r/SoundBlasterOfficial/comments/i2mrhj/new_support_packs_for_xfi_and_audigy/g0zs768/)?)
But I'm afraid only windows XP could be the only true arbiter (not that authorial intent should matter more than "what your ears like", but still I feel like that would be overflying the most important piece of the equation). 

I'm not sure if you can do pcie passthrough of non-gpu devices in windows then, but I'm wondering an XP qemu vm from some linux distro should definitively do it. And [this](https://aur.archlinux.org/packages/mutter-vrr) could also probably still retain freesync for you :)

**Comment by Jenavieve-Rose** [comment]
You may want to open up a seperate ticket as this does not have anything to do with what I opened this ticket up about.

**Comment by kcat** [comment]
Does https://github.com/kcat/dsoal/commit/a16c19fdbb6c56bbd40a011362da0742a49f6f35 fix the issue mentioned here? It shouldn't force reverb to be audible anymore with games that don't use EAX.

**Comment by Jenavieve-Rose** [comment]
> Does [kcat/dsoal@a16c19f](https://github.com/kcat/dsoal/commit/a16c19fdbb6c56bbd40a011362da0742a49f6f35) fix the issue mentioned here? It shouldn't force reverb to be audible anymore with games that don't use EAX.

Yes this has fixed the issue thanks
