### ISSUE TITLE
"Oboe" in `find_package(Oboe)` should be lowercase.

### ISSUE THREAD

**Issue by MikuAuahDark** [kcat/openal-soft#709]
https://github.com/kcat/openal-soft/blob/c6820bf266beabb0de99df1ee5474a62015c1554/CMakeLists.txt#L1146

Google page on [Oboe getting started](https://github.com/google/oboe/blob/main/docs/GettingStarted.md) uses `oboe` with lowercase "O" as the package name. This causes confusion when I try to diagnose build failure of my app in CI but not locally as turns out the prebuilt config file assumes lowercase "O".

Changing it to lowercase "O" then replacing `FindOboe.cmake` to `Findoboe.cmake` is one solution, but then people won't able to use prebuilt binaries by Google because CMake prefers module searchers by default and if CMake found one (likely the ones that OpenAL-soft provide), it won't fallback to config mode and reports that Oboe is not found.

I can think of 2 solutions without thinking of the possibility:
1. Remove `FindOboe.cmake` altogether from OpenAL-soft repository. This will allow CMake to fallback to config mode (assume the package case is changed too and the `OBOE_FOUND` check is changed to `TARGET oboe::oboe`), which then allows user to use Google prebuilt binaries.
2. Somehow make `Findoboe.cmake` attempts to find `oboe` in config mode first then search normally so people can use Google's prebuilt binaries.

**Comment by kcat** [comment]
Commit f3092e286e8dc8ca7a2c6f2b89cb413f806944d2 now searches for Oboe using `CONFIG` and a lowercase "o", as in that getting started page, then falls back to the normal Find module if it's not found.

**Comment by MikuAuahDark** [comment]
Everything now works, thanks. Gotta continue testing the microphone recording issue ASAP.
