### ISSUE TITLE
Failed to build openal-soft with mingw81_32

### ISSUE THREAD

**Issue by 8Observer8** [kcat/openal-soft#715]
MinGW Version: 8.1 32 bit (from Qt 5.15.2)
OS: Win10
OpenAL-Soft Version: master-branch
CMake GUI from Qt 5.15.2

I set three check boxes:

![image](https://user-images.githubusercontent.com/3908473/172269863-133f487c-abe0-408e-a8c1-1ed001ac2692.png)

![image](https://user-images.githubusercontent.com/3908473/172269655-4216edbb-a845-480d-8985-f56f26ea98bb.png)

**Comment by kcat** [comment]
I'm not sure exactly why this happens. As far as I can tell, nothing improper is being set, but the way CMake is trying to define a macro for windres/gcc is failing to escape it properly, making gcc think a filename is being specified instead of a macro body.

**Comment by 8Observer8** [comment]
I tried to use MinGW GNU 8.1.0 64-bit from Qt 6.2.0 64-bit. I do not change any configuration setting. It works:

![image](https://user-images.githubusercontent.com/3908473/174072047-ab19f013-6b3f-4490-818a-676606f84e07.png)

**Comment by kcat** [comment]
64-bit doesn't need to set the `__attribute__((force_align_arg_pointer))` attribute on exported functions, so it doesn't get passed to windres/gcc to confuse it.

**Comment by kcat** [comment]
Should be fixed with commit fa51c89549590319cb545a8c81419e2e1ddc5db3.
