### ISSUE TITLE
Missing functions in Windows import libs (again)

### ISSUE THREAD

**Issue by slipher** [kcat/openal-soft#719]
In the 1.22.0 binary release, the `alEffect`* extension functions are again missing from `libOpenAL32.dll.a`. This is a recurrence of #497.

In the 1.21.1 binary release, those functions are present in the import library.

**Comment by kcat** [comment]
Add back with commit 0e7d5736c0b66d0639beb395b512416d252d28fb, along with a note to help ensure they're not removed again.
