### ISSUE TITLE
Rejection of older pipewire version works the other way around

### ISSUE THREAD

**Issue by ilya-fedin** [kcat/openal-soft#721]
PW_CHECK_VERSION checks for the library version to be greater than the specified version. As a result, I get `[ALSOFT] (WW) PipeWire version "0.3.51" too old (0.3.33 or newer required)`

**Comment by ilya-fedin** [comment]
openal doesn't build build with pipewire 0.3.23 btw, it uses PW_KEY_NODE_RATE that was added 0.3.33

**Comment by kcat** [comment]
Fixed. The `PW_CHECK_VERSION` macro can't actually be used to check the library version, despite what the headers say. And `PW_KEY_NODE_RATE` now gets defined if missing, so it should build with 0.3.23.

**Comment by ilya-fedin** [comment]
I fixed it as `!PW_CHECK_VERSION(major, minor, revision + 1)` for myself :D

**Comment by ilya-fedin** [comment]
I hope new release will be done soon as it's quite a big bug
