### ISSUE TITLE
confusion about source that feeds an effect

### ISSUE THREAD

**Issue by Lulu04** [kcat/openal-soft#732]
Hi, in a previous question [https://github.com/kcat/openal-soft/issues/673](https://github.com/kcat/openal-soft/issues/673)
you write we can use a source direct filter to control the dry gain and an another filter applied on an auxiliary send to control the wet gain.
The code to sets wet gain is:
`alFilterf(filter, AL_LOWPASS_GAIN, wetgain);
alSource3i(source, AL_AUXILIARY_SEND_FILTER, auxslot, sendindex, filter);`

Reading OpenAL Effects Extension Guide, I found that we can also control wet gain with:
`alAuxiliaryEffectSlotf(SlotID, AL_EFFECTSLOT_GAIN, wetgain);`

I tested the two way and I don't hear the difference between the two.
If I understand correctly, with an auxiliary send filter one controls the level of the sound that enter in the effect, while AL_EFFECTSLOT_GAIN controls the level of the sound after processed by the effect ? That's right ?
Sorry for my confusion.

Regards

**Comment by kcat** [comment]
> If I understand correctly, with an auxiliary send filter one controls the level of the sound that enter in the effect, while AL_EFFECTSLOT_GAIN controls the level of the sound after processed by the effect ? That's right ?

Yes. The send filter attenuates the sound before it goes to the effect, so any sound in the effect (e.g. the reverb decay) will continue as normal until the sound works its way through, while the effect slot gain changes the effect output right away. The send filter also only affects the gain of that specific source, where the effect slot gain affects all sounds in the effect.

**Comment by Lulu04** [comment]
Thanks you for your reply and for your amazing work.
Regards
