### ISSUE TITLE
Max sources design question

### ISSUE THREAD

**Issue by Leadwerks** [kcat/openal-soft#736]
In hardware OpenAL we needed to dynamically assign a pool of alsource objects to various sound sources, based on distance from the camera, due to the limited number of sources that can be created and played.

Is openal-soft designed with the same limitations, or is there already a built in that allows us to just create and play as many sound sources as we want, and let the library take care of the details?

The answer to this question will determine the code design for our sound system.

**Comment by kcat** [comment]
> Is openal-soft designed with the same limitations, or is there already a built in that allows us to just create and play as many sound sources as we want, and let the library take care of the details?

Yes and no. OpenAL Soft allows you to specify how many sources you want to be able to create, which can be almost any number you want (the `ALC_MONO_SOURCES` and `ALC_STEREO_SOURCES` context attributes will, added together, specify the number of sources you want to be able to create), but it has to be declared at context creation time. The library also doesn't do any automatic load limiting, so if you ask for, create, then play 10000 sources, it will attempt to mix/process all of them, even if that makes the device underrun.

So you'll be able to ask for and create a virtually unlimited number, but you will need to limit the number you play at any given time if you want to avoid overloading the system.

**Comment by Leadwerks** [comment]
Okay, so there's really no downside to creating 1000 sound sources as long as the number of _currently playing_ sources is limited?
