### ISSUE TITLE
Win32 application crash with equalizer effect

### ISSUE THREAD

**Issue by Lulu04** [kcat/openal-soft#738]
Hi, I have translated OpenAL-Soft header to FreePascal and write some demos to the pascal community.
This demos are tested under Windows and Linux, 32 and 64bits.

All works well until in one of this demo I use Equalizer effect:
On Win32 application sometime crash, sometime not. Application that use equalizer never crash under Win64, Linux32 nor Linux64.

First, I thought that the problem was with the pascal code layer. To eliminate this possible cause, I added the use of equalizer effect in one of the C example provided with OpenAL-Soft  -> **altonegen.c** 

On my Win7 32bits old computer, the transformed altonegen some time crash, sometime not.
The DLL used to make the test is from [https://openal-soft.org/openal-binaries/openal-soft-1.22.2-bin.zip](https://openal-soft.org/openal-binaries/openal-soft-1.22.2-bin.zip)

In the attached ZIP file, you will found the transformed **altonegen.c**, one log file with crash, one without and the result of openal-info.
Thanks for your time.

[Win32EqualizerCrashTest.zip](https://github.com/kcat/openal-soft/files/9150739/Win32EqualizerCrashTest.zip)

**Comment by Lulu04** [comment]
I forgot to mention that all the other effects proposed by the extension work very well, both in 64 and 32 bits.

In the transformed altonegen.c, we creates 60 equalizer effects, this have no sense, it's only to do an intensive use of it.
Only the first is attached to the source.
If you have time and the possibility to compile on a win32 machine, could you test it ? Just to see if the crash also appears.
Here, the average is 5 crashes on 10 tries.
Regards

**Comment by kcat** [comment]
If you're able, try now with commit f35eb64619ae91cd786380660e3d90da18f557fb. The equalizer's processing buffer wasn't explicitly aligned, so depending on the allocated address for the effect object, it could end up unaligned and crash when trying to use SSE with it.

**Comment by Lulu04** [comment]
Well done, crash not appears any more ! Thanks you very much and 'bravo' for your efficiency !
