### ISSUE TITLE
attach reverb effect to stereo or mono sound

### ISSUE THREAD

**Issue by palfu** [kcat/openal-soft#74]
Env: windows 7, code version(git commit "Recognize Headset formfactors as headphones")
Mono sound
a. Attaching reverb effect to mono sound, the output of aluMixData is stereo, and signal of left channel is different with right channel. Effect code like this:
```
alEffecti(effect, AL_EFFECT_TYPE, AL_EFFECT_REVERB);
alEffectf(effect, AL_REVERB_DECAY_TIME, 10.0f);
alEffectf(effect, AL_REVERB_GAIN, 0.9f);
```
Stereo sound
b. Switching to stereo sound, the output of AluMixData just played half time of origin source, then no sound produced

The reverb effect compute just the frames of import sound?

**Comment by kcat** [comment]
Difficult to say without seeing the code, but for a stereo sound, make sure you're passing the proper size to ```alBufferData``` (if it just plays half the sound, you're probably not multiplying by the number of channels). Reverb is computed continuously in real-time using all sources that are connected to the auxiliary slot, it doesn't matter how long the sound is.

**Comment by palfu** [comment]
Just use sndfile module to import wav file:
```
initContext();

ALuint bufferid;
alGenBuffers(1, &bufferid);
ALenum datatype = getOpenALType(ptr_wavfile->channels, ptr_wavfile->bytenum);
int buffer_lens = ptr_wavfile->frames * ptr_wavfile->bytenum* ptr_wavfile->channels;
alBufferData(bufferid, datatype, ptr_wavfile->data, buffer_lens, ptr_wavfile->freq);

ALuint sourceid;
alGenSources(1, &sourceid);
alSourcei(sourceid, AL_BUFFER, bufferid);

ALuint effectslot;
ptr_fun->alGenAuxiliaryEffectSlots(1, &effectslot);

ALuint effectid;
ptr_fun->alGenEffects(1, &effectid);
setEffect(effectid, nullptr);

ptr_fun->alAuxiliaryEffectSloti(effectslot, AL_EFFECTSLOT_EFFECT, effectid);
alSource3i(sourceid, AL_AUXILIARY_SEND_FILTER, effectslot, 0, AL_FILTER_NULL);

ALint state;
alSourcePlay(sourceid);
do 
{
	alGetSourcei(sourceid, AL_SOURCE_STATE, &state);
	Sleep(20);
} while (state==AL_PLAYING);
```
"setEffect" func just like before. I've checked the buffer length, in alBufferData, when double the buffer_len, I get error "DECL_TEMPLATE2(ALshort)". Data of ptr_wavfile, channels is 2, bytenum is 2, datatype is AL_FORMAT_STEREO16

**Comment by palfu** [comment]
get the mistake in sndfile!
