### ISSUE TITLE
"error: constexpr function never produces a constant expression" Clang Windows cross-compile fails

### ISSUE THREAD

**Issue by darktohka** [kcat/openal-soft#741]
I am trying to cross-compile OpenAL Soft to Windows with Clang 14.0.6.

When compiling OpenAL Soft master with Clang 14.0.6 and CMake 3.23.2, on a fully-upgraded Arch Linux host, using the Windows MSVC toolchain, the following errors occur:

```
In file included from /home/user/Desktop/build-tc/toolchains/windows-x86_64/include/system_error:18:
/home/user/Desktop/build-tc/openal/common/ringbuffer.h:111:5: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
1 error generated.
In file included from /home/user/Desktop/build-tc/toolchains/windows-x86_64/include/system_error:14:
/home/user/Desktop/build-tc/openal/core/device.h:94:5: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
1 error generated.
/home/user/Desktop/build-tc/openal/core/device.h:94:5: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
1 error generated.
In file included from /home/user/Desktop/build/toolchains/windows-x86_64/include/system_error:14:
/home/user/Desktop/build-tc/openal/core/device.h:94:5: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
1 error generated.
```

It seems that Clang is angry about `DEF_FAM_NEWDEL` being marked as constexpr: https://github.com/kcat/openal-soft/blob/556c5d14d7fd862e86d428477afcc708b3f4055c/common/almalloc.h#L52

**Comment by kcat** [comment]
I'm curious why it thinks the `Sizeof` method can never be a constant expression. `std::max` is constexpr in C++14, and `sizeof` is a constant expression, as is `offsetof`. Everything else it calls is constexpr too.

**Comment by darktohka** [comment]
I've compiled the latest Clang 15.0.0git and attempted to build with this version.

Compiling with 15.0.0 yields the following extra notes:

```
In file included from /home/user/Desktop/build-tc/openal/alc/device.h:17:
/home/user/Desktop/build-tc/openal/core/device.h:94:5: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
/home/user/Desktop/build-tc/openal/common/almalloc.h:53:29: note: expanded from macro 'DEF_FAM_NEWDEL'
    static constexpr size_t Sizeof(size_t count) noexcept                     \
                            ^
/home/user/Desktop/build-tc/openal/core/device.h:94:5: note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
/home/user/Desktop/build-tc/openal/common/almalloc.h:55:57: note: expanded from macro 'DEF_FAM_NEWDEL'
        return std::max(decltype(FamMem)::Sizeof(count, offsetof(T, FamMem)), \
                                                        ^
/home/user/Desktop/build-tc/toolchains/windows-x86_64/include/stddef.h:47:32: note: expanded from macro 'offsetof'
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
                               ^
```

It seems that the MSVC C headers use reinterpret_cast in their definition of `offsetof`, therefore the MSVC definition of `offsetof` cannot be constexpr.

**Comment by kcat** [comment]
Sounds like a bug with either Clang or the MSVC headers. The definition for [offsetof](https://en.cppreference.com/w/cpp/types/offsetof) explicitly states "The macro **offsetof** expands to an integral constant expression of type [std::size_t](https://en.cppreference.com/w/cpp/types/size_t)". So the MSVC headers expect the compiler to allow `reinterpret_cast` in constant expressions, which Clang would need to support if it wants to use MSVC headers, or the MSVC headers need another `constexpr`-safe way to calculate the offset for more strict compilers.

**Comment by darktohka** [comment]
Most likely it's an MSVC issue.

https://en.cppreference.com/w/cpp/language/constant_expression

```
A core constant expression is any expression whose evaluation would not evaluate any one of the following:
  18. reinterpret_cast
```

If `offsetof` has to be a constant expression, it cannot use reinterpret_cast. It does, and that's on MSVC. I solved this issue on my end by replacing the MSVC stddef.h with the stddef.h provided by Clang. Not a pretty solution, but it works.

I m not sure if we can do anything about this. I feel like OpenAL should keep this as a constexpr function.
