### ISSUE TITLE
poll() not available under MinGW

### ISSUE THREAD

**Issue by neheb** [kcat/openal-soft#753]
```
openal-soft-1.22.2/alc/backends/pulseaudio.cpp:40:10: fatal error: 'sys/poll.h' file not found
#include <sys/poll.h>
         ^~~~~~~~~~~~
1 error generated.
```

after removing,

```
openal-soft-1.22.2/alc/backends/pulseaudio.cpp:288:17: error: no member named 'poll' in the global namespace
        int r{::poll(ufds, nfds, timeout)};
              ~~^
1 error generated.
```

**Comment by kcat** [comment]
I wouldn't expect PulseAudio to be supported on Windows/MinGW. `poll` is what that callback is expected to call, so if it's not available on Windows, I don't know what it's supposed to do instead.

**Comment by neheb** [comment]
I mean...MSYS2 includes pulseaudio for windows.

**Comment by kcat** [comment]
It seems PulseAudio implements its own poll function for [Windows](https://github.com/pulseaudio/pulseaudio/blob/master/src/pulsecore/poll-win32.c) and [other systems](https://github.com/pulseaudio/pulseaudio/blob/master/src/pulsecore/poll-posix.c) that don't have it. I'm not sure why it doesn't export the function for systems that need it, and I don't see a reason to add that much more code to OpenAL Soft when the backend isn't really needed on Windows anyway.

That said, there may not be a reason to use a custom mainloop in the PulseAudio backend anymore anyway. Using Pulse's default threaded mainloop would avoid the need for `poll()` and let it build on Windows.

**Comment by neheb** [comment]
Sounds good.

**Comment by kcat** [comment]
Commit 985cb7b38cdf5bbfe6fa9b7f5ffbf2030f1fff99 switches away from the custom mainloop. Does it build/work with MinGW now?

**Comment by neheb** [comment]
```
../alc/backends/pulseaudio.cpp:37:10: fatal error: 'poll.h' file not found
#include <poll.h>
```

After getting rid of that it builds
