### ISSUE TITLE
Question: can OpenAL Soft be built with only SDL2 backend?

### ISSUE THREAD

**Issue by ericoporto** [kcat/openal-soft#755]
Hi,

I would be interested in building OpenAL Soft using ***only*** SDL2 backend. Essentially, this would enable me to decouple the effects and mixer of OpenAL from the device doing the playback which would them be managed by SDL2.

Is this viable? Is there a platform where this would not be possible?

**Comment by kcat** [comment]
The "Null" backend is the only one that can't be disabled, but it won't be used if any other backend is usable (except the wave writer, which is never auto-picked). Having a build where the SDL2 backend is the only one available for output is possible, just disable all the other backends and set the SDL2 backend as required:
```sh
-DALSOFT_BACKEND_ALSA=FALSE -DALSOFT_BACKEND_OSS=FALSE -DALSOFT_BACKEND_PIPEWIRE=FALSE -DALSOFT_BACKEND_SOLARIS=FALSE -DALSOFT_BACKEND_SNDIO=FALSE -DALSOFT_BACKEND_WINMM=FALSE -DALSOFT_BACKEND_DSOUND=FALSE -DALSOFT_BACKEND_WASAPI=FALSE -DALSOFT_BACKEND_PORTAUDIO=FALSE -DALSOFT_BACKEND_PULSEAUDIO=FALSE -DALSOFT_BACKEND_JACK=FALSE -DALSOFT_BACKEND_COREAUDIO=FALSE -DALSOFT_BACKEND_OPENSL=FALSE -DALSOFT_BACKEND_OBOE=FALSE -DALSOFT_REQUIRE_SDL2=TRUE
```
Be aware that the SDL2 backend only does up to stereo, can't detect headphones (to auto-enable HRTF or crossfeed filters), and doesn't do capture.

**Comment by ericoporto** [comment]
@kcat thank you! I was mostly interested in having something like MojoAL, but with the effects working. This will do.
