### ISSUE TITLE
SET_TARGET_PROPERTIES: Incorrect Arguments

### ISSUE THREAD

**Issue by marauder2k7** [kcat/openal-soft#756]
https://github.com/kcat/openal-soft/blob/0891f1342d3d4741ca38f3c1e7437aeb7e0c0d01/CMakeLists.txt#L1391

These variables in the properties were failing for me building, wrapping them in quotes fixed the issue though

error: set_target_properties incorrect arguments

Wrapping them in quotes makes sure they get assigned even if the var is empty

**Comment by kcat** [comment]
Does it work now with commit 6e94db24015ca9aa7a76e7c3340143e4c3a66806?

**Comment by marauder2k7** [comment]
Sorry you need to wrap ${BUNDLE_VERSION} aswell with quotes, i made those changes and it works for me yeah :)

**Comment by kcat** [comment]
Fixed with commit 057a350c1e15906d12559acb56115fbef2d9a3bf.
