### ISSUE TITLE
Correct OpenAL build for Linux

### ISSUE THREAD

**Issue by daniilpetrov** [kcat/openal-soft#758]
I occasionally crash the game engine runtime. I connected AddressSanitizer, it complains about PulseAudio, and then I realized that it is before the sound starts to play that the timing crashes. How to build the library correctly on Linux? I set the following flags in CMake: CMAKE_CXX_FLAGS_RELEASE and CMAKE_C_FLAGS_RELEASE: -static-libgcc -static-libstdc++ -O3 -s -DNDEBUG

**Comment by kcat** [comment]
The first thing to check is where it's crashing. AddressSanitizer complaining about PulseAudio doesn't necessarily mean that's the cause of the crash, so it's important to find out where it actually is crashing.

If you're sure it's crashing in libopenal, try building with the default compiler flags and see if it still crashes. If it does, try to make a RelWithDebInfo build and use a debugger to find where in libopenal it's crashing.

**Comment by daniilpetrov** [comment]
During the engine crash AddressSanitizer pointed to texture loading, so it's not about OpenAL. However, AddressSanitizer indicated memory leaks in PulseAudio... The problem occurred after I switched the GL objects to Direct State Access, and AddressSanitizer confused me. Anyway, sorry :)
