### ISSUE TITLE
ALAW and MULAW extensions

### ISSUE THREAD

**Issue by Alicemargatroid** [kcat/openal-soft#76]
Is AL_FORMAT_MONO_MULAW_EXT 8 bits?
What about AL_FORMAT_STEREO_MULAW_EXT?

Same question with regards to ALAW extension.

Thank you!

**Comment by kcat** [comment]
8 bits per sample, yes. Stereo uses interleaved samples, so it's two 8-bit values together, or 2 bytes per sample frame. That's for both muLaw and aLaw, which are just two different ways of encoding 16-bit samples in 8 bits.

**Comment by Alicemargatroid** [comment]
@kcat Excellent, thank you!
