### ISSUE TITLE
Problems with iOS

### ISSUE THREAD

**Issue by paulocoutinhox** [kcat/openal-soft#760]
Hi,

I have some problems with openal on iOS related to lib atomic:

Log:
https://github.com/axys1/axys/runs/8181514696?check_suite_focus=true#step:4:1885

Our CMakeLists is the same of yours:
https://github.com/paulocoutinhox/axys/blob/support-tvos/thirdparty/openal/CMakeLists.txt

Error:
`ld: library not found for -latomic`

Can you help me?

**Comment by kcat** [comment]
That's odd. It passed the check for libatomic during configuration, so it found it while cmake was testing it, but fails to find it during linking, Where is libatomic that it was found at one point and not the other?

**Comment by paulocoutinhox** [comment]
Fixed. The problem is with `ios.toolchain.cmake` that has a flag `ENABLE_STRICT_TRY_COMPILE` = `OFF`. When i set to `ON` it works.
