### ISSUE TITLE
Problems with tvOS

### ISSUE THREAD

**Issue by paulocoutinhox** [kcat/openal-soft#761]
Hi,

I have some problems with openal on tvOS related to framework AudioUnit:

Log:
https://github.com/axys1/axys/runs/8181515025?check_suite_focus=true#step:4:1917

Our CMakeLists is the same of yours:
https://github.com/paulocoutinhox/axys/blob/support-tvos/thirdparty/openal/CMakeLists.txt

Error:
`2022-09-05T03:27:52.8904330Z ld: framework not found AudioUnit`

Maybe need add tvOS to this check?
https://github.com/kcat/openal-soft/blob/master/CMakeLists.txt#L1091

Can you help me?

**Comment by kcat** [comment]
Does it work to add an extra check for `tvos` there? I can't test it myself, but if that fixes it for you, I can change it.

**Comment by paulocoutinhox** [comment]
I made a PR that work for me:
https://github.com/kcat/openal-soft/pull/762
