### ISSUE TITLE
Cannot create directory /usr/local/lib64: permission denied

### ISSUE THREAD

**Issue by shoober420** [kcat/openal-soft#77]
When I run a make install after building the source, the lib64 directory tries to be created, but it doesn't have permission to do so. The lib64 directory is just a symlink to the /lib directory on my system as well. I'm on Arch Linux by the way.

**Comment by JohnMHarrisJr** [comment]
You're supposed to run `sudo make install` or otherwise run `make install` as the root user. Normal users don't have permission to write to the root directory of your system.

**Comment by shoober420** [comment]
Ok cool, it now installs in the /usr/local directory. Is there any way I can install it normally, outside of the local directory and just in the /usr directory so my machine sees the .so files?

**Comment by kcat** [comment]
First, make sure you ran ```ldconfig``` as root (or with sudo) after running ```make install```. That refreshes the linker cache so it can recognize new dynamic libs that have been installed. The system should know about ```/usr/local``` and find libs in the appropriate sub-directories there. ```/usr``` is where the package manager will install files from packages, and can cause conflicts and unexpected overwrites if you install files there manually.

If that still doesn't fix it, then from what I can tell, it seems CMake's GNUInstallDirs module defaults to installing in ```lib64``` if you're on 64-bit Linux, not cross-compiling, and not on Debian. It could be that your system isn't set up to look in ```/usr/local/lib64``` for libs. In which case, you have two options.

The easiest is to run cmake with ```-DCMAKE_INSTALL_LIBDIR=lib```, then do ```make``` and ```sudo make install``` again (make sure to remove the old ```/usr/local/lib64/libopenal.so*``` files which were installed previously). However that will only fix OpenAL Soft -- anything else that uses the GNUInstallDirs module will have the same issue. The alternative is to create/edit ```/etc/ld.so.conf.d/zz_local-lib64.conf``` and write in:
```
# Custom conf to recognize /usr/local/lib64
/usr/local/lib64
```
Then run ```ldconfig``` again, and it should recognize libs that were installed to ```/usr/local/lib64```.

**Comment by shoober420** [comment]
Thank you very much for explaining this. Everything works.
