### ISSUE TITLE
Can not disable output limiter

### ISSUE THREAD

**Issue by Lulu04** [kcat/openal-soft#772]
Hi,
Porting OpenAL-Soft header to FreePascal, and writing some demos, I have noticed that output limiter can not be disable.
I can not post the code because it is in FreePascal.
I try to disable output limiter by:
  - Checks for the presence of **ALC_SOFT_output_limiter** extension.
  - If present, add the attribute **ALC_OUTPUT_LIMITER_SOFT** with the value **ALC_FALSE** to the attributes list.
  - Call alcCreateContext with the attributes list.
 The context is created and no error is returned by ALCGetError(device).
Throught **AL_SOFT_gain_clamp_ex** extension the max gain is set to 8.0. All works fine, in the speakers the sound is amplified until gain of 8.
Normally, with such gain, the sound should be distorted but it is not the case, instead attenuation can be clearly heared on the loudest parts.
The same sound played on Audacity with a gain of 8dB is clearly distorted.

Tested with OpenAL-Soft v1.22.2

**Comment by Lulu04** [comment]
I forgot to attach the log file
[ALSOFT_LOG.txt](https://github.com/kcat/openal-soft/files/9638632/ALSOFT_LOG.txt)

**Comment by kcat** [comment]
Windows has its own output limiter built-in that it applies after the app and device gain adjustments (along with any other effects/APOs). By default, OpenAL Soft outputs full range float samples, so the up-to-8dB samples are written out as-is, which WASAPI can adjust down as needed to avoid clipping on the device output.

You can workaround it by setting OpenAL Soft to output 16- or 32-bit int Sample Format with the `alsoft-conf` utility. Or perhaps there's a way to turn it off on Windows if you don't want it.

**Comment by Lulu04** [comment]
i did not know about the Windows built-in output limiter. I prefer to keep float samples, so it is then preferable to apply the amplification directly on the buffers to have a behavior like in an audio editing software.
Thanks you for your help.

Do you think OpenAL-Soft is suitable for audio editing software? Although I don't have the technical knowledge about acoustics, I have this idea in mind, just for fun.

**Comment by kcat** [comment]
> Do you think OpenAL-Soft is suitable for audio editing software?

Not really. OpenAL Soft is designed for real-time dynamic 3D audio playback, not modifying audio samples in-place.

**Comment by Lulu04** [comment]
Ok. Thanks you for your answers.
Regards
