### ISSUE TITLE
Clarification on alcGetEnumValue

### ISSUE THREAD

**Issue by BurningWitness** [kcat/openal-soft#788]
From what I gather:
- `al[c]IsExtensionPresent` queries whether an extension is supported;
- `al[c]GetProcAddress` retrieves functions;
- `al[c]GetEnumValue` retrieves enumerations.

All of the information on extensions is supposed to be retrieved during runtime, so we don't have to rely on any particular headers during compilation.

The first two work like a charm, but the third one seemingly lacks entries for certain extensions, e.g.:
- `ALC_SOFT_device_clock` is a supported extension on my machine;
- `alcGetInteger64vSOFT` is a supported function;
- `ALC_DEVICE_CLOCK_SOFT`/`ALC_DEVICE_LATENCY_SOFT`/`ALC_DEVICE_CLOCK_LATENCY_SOFT` all return `0` if queried using `alcGetEnumValue`;
- `alcGetInteger64vSOFT` nonetheless queries clock time with `0x1600` and latency with `0x1601` as expected.

On the other hand, defined within the `AL_SOFT_deferred_updates` extension, `AL_DEFERRED_UPDATES_SOFT` is correctly returned by `alGetEnumValue`. The spec doesn't define its numeric representation.

Am I supposed to rely on enumeration bindings within the spec or is this an oversight?

**Comment by kcat** [comment]
It's an oversight that `ALC_DEVICE_CLOCK_SOFT`/`ALC_DEVICE_LATENCY_SOFT`/`ALC_DEVICE_CLOCK_LATENCY_SOFT` can't be queried with `alcGetEnumValue`. But they're also not necessary to query as long as you're building with an `alext.h` that has the macros. Their values can't change without breaking anything since apps compiled using the macros will always use those values.

**Comment by BurningWitness** [comment]
I'm pretty sure Windows still ships with the original OpenAL 1.1 (and I'm pretty sure that one doesn't even have `alext.h`), so this would mean making OpenAL Soft a direct dependency instead of an optional one.

Nonetheless the chance of hardcoded enumerations breaking is pretty much zero as long as the other two functions work correctly, so this shouldn't matter.
