### ISSUE TITLE
makemhr: Could not load EAC.sofa: Invalid format

### ISSUE THREAD

**Issue by ThreeDeeJay** [kcat/openal-soft#793]
Follow-up on https://github.com/kcat/openal-soft/issues/779, which was fixed in https://github.com/davircarvalho/Individualized_HRTF_Synthesis/commit/05ac8cc0cdc01d09ff022c0d3c075b49638c86a5, but now I'm getting `Invalid format` as explained in https://github.com/davircarvalho/Individualized_HRTF_Synthesis/issues/8#issuecomment-1345658160
![image](https://user-images.githubusercontent.com/71472458/206929692-725f206d-a847-4a5d-8386-8826c9bbf2e6.png)

Here's a simple way to replicate the error (using the latest [makemhr](https://github.com/kcat/openal-soft/releases/download/makemhr/makemhr.zip)): https://www.dropbox.com/s/ow1f3t46tw4tuvr/makemhr-f176484%2BEAC.SOFA-05ac8cc_InvalidFormat.7z?dl=1

**Comment by kcat** [comment]
This should be reported to [libmysofa](https://github.com/hoene/libmysofa). `mysofa_load` is returning null with that file so makemhr can't do anything with it.

**Comment by ThreeDeeJay** [comment]
I see. does makemhr have verbose/error logging or did you get `null` by using debugging tools?
Anyhow, I guess I'll close this and forward the report to libmysofa 😅

**Comment by kcat** [comment]
> I see. does makemhr have verbose/error logging or did you get `null` by using debugging tools?

The `"Error: Could not load ..."` message for sofa files only occurs if `mysofa_load` returns null, and the message after the filename is the error code given by libmysofa. makemhr has no further information about the problem.
