### ISSUE TITLE
Battlefield 2 menu mouse click sounds have reverb starting in 1.22.2

### ISSUE THREAD

**Issue by jeremywh7** [kcat/openal-soft#794]
I know there was a [similar sounding issue fixed](https://github.com/kcat/openal-soft/issues/725) right after 1.22.2 but as far back as I can test Artifacts, and up through at least 4de5c7d, it still occurs.  v1.22.0 was fine, and I also tested the original BF2 audio to verify there was no reverb.  I tried with and without "default-reverb = None".  I tried to determine if the reverb exists in-game w/ e.g. dialog, etc. but there's normally so many other sounds occurring that it's hard to tell.  It's very clear from the menus though.

Log in case it helps:
[alsoft.txt](https://github.com/kcat/openal-soft/files/10232928/alsoft.txt)

**Comment by kcat** [comment]
This is likely an issue with incorrect default EAX properties being set on a source. Either the source is feeding the reverb effect when it shouldn't, or the reverb effect isn't silent when it should be.

I plan to do some work on EAX behavior after the coming release, but I don't want to do such changes that could end up breaking EAX for the release.

**Comment by kcat** [comment]
Just to be sure, does the game use OpenAL with EAX natively, or is this with DSOAL?

Is behavior any better with commit d7cabd2c57025c7f3dad81c22c397ac27183102e? Ensuring reverb is still being applied on the sounds it should be, and not on the menu clicks.

**Comment by jeremywh7** [comment]
Yes, it is [native OpenAL](https://www.openal.org/games/) EAX.  I will reboot to Win10 and check in a bit...

**Comment by jeremywh7** [comment]
Fyi, I tested with the latest artifact 3184ab5 (Don't get the front element of an empty queue) and still exhibits the same issue.

**Comment by jeremywh7** [comment]
I saw a bunch of new EAX changes, so I tried 9fd9fee (Don't allow queuing a buffer with no format) and the menu click reverb issue is now fixed!
