### ISSUE TITLE
Provide router binary (OpenAL32.dll)

### ISSUE THREAD

**Issue by Xottab-DUTY** [kcat/openal-soft#796]
Can you provide OpenAL32.dll also in the next release and GitHub Actions builds?

**Comment by kcat** [comment]
It's in the GitHub Actions builds now. I may include it in the next release, although there's issue #661 that prevents it from being a safe replacement for Creative's router.

**Comment by Xottab-DUTY** [comment]
#661 is fixed, 1.23.0 and newer now have router included, yay! Thanks!
