### ISSUE TITLE
dsoal-aldrv.dll Causing all games using it to crash

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/openal-soft#797]
Building from the latest commit ab19694f6027303ad548e15998dd6d18437fad7b causes any game using OpenAL-Soft to crash. When looking at dsoal logs I cannot find any reason why they do this the PC sees OpenAL-Soft just fine. Some games, like Unreal Engine based games, will display a warning that seems to indicate issues with the dsoal-aldrv.dll. As far as I can tell I have to go back all the way to commit b0be3bf883c147a87840b880a6b0a8db36333b6a in order to get a working build. 
[dsoal_log.txt](https://github.com/kcat/openal-soft/files/10252122/dsoal_log.txt)

**Comment by MystyleGit** [comment]
The same has been occurring on my end. Max Payne and Red Faction have both been crashing on startup. No commit past b0be3bf883c147a87840b880a6b0a8db36333b6a has been functional for me.

**Comment by kcat** [comment]
Are you able to get a backtrace to the crash, and/or an OpenAL Soft log? Does it happen only with DSOAL, or does it happen with apps that use OpenAL natively too?

**Comment by Jenavieve-Rose** [comment]
I'm not entirely sure how to do a backtrace tbh. I didn't test openal by itself, but every game that requires DSOAL does crash. I can recompile and try openal as soon as I get home.

**Comment by kcat** [comment]
I'm not sure if this is the same thing you're experiencing, but using the (Win64) DLL from the GitHub CI seems to be causing a crash when run under Proton, too. Specifically, it seems to be calling a function that does an `int3` instruction, which causes an unhandled exception `0x80000003`. If I were to guess, this is some kind of `abort`, `terminate`, or unhandled C++ exception, but since I only have MinGW tools and this is a release build, I can't get more insight into what's calling it. All I can tell right now is it happens moments after creating a context and playback starts.

MinGW builds don't seem to have this issue, so it'll take a bit more for me to track down.

**Comment by Jenavieve-Rose** [comment]
So, I did test on the latest builds from last night's commits b53fea6d18d508fb41c97f13284590e24fb78f6a same issue persists and I tested with OpenAL only games and they hang or crash as well. I can't seem to get an OpenAl log to be created. For the record I am using cmake then building in the latest and most up to date version of Visual Studio.

**Comment by chaosophy** [comment]
Hi, I seem to be having this issue with Minecraft Java edition.
I normally download an unzip the latest dll from the 'actions' tab and use a jvm switch to load 'soft_oal.dll'
The last version to work for me was...
08/12/2022  14:57         1,117,184 soft_oal.dll
[ALSOFT] (II) Initializing library v1.22.2-b0be3bf8 HEAD
any version after that and MC crashes.
I have the env variables set to create a log file, which works with the versions that work with MC but with the newer ones that crash MC nothing makes it to the log file.
Happy to supply more info if needed.
thanks.

**Comment by kcat** [comment]
> For the record I am using cmake then building in the latest and most up to date version of Visual Studio.

Are you able to make a debug build, and run something simple like `openal-info` under VS's debugger?

**Comment by kcat** [comment]
Commit 6753601b1570876ffa6ac36f8a5fde10c35a9a7c seems to have fixed the crash I was experiencing with the CI builds. Can you check if the latest commit works?

**Comment by chaosophy** [comment]
Hi, downloaded 'soft_oal-Win64-Release.zip' from the latest action and it has fixed the crash issue with MC.

[ALSOFT] (II) Initializing library v1.22.2-6753601b HEAD

Thanks!

**Comment by Jenavieve-Rose** [comment]
> Commit [6753601](https://github.com/kcat/openal-soft/commit/6753601b1570876ffa6ac36f8a5fde10c35a9a7c) seems to have fixed the crash I was experiencing with the CI builds. Can you check if the latest commit works?

Yeah, this definitely seems to have fixed it.
