### ISSUE TITLE
FreeBSD Build problem

### ISSUE THREAD

**Issue by ForserX** [kcat/openal-soft#808]
![image](https://user-images.githubusercontent.com/13867290/212342993-6229321d-677e-45f4-b33a-310d97444f31.png)

**Comment by kcat** [comment]
Looks like an issue with the way CMake generated the makefile, causing the dependency name to not be properly escaped. It's not happening here, so I'm not sure what the issue is or how I could fix it.

**Comment by ForserX** [comment]
Maybe filename problem? Whitespace 
![image](https://user-images.githubusercontent.com/13867290/212457517-83d1ce8b-1978-4b22-9182-061bc59d6b6c.png)

**Comment by ForserX** [comment]
make into FreeBSD is trash... Need install gmake for build OpenAL
