### ISSUE TITLE
Supporting head tracking headsets

### ISSUE THREAD

**Issue by choene** [kcat/openal-soft#81]
Nowadays, some headphone support head tracking, which is beneficial for a better 3D audio experience.

A few games support TrackIR (or opentrack) by themselves. For the remaining, it would be good to add head tracking support into the HRTF renderer - or is this out of scope?

**Comment by kcat** [comment]
I believe it would be out of scope. The app specifies the position and orientation for the listener, so it's up to the app to provide changes as the head/view moves. Even if I could hook into some head-tracking API and apply a head offset on top of the app-specified position and orientation, the scale isn't known (some apps may use meters, inches, feet, or whatever else).

**Comment by choene** [comment]
ok
