### ISSUE TITLE
How to solve the problem of audio broken when receiving an phone call on iPhone？

### ISSUE THREAD

**Issue by SaintZhao** [kcat/openal-soft#820]
I used this library to develop an application on IOS, and found that when there is an incoming call, the audio will be broken and cannot continue to play and resume normally after hanging up. However using the OpenAL library that comes with IOS will not have this problem.

I also tried some solutions from the web, but still can't solve my problem.

https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/HandlingAudioInterruptions/HandlingAudioInterruptions.html#//apple_ref/doc/uid/TP40007875-CH4-SW1

https://github.com/cocos/engine-native/pull/3565/commits/7aa47bf977b19cbd26a6d3032603aafc5b466364

https://github.com/grapefrukt/extension-ios-audio/blob/master/project/iphone/OpenFLIOSAudio.mm

**Comment by kcat** [comment]
With OpenAL Soft, you'll want to use the `ALC_SOFT_pause_device` extension. When that's available, you can get the `alcDevicePauseSOFT` and `alcDeviceResumeSOFT` functions using `alcGetProcAddress`. They take an `ALCdevice*` parameter and will stop/resume playback respectively for the given device when called. So in the interruption begin notification, you call `alcDevicePauseSOFT(myDevice);` to temporarily stop playback, then in the interruption end notification, call `alcDeviceResumeSOFT(myDevice);` to resume playback.

**Comment by SaintZhao** [comment]
I have tried this method and it works. Thanks very much!
