### ISSUE TITLE
stereo audio file playback does not properly match input file

### ISSUE THREAD

**Issue by gabeklavans** [kcat/openal-soft#825]
The simplest example I could think of creating:

I have a test file that has music in the left channel, and complete silence in the right channel. If I play this file back through my OS on stereo speakers (like headphones), it can clearly be heard that the left speaker plays audio, and the right speaker is silent.
If I compile master as of this post (1.23.0), including outputting `alplay.exe`, and use `alplay.exe` to play back this test file using OpenAL-Soft, then audio can be heard playing from the right speaker (albeit at a lower volume than the left). This seems weird, as openal properly reports that it's a stereo file, and it is playing the two channels back at different volumes, so it hasn't just become mono.

Am I missing something with configuration here? I only discovered this through testing in a game engine using OpenAL-Soft 1.19.1, where I observed the exact same issue.

For more info, I am compiling with Windows SDK version 10.0.19041.0, the `Visual Studio Community 2019 Release - amd64` kit

**Comment by kcat** [comment]
If OpenAL Soft detects headphones from the system, it will auto-select HRTF output (since a plain stereo mix doesn't sound great over headphones). With HRTF, each sound channel is virtualized as if it's in space around you, so a sound on the left channel will be heard primarily by the left ear and subtly by the right ear (and vice-versa), in a way similar to an external sound point (e.g. a left speaker).

If you prefer HRTF to be disabled even with headphones, you can use the `alsoft-config.exe` utility to set the Stereo Mode to "Speakers".

**Comment by gabeklavans** [comment]
I see, using `alsoft-config.exe` to force disable HRTF does make the playback sound like the original.

Feel free to disagree with me, but I believe that HRTF should be solely opt-in instead of opt-out. `alsoft-config.exe` seems to suggest the default setting is "application preference", but it seems that HRTF is just on for an application without preference.

HRTF is a layer of audio processing that, in my opinion, is not easily anticipated when simply playing back an audio file using OpenAL. You mentioned that a "plain stereo mix" doesn't sound great on headphones, but that is what music creators are targeting; they aren't anticipating this sort of virtualization layer on top, and it should be treated as a tool to enhance playback in some cases, rather than be the default.

And in my specific case, I simply thought that OpenAL was just worse at playing back audio than the other library I was comparing it to (Fmod in this case), because HRTF was just making the music sound muffled, have less stereo wideness, and even sound like the bass frequencies were being reduced.

That being said, I can now move forward by figuring out how to turn off HRTF for my usage, so thank you for pointing me towards this. But my experience so far has lead me to argue for making it disabled by default.

**Comment by gabeklavans** [comment]
Thank you for taking the time to explain the rationale! And thank you for the links to the extensions, they seem like they will help in configuring things for my use case.

That all makes enough sense to me. The fact that it is an API designed primarily for 3D audio does seem to make having virtualization on by default make sense. I just thought I'd throw my onion into the mix, in case it helps in seeing a trend to change it, as you mentioned.

**Comment by gabeklavans** [comment]
Hi @kcat, just wanted to ask a question here since it's somewhat relevant, hope this isn't too disruptive.

Is it pragmatic to set an openal config value during runtime? It seems that the main way to get config values set is just reading them from the config file `alsoft.ini`, and then they can be retrieved later via a GetConfigValue func. However, if I want to set a config (say speaker-mode in the case of this thread) in code, preferably via the wrapper that is using the openal include API, how could I go about this? Is this something I should even consider doing, or should I just package my application with an `alsoft.ini` file?

**Comment by kcat** [comment]
> Is it pragmatic to set an openal config value during runtime?

Not really. There's no guarantee if or when any given config value will be read again after changing it, and there's little to no feedback on what happens (e.g. you could set `speaker-mode=headphones`, but it may still do plain stereo rendering; you'll need to use one of the extensions anyway to tell what it's doing). Config file settings are also subject to change, with options getting removed entirely (become ignored), or some option values becoming invalid or changed. Apps should use extensions to specify or request OpenAL behavior, which can be checked and guarantee their behavior.
