### ISSUE TITLE
Play using openal-soft in webrtc c++

### ISSUE THREAD

**Issue by Tuner32** [kcat/openal-soft#826]
Hello I am a developer trying to play audio using openal-soft in webrtc c++
I'm trying to classify audio based on ssrc in webrtc and play it using openal-soft
[I added code to this part](https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/modules/audio_mixer/audio_mixer_impl.cc;l=207)
Added the following code to the above code
```
 int16_t* audio_data = audio_frame.data_;
    int num_samples = audio_frame.samples_per_channel_ * audio_frame.num_channels_;
    int sample_rate = audio_frame.sample_rate_hz_;
    int num_channels = audio_frame.num_channels_;
    ALuint buffer, source;
    alGenBuffers(1, &buffer);
    alGenSources(1, &source);
    alBufferData(buffer, (num_channels == 1) ? AL_FORMAT_MONO16 : AL_FORMAT_STEREO16, audio_data, num_samples * sizeof(int16_t), sample_rate);
    alSourcei(source, AL_BUFFER, buffer);
    alSourcePlay(source);

    ALint state;
    alGetSourcei(source, AL_SOURCE_STATE, &state);
    while (state == AL_PLAYING) {
        alGetSourcei(source, AL_SOURCE_STATE, &state);
    }
    alDeleteSources(1, &source);
    alDeleteBuffers(1, &buffer);
```
By adding the following code to the above code, I was able to play the audio like this:
[Audio](https://voca.ro/1hcjNPxeDctO)
The first one played is the original, the next one is played in openal

Does anyone know if there is another way to play webrtc data in openal soft or how to solve this problem?

**Comment by ilya-fedin** [comment]
https://github.com/desktop-app/lib_webrtc/tree/master/webrtc/details

**Comment by Tuner32** [comment]
Thanks
