### ISSUE TITLE
Does openal-soft support set optimal latency when use oboe backend?

### ISSUE THREAD

**Issue by halx99** [kcat/openal-soft#827]
Refer to: https://github.com/google/oboe/blob/main/docs/GettingStarted.md

## Obtaining optimal latency
One of the goals of the Oboe library is to provide low latency audio streams on the widest range of hardware configurations.
When a stream is opened using AAudio, the optimal rate will be chosen unless the app requests a specific rate. The framesPerBurst is also provided by AAudio.

But OpenSL ES cannot determine those values. So applications should query them using Java and then pass them to Oboe. They will be used for OpenSL ES streams on older devices.

Here's a code sample showing how to set these default values. 

*MainActivity.java*

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1){
        AudioManager myAudioMgr = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);
        String sampleRateStr = myAudioMgr.getProperty(AudioManager.PROPERTY_OUTPUT_SAMPLE_RATE);
	    int defaultSampleRate = Integer.parseInt(sampleRateStr);
	    String framesPerBurstStr = myAudioMgr.getProperty(AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER);
	    int defaultFramesPerBurst = Integer.parseInt(framesPerBurstStr);

	    native_setDefaultStreamValues(defaultSampleRate, defaultFramesPerBurst);
	}

*jni-bridge.cpp*

	JNIEXPORT void JNICALL
	Java_com_google_sample_oboe_hellooboe_MainActivity_native_1setDefaultStreamValues(JNIEnv *env,
	                                                                                  jclass type,
	                                                                                  jint sampleRate,
	                                                                                  jint framesPerBurst) {
	    oboe::DefaultStreamValues::SampleRate = (int32_t) sampleRate;
	    oboe::DefaultStreamValues::FramesPerBurst = (int32_t) framesPerBurst;
	}

Note that the values from Java are for built-in audio devices. Peripheral devices, such as Bluetooth may need larger framesPerBurst.

**Comment by kcat** [comment]
The Oboe backend doesn't really force anything and lets the system pick defaults. It sets
```c++
builder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
builder.setSampleRateConversionQuality(oboe::SampleRateConversionQuality::None);
```
to request low latency output and not do extra resampling to keep the latency down. It also only tries to request a specific sample rate only if the app or user requests it. The only other thing it does is set a buffer size according to the device configuration:
```c++
mStream->setBufferSizeInFrames(mini(static_cast<int32_t>(mDevice->BufferSize),
    mStream->getBufferCapacityInFrames()));
```
However, since OpenAL Soft uses the callback mechanism to provide audio on-demand, I don't think that actually affects anything.

**Comment by halx99** [comment]
Thanks
