### ISSUE TITLE
Failed to compile 

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#830]
![image](https://user-images.githubusercontent.com/35676228/222939353-abf0ef2f-6fe7-4d88-8209-dcc8b9e7ae01.png)
[sysinfo.txt](https://github.com/kcat/openal-soft/files/10890675/sysinfo.txt)

**Comment by TheBestKmanEver** [comment]
solved by downloading the zip of 1.23.0 and compiling from there

**Comment by kcat** [comment]
Updating libsndfile should also fix it.

**Comment by TheBestKmanEver** [comment]
unfortunately MX doesnt have the latest of that but running 1.23.0 instead of the only available 1.19 via repo works just fine

**Comment by kcat** [comment]
Commit 28ec3afb7949be155aaa477c6e8c7358ac309459 should work around the issue too, as a temporary measure.
