### ISSUE TITLE
1.23.0 - Unable to integrate as a git submodule

### ISSUE THREAD

**Issue by char8t** [kcat/openal-soft#832]
With 1.23.0 I am unable to integrate OpenAL as a git submodule via CMake. Previous versions worked fine.

Error:

[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/marvin/dev/Test/build --config Debug --target all -j 26 --
[build] gmake[2]: *** Keine Regel vorhanden, um das Ziel „/home/marvin/dev/Test/thirdparty/openal-soft/.git/index“, 
[build]   benötigt von „Test/thirdparty/openal-soft/version_witness.txt“, zu erstellen.  Schluss.
[build] gmake[1]: *** [CMakeFiles/Makefile2:407: thirdparty/openal-soft/CMakeFiles/build_version.dir/all] Fehler 2
[build] gmake[1]: *** Auf noch nicht beendete Prozesse wird gewartet …

Due to OpenAL being a submodule „/home/marvin/dev/Test/thirdparty/openal-soft/.git" is not a directory but a file containing the path to the git submodule:

gitdir: ../../.git/modules/thirdparty/openal-soft

It worked fine on previous versions (e.g. 1.22.2).

**Comment by kcat** [comment]
This should be fixed in the latest Git (commits 8695aa49a5f5d62782217d2380b037d18e7a7460 and 3ce537d474bbde645017ecbcc3255c9a2d9432fe).

**Comment by char8t** [comment]
Yeah you right. I somehow thought i tested in on master as well but i guess i didn't. Works thanks!
