### ISSUE TITLE
Are you considering renaming some library names ？

### ISSUE THREAD

**Issue by wzhengsen** [kcat/openal-soft#834]
e.g. common->al-common / ex-common->al-ex-common?

I've imported too many 3rd libraries, will too generic a name like common lead to some confusion?

And, should ex-common be moved to the ```if(ALSOFT_EXAMPLES)``` branch?

**Comment by kcat** [comment]
`common`/`ex-common` are internal static libraries, and are linked with the main library and certain utility and example apps. They're not installed with the OpenAL library or used publicly, so shouldn't interfere with external projects (they don't need to be kept to link with or use the library).

Unless CMake doesn't like having multiple targets with the same name even when they're part of different projects, in which case it may make sense to give them a prefix to avoid clashing over a generic name.
