### ISSUE TITLE
Couldn't find alut.h.

### ISSUE THREAD

**Issue by blackcoding** [kcat/openal-soft#84]
Could you offer me the package of alut so that my program could find the "AL/alut.h" file. Thank you very much.

**Comment by rbt2008** [comment]
isn't that something 3rd party? https://github.com/vancegroup/freealut/tree/master/include/AL

**Comment by kcat** [comment]
Yes, ALUT is a separate library which OpenAL Soft doesn't provide. But it will work with any version of ALUT you can get, such as the aforementioned repo.
