### ISSUE TITLE
Error: Failed to connect PipeWire event context

### ISSUE THREAD

**Issue by SpeackerDev** [kcat/openal-soft#840]
When i initialize my program this error appears and no sound plays i don't know why

Error Message:
``
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
``

Please help me fast thank you!

**Comment by kcat** [comment]
Errno 112 is `EHOSTDOWN`. Do you have PipeWire installed, and is it your audio server? What version of OpenAL Soft are you using, and where did you get it from (self built, your distro's repo, ...)?

Can you provide a full trace log? Set the `ALSOFT_LOGLEVEL` environment variable to `3` when you run your program to have it print more information to the terminal.

**Comment by nullspoon** [comment]
Heyo, I have been having the same issue and have been troubleshooting for about a week now. I doubt my setup is close to the OP (I'm on Crux Linux), but in my case I get it from webkitgtk 6.0 running epiphany 44.0 under sway and wayland. I am using pipewire and wireplumber without pulseaudio installed on my system at all.

I have no config overrides on alsa (no ~/.asoundrc and everything in /etc/alsa is stock), no overrides on pipewire or wireplumber or openal. I did try using the example config file placed in ~/.config/alsoft.conf to see if I could change the behavior of things (specifically drivers being attempted) with no luck. Also if it's useful, I have tried various combinations of launching pipewire, wireplumber, and epiphany with dbus-launch with no change in behavior there either.

Here's the trace log. Thanks so much for mentioning that environment variable. It's super helpful!

<details>
<summary>Trace Log</summary>

```
[ALSOFT] (II) Initializing library v1.23.0-unknown UNKNOWN
[ALSOFT] (II) Supported backends: pipewire, alsa, oss, port, null, wave
[ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
[ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/aaron/.alsoftrc...
[ALSOFT] (II) Loading config /home/aaron/.config/alsoft.conf...
[ALSOFT] (II) Got binary: "/usr/lib/webkitgtk-6.0", "WebKitWebProcess"
[ALSOFT] (II) Loading config /usr/lib/webkitgtk-6.0/alsoft.conf...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 7 6800U with Radeon Graphics"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key rt-time-limit not found
[ALSOFT] (II) Key game_compat/reverse-x not found
[ALSOFT] (II) Key game_compat/reverse-y not found
[ALSOFT] (II) Key game_compat/reverse-z not found
[ALSOFT] (II) Key game_compat/nfc-scale not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key uhj/decode-filter not found
[ALSOFT] (II) Key uhj/filter not found
[ALSOFT] (II) Key uhj/encode-filter not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Found PipeWire version "0.3.67" (0.3.67 or newer)
[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
[ALSOFT] (WW) Failed to initialize backend "pipewire"
[ALSOFT] (II) Initialized backend "alsa"
[ALSOFT] (II) Added "alsa" for playback
[ALSOFT] (II) Added "alsa" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Opening default playback device
[ALSOFT] (II) Key alsa/device not found
[ALSOFT] (II) Opening device "default"
[ALSOFT] (WW) Failed to open playback device: Could not open ALSA device "default"
[ALSOFT] (WW) Error generated on device (nil), code 0xa004
[ALSOFT] (II) Freeing device 0x5555c4e928e0
```

</details>

I have the sneaking suspicion this has something to do with webkitgtk 6.0, but I haven't had time yet to go back and compile 5.0 to see if that fixes the issue (also I believe there are some incompatibilities between lower webkit api versions and latest epiphany).

**Comment by SpeackerDev** [comment]
Ok now i found the solution wireplumber was somehow crashing the pipewire but i just removed wireplumber then i downloaded the pipewire-media-session package and it works again!

Thanks kcat for trying to help me!
