### ISSUE TITLE
Invalid header on default HRTF.mhr

### ISSUE THREAD

**Issue by NafzorOB** [kcat/openal-soft#847]
Hello, i tried to open a HaxeFlixel project but when i try to play sound i get this error on the console:

AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"

AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr

Here is the full log: https://pastebin.com/R7kpiGzf
And here is my openal-info output: https://pastebin.com/7BMbTV5v

I'm on Void Linux

**Comment by kcat** [comment]
The app is using an older `libopenal.so` that doesn't support v3 of the HRTF data sets OpenAL Soft uses. That HRTF profile will be excluded from the available HRTFs, though the other built-in ones will still work.
