### ISSUE TITLE
[bug] windows unhandled exception

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#857]
Hi, I need to do some debugging, but it seems like a recent commit here has started causing a crash on windows:

![image](https://github.com/kcat/openal-soft/assets/4100142/2affc693-8af3-4cd3-92a8-7e067f12163e)

Confirming things work until `6cd3d2414ac40a94713c84a0703d3e021bf9a570`

**Comment by kcat** [comment]
Commit 6cd3d2414ac40a94713c84a0703d3e021bf9a570 shouldn't have any bearing on Windows/WASAPI behavior. It shouldn't be functionally different at all, and neither the previous or following commit. Are you able to get a backtrace?

**Comment by hsdk123** [comment]
@kcat I think you've misread my comment, I was stating that things [work] until Commit https://github.com/kcat/openal-soft/commit/6cd3d2414ac40a94713c84a0703d3e021bf9a570. Not sure what commit after creates the bug. 

I'll try get a backtrace

**Comment by Rynnya** [comment]
Reventing commit https://github.com/kcat/openal-soft/commit/1a583b016a7b5e22f370e2f425722e3dc240a7dd fixes this issue

**Comment by kcat** [comment]
I really don't like COM. Try with commit d769041916df4efb48fd212683dc9842decc10f1.

**Comment by Rynnya** [comment]
Issue gone after applying https://github.com/kcat/openal-soft/commit/d769041916df4efb48fd212683dc9842decc10f1, program didn't crash anymore, thank you!

**Comment by hsdk123** [comment]
Confirmed as well, thanks! Would be great to add a test around this if possible

**Comment by kcat** [comment]
There is `openal-info` and the other utilities/examples. I'm not sure how to do automated tests as part of CI, though.
