### ISSUE TITLE
Latest Builds Crash Games using DSOAL

### ISSUE THREAD

**Issue by Jenavieve-Rose** [kcat/openal-soft#858]
Latest build 6752d5516c8b30fe7db559c7f3a1423705d2a4fd and several builds before that cause any game that uses DSOAL (Using the latest build of DSOAL) to crash on my desktop. I can use the latest Official release with zero issues and If I go back a week in builds it seems to be fine. 

[dsoal_log.txt](https://github.com/kcat/openal-soft/files/11636108/dsoal_log.txt)

**Comment by kcat** [comment]
Try now with commit d769041916df4efb48fd212683dc9842decc10f1.

**Comment by Jenavieve-Rose** [comment]
Yeah that fixed it. Thanks
