### ISSUE TITLE
Feature request: setting ALSOFT_LOGFILE by app

### ISSUE THREAD

**Issue by Lulu04** [kcat/openal-soft#862]
Hi, thanks for sharing OpenAL Soft. Sorry for my bad english.

At the moment, to set the path and filename for the log file, we have to declare an environment variable or changing a line in the config file.
This action must be done by the user and it is not convenient for an app that use OpenAL-Soft to ask its user to sets this variable.

There is also the problem when two application use openAL Soft:
  - the user start the first one, a log file is created by the AL
  - the user quits the first application and starts the second: the first log file is erased and the debug info are lost.
 
In addition, setting this variable programatically seem to be not easy under Linux (however I'm not a Linux expert).

It would be usefull if the app itself can set this path+filename for the log file when it start. This way, both the app log file and OpenAL log file can be to the same directory, easy to retrieve for debug purpose.

Regards

**Comment by kcat** [comment]
Sorry for the delayed response.

For the time being, I've added a function to set a callback that gets the log messages:
```c++
typedef void (ALC_APIENTRY*LPALSOFTLOGCALLBACK)(void *userptr, char level, const char *message, int length) noexcept;
void ALC_APIENTRY alsoft_set_log_callback(LPALSOFTLOGCALLBACK callback, void *userptr) noexcept;
```

This function isn't directly exported by the library, so you have to load it with `alcGetProcAddress(NULL, "alsoft_set_log_callback");`, then call it with a non-null callback before calling any other OpenAL function. The callback will get a `level` parameter which is a character indicating the severity of the message (currently `'I'` for informational, `'W'` for non-severe warning, and `'E'` for error; more may be used in the future), a 'message' pointer to the null-terminated string, and the `length` of the string (excluding the null char).

The callback may be called on various different threads. It uses a mutex internally to prevent being called from multiple threads at the same exact time, but different calls can be on different threads.

If a callback isn't set before messages start getting logged, the callback won't ever be called if set later. You also must not call OpenAL functions in the callback.

**Comment by Lulu04** [comment]
Thanks you very much for implementing this feature.
I've just tested it and it works like a charm!
[GiveYourVoice.log](https://github.com/kcat/openal-soft/files/12016914/GiveYourVoice.log)

Thanks again for your great work
Regards
