### ISSUE TITLE
Github API not showing tags past openal-soft-1.21.0

### ISSUE THREAD

**Issue by xXTeraXx** [kcat/openal-soft#867]
Not sure if this is a github problem or a project problem.  But if you use the [REST API](https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28) and attempt to get the tags for the project, it doesn' t return any of the newer tags.  It seems like it is only returning the tags that start with openal-soft.

I think you would need to reach out to github or modify something within the project settings to get the tags going again.

**Comment by okuoku** [comment]
Did you properly did paging? e.g. https://api.github.com/repos/kcat/openal-soft/tags?page=2 will show `1.23.1` etc.

**Comment by xXTeraXx** [comment]
I didn't even realize the API had paging, thanks I'll close the issue.
