### ISSUE TITLE
CMake error linking OpenAL with OpenSL + android + static

### ISSUE THREAD

**Issue by bwrsandman** [kcat/openal-soft#871]
### Description

I'm seeing this issue on android when I use vcpkg's package but it affects this project in regular usage.

If you compile  in static mode, the OpenALTargets.cmake adds a linking command with an undefined OpenSL::OpenSLES.

### How to replicate
Set the `ANDROID_NDK_HOME` environment variable to a recent NDK. I used 23.1.7779620.

Cross compile and install openal-soft as a static lib with the OPENSL backend
```bash
cmake -S. -Bcmake-build \
    -DLIBTYPE=STATIC \
    -DALSOFT_BACKEND_OPENSL=ON \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake
cmake --build cmake-build
cmake --install cmake-build --prefix=test-project/installed/OpenAL
```

In test project, Make a simple project linking with OpenAL

```cmake
cmake_minimum_required(VERSION 3.18 FATAL_ERROR)
project(test-project)
find_package(OpenAL CONFIG REQUIRED)
add_executable(main main.cpp)
target_link_libraries(main OpenAL::OpenAL)
```

Configure this project to use the installed package
```bash
cmake -S. -Bcmake-build \
    -DOpenAL_ROOT=installed/OpenAL \
    -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH \
    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake
```
### Desired result

The test project should configure without issue and link with OpenSL in the android NDK.
This requires the Target.cmake to find and import the library from the NDK using a similar configuration as FindOpenSL.cmake.

### Actual result

The configuration fails to find OpenSL

```
CMake Error at installed/OpenAL/lib/cmake/OpenAL/OpenALTargets.cmake:61 (set_target_properties):
  The link interface of target "OpenAL::OpenAL" contains:

    OpenSL::OpenSLES

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  installed/OpenAL/lib/cmake/OpenAL/OpenALConfig.cmake:3 (include)
  CMakeLists.txt:3 (find_package)
```

**Comment by kcat** [comment]
It should work now with commit c12ada68951ea67a59bef7d4fcdf22334990c12a.

**Comment by bwrsandman** [comment]
I've tried it out and it indeed works both with my test project and updating the vcpkg port to the makemhr works too.
