### ISSUE TITLE
Random app crash with OpenAL, read access violation in voice.cpp

### ISSUE THREAD

**Issue by rk85097** [kcat/openal-soft#880]
Hey, I've started to experience issues where my app suddenly crashes. When I ran it in debug, I found the following read access violation in the screenshot below.

![Screenshot 2023-07-14 233500](https://github.com/kcat/openal-soft/assets/5455346/4d71f0be-116b-4588-b3f8-5f40f59558f5)

**UPDATE**: I did find that the following [brakes_2.zip](https://github.com/kcat/openal-soft/files/12058935/brakes_2.zip) wav is causing this when I load it over and over (replacing source with new). It doesn't happen with any other file I have, any idea what is special about it? (For the record, it happens when I load it over and over as a new source as well, and not replacing, so something must be bad about that wav, yet, I cannot conclude what is it, as it is so simple)

This is how I replace the wav:

```
int OpenALStore::replaceWav(char* filePath, int SourceNo)
{
	try {
	
		if ((SourceNo < 0) || (SourceNo > OpenALTableLastElement))
		{
			return 0;
		}

		char FileNameToLoad[NORMALSTRING];
		strncpy(FileNameToLoad, filePath, sizeof(FileNameToLoad));
		OpenALTable[SourceNo].filename = FileNameToLoad;

		stop(SourceNo);

		alDeleteSources(1, &OpenALSources[SourceNo]);
		alDeleteBuffers(1, &OpenALBuffers[SourceNo]);
		err = alGetError();
		ErrorCheck(err);


		alGenSources(1, &OpenALSources[SourceNo]);
		OpenALBuffers[SourceNo] = 0;
		alGenBuffers(1, &OpenALBuffers[SourceNo]);
		if (!ALFWLoadWaveToBuffer(FileNameToLoad, OpenALBuffers[SourceNo]))
		{
			Logger().msg(OPENALIB, "Failed to load wav file");
		}
		err = alGetError();
		ErrorCheck(err);

		ALfloat zero[3] = { 0 };
		alSourcei(OpenALSources[SourceNo], AL_BUFFER, OpenALBuffers[SourceNo]);
		alSourcef(OpenALSources[SourceNo], AL_PITCH, OpenALTable[SourceNo].pitch);
		alSourcef(OpenALSources[SourceNo], AL_GAIN, OpenALTable[SourceNo].gain);
		alSourcei(OpenALSources[SourceNo], AL_LOOPING, OpenALTable[SourceNo].loop);
		alSourcefv(OpenALSources[SourceNo], AL_POSITION, zero);
		alSourcefv(OpenALSources[SourceNo], AL_VELOCITY, zero);
		err = alGetError();
		ErrorCheck(err);

		string errorStr = err == 0 ? "successfuly" : ("with error: " + to_string(err));
		const string logMsg = "File replaced " + errorStr;
		Logger().msg(OPENALIB, logMsg);

		return SourceNo;
	}
	catch (const std::exception& ex) {
		Logger().msg(XPLANE_CLIENT, ex.what());
		return replaceWav(filePath, SourceNo);
	}
}
```

**Comment by kcat** [comment]
The file doesn't look bad. It does seem a bit weird in being 192khz, 16-bit 6-channel, and 4266 samples long (lasting 22 milliseconds), but it should play exactly as it's supposed to.

How are you loading the buffer? Which extensions are you using (`AL_EXT_STATIC_BUFFER`, `AL_EXT_MCFORMATS`)? Are you using the latest release, or the latest Git master?

**Comment by rk85097** [comment]
@kcat  Due to time constrains, I ended up replacing the problematic wav file and all is back to normal, very strange. I may reopen this issue later on in the future, but please consider this closed for now. Many thanks for the help here.
