### ISSUE TITLE
AL_FILTER_LOWPASS and AL_FILTER_HIGHPASS are not working as expected

### ISSUE THREAD

**Issue by rk85097** [kcat/openal-soft#881]
Hey, I am trying to apply a low pass filter on all my sources (set of 20 wav files), in the following manner:

```
// When I load the wav file
OpenALFilters[OpenALTableLastElement] = 0;
alGenFilters(1, &OpenALFilters[OpenALTableLastElement]);
```

```
// When I update filter values
alFilteri(OpenALFilters[i], AL_FILTER_TYPE, AL_FILTER_LOWPASS);
alFilterf(OpenALFilters[i], AL_LOWPASS_GAIN, gain);
alFilterf(OpenALFilters[i], AL_LOWPASS_GAINHF, hfGain);
alSourcei(OpenALSources[i], AL_DIRECT_FILTER, OpenALFilters[i]);
```

- When I change `hfGain` I don't hear any change in the sound (0.0f-1.0f)
- When I change `gain` all I get is overall gain increase/decrease as if I were to change source gain normally
- I did the same for the high pass filter, same results
- I tried with both sources with high frequencies and low frequencies

I am using "1.23.1",
What am I missing?

Thanks!

**Comment by kcat** [comment]
You figured out the problem?
