### ISSUE TITLE
Where is `AL_DATA`?

### ISSUE THREAD

**Issue by ichordev** [kcat/openal-soft#884]
The [Programmer's Guide mentions](https://github.com/kcat/openal-soft/wiki/Programmer's-Guide#buffer-properties) that `AL_DATA` is a buffer property, yet I cannot find it in any of the header files with a textual search, and it is not grouped with the other buffer properties. Was it removed?

**Comment by kcat** [comment]
Looks like a mistake in the guide. `AL_DATA` doesn't seem to have ever been standard (the 1.1 spec doesn't mention it at all, not even as something that was deprecated/removed from 1.0). It may have been originally put there during 1.0 development when it was being considered, and ultimately dropped before the spec was finalized but not removed from the guide. Such a property couldn't work anyway given 64-bit systems (a 64-bit pointer couldn't fit through a 32-bit integer), on top of it potentially returning a freed pointer value.

**Comment by ichordev** [comment]
Wow, that's crazy.
I saw you removed one mention of it, but there are 3 others here:
1. https://github.com/kcat/openal-soft/wiki/Programmer's-Guide/28760da9568a99fca5ac047ffd0891f95a5ed97b#properties
2. https://github.com/kcat/openal-soft/wiki/Programmer's-Guide/28760da9568a99fca5ac047ffd0891f95a5ed97b#parameters-13
3. https://github.com/kcat/openal-soft/wiki/Programmer's-Guide/28760da9568a99fca5ac047ffd0891f95a5ed97b#parameters-15
