### ISSUE TITLE
Unimplemented formats?

### ISSUE THREAD

**Issue by ichordev** [kcat/openal-soft#885]
`alext.h` has a few formats at the start of the file that I cannot find any reference to (numerically or symbolically) in OpenAL-Soft's implementation:
```c
#define AL_FORMAT_IMA_ADPCM_MONO16_EXT           0x10000
#define AL_FORMAT_IMA_ADPCM_STEREO16_EXT         0x10001

#define AL_FORMAT_WAVE_EXT                       0x10002

#define AL_FORMAT_VORBIS_EXT                     0x10003
```

I'm aware that these from "legacy" extensions, but do they work? It seems odd for them to be here if using them would be an error?

**Comment by ichordev** [comment]
And same for these I suppose?
```c
#define AL_BYTE_RW_OFFSETS_SOFT                  0x1031
#define AL_SAMPLE_RW_OFFSETS_SOFT                0x1032
```

**Comment by ichordev** [comment]
I also can't find any other references to any of these in OpenAL-Soft except in `alext.h`:
```c
#define AL_FOLDBACK_EVENT_BLOCK                  0x4112
#define AL_FOLDBACK_EVENT_START                  0x4111
#define AL_FOLDBACK_EVENT_STOP                   0x4113
#define AL_FOLDBACK_MODE_MONO                    0x4101
#define AL_FOLDBACK_MODE_STEREO                  0x4102

AL_API void AL_APIENTRY alRequestFoldbackStart(ALenum mode,ALsizei count,ALsizei length,ALfloat *mem,LPALFOLDBACKCALLBACK callback);
AL_API void AL_APIENTRY alRequestFoldbackStop(void);
```

**Comment by kcat** [comment]
> I'm aware that these from "legacy" extensions, but do they work?

Not with OpenAL Soft, no. They're all defined for source compatibility. OpenAL extensions are detected at runtime, so if they weren't defined, it would cause compile errors for code that used them even if they weren't required at runtime.

`AL_BYTE_RW_OFFSETS_SOFT`/`AL_SAMPLE_RW_OFFSETS_SOFT` are part of the `AL_SOFT_buffer_sub_data` extension that used to be supported, but isn't anymore due to it clashing with `AL_EXT_SOURCE_RADIUS`.

`AL_EXT_FOLDBACK` is supported in the Rapture3D driver, but not OpenAL Soft. It might be in the future, but it isn't currently.

**Comment by ichordev** [comment]
Thank you for the clarification.

> OpenAL extensions are detected at runtime, so if they weren't defined, it would cause compile errors for code that used them even if they weren't required at runtime.

`alRequestFoldbackStart` and `alRequestFoldbackStop` present a bit of an issue with that for me...
I'm writing OpenAL bindings. For the static bindings, all the symbols will be looked up in the OpenAL-Soft dynamic library by the system just before the program starts. However, those two functions aren't exported by OpenAL-Soft... so I guess I'll just have to exclude them entirely.

**Comment by kcat** [comment]
Extension functions should be loaded dynamically, using `alcGetProcAddress`/`alGetProcAddress`. Using the functions directly puts a hard requirement on them existing, so the program can fail to load if the functions are removed or aren't available, even if they aren't required. On some systems, non-standard functions may not be exported and can only be retrieved with `alcGetProcAddress`/`alGetProcAddress` functions.

**Comment by ichordev** [comment]
> Extension functions should be loaded dynamically, using `alcGetProcAddress`/`alGetProcAddress`.

So to clarify, this means that loading any of the functions defined in `alext.h` before runtime is an erroneous use of OpenAL-Soft?

**Comment by kcat** [comment]
It's strongly discouraged. Some functions may only be accessible with `alcGetProcAddress`/`alGetProcAddress`, and extensions can potentially be removed along with their functions.
