### ISSUE TITLE
Multi-channel capture buffer layout

### ISSUE THREAD

**Issue by MV10** [kcat/openal-soft#893]
Is there documentation about capture buffer layout for >2 channels? I haven't had any luck trying to find it. I know a stereo capture buffer alternates left / right samples. I can write a test program, of course, but my app is multi-platform so I want to be sure it'll be the same everywhere.

Edit: As usual, almost immediately after posting this, I found the answer to the second question below about downmixing. In case anyone else ever needs it:

https://superuser.com/a/1219033/143047

Also, I know stereo to mono is a simple matter of averaging the two channels. Is there a rule of thumb for higher channel counts, or some way to determine or calculate the mix, or is it all much more complicated? My app needs to process mono PCM, but if I request that from the loopback drivers, all the audio ends up stereo even though the original source is 5.1, so I'd like to capture 5.1. But I realize that part isn't really an OpenAL-Soft concern...

**Comment by kcat** [comment]
> Is there documentation about capture buffer layout for >2 channels?

Not explicitly, but the channels follow the same order as the channel mask in wave files. Quad is front-left, front-right, rear-left, rear-right. 5.1 is front-left, front-right, front-center, lfe, side-left, side-right (sometimes uses the 'rear' or 'surround' in place of 'side', but it's all the same for purposes here). 6.1 is front-left, front-right, front-center, lfe, rear-center, side-left, side-right. And 7.1 is front-left, front-right, front-center, lfe, rear-left, rear-right, side-left, side-right.

Greater-than-stereo isn't well tested for capture though, and it's possible some systems may have the channels mixed up. But Windows, as well as PulseAudio and PipeWire, should be correct.

**Comment by MV10** [comment]
Unfortunately, it turns out my loopback driver (VB-Cable) doesn't use Windows KS (Kernel Streaming) yet, so 2-channel capture is all I can get, but hopefully in the future I can put this to good use. 

In case it's something you want to look into some rainy day, either OpenAL or OpenAL-Soft (not sure how to tell which) `GetAvailableSamples` crashes with an protected memory access violation if I try to open the capture device for multi-channel (16-bit 5.1 is all I tried). This is on Win10 Pro x64, I haven't tried it on Linux (Raspberry Pi, in my case), although now that I say it, I'd guess Pulse Audio probably does support it, alsa/pulse seems to do everything else!

Thanks for the info!

**Comment by kcat** [comment]
Are you able to get a trace log with the crash? If you set the `ALSOFT_LOGLEVEL` environment variable to `3`, it'll print a log about what it's doing to stderr (you can also set `ALSOFT_LOGFILE` to a path+filename to write it there instead).

**Comment by MV10** [comment]
Sure. Log below (I use a .NET wrapper library called OpenTK, which is very 1:1 with the native API). The test program is as minimal as possible ... about 100 lines including declarations, braces, blank lines etc. When I set a flag to capture 2-channel, it works as expected.

```
C:\Source\multichan\multichan\bin\Debug\net6.0>multichan
[ALSOFT] (II) Initializing library v1.23.1-d3875f33 master
[ALSOFT] (II) Supported backends: wasapi, dsound, winmm, null, wave
[ALSOFT] (II) Loading config C:\Users\Jon\AppData\Roaming\alsoft.ini...
[ALSOFT] (II)  found 'decoder/hq-mode' = 'true'
[ALSOFT] (II) Got binary: C:\Source\multichan\multichan\bin\Debug\net6.0, multichan.exe
[ALSOFT] (II) Loading config C:\Source\multichan\multichan\bin\Debug\net6.0\alsoft.ini...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 9 3900XT 12-Core Processor"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key rt-time-limit not found
[ALSOFT] (II) Key game_compat/enable-sub-data-ext not found
[ALSOFT] (II) Key game_compat/reverse-x not found
[ALSOFT] (II) Key game_compat/reverse-y not found
[ALSOFT] (II) Key game_compat/reverse-z not found
[ALSOFT] (II) Key game_compat/nfc-scale not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key uhj/decode-filter not found
[ALSOFT] (II) Key uhj/filter not found
[ALSOFT] (II) Key uhj/encode-filter not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (II) Initialized backend "wasapi"
[ALSOFT] (II) Added "wasapi" for playback
[ALSOFT] (II) Added "wasapi" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Key eax/enable not found
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Got message "Enumerate Playback" (0x0005, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "CABLE Input (VB-Audio Virtual Cable)", "{DCBCE132-254B-488A-B719-B279FDF8C34F}", "{0.0.0.00000000}.{dcbce132-254b-488a-b719-b279fdf8c34f}"
[ALSOFT] (II) Got device "Speakers (Realtek(R) Audio)", "{C8F818D7-B351-41BA-B741-26D4FC840E11}", "{0.0.0.00000000}.{c8f818d7-b351-41ba-b741-26d4fc840e11}"
[ALSOFT] (II) Message loop finished
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Got message "Enumerate Capture" (0x0006, this=0000000000000000, param=0000000000000000)
[ALSOFT] (II) Got device "CABLE Output (VB-Audio Virtual Cable)", "{F43E8DDB-D121-4707-A78A-B5ECAB5F4883}", "{0.0.1.00000000}.{f43e8ddb-d121-4707-a78a-b5ecab5f4883}"
[ALSOFT] (II) Message loop finished
[ALSOFT] (II) Opening playback device "OpenAL Soft"
[ALSOFT] (II) Starting message thread
[ALSOFT] (II) Starting message loop
[ALSOFT] (II) Got message "Open Device" (0x0000, this=0000022e9f7a6e40, param=0000000000000000)
[ALSOFT] (II) Created device 0000022ec05c2b90, "OpenAL Soft on CABLE Input (VB-Audio Virtual Cable)"
[ALSOFT] (II) Key frequency not found
[ALSOFT] (II) Key period_size not found
[ALSOFT] (II) Key periods not found
[ALSOFT] (II) Key sample-type not found
[ALSOFT] (II) Key channels not found
[ALSOFT] (II) Key ambi-format not found
[ALSOFT] (II) Key hrtf not found
[ALSOFT] (II) Key stereo-encoding not found
[ALSOFT] (II) Pre-reset: Stereo, Float32, 48000hz, 960 / 2880 buffer
[ALSOFT] (II) Got message "Reset Device" (0x0001, this=0000022e9f7a6e40, param=0000000000000000)
[ALSOFT] (II) Device mix format:
    FormatTag      = 0xfffe
    Channels       = 6
    SamplesPerSec  = 48000
    AvgBytesPerSec = 1152000
    BlockAlign     = 24
    BitsPerSample  = 32
    Size           = 22
    Samples        = 32
    ChannelMask    = 0x60f
    SubFormat      = {00000003-0000-0010-8000-00aa00389b71}
[ALSOFT] (II) Requesting playback format:
    FormatTag      = 0xfffe
    Channels       = 6
    SamplesPerSec  = 48000
    AvgBytesPerSec = 1152000
    BlockAlign     = 24
    BitsPerSample  = 32
    Size           = 22
    Samples        = 32
    ChannelMask    = 0x60f
    SubFormat      = {00000003-0000-0010-8000-00aa00389b71}
[ALSOFT] (II) Post-reset: 5.1 Surround, Float32, 48000hz, 960 / 2880 buffer
[ALSOFT] (II) Key stereo-mode not found
[ALSOFT] (II) Key decoder/surround51 not found
[ALSOFT] (II) Key front-stablizer not found
[ALSOFT] (II) Found decoder/hq-mode = "true"
[ALSOFT] (II) Channel config, Main: 5, Real: 6
[ALSOFT] (II) Allocating 11 channels, 45056 bytes
[ALSOFT] (II) Enabling dual-band second-order ambisonic decoder
[ALSOFT] (II) Key sources not found
[ALSOFT] (II) Key sends not found
[ALSOFT] (II) Max sources: 256 (255 + 1), effect slots: 64, sends: 4
[ALSOFT] (II) Key dither not found
[ALSOFT] (II) Key dither-depth not found
[ALSOFT] (II) Dithering disabled
[ALSOFT] (II) Key output-limiter not found
[ALSOFT] (II) Output limiter disabled
[ALSOFT] (II) Fixed device latency: 0ns
[ALSOFT] (II) Got message "Start Device" (0x0002, this=0000022e9f7a6e40, param=0000000000000000)
[ALSOFT] (II) Post-start: 5.1 Surround, Float32, 48000hz, 960 / 2880 buffer
[ALSOFT] (II) Increasing allocated voices to 256
[ALSOFT] (II) Key volume-adjust not found
[ALSOFT] (II) Created context 0000022ec05ebcc0
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at OpenTK.Audio.OpenAL.ALC.GetInteger(OpenTK.Audio.OpenAL.ALCaptureDevice, OpenTK.Audio.OpenAL.AlcGetInteger, Int32, Int32 ByRef)
--------------------------------
   at OpenTK.Audio.OpenAL.ALC.GetAvailableSamples(OpenTK.Audio.OpenAL.ALCaptureDevice)
   at multichan.Program.Main(System.String[])
```

**Comment by kcat** [comment]
It doesn't look like you're creating a capture device. You can't capture samples from a playback device, though it shouldn't crash if you try to, it would just return an error.

**Comment by MV10** [comment]
I thought the log output looked a bit odd, too, but I definitely do create a capture device. This multi-channel test app is the same basic code (simplified) that I'm using in another very complex multi-threaded OpenGL audio visualization app (sans a bunch of error-check calls after each statement, comments, etc.).

```csharp
static void Main(string[] args)
{
    var SampleRate = 44100;
    var Format = ALFormat.Multi51Chn16Ext;
    var ChannelCount = 6;
    var SampleCount = 1024;

    // this works
    // Format = ALFormat.Stereo16;
    // ChannelCount = 2;

    var Buffer = new short[SampleCount * ChannelCount];

    var Device = ALC.OpenDevice("OpenAL Soft");
    var Context = ALC.CreateContext(Device, (int[])null);
    ALC.MakeContextCurrent(Context);

    var captureDeviceName = ALC.GetString(ALDevice.Null, AlcGetString.CaptureDefaultDeviceSpecifier);
    var CaptureDevice = ALC.CaptureOpenDevice(captureDeviceName, SampleRate, Format, SampleCount);

    ALC.CaptureStart(CaptureDevice);

    var Quit = false;
    while(!Quit)
    {
        int available = ALC.GetAvailableSamples(CaptureDevice);
        while(available >= SampleCount)
        {
            // AccessViolation exception here
            ALC.CaptureSamples(CaptureDevice, ref Buffer[0], SampleCount);

            for(int i=0; i < SampleCount; i++)
            {
                int n = i * ChannelCount;
                Console.Clear();
                // Console.WriteLine($"{Buffer[n]:00000}\t{Buffer[n + 1]:00000}");
                Console.WriteLine($"{Buffer[n]:00000}\t{Buffer[n + 1]:00000}\t{Buffer[n + 2]:00000}\t{Buffer[n + 3]:00000}\t{Buffer[n + 4]:00000}\t");
            }

            available -= SampleCount;
        }

        if (Console.KeyAvailable)
        {
            var k = Console.ReadKey(true);
            Quit = (k.Key == ConsoleKey.Escape);
        }
        else
        {
            Thread.Sleep(0);
        }
    }

    ALC.CaptureStop(CaptureDevice);
    ALC.CaptureCloseDevice(CaptureDevice);
    ALC.MakeContextCurrent(ALContext.Null);
    ALC.DestroyContext(Context);
    ALC.CloseDevice(Device);
}
```

The value of `captureDeviceName` is `CABLE Output (VB-Audio Virtual ` which is correct:

![image](https://github.com/kcat/openal-soft/assets/794270/9b1f5daf-c1d1-46bf-ad6e-b6bf60898d8c)

Not that the details are important here, but since I was originally just wondering about the channel layout in the buffer, the loop just dumps six groups of values, then I was going to use the Windows Sound configuration tester to send a test sound to each speaker to see where the data showed up. (Which still left the question of whether this is standardized, all of which you've already answered, of course.)

**Comment by kcat** [comment]
> The log shows a capture device: `Created device 0000022ec05c2b90, "OpenAL Soft on CABLE Input (VB-Audio Virtual Cable)"`

That's the playback device:

> ```
> [ALSOFT] (II) Opening playback device "OpenAL Soft"
> [...]
> [ALSOFT] (II) Created device 0000022ec05c2b90, "OpenAL Soft on CABLE Input (VB-Audio Virtual Cable)"
> ```

> The value of `captureDeviceName` is `CABLE Output (VB-Audio Virtual ` which is correct:

That looks like the name given by Creative's wrapper driver. On Windows, OpenAL Soft's device names start with "OpenAL Soft on ...". That would explain why the capture device doesn't show in the log, since it's not OpenAL Soft handling the capture device.

**Comment by MV10** [comment]
Thanks for all the help!
