### ISSUE TITLE
Setting wasapi in alsoft.ini?

### ISSUE THREAD

**Issue by NikolaiVChr** [kcat/openal-soft#896]
In the alsoft.ini file can I select Wasapi by doing this:

`drivers = wasapi`

Also what is the default value of *drivers* on windows 64 bit?

**Comment by kcat** [comment]
The default value is blank, which means the current order of the available backends. For the prebuilt binaries, the the list is, in order:
wasapi, dsound, winmm, null, wave

The current full list, in order, is:
pipewire, pulse (PulseAudio), wasapi, core (CoreAudio for macOS), oboe, opensl, alsa, solaris, sndio, oss (Open Sound System), jack, dsound, winmm (Windows MultiMedia), port (PortAudio), sdl2, null (dummy output), wave (Wave file writer)

Obviously a Windows build won't have all of these... some aren't possible to use on Windows, while others are technically possible but unlikely to be available on Windows.

**Comment by NikolaiVChr** [comment]
Thank you
