### ISSUE TITLE
OpenAL EFX doesn't seem to be included even with -DENABLE_EFX turned on

### ISSUE THREAD

**Issue by lipx1508** [kcat/openal-soft#899]
I really feel dumb for asking this but I don't seem to find anything related to it elsewhere, sorry if it's bad issue etiquette.

I'm trying to compile the latest version of the library to use it in a project, and while trying to compile it, I noticed that EFX doesn't get included at all - no matter what flags I am using during compilation.

Here is my CMake output: [cmake_dump.txt](https://github.com/kcat/openal-soft/files/12423411/cmake_dump.txt)

I'm trying to use pkg-config to include it, and I got the error:
`error: ‘alGenEffects’ was not declared in this scope; did you mean ‘alGenBuffers’?`
Note that all the other AL features seem to be working very fine, but EFX is not for some reason.

If I define any of the functions included in the `AL/alext.h` header file it gets handled as if it's working, but the effects I'm applying don't get really applied as it seems.

**Comment by kcat** [comment]
EFX is always enabled in builds, but it's an extension that an app needs to load dynamically. `alcIsExtensionPresent` is used with an open `ALCdevice*` handle to determine if the given device supports the extension (in case it's running with a different implementation or driver that doesn't support it), then after setting up the context, you use `alGetProcAddress` to get the function pointers that you can call. See how the reverb example [declares](https://github.com/kcat/openal-soft/blob/master/examples/alreverb.c#L44) and [loads](https://github.com/kcat/openal-soft/blob/master/examples/alreverb.c#L261) the functions.

If you're calling the functions but not hearing any effect, there's probably an issue with the way it's used. Are you able to provide the relevant sound handling code?

**Comment by lipx1508** [comment]
@kcat I tried to compile the examples and everything seems to be working fine now!

The issue happened because I didn't loaded it dynamically. I adapted what I have written to the reverb example and it's working fine. 

Sorry for the inconvenience and thanks for the help :)
