### ISSUE TITLE
Changing a device can crash on Windows (wasapi)

### ISSUE THREAD

**Issue by frozax** [kcat/openal-soft#908]
Hi,
I'm using the new extension allowing OpenALSoft to detect changes of default device.
On some computer, I've had the app crash when I unplug a particular device (in my case, a USB headset), using Windows 10.
After some investigation, it looks like the issue is in `OnDefaultDeviceChanged`. 
According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immnotificationclient-ondefaultdevicechanged#parameters), the `pwstrDefaultDeviceId` parameter can be `NULL`, and it's not handled.
In my case, it's NULL for the `eCapture` flow.

**Comment by kcat** [comment]
Should be fixed now in commit d2d6365b3f965922f6c25198bcd9de30ccf9f6bb.

**Comment by frozax** [comment]
Bug confirmed fixed. Thanks!
