### ISSUE TITLE
how to enable Super Stereo mode in UHJ???

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#912]
i have MPV outputting quad audio but my final audio output is 2 channel stereo with UHJ, how would i enable the super stereo mode along with UHJ??? or is this already active???

**Comment by kcat** [comment]
They're two separate things. Super Stereo is a playback mode for stereo sources (typically with surround sound playback), to widen the sound and create a more encompassing sound stage (or narrow it down to a single point). The app needs to enable it and set the desired width when playing stereo content.

UHJ is for encoding surround sound into stereo (which can either be decoded back to surround sound or left as stereo, depending on what the user wants or can do when listening to it). This can either be requested by the app, or configured in OpenAL Soft's config file.

What are you trying to do?

**Comment by TheBestKmanEver** [comment]
oh ok then i guess i dont need this then :/
