### ISSUE TITLE
EFX Effects

### ISSUE THREAD

**Issue by jurgus** [kcat/openal-soft#93]
Hi,
I'm wondering if any EFX effect works on the OpenAL-soft 1.7.2 on Windows 7.
Because when I'm adding for e.g EAXReverb, Reverb, Echo nothing happens :(.
But when I'm using OpenAL.dll from OpenAL SDK the EAXReverb this effect is heard.

**Comment by kcat** [comment]
They should work, yes. Does ```alGetError()``` return any errors? What does ```alGetString(AL_VERSION)``` return? Are you able to provide code?

**Comment by jurgus** [comment]
Hi,
In the beginning I have few errors but after reading once again the documentation and some few samples I have manage to eliminate all errors 
OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.17.2
Default playback device: OpenAL Soft on Speakers (Realtek High Definition Audio)
Default capture device: OpenAL Soft on Microphone (Realtek High Definition Audio)

I can't run your's example (lack of SDL_audio at this time) but I found cAudio library (c++ wrapper of OpenAL) and the same issue occurred there too.
Tomorrow I will try run it on Windows 10.

**Comment by kcat** [comment]
> OpenAL vendor string: OpenAL Community
> OpenAL renderer string: OpenAL Soft
> OpenAL version string: 1.1 ALSOFT 1.17.2
> Default playback device: OpenAL Soft on Speakers (Realtek High Definition Audio)
> Default capture device: OpenAL Soft on Microphone (Realtek High Definition Audio)

Is that from your app? That looks like the output of ```openal-info```, but I'm trying to check what your app is actually using.

The OS shouldn't matter, since the code is largely system-agnostic. If there's a problem on Win7, I don't expect it to work on Win10 either without something else changing.

**Comment by jurgus** [comment]
Hi,
I'm sorry for the trouble but I found a bug in my code.
when attaching effect to slot I've made
first
alAuxiliaryEffectSloti( mEffectSlot, AL_EFFECTSLOT_EFFECT, mEffect );
then setting 
alEffectf params
and this order is working in OpenAL SDK. 
but it's inconsistent with the documentation.
Every day we learn something new.

**Comment by fatalfeel** [comment]
can openal add 2 effects

alEffecti(effect, AL_EFFECT_TYPE, AL_EFFECT_EQUALIZER);
+
alEffecti(effect, AL_EFFECT_TYPE, AL_EFFECT_EAXREVERB);

i try to use 2 slots but failed~

alAuxiliaryEffectSloti(slot01, AL_EFFECTSLOT_EFFECT, effect01);
alAuxiliaryEffectSloti(slot00, AL_EFFECTSLOT_EFFECT, effect00);

alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, slot01, 0, AL_FILTER_NULL);
alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, slot00, 0, AL_FILTER_NULL);
 
also failed on

alAuxiliaryEffectSloti(slot00, AL_EFFECTSLOT_EFFECT, effect01);
alAuxiliaryEffectSloti(slot00, AL_EFFECTSLOT_EFFECT, effect00);

alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, slot00, 0, AL_FILTER_NULL);

**Comment by kcat** [comment]
> can openal mix 2 effects ?

You can have two separate effects, but you can't have one effect feed another. You need two effect slots and two effect sends, like this:

```
// Set an equalizer effect on effect slot 0
alEffecti(effect, AL_EFFECT_TYPE, AL_EFFECT_EQUALIZER);
...
alAuxiliaryEffectSloti(slot00, AL_EFFECTSLOT_EFFECT, effect);

// Set a reverb effect on effect slot 1
alEffecti(effect, AL_EFFECT_TYPE, AL_EFFECT_EAXREVERB);
...
alAuxiliaryEffectSloti(slot00, AL_EFFECTSLOT_EFFECT, effect);

// Connect the source's auxiliary send 0 to effect slot 0, and auxiliary send 1 to effect slot 1
alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, slot00, 0, AL_FILTER_NULL);
alSource3i(al_source, AL_AUXILIARY_SEND_FILTER, slot01, 1, AL_FILTER_NULL);
```
This will effectively give you three copies of the sound. The first is normal on the direct path (with any panning or distance attenuation that may be applied), the second will be an equalized copy on send path 0, and the third will be a reverberation of the first on send path 1.

If you want to change the volume of the three outputs independently, you can use direct and send filters.

**Comment by fatalfeel** [comment]
thanks a lot...
how to select the separate effects and play

**Comment by fatalfeel** [comment]
i find alGenAuxiliaryEffectSlots
ALeffectslot *slot = al_calloc(16, sizeof(ALeffectslot)); 
generate slot address

and 

i find aluMixData
V(state,process)(SamplesToDo, cslot->WetBuffer, state->OutBuffer, state->OutChannels);
process slot independently

maybe they can mix togther send to next slot and do the mix~~~ a new feature
