### ISSUE TITLE
Warning Messages for Unreleased AuxiliaryEffectSlot and Effect on Program Exit

### ISSUE THREAD

**Issue by Bigfoot71** [kcat/openal-soft#931]
I'm facing these two warnings when closing my program:

```console
[ALSOFT] (WW) 1 AuxiliaryEffectSlot not deleted
[ALSOFT] (WW) 1 Effect not deleted
```

This happens when I instanciate an object on the stack _(creating an effect and a slot)_ in `main()` and the object's destructor _(properly releasing the effect and slot)_ is automatically called upon main's return.

What's strange _(and rather annoying)_ is that I receive these two messages before the destructor of my effect class is called.

It roughly looks something like this:
```console
[ALSOFT] (WW) 1 AuxiliaryEffectSlot not deleted
[ALSOFT] (WW) 1 Effect not deleted
LOG: Effect and Slot destroyed !
```

**Should I ignore this or is it a real issue?**

_Tested on https://github.com/kcat/openal-soft/commit/34cde4b55f87d775e79c1f4cbd6b14d129b1a949_

___

**Edit**: I use C++

**Comment by kcat** [comment]
> Should I ignore this or is it a real issue?

It's an issue in that the effect and slot aren't being destroyed as you intended.

Be aware that destructors are run when the object goes out of scope (and run in reverse order to constructors). So if you do something like this:

```c++
struct Filter {
    ALuint filter;

    Filter() { alGenFilters(1, &filter); }
    ~Filter() { alDeleteFilters(1, &filter); }
};

int main()
{
    auto device = alcOpenDevice(nullptr);
    auto context = alcCreateContext(device, nullptr);
    alcMakeContextCurrent(context);

    ...
    Filter myfilter; // Filter created here after setting context
    ...

    alcDestroyContext(context);
    alcCloseDevice(device);
} // <- myfilter goes out of scope and is destructed here, after the context and device it was created on is destroyed/closed
```

**Comment by Bigfoot71** [comment]
Really excuse me, I've been searching for several hours and I just realized that the context was destroyed before my effects...
Thank you very much for your answer !
