### ISSUE TITLE
Multichannel audio capture is unavailable on windows

### ISSUE THREAD

**Issue by Dmitry221060** [kcat/openal-soft#932]
Updating from 1.16.0 to 1.23.1 breaks multichannel (>2) audio capture on Windows (but not on Linux). I tried to trace it back and the issue persisted all the way to 1.17.0.

Steps to reproduce:
1. Build dll from master branch
2. Query list of extensions via `alGetString` and make sure `AL_EXT_MCFORMATS` is present
3. Try to create new capture device in `AL_FORMAT_QUAD16` format
4. Check that handle isn't zero

On 1.16.0 Quad capture device will be successfully created and will function without any issues
On 1.17.0 and above OpenAL returns zero pointer and `InvalidValue` error

Capture devices in `Mono16` and `Stereo16` can be created without any issues and `AL_EXT_MCFORMATS` extension is present, device names are being resolved using `alcGetString` and contain valid devices(including default one and `null`).

We are calling OpenAL from managed(C#) code via OpenTK, but it is pretty much just a wrapper library.  `WASAPI` backed is detected, here is a fragment from build logs:
```
-- Building OpenAL with support for the following backends:
--     WinMM, DirectSound, WASAPI, WaveFile, Null
--
-- Building with support for CPU extensions:
--     Default, SSE, SSE2, SSE3, SSE4.1
--
-- Building with legacy EAX extension support
```
The OS on which the library was built and is used: Windows 10

If you need any more information please let me know

**Comment by kcat** [comment]
WASAPI requires the capture stream to match the channel configuration of the device, and won't remix the channels to fit a desired configuration. OpenAL Soft will apply its own converter from mono to stereo, or from multichannel/stereo to mono, as those are the most common setups callers need, but it won't convert to anything greater than stereo. 1.16 likely used DirectSound for capture, which apparently does convert.

So if `alcCaptureOpenDevice` fails with a given format, the device isn't capturing that format and neither the system or OpenAL Soft can convert to it. I can try to make the WASAPI backend do more conversions, but it will still only be capturing what the device is configured for (e.g. if the device is configured for mono and you try to capture quad, you'll only get a mono sound mixed into the quad's front channels with the rear channels left silent; or capture 5.1 and you'll only get a mono sound in front-center, with everything else silent).

**Comment by Dmitry221060** [comment]
Does WASAPI also detect what output channels are used by the device? The reason we needed Quad capture in the first place is because some people had setups routing their microphone audio into non-default channels (Stereo on 3-4 instead of 1-2, Mono on 4 instead of 1, etc). There was no way to explicitly tell OpenAL on what channels to look for audio so we went with capturing first 4 and manually detecting which of them contain audio.

**Comment by kcat** [comment]
It just reports the number of channels the device is configured for, and the channel labels (e.g. 4 channels using front-left, front-right, rear-left, and rear-right). It doesn't indicate anything about what the channels contain or what they're getting audio from.

**Comment by Dmitry221060** [comment]
I see, thank you for explaining the issue! 
I'll test if it captures audio channels appropriately for our use case and try disabling WASAPI backend if it doesn't.
