### ISSUE TITLE
OpenMW: No in-game sounds if sound device is already used

### ISSUE THREAD

**Issue by akortunov** [kcat/openal-soft#933]
When I use OpenAL-Soft 1.22.0 or newer with OpenMW on Linux, it seems to ignore sound mixing. It means that if there are another applications which play sounds (browser, music player or even DE's sound notifications), OpenMW starts without sound at all. With 1.21.1 OpenMW works fine in this case.

This bug does not happen on Windows or with another desktop applications (for example, I can play sound via browser and several instances of `aplay` in the same time).

Sound device: HDA Intel PCH, ALC887-VD with snd-hda-intel driver, Linux kernel version 6.1.57. Pure ALSA is used (no PulseAudio or alternatives).

OpenMW's log with `ALSOFT_LOGLEVEL=3`: [openmw.log](https://github.com/kcat/openal-soft/files/13339481/openmw.log)

Link to ticket on the OpenMW's bugtracker: https://gitlab.com/OpenMW/openmw/-/issues/7690

**Comment by kcat** [comment]
> Sound device: HDA Intel PCH, ALC887-VD with snd-hda-intel driver, Linux kernel version 6.1.57. Pure ALSA is used (no PulseAudio or alternatives).

The log shows you have PipeWire with audio:
```
[ALSOFT] (II) Found PipeWire version "0.3.80" (0.3.80 or newer)
[ALSOFT] (II) Key pipewire/assume-audio not found
[ALSOFT] (II) Ignoring metadata "settings"
[ALSOFT] (II) Ignoring node class Midi/Bridge
[ALSOFT] (II) Ignoring metadata "route-settings"
[ALSOFT] (II) Initialized backend "pipewire"
[ALSOFT] (II) Added "pipewire" for playback
[ALSOFT] (II) Added "pipewire" for capture
[...]
[ALSOFT] (II) Got default playback device "alsa_output.pci-0000_00_1f.3.analog-stereo"
[ALSOFT] (II) Got default capture device "alsa_input.pci-0000_00_1f.3.analog-stereo"
[ALSOFT] (II) Got sink device "alsa_output.pci-0000_01_00.1.hdmi-stereo"
[ALSOFT] (II)   "GA106 High Definition Audio Controller Цифровой стерео (HDMI)" = ID 46
[ALSOFT] (II) Device ID 46 sample rate: 48000 (range: 32000 -> 192000)
[ALSOFT] (II) Device ID 46 got 2 positions for Stereo
[ALSOFT] (II) Device ID 46 sample rate: 48000 (range: 32000 -> 192000)
[ALSOFT] (II) Got sink device "alsa_output.pci-0000_00_1f.3.analog-stereo"
[ALSOFT] (II)   "Встроенное аудио Аналоговый стерео" = ID 52
```

If PipeWire didn't report any audio nodes, it would be skipped, but it's reporting two playback devices and one capture device. 1.22.0 added the PipeWire backend, which is why it doesn't affect 1.21.1.

**Comment by akortunov** [comment]
I did not not install PipeWire, but it snuck in as a KDE dependency (Spectacle depends on it for some reason). It is not used by any other applications.

So basically OpenAL-Soft sees unused PipeWire devices, uses them, and then PipeWire server tries to acquire a sound device, which may be already used by non-PipeWire applications, what leads to conflict.

Is it possible to get a name of backend which is currently used by OpenAL-Soft inside client application (to display it to log)?

**Comment by kcat** [comment]
> I did not not install PipeWire, but it snuck in as a KDE dependency (Spectacle depends on it for some reason). It is not used by any other applications.

PipeWire is a fairly common part of the desktop these days, particularly on Wayland. It's basically the way to do screen/window sharing. Its audio support is generally optional.

> So basically OpenAL-Soft sees unused PipeWire devices, uses them, and then PipeWire server tries to acquire a sound device, which may be already used by non-PipeWire applications, what leads to conflict.

Something along those lines. OpenAL Soft initializes the PipeWire client library and queries the server about what nodes it has. When it detects usable audio sinks and sources, it will use them. There's no other indication about what audio APIs other apps may use, so from OpenAL Soft's perspective, PipeWire is there handling audio.

I suppose what's going on is that PipeWire is installed with audio support, PulseAudio isn't installed, and the ALSA->PipeWire wrapper isn't installed or is disabled. So most apps will try PulseAudio (and fail), then fall back to ALSA. I suspect more apps that gain native PipeWire support and use it by auto-detection, the more this will happen as long as PipeWire has audio enabled.

> Is it possible to get a name of backend which is currently used by OpenAL-Soft inside client application (to display it to log)?

Yes and no. The latest git version has a log callback function an app can use to include OpenAL Soft's log messages in their own log. However, an app can't rely on anything specific and it should be treated as opaque (UTF-8) strings; later versions can change what the messages say and remove/add/reorder them, and messages can be disabled (it also won't work on Windows through the router), so the app shouldn't parse it to get any information and should just pass the messages along.

**Comment by akortunov** [comment]
> I suppose what's going on is that PipeWire is installed with audio support, PulseAudio isn't installed, and the ALSA->PipeWire wrapper isn't installed or is disabled.

Yes, by default PipeWire comes without ALSA plugin. With this plugin PipeWire applications do not conflict with ALSA ones. 
But it causes another issues (for example, it reset master volume in ALSA after every login to Plasma desktop), so I just will disable PipeWire's sound server for now.

Thanks for the help.
