### ISSUE TITLE
After 33cd77b libc++ based toolchain can't build openal-soft

### ISSUE THREAD

**Issue by Andarwinux** [kcat/openal-soft#937]
https://github.com/kcat/openal-soft/commit/33cd77b81b1dce9a5b55ec7e215315c500f9d0bf
https://github.com/llvm/llvm-project/issues/72055
This commit uses Mathematical special functions that are not yet supported by libc++, which results in clang `error: no member named 'cyl_bessel_i' in namespace 'std'`

**Comment by kcat** [comment]
Should be fixed now with commit d6d572df66eb2b5beeb3da7f3b11a328500c33c3.
