### ISSUE TITLE
Crash in alcDeviceResumeSOFT with Oboe backend.

### ISSUE THREAD

**Issue by efroemling** [kcat/openal-soft#947]
I thought I'd report a particular crash I'm seeing in small numbers in the wild with my Oboe backend setup. It looks like something I can guard against in my own code but wanted to report it in case it's worth hardening OpenALSoft against.

First off, I switched to using the master build which has solved the crash I was previously seeing with disconnected devices on alcDevicePauseSOFT, so thank you for that advice. I also wired up alcResetDeviceSOFT() to try and resurrect those disconnected devices, which in general has been working well. Every so often though my remote logs are showing non-connected states remaining after the reset call, but I haven't worried about this since I figured weird corner cases like repeat headphone plugs/unplugs might lead to that. I just retry the reset again every several seconds and leave it at that. (holler if that's a bad idea).

I mention alcResetDeviceSOFT because this particular crash seems to only happen after a failed alcResetDeviceSOFT() attempt. It seems that if a reset fails and then at some point I run alcDevicePauseSOFT()/alcDeviceResumeSOFT() due to the app getting backgrounded/foregrounded, I can get a crash in alcDeviceResumeSOFT().

I'm guessing I can mostly prevent this by checking connected state before calling alcDevicePauseSOFT/alcDeviceResumeSOFT instead of just blindly running it whenever I have a device, but is this something OpenALSoft should be hardened to handle gracefully?

Type of logs I'm seeing for this crash: always a failed reset followed by pause and then crash on resume.
<img width="763" alt="Screenshot 2023-12-12 at 2 42 19 PM" src="https://github.com/kcat/openal-soft/assets/10857610/d2779615-533b-4163-834c-08c4abb1fbc6">

<img width="752" alt="Screenshot 2023-12-12 at 2 32 48 PM" src="https://github.com/kcat/openal-soft/assets/10857610/afe15955-06cf-4431-9695-8c0b2dff1c6a">

Any ideas what's happening here? The crash seems to be happening on mStream->start() in the oboe backend; is the failed reset leaving mStream in an uninitialized state or something? Though perhaps it's odd that the previous mStream->stop() in the pause isn't crashing in that case?..

**Comment by kcat** [comment]
It seems what's happening is when calling `alcResetDeviceSOFT`, the internal device state is set to "stopped" while the Oboe backend deletes the playback stream and tries to create a new one, and fails for some reason. Since the reset failed, the function returns false and the backend is left with no stream. `alcDevicePauseSOFT` is called and sees the device is already not playing, so does nothing. `alcDeviceResumeSOFT` is then called and also sees the device is not playing, then tries to start it. The backend tries to start the playback stream, but it doesn't have one since the reset failed.

It definitely shouldn't crash, so this is a bug. It's probably fair for `alcDevicePauseSOFT` to do nothing and not report an error since the device playback is stopped as requested, but `alcDeviceResumeSOFT` should be made aware that the backend hasn't been configured and set an error instead of trying to start.

**Comment by kcat** [comment]
Should be fixed now with commit c7774aa488961e0af2895008fb0063fb790b0a58 (also for other backends that would hit a similar issue).

**Comment by efroemling** [comment]
Awesome; thanks for such a fast fix!

**Comment by efroemling** [comment]
Quick followup question:
This sounds like it should fix the crash, but should I still expect alResetDeviceSOFT() to possibly work once a device has reached this state? (failed reset followed by pause followed by resume). My current strategy is to run alResetDeviceSOFT() once every 5 seconds or so if a device is disconnected in an attempt to bring it back. Is that a reasonable strategy in this particular case (Android/Oboe) or should I wire up something fancier like creating a fresh context once a reset has failed once or twice?

**Comment by kcat** [comment]
You can keep trying `alcResetDeviceSOFT` if it previously failed, yeah. With the fix, you can have `alcDevicePauseSOFT` and `alcDeviceResumeSOFT` in between attempts too.

And now with commit 70b3776032adf05a92fda89ac5f56eb705d06748, it should be safe to interleave them as well (e.g. the device disconnects, the device is paused asynchronously, the device is successfully reset, then the device is resumed). Before that commit, `alcDevicePauseSOFT` and `alcDeviceResumeSOFT` would return an error for a disconnected device, so resetting the device would try to resume it automatically; now `alcDevicePauseSOFT` will succeed for a disconnected device and internally mark it "paused", so a successful reset/reopen won't immediately resume until `alcDeviceResumeSOFT` is called afterward (`alcDeviceResumeSOFT` itself will still fail on disconnected devices and not clear the "paused" flag, so you should call to resume as desired after resetting).
