### ISSUE TITLE
Something broke due to clang-tidy cleanup.

### ISSUE THREAD

**Issue by efroemling** [kcat/openal-soft#948]
I pulled in the latest changes last night and started rolling out a new build of my Android app using the Oboe backend and this morning woke up to see a pretty crazy high crash rate (about 25%). I can't tell much from the crash reports in this case which are pretty cryptic, but I found that rolling back to an older OpenALSoft commit fixed things. I was then able to iterate and pinpoint which commit breaks things, and it seems the breaking commit is 040c172cdf186c9ccfb0642aa9ac598f115bb46b which is 'Clean up some more clang-tidy warnings'.

Here you can see my results when I run a build on 33 test devices using Firebase Test Lab using the previous commit 4527b873788373edb630046b0ab586255aa15e44 vs commit 040c172cdf186c9ccfb0642aa9ac598f115bb46b (later commits yield the same crash rate pretty consistently).

<img width="1189" alt="Screenshot 2023-12-15 at 9 17 55 AM" src="https://github.com/kcat/openal-soft/assets/10857610/c7923317-935c-4cad-b543-22741fc4322b">

The following is the kind of crash reports I'm seeing for this, which don't seem incredibly illuminating (to me at least). The crashes seem to be pretty instantaneous.

<img width="1189" alt="Screenshot 2023-12-15 at 9 11 27 AM" src="https://github.com/kcat/openal-soft/assets/10857610/28bde9dc-2ffa-4170-94c6-a1616623d457">

I'd wonder if this is something where replacing a #define with an uint or something like that could have inadvertently changed some logic. Or maybe a compiler bug? Or perhaps some previously existing issue that is now more consistently being detected? Any ideas? I'll poke around that clean-up commit a bit and will holler if I see something...

**Comment by kcat** [comment]
Can you check now with commit 1381a951bea78c67281a2e844e6db1dedbd5ed7c? The ring buffer size calculation was checking the wrong value, causing 32-bit targets to think size_t was larger than 32 bits and shift too much (causing UB). At least I hope that was the issue, if it still crashes then there's an issue with a caller of `RingBuffer::Create` somwhere passing a value that's too large, rather than the function itself miscalculating the power-of-two size.

**Comment by efroemling** [comment]
Sure thing; I'll kick off a test with that commit now and get back to you asap.

**Comment by efroemling** [comment]
Still waiting on 2 straggling device tests but it 99% certainly appears to be fixed. Once again, a huge thanks for the ultra-fast turnaround!

<img width="706" alt="Screenshot 2023-12-15 at 10 31 09 AM" src="https://github.com/kcat/openal-soft/assets/10857610/3e8751cd-84b3-418d-8179-1dcd67945a6f">
