### ISSUE TITLE
ios building a .framework?

### ISSUE THREAD

**Issue by mohamedSulaimanAlmarzooqi** [kcat/openal-soft#954]
I want to build for ios, but I'm not sure if there's a way to create a .framework bundle by default or if I should do that myself
note I'm new to .framework bundles so I apologize if this is a dumb question.

**Comment by kcat** [comment]
Setting the `ALSOFT_OSX_FRAMEWORK` cmake config option should make it build as a framework on macOS. That's typically done by passing `-DALSOFT_OSX_FRAMEWORK=ON` on the cmake command line, but you can set it with cmake GUIs as well.

**Comment by mohamedSulaimanAlmarzooqi** [comment]
would the framework be compatible on ios or is it only macos?

**Comment by kcat** [comment]
It should be compatible with whatever compile target it's made for. Someone more familiar with building for mac/apple stuff would have to give more details.

**Comment by halx99** [comment]
Yes, it's compatible on ios/tvos too, see `openal-soft` in this engine: [axmol](https://github.com/axmolengine/axmol/tree/dev/thirdparty/openal)

**Comment by mohamedSulaimanAlmarzooqi** [comment]
so just using the flag @kcat said will create a binary compatible for ios as well? I have no idea what flags I should use for ios with CMake.

**Comment by halx99** [comment]
openal-soft itself handle ios setting properly, just pass `-DCMAKE_SYSTEM_NAME=iOS` , this [PR](https://github.com/kcat/openal-soft/pull/466) would helpful

**Comment by mohamedSulaimanAlmarzooqi** [comment]
yay, thanks so much, it works perfectly 🥲
