### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Fyroeo** [kcat/openal-soft#956]
Hi !

In case you don't already know, it seems the project's website is currently down (timeout, no response), making some packages manager not being able to retrieve the sources, such as Conan.
From my searching, it does not seems to be a DNS problem but might be something related to the website hosting provider, Digital Ocean.

![image](https://github.com/kcat/openal-soft/assets/20495032/d547614b-92f4-4739-b875-7070f1f3d54e)

Have a nice day !

**Comment by ZerLock** [comment]
Hey ! I have the same issue

**Comment by kcat** [comment]
I'm poking the sysadmin about it. Might take a bit because of the holidays, but I'll get it back up as soon as I can.

**Comment by illwieckz** [comment]
Hi, I noticed the same problem yesterday. Is there any mirror we can rely on to download source tarballs of OpenAL when the primary server is down?

**Comment by kcat** [comment]
I made a couple releases on GitHub for the latest 1.22 and 1.23 versions:
https://github.com/kcat/openal-soft/releases/tag/1.23.1
(there shouldn't be a need to use 1.22, but just in case)

Alternatively, the sources can be retrieved by grabbing the corresponding tag from the repo. The source tarball is simply created from running `git archive` on the release commit, so there shouldn't be any difference.

**Comment by illwieckz** [comment]
Thanks !

**Comment by illwieckz** [comment]
> The internet website is still down 1 week later, makes it impossible to build several software using conan

Isn't it a conan issue to not be able to survive to a missing upstream? 🤷‍♀️️

**Comment by Bobini1** [comment]
It's been a while, can we expect the website to come back this month?

**Comment by kcat** [comment]
Really sorry for the delay. It's back up now.
