### ISSUE TITLE
GCC+MinGW-w64 cross-compile: Dependency on `libwinpthread-1.dll` albeit `ALSOFT_STATIC_WINPTHREAD=ON` is set

### ISSUE THREAD

**Issue by kamgha** [kcat/openal-soft#962]
I'm cross-compiling OpenAL-soft with GCC 13.2 and the current git revision of MinGW-w64 to Windows. DependencyWalker still shows a dependency to `libwinpthread-1.dll` on examination.

Compiling with a combination of `-DALSOFT_STATIC_LIBGCC=ON -DALSOFT_STATIC_STDCXX=ON -DALSOFT_STATIC_WINPTHREAD=ON`.

Since a revision between bab3a1c9f517446f6175815f1e943b5035747fda (5th December 2024) and 9c83a2e78ee8ff8a2f41ca40b94629a26a507356 (current revision as of 7th December 2024), my application complains about missing `libwinpthread-1.dll` upon initialization of OpenAL-soft. The missing dependency is listed in DependencyWalker on revisions before that date as well, though, but the application did not complain about the missing shared library.

For a workaround, I've added `-DCMAKE_SHARED_LINKER_FLAGS="-static"`, which ensures static linking and makes DependencyWalker not list `libwinpthread-1.dll` anymore.

**Comment by kcat** [comment]
Perhaps commit 59c466077fd6f16af64afcc6260bb61aa4e632dc affected it somehow. That changes how it static links to libstdc++ though, so I'm not really sure how it would affect libwinpthread which is linked like it always has been (with `-Wl,--push-state,-Bstatic,-lwinpthread,--pop-state`). I really wish MinGW was better about avoiding extra DLL dependencies for standards support.

**Comment by kcat** [comment]
Commit a7fa088e37678ef9f56bc2bd67c8179aabf18b36 should fix it. It seems to here, at least.

**Comment by kamgha** [comment]
I can confirm that this fixes it, thank you!
