### ISSUE TITLE
openal-info32/64 returns no devices, also alcOpenDevice can open any device [Windows 10, openal-soft-1.23.1-bin]

### ISSUE THREAD

**Issue by fr0zi** [kcat/openal-soft#965]
Hello,

I'm trying to use openal-soft in my project but I have hard time to make it work.

I downloaded openal-soft-1.23.1-bin binary release, and tried to run openal-info64, but I'm getting no devices whatsoever:

```
PS C:\Devel\Libraries\openal-soft-1.23.1-bin> .\openal-info64.exe
Available playback devices:
    !!! none !!!
Available capture devices:
    !!! none !!!
Default playback device:
Default capture device:
ALC version: 1.1

!!! Failed to open default device !!!

PS C:\Devel\Libraries\openal-soft-1.23.1-bin>
```

Also, when I try to use alcOpenDevice() in my project it always returns NULL, no no device can be opened:

![obraz](https://github.com/kcat/openal-soft/assets/606711/e14543c7-3885-4f4b-abd4-f3f44f336f10)

Project compiles with no problems, just the device can't be opened.

My system: Windows 10 Pro, 22H2

**Comment by fr0zi** [comment]
I figured that this issue had something to do with the fact that I build the lib with MinGW 32-bit and tried to use with it.
When I built whole OpenAL with Visual Studio 2019 it worked and also openal-info from that build worked ok and showed all audio devices.
So it seems that 32-bit version of MinGW was a problem here.

**Comment by kcat** [comment]
`openal-info64.exe` uses a 64-bit OpenAL. A 32-bit MinGW build should be detected by `openal-info32.exe`.

**Comment by fr0zi** [comment]
Yes, I messed up things with my previous setup. I think I put wrong dll next to my binary file. It was the one from folder `router/Win32` instead of `bin/Win32`. Now I tried with the one from `bin` folder, renamed it from `soft_oal.dll` to `OpenAL32.dll` and it worked :)
So problem is solved, I will close the ticket. Thanks!
