### ISSUE TITLE
[suggestion] on SCUT KEMAR HRTF

### ISSUE THREAD

**Issue by TheBestKmanEver** [kcat/openal-soft#970]
i did some playing around with 'makemhr' with the SCUT KEMAR HRTF (Near Field with multiple recorded distances) and found that i have better locational sound when i disabled the diffuse field EQ and the surface weighted settings for making the MHR, it is kinda weird sounding at first but i do recommend running 'alhrtf' to test to see if you like it after making the mhr

also i noticed a small issue with the the scut hrtf on the hrtf database on airtable, the radius is set at 0.105 rather than the default of 0.09  (oops this was my fault actually lol)

**Comment by kcat** [comment]
Unless there's some bugs in the diffuse-field equalization and surface-weighted diffuse-field average algorithms, the quality of them will be dependent on how closely a given HRTF matches your head, and the frequency response of your headphones (diffuse-field equalization effectively works by taking out what's common in all the responses, leaving just the differences between the responses, which tends to work better across the range of frequency responses headphones can have).

As for the SCUT KEMAR HRTF itself, unfortunately it can't be included with OpenAL Soft. At least, according to the SOFA file of it that I have, the license is CC 3.0 BY-SA-NC, the NC being Non-Commercial which is incompatible with the LGPL that allows commercial use. You can certainly make, use, and distribute `.mhr` files created from it in accordance with its license, but it can't be distributed built-in to OpenAL Soft itself without violating one of the licenses. Unless there's a different version of the dataset with a different, more compatible license.

**Comment by TheBestKmanEver** [comment]
> Unless there's some bugs in the diffuse-field equalization and surface-weighted diffuse-field average algorithms, the quality of them will be dependent on how closely a given HRTF matches your head, and the frequency response of your headphones (diffuse-field equalization effectively works by taking out what's common in all the responses, leaving just the differences between the responses, which tends to work better across the range of frequency responses headphones can have).
> 
ah so it's very dependent on the headphone and the listener?? also https://airtable.com/appayGNkn3nSuXkaz/shruimhjdSakUPg2m/tbloLjoZKWJDnLtTc/viwMmtPWIXCzhidSv/recdjA3pzV5Shob4b when you download the raw the radius set in the .def file is set to 0.105 which was my personal setting and the default radius is supposed to be 0.09, https://github.com/kcat/openal-soft/issues/775#issuecomment-1312820344

**Comment by ThreeDeeJay** [comment]
> when you download the raw the radius set in the .def file is set to 0.105

I'm not sure I follow. The radius is already 0.09 in both [your .def](https://github.com/kcat/openal-soft/files/9998198/SCUT_KEMAR.def.zip) and [the one linked on Airtable](https://mega.nz/folder/jPxghLCL#-WEV4eAq7zWfXoxaUJbgJA/file/jTo22TaS). So are you saying it should be 0.105 or user-specific? 🤔 
![image](https://github.com/kcat/openal-soft/assets/71472458/fbba5452-e1c9-4f76-8c05-d3d3c742acc1)

**Comment by TheBestKmanEver** [comment]
hm strange, it's default at 0.09 metres (or 9CM) for head radius which is the distance between ears and the average of 0.09 is used by default. i completely forgot that i had modified the file after the download :/
