### ISSUE TITLE
undefined hardware_destructive_interference_size

### ISSUE THREAD

**Issue by hsdk123** [kcat/openal-soft#977]
Hi, I'm getting the following error when building:
```
In file included from D:/Light.vn-core/_deps/openal-soft/3be63b3f39a174450de1f24ffd50073c72bb031a/common/ringbuffer.cpp:23:
D:/Light.vn-core/_deps/openal-soft/3be63b3f39a174450de1f24ffd50073c72bb031a/common/ringbuffer.h:24:55: error: no member named 'hardware_destructive_interference_size' in namespace 'std'
    static constexpr std::size_t sCacheAlignment{std::hardware_destructive_interference_size};
```
Compiling with
```
C:/Users/mrdol/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
```
for android

**Comment by hsdk123** [comment]
Upon some light inspection, perhaps this line is incorrect?
https://github.com/kcat/openal-soft/blob/master/common/ringbuffer.h#L23

According to https://stackoverflow.com/a/60004979/1709725
should be
```
#if __cpp_lib_hardware_interference_size >= 201603
```

**Comment by hsdk123** [comment]
https://github.com/rigtorp/SPSCQueue/issues/22

some similar issues

**Comment by kcat** [comment]
It seems to be a bug in older versions of Clang/LLVM/libc++. I currently have the Andoid NDK r25c installed, and I see it define:
```c++
# define __cpp_lib_hardware_interference_size           201703L
```
in `<version>`, but doesn't declare `hardware_destructive_interference_size` anywhere, so adding a value check won't fix it. It's simply defined when it shouldn't be. Seems a better fix would be to test if it's building against affected versions of libc++, though I don't know what to check `_LIBCPP_VERSION` against for the fix.

Commit 28f7b53f24030b66ab4b402aa8ccb3de9076c8b5 should work around it by not using `hardware_destructive_interference_size` at all on libc++.

**Comment by hsdk123** [comment]
Thank you, confirming builds are passing again!

**Comment by hsdk123** [comment]
Would perhaps also be great to have an android build in the github workflows!
