### ISSUE TITLE
Error when opening a device with multiple devices

### ISSUE THREAD

**Issue by HarryWheadon** [kcat/openal-soft#980]
Hi there,

I am using OpenAL in a C++ project to implement audio and I am having some trouble opening a device. (Windows 11)

 Using just my laptop speakers it seems to run and play audio fine, however, when I input my headphones, It gives me the error seen below (This only happens with multiple devices):
 
<img width="683" alt="image" src="https://github.com/kcat/openal-soft/assets/91532361/1a31e2e3-ec04-4cfd-b3d6-d794ccf1c96a">

Using an error check gives this error below, but I can't seem to find any documentation on why this might be caused (Error: 40964)

![image](https://github.com/kcat/openal-soft/assets/91532361/c69ce44a-01d2-416a-8515-159033dd861b)

This is my current code for initializing OpenAL

![image](https://github.com/kcat/openal-soft/assets/91532361/0c8ae536-adb7-4174-9b1c-46f4670ff5f3)

**Comment by kcat** [comment]
What version of OpenAL Soft are you using? The latest Git version, 1.23.1, or an earlier release? I don't know about that debug assertion, I would need to see a backtrace with line numbers.

For the OpenAL errors, you can't call `alGetError()` before setting a current context with `alcMakeContextCurrent`. Although for calls like `alcOpenDevice`, `alcGetString`, and `alcCreateContext` (basically any `alc` function), you should actually call `alcGetError` with the same device handle to get the error code. The `alGetError` function returns error values from `al` (non-`alc`) calls on the current context, but it can't get a context's error without a current context so returns `AL_INVALID_OPERATION` (it can't do the requested operation).

**Comment by HarryWheadon** [comment]
Appreciate the help with the error checking!

Yes, this is in the latest Git version (1.23.1) but I also tried it with an earlier version and got the same debug assertion. 

There's the call stack for reference:
![image](https://github.com/kcat/openal-soft/assets/91532361/79d68dd4-fdd0-4549-8bf7-d0b1530087e7)

It starts from:
`ALCcontext* context = alcCreateContext(device, nullptr);`

and ends at:
![image](https://github.com/kcat/openal-soft/assets/91532361/8e98700d-a6d9-4463-a9f1-fa2fd0e85086)

**Comment by kcat** [comment]
The assertion should be fixed with commit 94a6230a7295ff93815e2293189d5177fd6fca92 now.

**Comment by HarryWheadon** [comment]
Yep, that has fixed it. Thanks for the help!
