### ISSUE TITLE
Sending multichannel samples directly to speakers

### ISSUE THREAD

**Issue by pierre-aimi** [kcat/openal-soft#981]
Hi,
I generate my own multisample audio (in interleaved buffer format)...I was wondering if I could somehow send each channel directly to a single speaker (bypassing spatialisation).

Is it possible to do this using OpenAL?

I'm aware that I could create some spatialized sources that "align" with the speakers, but I'm hoping to bypass this process and sending audio directly to speakers. (Actually, I want to do both...i.e. spatialise, but also send directly)

**Comment by kcat** [comment]
With OpenAL Soft you can use the [`AL_SOFT_direct_channels_remix`](https://openal-soft.org/openal-extensions/SOFT_direct_channels_remix.txt) extension, to set the source's `AL_DIRECT_CHANNELS_SOFT` property to `AL_REMIX_UNMATCHED_SOFT` or `AL_DROP_UNMATCHED_SOFT`. They'll both cause each source channel to play directly on the matching output channel without spatialization, though for channels that don't have a matching output, the former (remix) will move or do minimal remixing to the closest possible output channels, and the latter (drop) will just drop it and it won't be heard.
