### ISSUE TITLE
New language binding: Freepascal/Lazarus

### ISSUE THREAD

**Issue by Lulu04** [kcat/openal-soft#988]
Hi Kcat,
This is not an issue, just to inform you that a binding for FreePascal is available at https://github.com/Lulu04/ALSound
ALSound also includes a high level API to ease the use of OpenAL-Soft and LibSndFile.
Feel free to add this link on your repository.
Thanks you for your work!

Regards

**Comment by kcat** [comment]
Added a mention with commit a9c0f915a9b79774503c7ff1e717c0725f278fa5. Thanks!

**Comment by Lulu04** [comment]
Thanks you for the mention!
